# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("delivery", "0001_initial"),
        ("sale", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="sale_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_address",
                to="sale.saleorder",
            ),
        ),
        migrations.AddField(
            model_name="shipmentevent",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipmentguide",
            name="courier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guides",
                to="delivery.courier",
            ),
        ),
        migrations.AddField(
            model_name="shipmentguide",
            name="sale_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipment_guide",
                to="sale.saleorder",
            ),
        ),
        migrations.AddField(
            model_name="shipmentevent",
            name="guide",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="delivery.shipmentguide",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Producto de servicio para la línea de envío (Odoo delivery.carrier.product_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_methods",
                to="catalogue.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="shipmentguide",
            constraint=models.UniqueConstraint(
                fields=("courier", "tracking_number"),
                name="unique_tracking_per_courier",
            ),
        ),
    ]
