# Generated by Django 6.0.5 on 2026-07-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_product_weight_kg"),
        ("delivery", "0005_anchor_guide_to_sale_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Producto de servicio para la línea de envío (Odoo delivery.carrier.product_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shipping_methods",
                to="catalogue.product",
            ),
        ),
    ]
