# Generated by Django 6.0.5 on 2026-08-19 16:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0030_rescompany_account_peppol_contact_email_and_more"),
        ("hr", "0010_hremployee_friday_location_hremployee_hourly_cost_and_more"),
        ("project", "0004_project_billing_type_project_timesheet_product"),
        ("sale", "0006_saleorderline_has_displayed_warning_upsell"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSaleLineEmployeeMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_unit",
                    models.FloatField(
                        default=0.0,
                        help_text="Odoo price_unit (compute, store) — se sincroniza desde sale_line.price_unit en pre_save.",
                        verbose_name="Precio unitario",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Odoo cost. Sustituye al hourly_cost por defecto del empleado en los apuntes de este proyecto.",
                        max_digits=14,
                        verbose_name="Costo por hora",
                    ),
                ),
                (
                    "is_cost_changed",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo is_cost_changed (compute, store).",
                        verbose_name="Costo modificado a mano",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo currency_id (compute, store).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_sale_line_maps",
                        to="base.rescurrency",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Odoo employee_id (required).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_sale_line_maps",
                        to="hr.hremployee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Odoo project_id (required, index).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_line_employee_ids",
                        to="project.project",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "sale_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo sale_line_id. Escribible directo — su compute y su domain quedan bloqueados (ver docstring del módulo).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_sale_line_maps",
                        to="sale.saleorderline",
                        verbose_name="Línea de pedido de venta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de empleado en proyecto",
                "verbose_name_plural": "Tarifas de empleado en proyecto",
                "db_table": "project_sale_line_employee_map",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "employee"), name="uniqueness_employee"
                    )
                ],
            },
        ),
    ]
