# Generated by Django 6.0.5 on 2026-08-02 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mrp", "0001_initial"),
        ("stock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubcontractingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_subcontracting_location",
                    models.BooleanField(
                        default=True,
                        help_text="La ubicación es de subcontratación (Odoo is_subcontracting_location).",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        help_text="Ubicación base (Odoo stock.location).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontracting_flag",
                        to="stock.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación de subcontratación",
                "verbose_name_plural": "Ubicaciones de subcontratación",
                "db_table": "stock_location_subcontracting",
            },
        ),
        migrations.CreateModel(
            name="Subcontractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Ubicación de stock del subcontratista (Odoo property_stock_subcontractor).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontractors",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        help_text="Subcontratista (Odoo res.partner).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontratista",
                "verbose_name_plural": "Subcontratistas",
                "db_table": "res_partner_subcontractor",
            },
        ),
        migrations.CreateModel(
            name="SubcontractProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "production",
                    models.OneToOneField(
                        help_text="Orden de fabricación (Odoo mrp.production).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontract",
                        to="mrp.mrpproduction",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        help_text="Subcontratista de la orden (Odoo subcontractor_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontract_productions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontratación de orden",
                "verbose_name_plural": "Subcontrataciones de orden",
                "db_table": "mrp_production_subcontractor",
            },
        ),
        migrations.CreateModel(
            name="BomSubcontractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "bom",
                    models.ForeignKey(
                        help_text="BoM de subcontratación (Odoo mrp.bom).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontractor_links",
                        to="mrp.mrpbom",
                    ),
                ),
                (
                    "subcontractor",
                    models.ForeignKey(
                        help_text="Subcontratista (Odoo res.partner).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcontracted_boms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcontratista de BoM",
                "verbose_name_plural": "Subcontratistas de BoM",
                "db_table": "mrp_bom_subcontractor",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bom", "subcontractor"), name="unique_bom_subcontractor"
                    )
                ],
            },
        ),
    ]
