# Generated by Django 6.0.5 on 2026-08-27 06:22

import addons.hr_skills.models.hr_individual_skill_mixin
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr_recruitment", "0003_alter_hrapplicant_email_normalized_and_more"),
        ("hr_skills", "0002_alter_hrresumeline_certificate_filename_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrApplicantSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Inicio de validez"
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de validez"
                    ),
                ),
                (
                    "display_warning_message",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo display_warning_message — poblado por _onchange_valid_date() (divergencia: sin motor de onchange, no auto-wireado).",
                        verbose_name="Mostrar advertencia",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_skill_ids",
                        to="hr_recruitment.hrapplicant",
                        verbose_name="Candidato",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Odoo skill_id (compute+store, readonly=False, required) — poblado por _compute_skill_id() o directo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_set",
                        to="hr_skills.hrskill",
                        verbose_name="Habilidad",
                    ),
                ),
                (
                    "skill_level",
                    models.ForeignKey(
                        help_text="Odoo skill_level_id (compute+store, readonly=False, required) — poblado por _compute_skill_level_id() o directo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_level_set",
                        to="hr_skills.hrskilllevel",
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "skill_type",
                    models.ForeignKey(
                        default=addons.hr_skills.models.hr_individual_skill_mixin._default_skill_type,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_type_set",
                        to="hr_skills.hrskilltype",
                        verbose_name="Tipo de habilidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidad de candidato",
                "verbose_name_plural": "Habilidades de candidato",
                "db_table": "hr_applicant_skill",
                "ordering": ["skill_type", "-skill_level"],
            },
        ),
    ]
