# Generated by Django 6.0.5 on 2026-08-28 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_recruitment_skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrapplicantskill",
            name="applicant",
            field=models.ForeignKey(
                db_column="applicant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_skill_ids",
                to="hr_recruitment.hrapplicant",
                verbose_name="Candidato",
            ),
        ),
        migrations.RenameField(
            model_name="hrapplicantskill",
            old_name="applicant",
            new_name="applicant_id",
        ),
    ]
