# Generated by Django 6.0.5 on 2026-08-03 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OauthProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la entidad OAuth2: Google, etc.",
                        max_length=255,
                        verbose_name="Nombre del proveedor",
                    ),
                ),
                (
                    "client_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nuestro identificador ante el proveedor.",
                        max_length=255,
                        verbose_name="Client ID",
                    ),
                ),
                (
                    "auth_endpoint",
                    models.CharField(
                        help_text="URL del proveedor para autenticar usuarios.",
                        max_length=1024,
                        verbose_name="URL de autorización",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        default="openid profile email",
                        help_text="Datos del usuario a los que se pide acceso.",
                        max_length=255,
                        verbose_name="Scope",
                    ),
                ),
                (
                    "validation_endpoint",
                    models.CharField(
                        help_text="URL del proveedor para obtener la información del usuario.",
                        max_length=1024,
                        verbose_name="URL de UserInfo",
                    ),
                ),
                (
                    "data_endpoint",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="URL de datos",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="Permitido"),
                ),
                (
                    "css_class",
                    models.CharField(
                        blank=True,
                        default="fa fa-fw fa-sign-in text-primary",
                        max_length=255,
                        verbose_name="Clase CSS",
                    ),
                ),
                (
                    "body",
                    models.CharField(
                        help_text="Texto del enlace en el diálogo de login.",
                        max_length=255,
                        verbose_name="Etiqueta del botón de login",
                    ),
                ),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
            ],
            options={
                "verbose_name": "Proveedor OAuth2",
                "verbose_name_plural": "Proveedores OAuth2",
                "db_table": "auth_oauth_provider",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="OauthAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "oauth_uid",
                    models.CharField(
                        help_text="user_id del proveedor OAuth.",
                        max_length=255,
                        verbose_name="OAuth User ID",
                    ),
                ),
                (
                    "oauth_access_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="NO se expone por la API (NO_ACCESS en la referencia).",
                        max_length=2048,
                        verbose_name="Access token OAuth",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="authz_oauth.oauthprovider",
                        verbose_name="Proveedor OAuth",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta OAuth",
                "verbose_name_plural": "Cuentas OAuth",
                "db_table": "authz_oauth_account",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "oauth_uid"),
                        name="uniq_oauth_provider_oauth_uid",
                    )
                ],
            },
        ),
    ]
