"""Retira los 6 modelos del estado de ``payments`` (movidos a ``payment``).

State-only: las tablas ``payments_*`` NO se tocan — las adopta
``payment.0001_initial``. ``payments`` queda como paquete controlador sin
modelos propios.
"""
# Generated by Django 6.0.5 on 2026-07-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_gatewaysettlement_payment"),
        ("payments", "0001_initial"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="chargeback",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order",
        ),
        migrations.RemoveField(
            model_name="refund",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="paymentgatewayevent",
            name="payment",
        ),
        migrations.RemoveConstraint(
            model_name="savedcard",
            name="unique_user_mp_card",
        ),
        migrations.RemoveConstraint(
            model_name="webhookevent",
            name="unique_webhook_event",
        ),
        migrations.DeleteModel(
            name="WebhookEvent",
        ),
        migrations.DeleteModel(
            name="Chargeback",
        ),
        migrations.DeleteModel(
            name="Refund",
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="PaymentGatewayEvent",
        ),
        migrations.DeleteModel(
            name="SavedCard",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
