# Generated by Django 6.0.5 on 2026-08-19 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0010_hremployee_friday_location_hremployee_hourly_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAnalyticLineCalendarEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked", models.BooleanField(default=True, verbose_name="Marcado")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calendar_filters",
                        to="hr.hremployee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Odoo user_id (required, ondelete=cascade). Sin default a env.user — ver docstring del módulo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheet_calendar_filters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtro de empleado en calendario",
                "verbose_name_plural": "Filtros de empleado en calendario",
                "db_table": "account_analytic_line_calendar_employee",
            },
        ),
    ]
