# Generated by Django 6.0.5 on 2026-08-28 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_timesheet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountanalyticlinecalendaremployee",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                db_column="employee_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_filters",
                to="hr.hremployee",
                verbose_name="Empleado",
            ),
        ),
        migrations.RenameField(
            model_name="accountanalyticlinecalendaremployee",
            old_name="employee",
            new_name="employee_id",
        ),
        migrations.AlterField(
            model_name="accountanalyticlinecalendaremployee",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                help_text="Odoo user_id (required, ondelete=cascade). Sin default a env.user — ver docstring del módulo.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timesheet_calendar_filters",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.RenameField(
            model_name="accountanalyticlinecalendaremployee",
            old_name="user",
            new_name="user_id",
        ),
    ]
