# Generated by Django 6.0.5 on 2026-08-06 00:31

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0007_alter_iractionsreport_report_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingOnboardingStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Título"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="Let's do it",
                        help_text="Texto del botón que arranca este paso (Odoo button_text).",
                        max_length=255,
                        verbose_name="Texto del botón",
                    ),
                ),
                (
                    "done_icon",
                    models.CharField(
                        default="fa-star",
                        max_length=64,
                        verbose_name="Ícono Font Awesome al completar",
                    ),
                ),
                (
                    "done_text",
                    models.CharField(
                        default="Step Completed!",
                        max_length=255,
                        verbose_name="Texto al completar el paso",
                    ),
                ),
                (
                    "step_image",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Imagen del paso"
                    ),
                ),
                (
                    "step_image_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nombre de archivo de la imagen",
                    ),
                ),
                (
                    "step_image_alt",
                    models.CharField(
                        default="Onboarding Step Image",
                        max_length=255,
                        verbose_name="Texto alternativo de la imagen del paso",
                    ),
                ),
                (
                    "panel_step_open_action_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la acción de modelo a ejecutar al abrir el paso, p. ej. action_open_onboarding_1_step_1.",
                        max_length=255,
                        verbose_name="Acción de apertura",
                    ),
                ),
                (
                    "is_per_company",
                    models.BooleanField(default=True, verbose_name="¿Es per-company?"),
                ),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
            ],
            options={
                "verbose_name": "Paso de onboarding",
                "verbose_name_plural": "Pasos de onboarding",
                "db_table": "onboarding_onboarding_step",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Nombre"
                    ),
                ),
                (
                    "route_name",
                    models.CharField(
                        help_text="Identificador estable del onboarding (Odoo route_name; sin panel web, no define una ruta HTTP aquí).",
                        max_length=64,
                        unique=True,
                        verbose_name="Identificador de una palabra",
                    ),
                ),
                (
                    "text_completed",
                    models.CharField(
                        blank=True,
                        default="Nice work! Your configuration is done.",
                        help_text="Texto mostrado cuando el onboarding se completa.",
                        max_length=255,
                        verbose_name="Mensaje al completar",
                    ),
                ),
                (
                    "panel_close_action_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la acción de modelo a ejecutar al cerrar el panel.",
                        max_length=255,
                        verbose_name="Acción de cierre",
                    ),
                ),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                (
                    "steps",
                    models.ManyToManyField(
                        blank=True,
                        related_name="onboardings",
                        to="onboarding.onboardingonboardingstep",
                        verbose_name="Pasos del onboarding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Onboarding",
                "verbose_name_plural": "Onboardings",
                "db_table": "onboarding_onboarding",
                "ordering": ["sequence", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OnboardingProgressStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "step_state",
                    models.CharField(
                        choices=[
                            ("not_done", "Not done"),
                            ("just_done", "Just done"),
                            ("done", "Done"),
                        ],
                        default="not_done",
                        max_length=16,
                        verbose_name="Estado de progreso del paso",
                    ),
                ),
                (
                    "company_key",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "company_id", models.Value(0)
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress_step_records",
                        to="base.rescompany",
                        verbose_name="Empresa (si el paso es per-company)",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        help_text="Paso cuyo progreso trackea este registro (Odoo step_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_step_records",
                        to="onboarding.onboardingonboardingstep",
                        verbose_name="Paso del onboarding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de paso de onboarding",
                "verbose_name_plural": "Progresos de paso de onboarding",
                "db_table": "onboarding_progress_step",
            },
        ),
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_onboarding_closed",
                    models.BooleanField(default=False, verbose_name="¿Panel cerrado?"),
                ),
                (
                    "company_key",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.functions.comparison.Coalesce(
                            "company_id", models.Value(0)
                        ),
                        output_field=models.BigIntegerField(),
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress_records",
                        to="base.rescompany",
                        verbose_name="Empresa (si es per-company)",
                    ),
                ),
                (
                    "onboarding",
                    models.ForeignKey(
                        help_text="Onboarding cuyo progreso trackea este registro (Odoo onboarding_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="onboarding.onboardingonboarding",
                        verbose_name="Onboarding",
                    ),
                ),
                (
                    "progress_steps",
                    models.ManyToManyField(
                        blank=True,
                        related_name="progress_records",
                        to="onboarding.onboardingprogressstep",
                        verbose_name="Trackers de progreso de los pasos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de onboarding",
                "verbose_name_plural": "Progresos de onboarding",
                "db_table": "onboarding_progress",
            },
        ),
        migrations.AddConstraint(
            model_name="onboardingprogressstep",
            constraint=models.UniqueConstraint(
                fields=("step", "company_key"),
                name="onboarding_progress_step_company_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="onboardingprogress",
            constraint=models.UniqueConstraint(
                fields=("onboarding", "company_key"),
                name="onboarding_progress_company_uniq",
            ),
        ),
    ]
