# Generated by Django 6.0.5 on 2026-08-13 21:58

import addons.base_sparse_field.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SparseFieldsTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    addons.base_sparse_field.models.fields.Serialized(
                        verbose_name="Datos"
                    ),
                ),
            ],
            options={
                "verbose_name": "Prueba de campos dispersos",
                "verbose_name_plural": "Pruebas de campos dispersos",
                "db_table": "sparse_fields_test",
                "abstract": False,
                "managed": False,
            },
        ),
    ]
