"""Tablas laterales de ``website_sale`` — recuperación de carrito (tarea #258).

Las dos tablas que este addon estrena existen por la restricción de plataforma
que ``models/sale_order.py`` y ``models/website.py`` declaran como su D-1: el
autodetector atribuye la migración al ``app_label`` del **modelo**, así que las
columnas que la referencia añade a ``sale_order`` y a ``website`` no se pueden
crear desde aquí. La forma que el árbol ya usa para eso es la tabla lateral 1-1
propiedad del addon que extiende (``account_check_printing``, ``delivery``).

- ``website_sale_order_info`` ≙ ``website_id`` y ``cart_recovery_email_sent``
  de ``sale.order`` (``odoo19c: website_sale/models/sale_order.py:24-31``).
- ``website_sale_settings`` ≙ los cuatro campos ``cart_*``/
  ``send_abandoned_cart_email*`` de ``website``
  (``odoo19c: website_sale/models/website.py:98-115``).

``is_abandoned_cart`` **no** aparece: es ``store=False`` en la fuente, y aquí
un ``fields.NonStored``, que por construcción no genera columna.
"""
# Generated by Django 6.0.5 on 2026-08-18 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mail", "0004_seed_cron_email_queue"),
        ("sale", "0005_saleorder_validity_date"),
        # El autodetector propuso la última migración de ``website`` que hay en
        # disco; se ancla a la última **publicada** porque lo único que esta
        # tabla necesita de allá es que ``website.website`` exista, y ese
        # modelo ya está en 0007. Depender de una migración sin publicar ataría
        # este addon a un nombre que todavía puede cambiar.
        ("website", "0007_websiteroute_websitepage_websitemenu_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteSaleOrderInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart_recovery_email_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo cart_recovery_email_sent.",
                        verbose_name="Correo de recuperación ya enviado",
                    ),
                ),
                (
                    "sale_order",
                    models.OneToOneField(
                        help_text="Pedido al que pertenece esta información (Odoo _inherit sale.order).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_sale_info",
                        to="sale.saleorder",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        help_text="Sitio por el que se hizo el pedido (Odoo website_id, readonly).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_orders",
                        to="website.website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datos de tienda del pedido",
                "verbose_name_plural": "Datos de tienda de los pedidos",
                "db_table": "website_sale_order_info",
                "ordering": ["sale_order_id"],
            },
        ),
        migrations.CreateModel(
            name="WebsiteSaleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cart_abandoned_delay",
                    models.FloatField(
                        default=10.0,
                        help_text="Horas sin actividad tras las cuales el carrito se considera abandonado (Odoo cart_abandoned_delay).",
                        verbose_name="Retraso de abandono",
                    ),
                ),
                (
                    "send_abandoned_cart_email",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo send_abandoned_cart_email.",
                        verbose_name="Enviar correo a quien abandonó su carrito",
                    ),
                ),
                (
                    "send_abandoned_cart_email_activation_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que se activó el envío de recuperación; los carritos anteriores no se recuperan (Odoo send_abandoned_cart_email_activation_time, store=True).",
                        null=True,
                        verbose_name="Hora de activación del envío",
                    ),
                ),
                (
                    "cart_recovery_mail_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Plantilla que se envía al carrito abandonado (Odoo cart_recovery_mail_template_id). Vacío = la plantilla por defecto del addon.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="mail.mailtemplate",
                        verbose_name="Correo de recuperación de carrito",
                    ),
                ),
                (
                    "website",
                    models.OneToOneField(
                        help_text="Sitio al que aplica esta política (Odoo _inherit website).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_sale_settings",
                        to="website.website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Política de recuperación de carrito",
                "verbose_name_plural": "Políticas de recuperación de carrito",
                "db_table": "website_sale_settings",
                "ordering": ["website_id"],
            },
        ),
    ]
