# Generated by Django 6.0.5 on 2026-08-28 22:36

import addons.website_sale.models.website
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_seed_cron_email_queue"),
        ("sales_team", "0002_remove_crmteammember_uniq_crm_team_member_and_more"),
        ("website", "0009_websiteviewinfo"),
        ("website_sale", "0003_websitesalesettings_salesteam_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="websitesalesettings",
            name="website_sale_salesteam_nn",
        ),
        migrations.AlterField(
            model_name="websitesaleorderinfo",
            name="website",
            field=models.ForeignKey(
                db_column="website_id",
                help_text="Sitio por el que se hizo el pedido (Odoo website_id, readonly).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sale_orders",
                to="website.website",
            ),
        ),
        migrations.RenameField(
            model_name="websitesaleorderinfo",
            old_name="website",
            new_name="website_id",
        ),
        migrations.AlterField(
            model_name="websitesalesettings",
            name="cart_recovery_mail_template",
            field=models.ForeignKey(
                blank=True,
                db_column="cart_recovery_mail_template_id",
                help_text="Plantilla que se envía al carrito abandonado (Odoo cart_recovery_mail_template_id). Vacío = la plantilla por defecto del addon.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mail.mailtemplate",
                verbose_name="Correo de recuperación de carrito",
            ),
        ),
        migrations.RenameField(
            model_name="websitesalesettings",
            old_name="cart_recovery_mail_template",
            new_name="cart_recovery_mail_template_id",
        ),
        migrations.AlterField(
            model_name="websitesalesettings",
            name="salesteam",
            field=models.ForeignKey(
                blank=True,
                db_column="salesteam_id",
                default=addons.website_sale.models.website._default_salesteam_id,
                help_text="Equipo de venta al que se atribuyen los pedidos de este sitio (Odoo website.salesteam_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="websites",
                to="sales_team.crmteam",
                verbose_name="Equipo de venta",
            ),
        ),
        migrations.RenameField(
            model_name="websitesalesettings",
            old_name="salesteam",
            new_name="salesteam_id",
        ),
        migrations.AddIndex(
            model_name="websitesalesettings",
            index=models.Index(
                condition=models.Q(("salesteam_id__isnull", False)),
                fields=["salesteam_id"],
                name="website_sale_salesteam_nn",
            ),
        ),
    ]
