# Generated by Django 6.0.5 on 2026-08-19 04:55

import addons.hr_skills.models.hr_individual_skill_mixin
import addons.hr_skills.models.hr_skill_type
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0009_hremployeepublic"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrResumeLineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                ("is_course", models.BooleanField(default=False, verbose_name="Curso")),
                (
                    "resume_line_type_properties_definition",
                    models.JSONField(
                        blank=True,
                        help_text="Odoo resume_line_type_properties_definition — esquema de propiedades dinámicas para las líneas de este tipo (JSON en este árbol; src/orm/fields_properties.py).",
                        null=True,
                        verbose_name="Propiedades de sección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de línea de CV",
                "verbose_name_plural": "Tipos de línea de CV",
                "db_table": "hr_resume_line_type",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="HrSkillType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                ("sequence", models.IntegerField(default=0, verbose_name="Secuencia")),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "color",
                    models.IntegerField(
                        default=addons.hr_skills.models.hr_skill_type._get_default_color,
                        help_text="Odoo color — aleatorio 1-11 al crear (_get_default_color).",
                        verbose_name="Color",
                    ),
                ),
                (
                    "levels_count",
                    models.IntegerField(
                        default=0,
                        help_text="Odoo levels_count (compute+store, readonly=False) — nº de hr.skill.level ligados a este tipo. Recómputo: _compute_levels_count() (divergencia 1: sin @api.depends).",
                        verbose_name="Nº de niveles",
                    ),
                ),
                (
                    "is_certification",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo is_certification — si está marcado, este tipo se trata como certificación (fecha de validez, ícono).",
                        verbose_name="Certificación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de habilidad",
                "verbose_name_plural": "Tipos de habilidad",
                "db_table": "hr_skill_type",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="HrSkillLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "level_progress",
                    models.IntegerField(
                        default=0,
                        help_text="Odoo level_progress — de 0 por ciento (sin conocimiento) a 100 por ciento (dominio total).",
                        verbose_name="Progreso",
                    ),
                ),
                (
                    "default_level",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo default_level — si está marcado, este nivel se preselecciona al elegir esta habilidad.",
                        verbose_name="Nivel por defecto",
                    ),
                ),
                (
                    "skill_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_level_ids",
                        to="hr_skills.hrskilltype",
                        verbose_name="Tipo de habilidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nivel de habilidad",
                "verbose_name_plural": "Niveles de habilidad",
                "db_table": "hr_skill_level",
                "ordering": ["level_progress"],
            },
        ),
        migrations.CreateModel(
            name="HrSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                (
                    "skill_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_ids",
                        to="hr_skills.hrskilltype",
                        verbose_name="Tipo de habilidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades",
                "db_table": "hr_skill",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="HrJobSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Inicio de validez"
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de validez"
                    ),
                ),
                (
                    "display_warning_message",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo display_warning_message — poblado por _onchange_valid_date() (divergencia: sin motor de onchange, no auto-wireado).",
                        verbose_name="Mostrar advertencia",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_skill_ids",
                        to="hr.hrjob",
                        verbose_name="Puesto",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Odoo skill_id (compute+store, readonly=False, required) — poblado por _compute_skill_id() o directo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_set",
                        to="hr_skills.hrskill",
                        verbose_name="Habilidad",
                    ),
                ),
                (
                    "skill_level",
                    models.ForeignKey(
                        help_text="Odoo skill_level_id (compute+store, readonly=False, required) — poblado por _compute_skill_level_id() o directo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_level_set",
                        to="hr_skills.hrskilllevel",
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "skill_type",
                    models.ForeignKey(
                        default=addons.hr_skills.models.hr_individual_skill_mixin._default_skill_type,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_type_set",
                        to="hr_skills.hrskilltype",
                        verbose_name="Tipo de habilidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidad de puesto",
                "verbose_name_plural": "Habilidades de puesto",
                "db_table": "hr_job_skill",
                "ordering": ["skill_type", "-skill_level"],
            },
        ),
        migrations.CreateModel(
            name="HrEmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Inicio de validez"
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de validez"
                    ),
                ),
                (
                    "display_warning_message",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo display_warning_message — poblado por _onchange_valid_date() (divergencia: sin motor de onchange, no auto-wireado).",
                        verbose_name="Mostrar advertencia",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_skill_ids",
                        to="hr.hremployee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Odoo skill_id (compute+store, readonly=False, required) — poblado por _compute_skill_id() o directo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_set",
                        to="hr_skills.hrskill",
                        verbose_name="Habilidad",
                    ),
                ),
                (
                    "skill_level",
                    models.ForeignKey(
                        help_text="Odoo skill_level_id (compute+store, readonly=False, required) — poblado por _compute_skill_level_id() o directo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_level_set",
                        to="hr_skills.hrskilllevel",
                        verbose_name="Nivel",
                    ),
                ),
                (
                    "skill_type",
                    models.ForeignKey(
                        default=addons.hr_skills.models.hr_individual_skill_mixin._default_skill_type,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_skill_type_set",
                        to="hr_skills.hrskilltype",
                        verbose_name="Tipo de habilidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habilidad de empleado",
                "verbose_name_plural": "Habilidades de empleado",
                "db_table": "hr_employee_skill",
                "ordering": ["skill_type", "skill_level"],
            },
        ),
        migrations.CreateModel(
            name="HrResumeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "date_start",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(
                        default=0, help_text="Odoo duration.", verbose_name="Duración"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Odoo description (translate=True en la fuente — sin dispatcher de traducción en fields.Html, ver fields.Char.odoo_translate en la fachada).",
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[("external", "Externo")],
                        default="external",
                        max_length=16,
                        verbose_name="Tipo de curso",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#000000",
                        help_text="Odoo color (compute) — recómputo: _compute_color().",
                        max_length=16,
                        verbose_name="Color",
                    ),
                ),
                (
                    "external_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo external_url (compute, store=True) — recómputo: _compute_external_url().",
                        max_length=2048,
                        verbose_name="URL externa",
                    ),
                ),
                (
                    "certificate_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nombre de archivo del certificado",
                    ),
                ),
                (
                    "certificate_file",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Certificado"
                    ),
                ),
                (
                    "resume_line_properties",
                    models.JSONField(
                        blank=True,
                        help_text="Odoo resume_line_properties — esquema definido por line_type_id.resume_line_type_properties_definition (JSON en este árbol).",
                        null=True,
                        verbose_name="Propiedades",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_line_ids",
                        to="hr.hremployee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "line_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resume_line_ids",
                        to="hr_skills.hrresumelinetype",
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de CV",
                "verbose_name_plural": "Líneas de CV",
                "db_table": "hr_resume_line",
                "ordering": ["line_type", "-date_end", "-date_start"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("date_end__isnull", True),
                            ("date_start__lte", models.F("date_end")),
                            _connector="OR",
                        ),
                        name="hr_resume_line_date_chk",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="hrskilllevel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("level_progress__gte", 0), ("level_progress__lte", 100)
                ),
                name="hr_skill_level_progress_chk",
            ),
        ),
    ]
