# Generated by Django 6.0.5 on 2026-08-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrresumeline",
            name="certificate_filename",
            field=models.CharField(
                blank=True, default="", verbose_name="Nombre de archivo del certificado"
            ),
        ),
        migrations.AlterField(
            model_name="hrresumeline",
            name="color",
            field=models.CharField(
                default="#000000",
                help_text="Odoo color (compute) — recómputo: _compute_color().",
                verbose_name="Color",
            ),
        ),
        migrations.AlterField(
            model_name="hrresumeline",
            name="course_type",
            field=models.CharField(
                choices=[("external", "Externo")],
                default="external",
                verbose_name="Tipo de curso",
            ),
        ),
        migrations.AlterField(
            model_name="hrresumeline",
            name="external_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo external_url (compute, store=True) — recómputo: _compute_external_url().",
                verbose_name="URL externa",
            ),
        ),
        migrations.AlterField(
            model_name="hrresumeline",
            name="name",
            field=models.CharField(verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="hrresumelinetype",
            name="name",
            field=models.CharField(verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="hrskill",
            name="name",
            field=models.CharField(verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="hrskilllevel",
            name="name",
            field=models.CharField(verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="hrskilltype",
            name="name",
            field=models.CharField(verbose_name="Nombre"),
        ),
    ]
