# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sale", "0001_initial"),
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderSmsConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        help_text="SMS de confirmación emitido (Odoo sms.sms).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_confirmations",
                        to="sms.smssms",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Orden de venta (Odoo sale.order).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_confirmation",
                        to="sale.saleorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmación SMS de orden de venta",
                "verbose_name_plural": "Confirmaciones SMS de órdenes de venta",
                "db_table": "sale_order_sms_confirmation",
            },
        ),
    ]
