# Generated by Django 6.0.5 on 2026-07-19 05:13

import addons.mass_mailing.models.mailing_subscription
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mass_mailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingsubscription",
            name="confirmation_token",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Token del enlace de confirmacion (doble opt-in).",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mailingsubscription",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento de la confirmacion (nulo = pendiente doble opt-in).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mailingsubscription",
            name="unsubscribe_token",
            field=models.CharField(
                default=addons.mass_mailing.models.mailing_subscription._generate_unsubscribe_token,
                help_text="Token del enlace de baja (Odoo lo computa; aqui se almacena).",
                max_length=200,
                unique=True,
            ),
        ),
    ]
