# Generated by Django 6.0.5 on 2026-07-15 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
        ("users", "0002_mfadevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityuser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="tenancy.tenant",
                verbose_name="Tenant",
            ),
        ),
    ]
