# Generated by Django 6.0.5 on 2026-07-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("users", "0002_mfadevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="identityuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="company.company",
                verbose_name="Empresa",
            ),
        ),
    ]
