# Generated by Django 6.0.5 on 2026-08-02 20:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0002_initial"),
        ("company", "0001_initial"),
        ("delivery", "0001_initial"),
        ("product", "0001_initial"),
        ("sales_team", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Referencia SO (Odoo sale.order.name). NULL en borrador.",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "cart_token",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="Carrito anónimo — draft sin partner (paridad cart.cart_token).",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Cotización"),
                            ("sent", "Cotización enviada"),
                            ("sale", "Orden de venta"),
                            ("cancel", "Cancelada"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "date_order",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de la orden (Odoo date_order); se fija al confirmar.",
                        null=True,
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(
                        default=False,
                        help_text="Orden bloqueada, no modificable (Odoo locked).",
                    ),
                ),
                (
                    "guest_email",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Email del comprador anónimo (BR-011). Vacío si hay partner.",
                        max_length=254,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notas del comprador al confirmar (paridad orders.Order.notes).",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Motivo de la cancelación (comprador o admin).",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento de la cancelación. NULL si la orden no se canceló.",
                        null=True,
                    ),
                ),
                (
                    "amount_untaxed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Subtotal sin IVA, suma de líneas (Odoo amount_untaxed).",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="IVA de la orden, suma de líneas (Odoo amount_tax).",
                        max_digits=10,
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total de la orden, suma de líneas (Odoo amount_total).",
                        max_digits=10,
                    ),
                ),
                (
                    "admin_cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin que canceló. NULL si la canceló el comprador.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_cancelled_sale_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Método de envío elegido (Odoo sale.order.carrier_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_orders",
                        to="delivery.shippingmethod",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa dueña de la orden (Odoo company_id). NULL pre-backfill.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale_orders",
                        to="company.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Factura emitida de la orden (Odoo invoice_ids, 1:1).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="account.accountmove",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente (Odoo partner_id). NULL en carrito anónimo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equipo de venta atribuido (Odoo sale.order.team_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_orders",
                        to="sales_team.crmteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de venta",
                "verbose_name_plural": "Órdenes de venta",
                "db_table": "sale_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SaleOrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción de la línea (Odoo name).",
                        max_length=255,
                    ),
                ),
                (
                    "product_uom_qty",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Cantidad (Odoo product_uom_qty).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Odoo price_unit (IVA incl.).",
                        max_digits=12,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Descuento % de la línea (Odoo discount).",
                        max_digits=5,
                    ),
                ),
                (
                    "is_delivery",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="La línea representa el costo de envío (Odoo is_delivery).",
                    ),
                ),
                (
                    "is_reward",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="La línea representa un descuento/recompensa (precio negativo).",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Odoo order_id.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_line",
                        to="sale.saleorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Odoo product_id.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_order_lines",
                        to="product.productproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de orden de venta",
                "db_table": "sale_order_line",
            },
        ),
    ]
