# Generated by Django 6.0.5 on 2026-07-18 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
        ("sales_team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="team",
            field=models.ForeignKey(
                blank=True,
                help_text="Equipo de venta atribuido (Odoo sale.order.team_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_orders",
                to="sales_team.crmteam",
            ),
        ),
    ]
