# Generated by Django 6.0.5 on 2026-08-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
