# Generated by Django 6.0.5 on 2026-08-06 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
        ("base", "0007_alter_iractionsreport_report_type"),
        ("delivery", "0002_initial"),
        ("sale", "0002_seed_report_saleorder_view"),
        ("sales_team", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="saleorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("partner__isnull", False), ("state", "draft")),
                fields=("partner",),
                name="sale_order_un_draft_por_partner",
            ),
        ),
    ]
