# Generated by Django 6.0.5 on 2026-07-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0002_saleorder_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="delivery_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pendiente"),
                    ("started", "Iniciada"),
                    ("partial", "Entrega parcial"),
                    ("full", "Entregada"),
                ],
                help_text="Estado de entrega (Odoo sale.order.delivery_status).",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="qty_delivered",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Cantidad entregada (Odoo sale.order.line.qty_delivered).",
            ),
        ),
    ]
