# Generated by Django 6.0.5 on 2026-07-18 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_saleorder_delivery_status_and_more"),
        ("loyalty", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                help_text="Cupón aplicado (paridad cart.voucher; = sale_loyalty coupon).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_orders",
                to="loyalty.voucher",
            ),
        ),
    ]
