# Generated by Django 6.0.5 on 2026-07-18 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0004_saleorder_voucher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleorder",
            name="delivery_status",
        ),
        migrations.RemoveField(
            model_name="saleorderline",
            name="qty_delivered",
        ),
    ]
