# Generated by Django 6.0.5 on 2026-07-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0005_remove_saleorder_delivery_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleorder",
            name="voucher",
        ),
    ]
