# Generated by Django 6.0.5 on 2026-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0006_remove_saleorder_voucher"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="guest_email",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Email del comprador anónimo (BR-011). Vacío si hay partner.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notas del comprador al confirmar (paridad orders.Order.notes).",
            ),
        ),
    ]
