# Generated by Django 6.0.5 on 2026-07-26 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("sale", "0009_saleorder_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Factura emitida de la orden (Odoo invoice_ids, 1:1).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.accountmove",
            ),
        ),
    ]
