"""Paridad de campos ``SaleOrder`` — E1 del retiro de la entidad espejo.

Cuatro campos que el flujo vivo guardaba sólo en ``orders.Order`` y el
canónico no podía representar:

- ``carrier`` — método de envío elegido. Odoo ``sale.order.carrier_id``
  (``delivery/models/sale_order.py:13``), que el módulo ``delivery`` añade a
  ``sale.order``.
- ``admin_cancelled_by`` / ``cancellation_reason`` / ``cancelled_at`` —
  trazabilidad de cancelación (UC-ORD-04, UC-ORD-08). Sin equivalente en Odoo
  core: allí la cancelación es ``state='cancel'`` + el hilo de ``mail.thread``.

Aditiva y reversible: no toca los 20 consumidores del espejo ni el puente de
``sale/services.py``. Esos vienen en las rebanadas E2-E5.
"""
# Generated by Django 6.0.5 on 2026-07-28 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_shipmentguide_sale_order"),
        ("sale", "0010_saleorder_invoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="admin_cancelled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin que canceló. NULL si la canceló el comprador.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_cancelled_sale_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="cancellation_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Motivo de la cancelación (comprador o admin).",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento de la cancelación. NULL si la orden no se canceló.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                help_text="Método de envío elegido (Odoo sale.order.carrier_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_orders",
                to="delivery.shippingmethod",
            ),
        ),
    ]
