# Generated by Django 6.0.5 on 2026-07-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0011_saleorder_carrier_and_cancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorderline",
            name="is_delivery",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="La línea representa el costo de envío (Odoo is_delivery).",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="is_reward",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="La línea representa un descuento/recompensa (precio negativo).",
            ),
        ),
    ]
