# Generated by Django 6.0.5 on 2026-07-28 22:33
"""H-API-30 — materializa amount_untaxed/tax/total como columnas.

Las tres ``AddField`` las generó ``makemigrations sale``; el ``RunPython`` se
agrega a mano para dejar las órdenes **preexistentes** (las que se crearon
antes de que ``SaleOrder`` tuviera estas columnas, con default ``0.00``) con
su total real, en vez de en cero.

El backfill NO puede llamar a ``SaleOrderLine.price_total()``/``price_tax()``/
``price_subtotal()`` ni a ``SiteSettings.get_current()``: ``apps.get_model``
devuelve el modelo **histórico** (congelado a este punto del historial de
migraciones), que sólo conserva los campos, no los métodos custom del modelo
real. Por eso el cálculo se reimplementa aquí con los mismos campos crudos
(``price_unit``/``product_uom_qty``/``discount`` + la tasa de IVA vigente),
espejo de ``SaleOrderLine.price_total/tax/subtotal``
(``sale/models/sale_order_line.py:85-95``): redondeo **por línea**, no al
final — misma razón que fija ``tests/integration/sale/
test_amount_sql_paridad_e4.py::TestRedondeoPorLinea``.
"""
from decimal import Decimal

from django.db import migrations, models


def backfill_sale_order_amounts(apps, schema_editor):
    SaleOrder = apps.get_model('sale', 'SaleOrder')
    SaleOrderLine = apps.get_model('sale', 'SaleOrderLine')
    SiteSettings = apps.get_model('base', 'SiteSettings')

    settings_row, _created = SiteSettings.objects.get_or_create(pk=1)
    rate = settings_row.iva_rate

    for order in SaleOrder.objects.all().iterator():
        untaxed = Decimal('0.00')
        tax = Decimal('0.00')
        total = Decimal('0.00')
        for line in SaleOrderLine.objects.filter(order=order):
            line_total = (
                line.price_unit * line.product_uom_qty
                * (Decimal('1') - line.discount / Decimal('100'))
            ).quantize(Decimal('0.01'))
            line_tax = (line_total * rate / (1 + rate)).quantize(Decimal('0.01'))
            total += line_total
            tax += line_tax
            untaxed += (line_total - line_tax)
        order.amount_untaxed = untaxed
        order.amount_tax = tax
        order.amount_total = total
        order.save(update_fields=['amount_untaxed', 'amount_tax', 'amount_total'])


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0012_saleorderline_is_delivery_saleorderline_is_reward"),
        ('base', '0013_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="amount_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="IVA de la orden, suma de líneas (Odoo amount_tax).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="amount_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total de la orden, suma de líneas (Odoo amount_total).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="amount_untaxed",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Subtotal sin IVA, suma de líneas (Odoo amount_untaxed).",
                max_digits=10,
            ),
        ),
        migrations.RunPython(
            backfill_sale_order_amounts, migrations.RunPython.noop),
    ]
