# Generated by Django 6.0.5 on 2026-07-19 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0003_identityuser_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tech_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Nombre técnico del proveedor (Odoo tech_name, p.ej. "openstreetmap").',
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre visible del proveedor (Odoo name).",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "verbose_name": "Geo Provider",
                "verbose_name_plural": "Geo Providers",
                "db_table": "base_geo_provider",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="AddressGeolocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        default=0.0,
                        help_text="Latitud GPS (Odoo partner_latitude, base/res_partner.py:270).",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        default=0.0,
                        help_text="Longitud GPS (Odoo partner_longitude, base/res_partner.py:271).",
                    ),
                ),
                (
                    "date_localization",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la última geolocalización exitosa (Odoo date_localization, 19:10).",
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        help_text="Dirección a la que pertenece (Odoo res.partner).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geolocation",
                        to="users.address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geolocalización de dirección",
                "verbose_name_plural": "Geolocalizaciones de dirección",
                "db_table": "res_partner_geolocation",
            },
        ),
    ]
