# Generated by Django 6.0.5 on 2026-07-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReauthSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Sesión Django a la que se ata la reautenticación.",
                        max_length=40,
                        verbose_name="Clave de sesión",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="Iniciada")),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="Expira"),
                ),
                (
                    "ip_addr",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión reautenticada",
                "verbose_name_plural": "Sesiones reautenticadas",
                "db_table": "authz_reauth_session",
                "ordering": ["-started_at"],
            },
        ),
    ]
