# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authz_reauth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reauthsession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reauth_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="reauthsession",
            index=models.Index(
                fields=["user", "session_key", "expires_at"],
                name="authz_reaut_user_id_256fb4_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reauthsession",
            constraint=models.UniqueConstraint(
                fields=("user", "session_key"), name="uq_authz_reauth_session"
            ),
        ),
    ]
