# Generated by Django 6.0.5 on 2026-08-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mrp", "0001_initial"),
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderLineProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line",
                    models.OneToOneField(
                        help_text="Línea de venta origen (Odoo sale.order.line).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_link",
                        to="sale.saleorderline",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        blank=True,
                        help_text="Orden de fabricación (Odoo mrp.production).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_order_lines",
                        to="mrp.mrpproduction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fabricación de línea de orden de venta",
                "verbose_name_plural": "Fabricaciones de líneas de orden de venta",
                "db_table": "sale_order_line_production",
            },
        ),
    ]
