# Generated by Django 6.0.5 on 2026-08-28 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_team", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="crmteammember",
            name="uniq_crm_team_member",
        ),
        migrations.AlterField(
            model_name="crmteam",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_column="company_id",
                help_text="ResCompany propietaria (Odoo crm.team.company_id).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_teams",
                to="base.rescompany",
            ),
        ),
        migrations.RenameField(
            model_name="crmteam",
            old_name="company",
            new_name="company_id",
        ),
        migrations.AlterField(
            model_name="crmteammember",
            name="crm_team",
            field=models.ForeignKey(
                db_column="crm_team_id",
                help_text="Equipo (Odoo crm.team.member.crm_team_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_links",
                to="sales_team.crmteam",
            ),
        ),
        migrations.RenameField(
            model_name="crmteammember",
            old_name="crm_team",
            new_name="crm_team_id",
        ),
        migrations.AlterField(
            model_name="crmteammember",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                help_text="Vendedor (Odoo crm.team.member.user_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_team_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="crmteammember",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AddConstraint(
            model_name="crmteammember",
            constraint=models.UniqueConstraint(
                fields=("crm_team_id", "user_id"), name="uniq_crm_team_member"
            ),
        ),
    ]
