# Generated by Django 6.0.5 on 2026-08-28 23:18

import addons.sales_team.models.crm_tag
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_team", "0002_remove_crmteammember_uniq_crm_team_member_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmtag",
            name="color",
            field=models.IntegerField(
                default=addons.sales_team.models.crm_tag._get_default_color,
                help_text="Índice de color (Odoo crm.tag.color).",
            ),
        ),
    ]
