# Generated by Django 6.0.5 on 2026-08-28 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_team", "0003_alter_crmtag_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="crmteam",
            old_name="members",
            new_name="member_ids",
        ),
        migrations.AlterField(
            model_name="crmteam",
            name="leader",
            field=models.ForeignKey(
                blank=True,
                db_column="leader_id",
                help_text="Líder del equipo (Odoo crm.team.user_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_sales_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="crmteam",
            old_name="leader",
            new_name="user_id",
        ),
    ]
