# Generated by Django 6.0.5 on 2026-08-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_team", "0004_rename_members_crmteam_member_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmteammember",
            name="assignment_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo assignment_domain ("Assignment Domain").',
                max_length=255,
                verbose_name="Dominio de asignación",
            ),
        ),
        migrations.AddField(
            model_name="crmteammember",
            name="assignment_domain_preferred",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo assignment_domain_preferred ("Preference assignment Domain").',
                max_length=255,
                verbose_name="Dominio de asignación preferente",
            ),
        ),
        migrations.AddField(
            model_name="crmteammember",
            name="assignment_max",
            field=models.IntegerField(
                default=30,
                help_text='Odoo assignment_max ("Average Leads Capacity (on 30 days)").',
                verbose_name="Capacidad media (30 días)",
            ),
        ),
        migrations.AddField(
            model_name="crmteammember",
            name="assignment_optout",
            field=models.BooleanField(
                default=False,
                help_text='Odoo assignment_optout ("Pause assignment").',
                verbose_name="Pausar asignación",
            ),
        ),
    ]
