# Generated by Django 6.0.5 on 2026-08-29 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_team", "0005_crmteammember_assignment_domain_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmteammember",
            name="crm_team_id",
            field=models.ForeignKey(
                db_column="crm_team_id",
                help_text="Equipo (Odoo crm.team.member.crm_team_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crm_team_member_ids",
                to="sales_team.crmteam",
            ),
        ),
    ]
