# Generated by Django 6.0.5 on 2026-08-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales_team", "0006_alter_crmteammember_crm_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="crmteam",
            name="assignment_domain",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo assignment_domain ("Assignment Domain"): filtro adicional al buscar iniciativas sin asignar.',
                max_length=255,
                verbose_name="Dominio de asignación",
            ),
        ),
        migrations.AddField(
            model_name="crmteam",
            name="assignment_optout",
            field=models.BooleanField(
                default=False,
                help_text='Odoo assignment_optout ("Skip auto assignment").',
                verbose_name="Excluir del reparto automático",
            ),
        ),
        migrations.AddField(
            model_name="crmteam",
            name="lead_properties_definition",
            field=models.JSONField(
                blank=True,
                help_text='Odoo lead_properties_definition ("Lead Properties"): define las propiedades libres de crm.lead.',
                null=True,
                verbose_name="Propiedades de iniciativa",
            ),
        ),
        migrations.AddField(
            model_name="crmteam",
            name="use_leads",
            field=models.BooleanField(
                default=False,
                help_text='Odoo use_leads ("Leads"): calificar las peticiones entrantes antes de convertirlas en oportunidad.',
                verbose_name="Iniciativas",
            ),
        ),
        migrations.AddField(
            model_name="crmteam",
            name="use_opportunities",
            field=models.BooleanField(
                default=True,
                help_text='Odoo use_opportunities ("Pipeline").',
                verbose_name="Pipeline",
            ),
        ),
    ]
