# Generated by Django 6.0.5 on 2026-07-12 02:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("TEST", "Test (sandbox)"),
                            ("MERCADOPAGO", "MercadoPago"),
                            ("PAYPAL", "PayPal"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "credentials",
                    models.BinaryField(
                        help_text="Credenciales cifradas con Fernet (addons.settings_app.models._fernet_key)"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Pasarela de pago",
                "db_table": "settings_payment_gateway",
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo de envío. 0 = gratis.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("estimated_days", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "free_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("zones", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Método de envío",
                "db_table": "settings_shipping_method",
                "ordering": ["cost", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name",
                    models.CharField(default="PracticaYoruba", max_length=100),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logotipo del sitio para el recibo PDF (UC-PAY-10). PNG recomendado.",
                        null=True,
                        upload_to="settings/logo/",
                        verbose_name="Logotipo",
                    ),
                ),
                (
                    "iva_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.16"),
                        help_text="Tasa de IVA expresada como fracción decimal entre 0 y 1 (ej. 0.16 = 16%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN",
                        help_text="Código ISO 4217 de la moneda (3 letras mayúsculas).",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Currency must be a 3-letter ISO 4217 code (uppercase).",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "payment_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minutos hasta que una orden PENDING se cancela por timeout (UC-SYS-01).",
                    ),
                ),
                (
                    "order_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minutos antes de que una orden sin pagar expire (FR-CFG-03.01).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_return_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Días máximos para solicitar una devolución.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("min_stock_threshold", models.PositiveIntegerField(default=5)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "referral_active",
                    models.BooleanField(
                        default=False,
                        help_text="Si el programa de referidos esta activo (UC-PRO-05 PRE-02).",
                    ),
                ),
                (
                    "referral_welcome_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Descuento fijo del voucher de bienvenida emitido al nuevo comprador que canjea un codigo referral (UC-PRO-05 Subflujo B).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "referral_reward_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Descuento fijo del voucher de recompensa emitido al referidor cuando el referido completa su primera compra (UC-PRO-05 Subflujo C).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField(blank=True, default="")),
                ("social_links", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Configuración del sitio",
                "db_table": "settings_sitesettings",
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("about", "Acerca de nosotros"),
                            ("terms", "Términos y condiciones"),
                            ("privacy", "Política de privacidad"),
                            ("returns", "Política de devoluciones"),
                            ("faq", "Preguntas frecuentes"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Página estática",
                "db_table": "settings_static_page",
            },
        ),
        migrations.CreateModel(
            name="StaticPageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PUBLISHED", "Publicado"),
                            ("ARCHIVED", "Archivado"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_page_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="settings_app.staticpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de página estática",
                "db_table": "settings_static_page_version",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "version"), name="unique_static_page_version"
                    )
                ],
            },
        ),
    ]
