# Generated by Django 6.0.5 on 2026-07-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_banner"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="banner",
                    name="settings_ba_placeme_427603_idx",
                ),
                migrations.DeleteModel(
                    name="Banner",
                ),
                migrations.RemoveConstraint(
                    model_name="staticpageversion",
                    name="unique_static_page_version",
                ),
                migrations.RemoveField(
                    model_name="staticpageversion",
                    name="created_by",
                ),
                migrations.RemoveField(
                    model_name="staticpageversion",
                    name="page",
                ),
                migrations.DeleteModel(
                    name="StaticPage",
                ),
                migrations.DeleteModel(
                    name="StaticPageVersion",
                ),
            ],
            database_operations=[],
        ),
    ]
