# Generated by Django 6.0.5 on 2026-07-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_sitesettings"),
        ("settings_app", "0004_delete_paymentgateway"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="SiteSettings",
                ),
            ],
            database_operations=[],
        ),
    ]
