# Generated by Django 5.0.1 on 2026-05-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_admin_fields_statuslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden activa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='CancelledOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden cancelada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden entregada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='InPreparationOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden en preparación',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden pendiente',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='ProcessingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden en procesamiento',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='RefundedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden reembolsada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='ShippedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Orden enviada',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Orden'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item de orden'},
        ),
        migrations.AlterField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email del comprador invitado (BR-011).', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher_code',
            field=models.CharField(blank=True, default='', help_text='Código del voucher al momento del checkout.', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordervalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
