# Generated by Django 5.0.1 on 2026-05-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_squashed_0007_order_deleted_at_order_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddress",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ordervalue",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
