# Generated by Django 5.0.1 on 2026-05-23 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_seed_shipping_zones"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de pago"),
                    ("PROCESSING", "Procesando pago"),
                    ("PAGADA", "Pagada"),
                    ("IN_PREPARATION", "En preparación"),
                    ("SHIPPED", "Enviado"),
                    ("DELIVERED", "Entregado"),
                    ("CANCELLED", "Cancelado"),
                    ("REFUNDED", "Reembolsado"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="shippingzone",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="CheckoutAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100)),
                ("response_json", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkout attempt",
                "db_table": "orders_checkout_attempt",
                "unique_together": {("user", "idempotency_key")},
            },
        ),
    ]
