# Generated by Django 5.0.1 on 2026-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_merge_order_status_seed_zones"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente de pago"),
                    ("PROCESSING", "Procesando pago"),
                    ("PAGADA", "Pagada"),
                    ("IN_PREPARATION", "En preparación"),
                    ("SHIPPED", "Enviado"),
                    ("DELIVERED", "Entregado"),
                    ("CANCELLED", "Cancelado"),
                    ("CANCELLED_TIMEOUT", "Cancelado por timeout"),
                    ("REFUNDED", "Reembolsado"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
