# Generated by Django 5.0.1 on 2026-06-23 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0017_dedupe_shipping_zones_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActiveOrder",
        ),
        migrations.DeleteModel(
            name="CancelledOrder",
        ),
        migrations.DeleteModel(
            name="DeliveredOrder",
        ),
        migrations.DeleteModel(
            name="InPreparationOrder",
        ),
        migrations.DeleteModel(
            name="PendingOrder",
        ),
        migrations.DeleteModel(
            name="ProcessingOrder",
        ),
        migrations.DeleteModel(
            name="RefundedOrder",
        ),
        migrations.DeleteModel(
            name="ShippedOrder",
        ),
        migrations.AlterUniqueTogether(
            name="checkoutattempt",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="checkoutattempt",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="unique_checkout_attempt"
            ),
        ),
    ]
