# Generated by Django 6.0.5 on 2026-07-03 21:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0018_delete_activeorder_delete_cancelledorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzone",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo de envío específico de la zona. Vacío = usar el del método.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="estimated_days_max",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Días hábiles máximos de entrega en la zona.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="estimated_days_min",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Días hábiles mínimos de entrega en la zona.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
