# Generated by Django 6.0.5 on 2026-07-04 22:12

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_shippingzone_cost_shippingzone_estimated_days_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingzone",
            name="free_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Compra mínima para envío gratis en la zona. Vacío = usar el del método de envío.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
