# Generated by Django 6.0.5 on 2026-09-02 05:07

import django.db.models.deletion
import orm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Html_EditorConverterTestSub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "Html Editor Converter Subtest",
                "db_table": "html_editor_converter_test_sub",
            },
            bases=(
                orm.models.RecordLoaderMixin,
                orm.models.DisplayNameMixin,
                orm.models.OrderMixin,
                orm.models.CheckCompanyMixin,
                orm.models.BaseUrlMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Html_EditorConverterTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("char", models.CharField(blank=True, default="", max_length=255)),
                ("integer", models.IntegerField(default=0)),
                ("float", models.FloatField(default=0.0)),
                (
                    "numeric",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Odoo numeric = fields.Float(digits=(16, 2)).",
                        max_digits=16,
                        null=True,
                    ),
                ),
                ("binary", models.BinaryField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "selection_str",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Qu'il n'est pas arrivé à Toronto"),
                            ("B", "Qu'il était supposé arriver à Toronto"),
                            (
                                "C",
                                "Qu'est-ce qu'il fout ce maudit pancake, tabernacle ?",
                            ),
                            ("D", "La réponse D"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Lorsqu'un pancake prend l'avion à destination de Toronto et qu'il fait une escale technique à St Claude, on dit:",
                    ),
                ),
                ("html", models.TextField(blank=True, default="")),
                ("text", models.TextField(blank=True, default="")),
                (
                    "many2one",
                    models.ForeignKey(
                        blank=True,
                        db_column="many2one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="converter_tests",
                        to="html_editor.html_editorconvertertestsub",
                    ),
                ),
            ],
            options={
                "verbose_name": "Html Editor Converter Test",
                "db_table": "html_editor_converter_test",
            },
            bases=(
                orm.models.RecordLoaderMixin,
                orm.models.DisplayNameMixin,
                orm.models.OrderMixin,
                orm.models.CheckCompanyMixin,
                orm.models.BaseUrlMixin,
                models.Model,
            ),
        ),
    ]
