# Generated by Django 6.0.5 on 2026-08-28 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleordertemplateline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product_id",
                help_text="Producto (Odoo product_id); NULL en sección/nota.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_template_lines",
                to="product.productproduct",
            ),
        ),
        migrations.RenameField(
            model_name="saleordertemplateline",
            old_name="product",
            new_name="product_id",
        ),
    ]
