# Generated by Django 6.0.5 on 2026-08-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0029_rescompany_internal_project_id_and_more"),
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountEdiProxyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "id_client",
                    models.CharField(
                        help_text="Identificador asignado por el proxy (Odoo id_client, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "edi_identification",
                    models.CharField(
                        help_text="Identificador único del usuario (típicamente el RFC/VAT), requerido.",
                        max_length=255,
                    ),
                ),
                (
                    "refresh_token",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "is_token_out_of_sync",
                    models.BooleanField(
                        default=False,
                        help_text="El token quedó desincronizado con el proxy y necesita renovarse (Odoo is_token_out_of_sync).",
                    ),
                ),
                ("token_sync_version", models.IntegerField(default=0)),
                (
                    "proxy_type",
                    models.CharField(
                        blank=True,
                        choices=[],
                        default="",
                        help_text="Tipo de proxy — vacío hasta que un l10n_*_edi concreto declare valores (Odoo proxy_type, requerido allá).",
                        max_length=32,
                    ),
                ),
                (
                    "edi_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("prod", "Producción"),
                            ("test", "Prueba"),
                            ("demo", "Demo"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido). related_name da a res.company el O2M inverso sin tocar su archivo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_edi_proxy_client_ids",
                        to="base.rescompany",
                    ),
                ),
                (
                    "private_key",
                    models.ForeignKey(
                        help_text="Llave para cifrar los datos del usuario (Odoo private_key_id, requerido; domain público=False en la referencia, no reforzado a nivel de campo aquí).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="edi_proxy_users",
                        to="certificate.certificatekey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario del proxy EDI",
                "verbose_name_plural": "Usuarios del proxy EDI",
                "db_table": "account_edi_proxy_client_user",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("id_client",), name="uniq_edi_proxy_id_client"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("company", "proxy_type", "edi_mode"),
                        name="uniq_edi_proxy_active_company",
                    ),
                ],
            },
        ),
    ]
