# Generated by Django 6.0.5 on 2026-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_edi_proxy_client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountediproxyuser",
            name="proxy_type",
            field=models.CharField(
                blank=True,
                choices=[("peppol", "PEPPOL")],
                default="",
                help_text="Tipo de proxy — vacío hasta que un l10n_*_edi concreto declare valores (Odoo proxy_type, requerido allá).",
                max_length=32,
            ),
        ),
    ]
