# Generated by Django 6.0.5 on 2026-08-04 00:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfigSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_timeout_minutes", models.PositiveIntegerField(default=30)),
                ("order_timeout_minutes", models.PositiveIntegerField(default=60)),
                (
                    "site_name",
                    models.CharField(default="PracticaYoruba", max_length=100),
                ),
                (
                    "iva_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.16"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("max_return_days", models.PositiveIntegerField(default=30)),
                ("min_stock_threshold", models.PositiveIntegerField(default=5)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("999.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Ajustes generales del sitio",
                "db_table": "base_setup_siteconfigsettings_unmanaged",
                "managed": False,
            },
        ),
    ]
