# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebConfigSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "web_app_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre visible de la PWA (Odoo web_app_name, config_parameter=web.web_app_name).",
                        max_length=100,
                        verbose_name="Nombre de la app web",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajustes de la app web",
                "db_table": "web_webconfigsettings_unmanaged",
                "managed": False,
            },
        ),
    ]
