# Generated by Django 6.0.5 on 2026-08-03 22:04

import addons.stock.models.return_request
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("sale", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                ("order_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED_PRODUCT", "Producto danado"),
                            ("NOT_AS_DESCRIBED", "No coincide con la descripcion"),
                            ("CHANGED_MIND", "Cambio de opinion"),
                            ("OTHER", "Otro"),
                        ],
                        max_length=24,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pendiente de revision"),
                            ("INFO_REQUESTED", "Pendiente de informacion"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("RECEIVED", "Recibida"),
                            ("REFUNDED", "Reembolsada"),
                        ],
                        default="PENDING_REVIEW",
                        max_length=16,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("refund_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de devolucion",
                "verbose_name_plural": "Solicitudes de devolucion",
                "db_table": "return_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_id", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "product_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOD_CONDITION", "Buenas condiciones"),
                            ("DAMAGED", "Danado"),
                            ("INCOMPLETE", "Incompleto"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="stock.returnrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de devolucion",
                "verbose_name_plural": "Items de devolucion",
                "db_table": "return_item",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ReturnHistoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status_to",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pendiente de revision"),
                            ("INFO_REQUESTED", "Pendiente de informacion"),
                            ("APPROVED", "Aprobada"),
                            ("REJECTED", "Rechazada"),
                            ("RECEIVED", "Recibida"),
                            ("REFUNDED", "Reembolsada"),
                        ],
                        max_length=16,
                    ),
                ),
                ("justification", models.TextField(blank=True, default="")),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_history_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="stock.returnrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de historial de devolucion",
                "verbose_name_plural": "Entradas de historial de devoluciones",
                "db_table": "return_history_entry",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=addons.stock.models.return_request.return_evidence_upload_path
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="stock.returnrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia de devolucion",
                "verbose_name_plural": "Evidencias de devolucion",
                "db_table": "return_evidence",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la ubicación (Odoo stock.location.name).",
                        max_length=100,
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("supplier", "Proveedor"),
                            ("view", "Virtual"),
                            ("internal", "Interna"),
                            ("customer", "Cliente"),
                            ("inventory", "Pérdida de inventario"),
                            ("production", "Producción"),
                            ("transit", "Tránsito"),
                        ],
                        default="internal",
                        help_text="Tipo de ubicación (Odoo stock.location.usage).",
                        max_length=16,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación padre (Odoo location_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_ids",
                        to="stock.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación de inventario",
                "verbose_name_plural": "Ubicaciones de inventario",
                "db_table": "stock_location",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Número de lote / serie (Odoo stock.lot.name, requerido).",
                        max_length=120,
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia interna (Odoo stock.lot.ref).",
                        max_length=120,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto (Odoo product_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lots",
                        to="product.productproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote / número de serie",
                "verbose_name_plural": "Lotes / números de serie",
                "db_table": "stock_lot",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockPicking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia (Odoo stock.picking.name).",
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("waiting", "Esperando otro movimiento"),
                            ("confirmed", "Esperando"),
                            ("assigned", "Disponible"),
                            ("done", "Hecho"),
                            ("cancel", "Cancelada"),
                        ],
                        default="draft",
                        help_text="Estado (Odoo stock.picking.state).",
                        max_length=16,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Origen (Odoo location_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickings_out",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_dest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destino (Odoo location_dest_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickings_in",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "sale_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Orden de venta (Odoo stock.picking.sale_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickings",
                        to="sale.saleorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferencia de inventario",
                "verbose_name_plural": "Transferencias de inventario",
                "db_table": "stock_picking",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción (Odoo stock.move.name).",
                        max_length=255,
                    ),
                ),
                (
                    "product_uom_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad demandada (Odoo product_uom_qty).",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad reservada/hecha (Odoo stock.move.quantity).",
                        max_digits=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Nuevo"),
                            ("waiting", "Esperando otro movimiento"),
                            ("confirmed", "Esperando disponibilidad"),
                            ("assigned", "Disponible"),
                            ("done", "Hecho"),
                            ("cancel", "Cancelado"),
                        ],
                        default="draft",
                        help_text="Estado (Odoo stock.move.state).",
                        max_length=16,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Ubicación origen (Odoo location_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_out",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_dest",
                    models.ForeignKey(
                        help_text="Ubicación destino (Odoo location_dest_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_in",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "move_orig",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Movimientos origen que abastecen a éste (Odoo move_orig_ids).",
                        related_name="move_dest",
                        to="stock.stockmove",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto (Odoo product_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_moves",
                        to="product.productproduct",
                    ),
                ),
                (
                    "picking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transferencia (Odoo picking_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_ids",
                        to="stock.stockpicking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "db_table": "stock_move",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockQuant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad a la mano (Odoo stock.quant.quantity).",
                        max_digits=12,
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad reservada (Odoo reserved_quantity).",
                        max_digits=12,
                    ),
                ),
                (
                    "in_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha de entrada al quant (Odoo stock.quant.in_date; clave de orden de la estrategia FIFO).",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Ubicación (Odoo location_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quants",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote / número de serie (Odoo lot_id). NULL = sin lote.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quants",
                        to="stock.stocklot",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto (Odoo product_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quants",
                        to="product.productproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Existencia de inventario",
                "verbose_name_plural": "Existencias de inventario",
                "db_table": "stock_quant",
            },
        ),
        migrations.CreateModel(
            name="StockRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la regla (Odoo stock.rule.name).",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pull", "Extraer de"),
                            ("push", "Empujar a"),
                            ("pull_push", "Extraer y empujar"),
                        ],
                        default="pull",
                        help_text="Acción (Odoo stock.rule.action).",
                        max_length=16,
                    ),
                ),
                (
                    "procure_method",
                    models.CharField(
                        choices=[
                            ("make_to_stock", "Tomar de existencias"),
                            ("make_to_order", "Disparar otra regla"),
                        ],
                        default="make_to_stock",
                        help_text="Método de aprovisionamiento (Odoo procure_method).",
                        max_length=16,
                    ),
                ),
                (
                    "location_dest",
                    models.ForeignKey(
                        help_text="Ubicación destino (Odoo location_dest_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules_in",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_src",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación origen (Odoo location_src_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules_out",
                        to="stock.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de aprovisionamiento",
                "verbose_name_plural": "Reglas de aprovisionamiento",
                "db_table": "stock_rule",
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["user", "status"], name="return_requ_user_id_24a4d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["status", "created_at"], name="return_requ_status_f0f3fe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_lot_product_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockquant",
            constraint=models.UniqueConstraint(
                fields=("product", "location", "lot"),
                name="unique_quant_product_location_lot",
            ),
        ),
    ]
