# Generated by Django 6.0.5 on 2026-08-14 19:58

import datetime
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_irmodelfields_serialization_field_id_and_more"),
        ("product", "0005_expiry_and_tracking_surface"),
        ("stock", "0002_stock_lot_expiry_dates"),
        ("uom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductRemoval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la estrategia (Odoo name).",
                        max_length=120,
                        verbose_name="Name",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="FIFO, LIFO... — aquí además FEFO, closest y least_packages (Odoo method).",
                        max_length=32,
                        verbose_name="Method",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estrategia de retiro",
                "verbose_name_plural": "Estrategias de retiro",
                "db_table": "product_removal",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockWarehouseResupply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reabastecimiento entre almacenes",
                "verbose_name_plural": "Reabastecimientos entre almacenes",
                "db_table": "stock_wh_resupply_table",
            },
        ),
        migrations.AlterModelOptions(
            name="stocklocation",
            options={
                "ordering": ["complete_name", "id"],
                "verbose_name": "Ubicación de inventario",
                "verbose_name_plural": "Ubicaciones de inventario",
            },
        ),
        migrations.AlterModelOptions(
            name="stockquant",
            options={
                "ordering": ["in_date", "id"],
                "verbose_name": "Existencia de inventario",
                "verbose_name_plural": "Existencias de inventario",
            },
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Al desmarcarlo se oculta la ubicación sin borrarla (Odoo active).",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="barcode",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de barras de la ubicación (Odoo barcode).",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa; vacío si la ubicación es compartida (Odoo company_id).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_locations",
                to="base.rescompany",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="complete_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre jerárquico completo (Odoo complete_name, almacenado).",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="cyclic_inventory_frequency",
            field=models.IntegerField(
                default=0,
                help_text="Días entre conteos cíclicos; 0 desactiva (Odoo cyclic_inventory_frequency).",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="last_inventory_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha del último inventario (Odoo last_inventory_date).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="next_inventory_date",
            field=models.DateField(
                blank=True,
                help_text="Próximo conteo planeado (Odoo next_inventory_date, almacenado).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="parent_path",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Ruta materializada «1/4/9/» del árbol (Odoo parent_path).",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="replenish_location",
            field=models.BooleanField(
                default=False,
                help_text="Dispara sugerencias de reabastecimiento (Odoo replenish_location).",
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa (Odoo company_id, related a location_id.company_id con store=True; se recalcula en save()).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_quants",
                to="base.rescompany",
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="inventory_date",
            field=models.DateField(
                blank=True,
                help_text="Próximo conteo planeado (Odoo inventory_date, almacenado y editable: readonly=False en la referencia).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="inventory_diff_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Diferencia contada − teórica (Odoo inventory_diff_quantity, almacenado; lo recalcula compute_inventory_diff_quantity).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="inventory_quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Cantidad contada (Odoo inventory_quantity).",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="inventory_quantity_set",
            field=models.BooleanField(
                default=False,
                help_text="Marca que alguien ya fijó la cantidad contada (Odoo inventory_quantity_set, almacenado y editable).",
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Propietario de la existencia (Odoo owner_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_quants",
                to="base.respartner",
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario asignado al conteo (Odoo user_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_quants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación padre que la contiene (Odoo location_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_ids",
                to="stock.stocklocation",
            ),
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="name",
            field=models.CharField(
                help_text="Nombre de la ubicación (Odoo name, requerido).",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="usage",
            field=models.CharField(
                choices=[
                    ("supplier", "Proveedor"),
                    ("view", "Virtual"),
                    ("internal", "Interna"),
                    ("customer", "Cliente"),
                    ("inventory", "Pérdida de inventario"),
                    ("production", "Producción"),
                    ("transit", "Tránsito"),
                ],
                db_index=True,
                default="internal",
                help_text="Tipo de ubicación (Odoo usage, requerido).",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PickingTypeFavoriteUserRel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de operación favorito",
                "verbose_name_plural": "Tipos de operación favoritos",
                "db_table": "picking_type_favorite_user_rel",
            },
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="removal_strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Estrategia de retiro por defecto: FIFO, LIFO, cercanía, menos paquetes o FEFO (Odoo removal_strategy_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_ids",
                to="stock.productremoval",
            ),
        ),
        migrations.CreateModel(
            name="StockMoveLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Cantidad en la unidad de la línea (Odoo quantity, compute+store con readonly=False).",
                        max_digits=16,
                    ),
                ),
                (
                    "quantity_product_uom",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="La misma cantidad en la unidad del producto (Odoo quantity_product_uom, compute+store).",
                        max_digits=16,
                    ),
                ),
                (
                    "picked",
                    models.BooleanField(
                        default=False,
                        help_text="La línea ya fue tomada (Odoo picked, compute+store con readonly=False).",
                    ),
                ),
                (
                    "lot_name",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del lote cuando aún no existe el registro (Odoo lot_name); lo materializa _create_and_assign_production_lot.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "is_entire_pack",
                    models.BooleanField(
                        default=False,
                        help_text="La línea entró por un paquete completo (Odoo is_entire_pack).",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha de creación, actualizada al aumentar cantidad, al marcarse tomada o al terminar (Odoo date).",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Estado heredado del movimiento (Odoo state, related+store; lo recalcula save()).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que la mercancía de esta línea deja de ser consumible (Odoo expiration_date).",
                        null=True,
                    ),
                ),
                (
                    "removal_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que la mercancía debe retirarse; clave del orden FEFO (Odoo removal_date).",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, readonly+required; se recalcula en save() desde el movimiento o el albarán).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_move_lines",
                        to="base.rescompany",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Ubicación de origen (Odoo location_id, compute+store).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="move_line_ids",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_dest",
                    models.ForeignKey(
                        help_text="Ubicación de destino (Odoo location_dest_id, compute+store).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dest_move_line_ids",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote / número de serie (Odoo lot_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_line_ids",
                        to="stock.stocklot",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        help_text="Movimiento de inventario al que pertenece (Odoo move_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_line_ids",
                        to="stock.stockmove",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Propietario de la mercancía en origen (Odoo owner_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_move_lines",
                        to="base.respartner",
                    ),
                ),
                (
                    "picking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transferencia donde se hizo el empaque (Odoo picking_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_line_ids",
                        to="stock.stockpicking",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto (Odoo product_id; el dominio excluye servicios).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_move_lines",
                        to="product.productproduct",
                    ),
                ),
                (
                    "product_uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unidad de la línea (Odoo product_uom_id, compute+store; la recalcula _compute_product_uom_id).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_move_lines",
                        to="uom.uom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de movimiento de inventario",
                "verbose_name_plural": "Líneas de movimiento de inventario",
                "db_table": "stock_move_line",
                "ordering": ["-result_package", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockMoveLineConsumeRel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consume_line",
                    models.ForeignKey(
                        help_text="Línea consumida (Odoo consume_line_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stock.stockmoveline",
                    ),
                ),
                (
                    "produce_line",
                    models.ForeignKey(
                        help_text="Línea producida (Odoo produce_line_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="stock.stockmoveline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relación consumo/producción de líneas",
                "verbose_name_plural": "Relaciones consumo/producción de líneas",
                "db_table": "stock_move_line_consume_rel",
            },
        ),
        migrations.AddField(
            model_name="stockmoveline",
            name="consume_line_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Líneas consumidas por ésta (Odoo consume_line_ids).",
                related_name="+",
                through="stock.StockMoveLineConsumeRel",
                through_fields=("consume_line", "produce_line"),
                to="stock.stockmoveline",
            ),
        ),
        migrations.CreateModel(
            name="StockPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Referencia del paquete (Odoo name, requerido).",
                        max_length=120,
                    ),
                ),
                (
                    "complete_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre jerárquico «A > B > C» (Odoo complete_name, almacenado).",
                        max_length=512,
                    ),
                ),
                (
                    "shipping_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Peso total declarado del paquete (Odoo shipping_weight).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pack_date",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Fecha de empaquetado (Odoo pack_date).",
                    ),
                ),
                (
                    "parent_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Ruta materializada del árbol de contenedores ACTUALES (Odoo parent_path).",
                        max_length=512,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa, derivada de su contenido (Odoo company_id, computado y almacenado).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_packages",
                        to="base.rescompany",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación actual, derivada de su contenido (Odoo location_id, computado y almacenado).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_ids",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "package_dest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contenedor DESTINO al validar (Odoo package_dest_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_package_dest_ids",
                        to="stock.stockpackage",
                    ),
                ),
                (
                    "parent_package",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contenedor ACTUAL (Odoo parent_package_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_package_ids",
                        to="stock.stockpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paquete",
                "verbose_name_plural": "Paquetes",
                "db_table": "stock_package",
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="stockmoveline",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="Paquete de origen (Odoo package_id).",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="source_move_line_ids",
                to="stock.stockpackage",
            ),
        ),
        migrations.AddField(
            model_name="stockmoveline",
            name="result_package",
            field=models.ForeignKey(
                blank=True,
                help_text="Paquete de destino (Odoo result_package_id).",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="move_line_ids",
                to="stock.stockpackage",
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="package",
            field=models.ForeignKey(
                blank=True,
                help_text="Paquete que contiene esta existencia (Odoo package_id).",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="quant_ids",
                to="stock.stockpackage",
            ),
        ),
        migrations.CreateModel(
            name="StockPackageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package_name",
                    models.CharField(
                        help_text="Nombre completo del paquete al momento del movimiento (Odoo package_name, requerido).",
                        max_length=512,
                    ),
                ),
                (
                    "parent_orig_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre del contenedor de origen (Odoo parent_orig_name).",
                        max_length=512,
                    ),
                ),
                (
                    "parent_dest_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre del contenedor de destino (Odoo parent_dest_name).",
                        max_length=512,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_histories",
                        to="base.rescompany",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación de origen (Odoo location_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_history_origins",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_dest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación de destino (Odoo location_dest_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_history_destinations",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "outermost_dest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contenedor destino más externo (Odoo outermost_dest_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_as_outermost_container",
                        to="stock.stockpackage",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        help_text="Paquete movido (Odoo package_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_ids",
                        to="stock.stockpackage",
                    ),
                ),
                (
                    "parent_dest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contenedor de destino (Odoo parent_dest_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_as_dest_container",
                        to="stock.stockpackage",
                    ),
                ),
                (
                    "parent_orig",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contenedor de origen (Odoo parent_orig_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_as_origin_container",
                        to="stock.stockpackage",
                    ),
                ),
                (
                    "picking_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Transferencias implicadas (Odoo picking_ids).",
                        related_name="package_history_ids",
                        to="stock.stockpicking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de paquete",
                "verbose_name_plural": "Historiales de paquete",
                "db_table": "stock_package_history",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="stockmoveline",
            name="package_history",
            field=models.ForeignKey(
                blank=True,
                help_text="Instantánea del paquete al momento del movimiento (Odoo package_history_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="move_line_ids",
                to="stock.stockpackagehistory",
            ),
        ),
        migrations.CreateModel(
            name="StockPackageType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo de paquete (Odoo name, requerido).",
                        max_length=120,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Orden; el primero es el tipo por defecto (Odoo sequence).",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Alto del embalaje (Odoo height).",
                        max_digits=12,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Ancho del embalaje (Odoo width).",
                        max_digits=12,
                    ),
                ),
                (
                    "packaging_length",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Largo del embalaje (Odoo packaging_length).",
                        max_digits=12,
                    ),
                ),
                (
                    "base_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Peso del propio embalaje vacío (Odoo base_weight).",
                        max_digits=12,
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Peso máximo embarcable en este embalaje (Odoo max_weight).",
                        max_digits=12,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código de barras del tipo de paquete (Odoo barcode).",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "package_use",
                    models.CharField(
                        choices=[
                            ("disposable", "Caja desechable"),
                            ("reusable", "Caja reutilizable (tote)"),
                        ],
                        default="disposable",
                        help_text="Las cajas reutilizables se usan en preparación por lotes y se vacían después; al escanear una desechable, sus productos se añaden a la transferencia (Odoo package_use).",
                        max_length=12,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_types",
                        to="base.rescompany",
                    ),
                ),
                (
                    "sequence_ref",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secuencia de numeración de los paquetes de este tipo (Odoo sequence_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="package_types",
                        to="base.irsequence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de paquete",
                "verbose_name_plural": "Tipos de paquete",
                "db_table": "stock_package_type",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.AddField(
            model_name="stockpackage",
            name="package_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de paquete (Odoo package_type_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="package_ids",
                to="stock.stockpackagetype",
            ),
        ),
        migrations.CreateModel(
            name="StockPickingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo de operación (Odoo name).",
                        max_length=100,
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=0, help_text="Color del kanban (Odoo color)."
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0,
                        help_text="Orden en la vista «Todas las operaciones» (Odoo sequence).",
                    ),
                ),
                (
                    "sequence_code",
                    models.CharField(
                        help_text="Prefijo de la secuencia (Odoo sequence_code).",
                        max_length=32,
                        verbose_name="Sequence Prefix",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("incoming", "Recepción"),
                            ("outgoing", "Entrega"),
                            ("internal", "Transferencia interna"),
                        ],
                        default="incoming",
                        help_text="Tipo de operación (Odoo code, requerido).",
                        max_length=16,
                    ),
                ),
                (
                    "show_entire_packs",
                    models.BooleanField(
                        default=False,
                        help_text="Mostrar paquetes completos en vez de su contenido (Odoo show_entire_packs).",
                    ),
                ),
                (
                    "set_package_type",
                    models.BooleanField(
                        default=False,
                        help_text="Permite elegir el tipo de paquete al empaquetar (Odoo set_package_type).",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Al desmarcarlo se archiva sin borrar (Odoo active).",
                    ),
                ),
                (
                    "use_create_lots",
                    models.BooleanField(
                        default=True,
                        help_text="Permite crear lotes/series nuevos (Odoo use_create_lots, almacenado).",
                    ),
                ),
                (
                    "use_existing_lots",
                    models.BooleanField(
                        default=True,
                        help_text="Permite elegir lotes/series existentes (Odoo use_existing_lots, almacenado).",
                    ),
                ),
                (
                    "print_label",
                    models.BooleanField(
                        default=False,
                        help_text="Genera etiqueta de envío al validar (Odoo print_label, almacenado).",
                    ),
                ),
                (
                    "show_operations",
                    models.BooleanField(
                        default=False,
                        help_text="Muestra las operaciones detalladas (Odoo show_operations).",
                    ),
                ),
                (
                    "reservation_method",
                    models.CharField(
                        choices=[
                            ("at_confirm", "Al confirmar"),
                            ("manual", "Manualmente"),
                            ("by_date", "Antes de la fecha prevista"),
                        ],
                        default="at_confirm",
                        help_text="Cuándo se reservan los productos (Odoo reservation_method).",
                        max_length=16,
                    ),
                ),
                (
                    "reservation_days_before",
                    models.IntegerField(
                        default=0,
                        help_text="Días máximos antes de la fecha prevista para reservar (Odoo reservation_days_before).",
                    ),
                ),
                (
                    "reservation_days_before_priority",
                    models.IntegerField(
                        default=0,
                        help_text="Días máximos para reservar cuando la transferencia es prioritaria (Odoo reservation_days_before_priority).",
                    ),
                ),
                (
                    "auto_show_reception_report",
                    models.BooleanField(
                        default=False,
                        help_text="Muestra el informe de recepción al validar (Odoo auto_show_reception_report).",
                    ),
                ),
                (
                    "auto_print_delivery_slip",
                    models.BooleanField(
                        default=False,
                        help_text="Imprime el albarán de entrega al validar (Odoo auto_print_delivery_slip).",
                    ),
                ),
                (
                    "auto_print_return_slip",
                    models.BooleanField(
                        default=False,
                        help_text="Imprime el comprobante de devolución al validar (Odoo auto_print_return_slip).",
                    ),
                ),
                (
                    "auto_print_product_labels",
                    models.BooleanField(
                        default=False,
                        help_text="Imprime las etiquetas de producto al validar (Odoo auto_print_product_labels).",
                    ),
                ),
                (
                    "product_label_format",
                    models.CharField(
                        choices=[
                            ("dymo", "Dymo"),
                            ("2x7xprice", "2 × 7 con precio"),
                            ("4x7xprice", "4 × 7 con precio"),
                            ("4x12", "4 × 12"),
                            ("4x12xprice", "4 × 12 con precio"),
                            ("zpl", "Etiquetas ZPL"),
                            ("zplxprice", "Etiquetas ZPL con precio"),
                        ],
                        default="2x7xprice",
                        help_text="Formato de etiqueta de producto (Odoo product_label_format).",
                        max_length=16,
                    ),
                ),
                (
                    "auto_print_lot_labels",
                    models.BooleanField(
                        default=False,
                        help_text="Imprime las etiquetas de lote/serie al validar (Odoo auto_print_lot_labels).",
                    ),
                ),
                (
                    "lot_label_format",
                    models.CharField(
                        choices=[
                            ("4x12_lots", "4 × 12 — una por lote/serie"),
                            ("4x12_units", "4 × 12 — una por unidad"),
                            ("zpl_lots", "Etiquetas ZPL — una por lote/serie"),
                            ("zpl_units", "Etiquetas ZPL — una por unidad"),
                        ],
                        default="4x12_lots",
                        help_text="Formato de etiqueta de lote/serie (Odoo lot_label_format).",
                        max_length=16,
                    ),
                ),
                (
                    "auto_print_reception_report",
                    models.BooleanField(
                        default=False,
                        help_text="Imprime el informe de recepción al validar (Odoo auto_print_reception_report).",
                    ),
                ),
                (
                    "auto_print_reception_report_labels",
                    models.BooleanField(
                        default=False,
                        help_text="Imprime las etiquetas del informe de recepción al validar (Odoo auto_print_reception_report_labels).",
                    ),
                ),
                (
                    "auto_print_packages",
                    models.BooleanField(
                        default=False,
                        help_text="Imprime los paquetes y su contenido al validar (Odoo auto_print_packages).",
                    ),
                ),
                (
                    "auto_print_package_label",
                    models.BooleanField(
                        default=False,
                        help_text="Imprime la etiqueta del paquete al empaquetar (Odoo auto_print_package_label).",
                    ),
                ),
                (
                    "package_label_to_print",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("zpl", "ZPL")],
                        default="pdf",
                        help_text="Formato de la etiqueta de paquete (Odoo package_label_to_print).",
                        max_length=8,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código de barras del tipo (Odoo barcode).",
                        max_length=64,
                    ),
                ),
                (
                    "create_backorder",
                    models.CharField(
                        choices=[
                            ("ask", "Preguntar"),
                            ("always", "Siempre"),
                            ("never", "Nunca"),
                        ],
                        default="ask",
                        help_text="Qué hacer con lo que queda al validar (Odoo create_backorder).",
                        max_length=8,
                    ),
                ),
                (
                    "picking_properties_definition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Definición de propiedades de la transferencia (Odoo picking_properties_definition).",
                        verbose_name="Picking Properties",
                    ),
                ),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("direct", "En cuanto sea posible"),
                            ("one", "Cuando todos los productos estén listos"),
                        ],
                        default="direct",
                        help_text="Política de envío: parcial o todo junto (Odoo move_type).",
                        max_length=8,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa dueña del tipo (Odoo company_id, requerido).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picking_types",
                        to="base.rescompany",
                    ),
                ),
                (
                    "default_location_dest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación de destino por defecto (Odoo default_location_dest_id, almacenado).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="picking_types_dest",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "default_location_src",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación de origen por defecto (Odoo default_location_src_id, almacenado).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="picking_types_src",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "favorite_user_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Usuarios que marcaron el tipo como favorito (Odoo favorite_user_ids).",
                        related_name="favorite_picking_types",
                        through="stock.PickingTypeFavoriteUserRel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_picking_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tipo de operación para devoluciones (Odoo return_picking_type_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returned_by",
                        to="stock.stockpickingtype",
                    ),
                ),
                (
                    "sequence_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Secuencia de referencia (Odoo sequence_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picking_types",
                        to="base.irsequence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de operación",
                "verbose_name_plural": "Tipos de operación",
                "db_table": "stock_picking_type",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.AddField(
            model_name="pickingtypefavoriteuserrel",
            name="picking_type",
            field=models.ForeignKey(
                db_column="picking_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="stock.stockpickingtype",
                verbose_name="Tipo de operación",
            ),
        ),
        migrations.CreateModel(
            name="StockRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la ruta (Odoo name, requerido, traducible).",
                        max_length=120,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Al desmarcarlo se oculta la ruta sin borrarla (Odoo active).",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0, help_text="Orden de evaluación (Odoo sequence)."
                    ),
                ),
                (
                    "product_selectable",
                    models.BooleanField(
                        default=True,
                        help_text="Seleccionable en la pestaña Inventario del producto (Odoo product_selectable).",
                    ),
                ),
                (
                    "product_categ_selectable",
                    models.BooleanField(
                        default=False,
                        help_text="Seleccionable en la categoría de producto (Odoo product_categ_selectable).",
                    ),
                ),
                (
                    "warehouse_selectable",
                    models.BooleanField(
                        default=False,
                        help_text="Seleccionable en el almacén; al elegirlo, es la ruta por defecto de lo que pase por él (Odoo warehouse_selectable).",
                    ),
                ),
                (
                    "package_type_selectable",
                    models.BooleanField(
                        default=False,
                        help_text="Seleccionable en el tipo de paquete (Odoo package_type_selectable).",
                    ),
                ),
                (
                    "categ_ids",
                    models.ManyToManyField(
                        blank=True,
                        db_table="stock_route_categ",
                        help_text="Categorías que declaran esta ruta (Odoo categ_ids).",
                        related_name="route_ids",
                        to="product.productcategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa; vacío si la ruta es compartida (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_routes",
                        to="base.rescompany",
                    ),
                ),
                (
                    "product_ids",
                    models.ManyToManyField(
                        blank=True,
                        db_table="stock_route_product",
                        help_text="Productos que declaran esta ruta (Odoo product_ids).",
                        related_name="route_ids",
                        to="product.producttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta de inventario",
                "verbose_name_plural": "Rutas de inventario",
                "db_table": "stock_route",
                "ordering": ["sequence"],
            },
        ),
        migrations.AddField(
            model_name="stockpackagetype",
            name="route_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Rutas aplicables a este tipo de paquete (Odoo route_ids).",
                related_name="package_type_ids",
                to="stock.stockroute",
            ),
        ),
        migrations.CreateModel(
            name="StockStorageCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la categoría de almacenamiento (Odoo name).",
                        max_length=120,
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Peso máximo admitido (Odoo max_weight, digits Stock Weight).",
                        max_digits=12,
                    ),
                ),
                (
                    "allow_new_product",
                    models.CharField(
                        choices=[
                            ("empty", "Si la ubicación está vacía"),
                            ("same", "Si todos los productos son el mismo"),
                            ("mixed", "Permitir productos mezclados"),
                        ],
                        default="mixed",
                        help_text="Criterio de mezcla al ingresar un producto nuevo (Odoo allow_new_product).",
                        max_length=8,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_categories",
                        to="base.rescompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de almacenamiento",
                "verbose_name_plural": "Categorías de almacenamiento",
                "db_table": "stock_storage_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockPutawayRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.IntegerField(
                        default=0,
                        help_text="Prioridad; mayor para la categoría más específica (Odoo sequence).",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Regla activa (Odoo active)."
                    ),
                ),
                (
                    "sublocation",
                    models.CharField(
                        choices=[
                            ("no", "No"),
                            ("last_used", "Última usada"),
                            ("closest_location", "Ubicación más cercana"),
                        ],
                        default="no",
                        help_text="Cómo elegir la sububicación concreta (Odoo sublocation).",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Categoría de producto a la que aplica (Odoo category_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putaway_rule_ids",
                        to="product.productcategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putaway_rules",
                        to="base.rescompany",
                    ),
                ),
                (
                    "location_in",
                    models.ForeignKey(
                        help_text="Ubicación donde llega el producto (Odoo location_in_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putaway_rule_ids",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_out",
                    models.ForeignKey(
                        help_text="Sububicación donde se almacena (Odoo location_out_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putaway_destination_ids",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "package_type_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Tipos de paquete a los que aplica (Odoo package_type_ids).",
                        related_name="putaway_rule_ids",
                        to="stock.stockpackagetype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Producto al que aplica la regla (Odoo product_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putaway_rule_ids",
                        to="product.productproduct",
                    ),
                ),
                (
                    "storage_category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Categoría de almacenamiento exigida a la sububicación (Odoo storage_category_id, computado y almacenado).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="putaway_rule_ids",
                        to="stock.stockstoragecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de colocación",
                "verbose_name_plural": "Reglas de colocación",
                "db_table": "stock_putaway_rule",
                "ordering": ["sequence", "product_id"],
            },
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="storage_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría de almacenamiento (Odoo storage_category_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="location_ids",
                to="stock.stockstoragecategory",
            ),
        ),
        migrations.CreateModel(
            name="StockStorageCategoryCapacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad admitida (Odoo quantity, requerido).",
                        max_digits=12,
                    ),
                ),
                (
                    "package_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tipo de paquete acotado (Odoo package_type_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_category_capacity_ids",
                        to="stock.stockpackagetype",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Producto acotado (Odoo product_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storage_category_capacity_ids",
                        to="product.productproduct",
                    ),
                ),
                (
                    "storage_category",
                    models.ForeignKey(
                        help_text="Categoría a la que pertenece la regla (Odoo storage_category_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacity_ids",
                        to="stock.stockstoragecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidad de categoría de almacenamiento",
                "verbose_name_plural": "Capacidades de categoría de almacenamiento",
                "db_table": "stock_storage_category_capacity",
                "ordering": ["storage_category_id"],
            },
        ),
        migrations.CreateModel(
            name="StockWarehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del almacén (Odoo name; su default es el nombre de la empresa — ver _default_name).",
                        max_length=255,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Almacén activo (Odoo active)."
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Nombre corto que identifica el almacén; prefija los códigos de barras y las secuencias (Odoo code, size=5).",
                        max_length=5,
                    ),
                ),
                (
                    "reception_steps",
                    models.CharField(
                        choices=[
                            ("one_step", "Receive and Store (1 step)"),
                            ("two_steps", "Receive then Store (2 steps)"),
                            (
                                "three_steps",
                                "Receive, Quality Control, then Store (3 steps)",
                            ),
                        ],
                        default="one_step",
                        help_text="Ruta de entrada por defecto (Odoo reception_steps).",
                        max_length=16,
                    ),
                ),
                (
                    "delivery_steps",
                    models.CharField(
                        choices=[
                            ("ship_only", "Deliver (1 step)"),
                            ("pick_ship", "Pick then Deliver (2 steps)"),
                            ("pick_pack_ship", "Pick, Pack, then Deliver (3 steps)"),
                        ],
                        default="ship_only",
                        help_text="Ruta de salida por defecto (Odoo delivery_steps).",
                        max_length=16,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10,
                        help_text="Orden de despliegue del almacén (Odoo sequence).",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, readonly+required: se toma de las preferencias del usuario y no se cambia después).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="base.rescompany",
                    ),
                ),
                (
                    "delivery_route",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ruta de entrega generada por delivery_steps (Odoo delivery_route_id).",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="warehouses_as_delivery",
                        to="stock.stockroute",
                    ),
                ),
                (
                    "in_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo in_type_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_in",
                        to="stock.stockpickingtype",
                    ),
                ),
                (
                    "int_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo int_type_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_int",
                        to="stock.stockpickingtype",
                    ),
                ),
                (
                    "lot_stock",
                    models.ForeignKey(
                        help_text="La estantería: ubicación interna donde vive la existencia (Odoo lot_stock_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouses_as_stock",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "mto_pull",
                    models.ForeignKey(
                        blank=True,
                        help_text="Regla MTO del almacén dentro de la ruta global «Replenish on Order» (Odoo mto_pull_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_mto",
                        to="stock.stockrule",
                    ),
                ),
                (
                    "out_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo out_type_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_out",
                        to="stock.stockpickingtype",
                    ),
                ),
                (
                    "pack_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo pack_type_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_pack_type",
                        to="stock.stockpickingtype",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dirección del almacén (Odoo partner_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses",
                        to="base.respartner",
                    ),
                ),
                (
                    "pick_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo pick_type_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_pick",
                        to="stock.stockpickingtype",
                    ),
                ),
                (
                    "qc_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo qc_type_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_qc_type",
                        to="stock.stockpickingtype",
                    ),
                ),
                (
                    "reception_route",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ruta de recepción generada por reception_steps (Odoo reception_route_id).",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="warehouses_as_reception",
                        to="stock.stockroute",
                    ),
                ),
                (
                    "store_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo store_type_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_store",
                        to="stock.stockpickingtype",
                    ),
                ),
                (
                    "view_location",
                    models.ForeignKey(
                        help_text="Ubicación raíz de tipo vista que cuelga de este almacén (Odoo view_location_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="warehouses_as_view",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "wh_input_stock_loc",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación de entrada (Odoo wh_input_stock_loc_id); activa sólo si reception_steps != one_step.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_input",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "wh_output_stock_loc",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación de salida (Odoo wh_output_stock_loc_id); activa sólo si delivery_steps != ship_only.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_output",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "wh_pack_stock_loc",
                    models.ForeignKey(
                        blank=True,
                        help_text="Zona de empaque (Odoo wh_pack_stock_loc_id); activa sólo con delivery_steps == pick_pack_ship.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_pack",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "wh_qc_stock_loc",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación de control de calidad (Odoo wh_qc_stock_loc_id); activa sólo con reception_steps == three_steps.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_qc",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "xdock_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo xdock_type_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouses_as_xdock",
                        to="stock.stockpickingtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Almacén",
                "verbose_name_plural": "Almacenes",
                "db_table": "stock_warehouse",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.AddField(
            model_name="stockroute",
            name="supplied_wh",
            field=models.ForeignKey(
                blank=True,
                help_text="Almacén abastecido (Odoo supplied_wh_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_route_ids",
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockroute",
            name="supplier_wh",
            field=models.ForeignKey(
                blank=True,
                help_text="Almacén que abastece (Odoo supplier_wh_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplier_route_ids",
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockroute",
            name="warehouse_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="stock_route_warehouse",
                help_text="Almacenes que declaran esta ruta (Odoo warehouse_ids).",
                related_name="route_ids",
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockpickingtype",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Almacén dueño del tipo (Odoo warehouse_id, almacenado).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="picking_type_ids",
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddField(
            model_name="stocklocation",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Almacén cuya vista contiene esta ubicación (Odoo warehouse_id, almacenado).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="descendant_location_ids",
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="stocklocation",
            index=models.Index(
                fields=["parent_path", "id"], name="stock_location_parent_path_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.UniqueConstraint(
                fields=("barcode", "company"),
                name="stock_location_barcode_company_uniq",
                violation_error_message="El código de barras de una ubicación debe ser único por empresa.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("cyclic_inventory_frequency__gte", 0)),
                name="stock_location_inventory_freq_nonneg",
                violation_error_message="La frecuencia de inventario (días) no puede ser negativa.",
            ),
        ),
        migrations.AddField(
            model_name="stockwarehouseresupply",
            name="supplied_wh",
            field=models.ForeignKey(
                help_text="Almacén abastecido (Odoo supplied_wh_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockwarehouseresupply",
            name="supplier_wh",
            field=models.ForeignKey(
                help_text="Almacén que abastece (Odoo supplier_wh_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockwarehouse",
            name="resupply_wh_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Almacenes desde los que éste se reabastece; marcar uno crea su ruta inter-almacén (Odoo resupply_wh_ids).",
                related_name="+",
                through="stock.StockWarehouseResupply",
                through_fields=("supplied_wh", "supplier_wh"),
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovelineconsumerel",
            constraint=models.UniqueConstraint(
                fields=("consume_line", "produce_line"),
                name="unique_stock_move_line_consume_rel",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmoveline",
            index=models.Index(
                condition=models.Q(
                    models.Q(
                        ("state__isnull", True),
                        models.Q(("state__in", ("done", "cancel")), _negated=True),
                        _connector="OR",
                    ),
                    ("quantity_product_uom__gt", 0),
                    models.Q(("picked", True), _negated=True),
                ),
                fields=[
                    "id",
                    "company",
                    "product",
                    "lot",
                    "location",
                    "owner",
                    "package",
                ],
                name="free_reservation_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="pickingtypefavoriteuserrel",
            constraint=models.UniqueConstraint(
                fields=("picking_type", "user"),
                name="picking_type_favorite_user_rel_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockpackagetype",
            constraint=models.UniqueConstraint(
                fields=("barcode",),
                name="stock_package_type_barcode_uniq",
                violation_error_message="Un código de barras sólo puede asignarse a un tipo de paquete.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockpackagetype",
            constraint=models.CheckConstraint(
                condition=models.Q(("height__gte", 0)),
                name="stock_package_type_positive_height",
                violation_error_message="El alto debe ser positivo.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockpackagetype",
            constraint=models.CheckConstraint(
                condition=models.Q(("width__gte", 0)),
                name="stock_package_type_positive_width",
                violation_error_message="El ancho debe ser positivo.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockpackagetype",
            constraint=models.CheckConstraint(
                condition=models.Q(("packaging_length__gte", 0)),
                name="stock_package_type_positive_length",
                violation_error_message="El largo debe ser positivo.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockpackagetype",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_weight__gte", 0)),
                name="stock_package_type_positive_max_weight",
                violation_error_message="El peso máximo debe ser positivo.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockstoragecategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_weight__gte", 0)),
                name="stock_storage_category_positive_max_weight",
                violation_error_message="El peso máximo debe ser positivo.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockstoragecategorycapacity",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stock_storage_capacity_positive_quantity",
                violation_error_message="La cantidad debe ser un número positivo.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockstoragecategorycapacity",
            constraint=models.UniqueConstraint(
                fields=("product", "storage_category"),
                name="stock_storage_capacity_unique_product",
                violation_error_message="Varias reglas de capacidad para un producto.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockstoragecategorycapacity",
            constraint=models.UniqueConstraint(
                fields=("package_type", "storage_category"),
                name="stock_storage_capacity_unique_package_type",
                violation_error_message="Varias reglas de capacidad para un tipo de paquete.",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockwarehouseresupply",
            constraint=models.UniqueConstraint(
                fields=("supplied_wh", "supplier_wh"), name="unique_stock_wh_resupply"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockwarehouse",
            constraint=models.UniqueConstraint(
                fields=("name", "company"),
                name="warehouse_name_uniq",
                violation_error_message="The name of the warehouse must be unique per company!",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockwarehouse",
            constraint=models.UniqueConstraint(
                fields=("code", "company"),
                name="warehouse_code_uniq",
                violation_error_message="The short name of the warehouse must be unique per company!",
            ),
        ),
    ]
