# Generated by Django 6.0.5 on 2026-08-14 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_irmodelfields_serialization_field_id_and_more"),
        ("product", "0006_port_stock_scrap_and_is_storable"),
        ("stock", "0004_alter_stockrule_options_stockrule_active_and_more"),
        ("uom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockScrap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia, de la secuencia stock.scrap (Odoo name).",
                        max_length=64,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Documento de origen (Odoo origin).",
                        max_length=255,
                    ),
                ),
                (
                    "scrap_qty",
                    models.FloatField(
                        default=1.0,
                        help_text="Cantidad a desechar (Odoo scrap_qty, computado y almacenado).",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("done", "Hecho")],
                        default="draft",
                        help_text="Estado (Odoo state: draft/done).",
                        max_length=8,
                    ),
                ),
                (
                    "date_done",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de validación (Odoo date_done).",
                        null=True,
                    ),
                ),
                (
                    "should_replenish",
                    models.BooleanField(
                        default=False,
                        help_text="Dispara abastecimiento por lo desechado (Odoo should_replenish).",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_scraps",
                        to="base.rescompany",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Ubicación origen, interna (Odoo location_id, computado y almacenado).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraps_out",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lote/serie (Odoo lot_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraps",
                        to="stock.stocklot",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Propietario (Odoo owner_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_scraps",
                        to="base.respartner",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        help_text="Paquete (Odoo package_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraps",
                        to="stock.stockpackage",
                    ),
                ),
                (
                    "picking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Albarán de origen (Odoo picking_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scraps",
                        to="stock.stockpicking",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto a desechar (Odoo product_id, requerido).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraps",
                        to="product.productproduct",
                    ),
                ),
                (
                    "product_uom",
                    models.ForeignKey(
                        help_text="Unidad (Odoo product_uom_id, computado y almacenado).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraps",
                        to="uom.uom",
                    ),
                ),
                (
                    "scrap_location",
                    models.ForeignKey(
                        help_text="Ubicación de desecho, de tipo inventory (Odoo scrap_location_id, computado y almacenado).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scraps_in",
                        to="stock.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Desecho",
                "verbose_name_plural": "Desechos",
                "db_table": "stock_scrap",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="stockmove",
            name="scrap",
            field=models.ForeignKey(
                blank=True,
                help_text="Desecho que originó el movimiento (Odoo scrap_id). Es el inverso que ``stock.scrap.move_ids`` declara (odoo19c: stock/models/stock_scrap.py:37).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="move_ids",
                to="stock.stockscrap",
            ),
        ),
        migrations.CreateModel(
            name="StockScrapReasonTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del motivo (Odoo name, requerido y traducible).",
                        max_length=64,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de presentación (Odoo sequence)."
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3C3C3C",
                        help_text="Color (Odoo color).",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo de desecho",
                "verbose_name_plural": "Motivos de desecho",
                "db_table": "stock_scrap_reason_tag",
                "ordering": ["sequence", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="stock_scrap_reason_tag_name_uniq",
                        violation_error_message="Tag name already exists!",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="stockscrap",
            name="scrap_reason_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Motivo del desecho (Odoo scrap_reason_tag_ids).",
                related_name="scraps",
                to="stock.stockscrapreasontag",
            ),
        ),
    ]
