# Generated by Django 6.0.5 on 2026-08-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_port_stock_scrap_and_is_storable"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Referencia compartida (Odoo name, requerido y readonly).",
                        max_length=255,
                    ),
                ),
                (
                    "move_ids",
                    models.ManyToManyField(
                        blank=True,
                        db_table="stock_reference_move_rel",
                        help_text="Movimientos que comparten esta referencia (Odoo move_ids). El inverso es ``move.reference_ids``, el nombre que la referencia le da a la otra mitad del M2M.",
                        related_name="reference_ids",
                        to="stock.stockmove",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referencia de inventario",
                "verbose_name_plural": "Referencias de inventario",
                "db_table": "stock_reference",
                "ordering": ["id"],
            },
        ),
    ]
