# Generated by Django 6.0.5 on 2026-08-14 23:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def _backfill_company(apps, schema_editor):
    """Rellena ``stock_move.company`` antes de cerrarla a NOT NULL.

    La empresa del movimiento sale de su albarán si lo tiene; si no, de la
    primera empresa del sistema. Si no hay ninguna empresa **y** hay
    movimientos, la migración falla a propósito: rellenar con NULL sería
    dejar la columna en un estado que el modelo declara imposible.
    """
    StockMove = apps.get_model('stock', 'StockMove')
    huerfanos = StockMove.objects.filter(company__isnull=True)
    if not huerfanos.exists():
        return
    ResCompany = apps.get_model('base', 'ResCompany')
    respaldo = ResCompany.objects.order_by('pk').first()
    if respaldo is None:
        raise RuntimeError(
            'stock_move tiene filas sin empresa y no hay ninguna ResCompany '
            'para asignarles. Crear la empresa antes de migrar.')
    for movimiento in huerfanos.select_related('picking').iterator():
        picking = getattr(movimiento, 'picking', None)
        movimiento.company_id = getattr(picking, 'company_id', None) or respaldo.pk
        movimiento.save(update_fields=['company'])


def _sin_marcha_atras(apps, schema_editor):
    """Sin inversa: el rellenado no distingue lo que puso de lo que ya estaba."""


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_irmodelfields_serialization_field_id_and_more"),
        ("product", "0007_producttemplate_description_picking_and_more"),
        ("stock", "0006_port_stock_reference"),
        ("uom", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockmove",
            options={
                "ordering": ["sequence", "id"],
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
            },
        ),
        migrations.RemoveField(
            model_name="stockmove",
            name="move_orig",
        ),
        migrations.RemoveField(
            model_name="stockmove",
            name="name",
        ),
        migrations.AddField(
            model_name="stockmove",
            name="additional",
            field=models.BooleanField(
                default=False,
                help_text="El movimiento se añadió DESPUÉS de confirmar el albarán (Odoo additional).",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Odoo company_id, requerido). Ver la divergencia D-5 del docstring: la columna nace NULL para poder añadirse a una tabla existente y la migración la cierra a NOT NULL.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="base.rescompany",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Fecha planificada hasta que se hace; después, la real (Odoo date, requerido, default=Datetime.now).",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="date_deadline",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha límite propagada por la cadena (Odoo date_deadline, readonly; lo escribe _set_date_deadline).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="delay_alert_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha de alerta por retraso de un movimiento origen (Odoo delay_alert_date, compute+store).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="description_picking_manual",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descripción escrita a mano (Odoo description_picking_manual, readonly). Cuando está, gana sobre la derivada del producto.",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="inventory_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre del ajuste (Odoo inventory_name, readonly).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="is_inventory",
            field=models.BooleanField(
                default=False,
                help_text="El movimiento es un ajuste de inventario (Odoo is_inventory).",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="location_final",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación destino FINAL de la cadena (Odoo location_final_id). El destino intermedio es el siguiente salto; éste es el fin del encargo.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moves_final",
                to="stock.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="move_orig_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="stock_move_move_rel",
                help_text="Movimientos origen que abastecen a éste (Odoo move_orig_ids). El inverso es move_dest_ids, el nombre que la referencia le da a la otra mitad.",
                related_name="move_dest_ids",
                to="stock.stockmove",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="never_product_template_attribute_value_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="template_attribute_value_stock_move_rel",
                help_text="Valores de atributo excluidos (Odoo never_product_template_attribute_value_ids).",
                related_name="stock_moves",
                to="product.producttemplateattributevalue",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="next_serial",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Primer número de serie a generar (Odoo next_serial).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="next_serial_count",
            field=models.IntegerField(
                default=0,
                help_text="Cuántos números de serie generar (Odoo next_serial_count).",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="origin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Documento de origen, en texto (Odoo origin).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="origin_returned_move",
            field=models.ForeignKey(
                blank=True,
                help_text="Movimiento que originó esta devolución (Odoo origin_returned_move_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="returned_move_ids",
                to="stock.stockmove",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="packaging_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidad de empaque de la orden de origen (Odoo packaging_uom_id, compute+store precompute).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves_packaging",
                to="uom.uom",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="packaging_uom_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="La demanda en la unidad de empaque (Odoo packaging_uom_qty, compute+store).",
                max_digits=16,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Dirección de entrega opcional (Odoo partner_id, compute+store desde el albarán).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_moves",
                to="base.respartner",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="picked",
            field=models.BooleanField(
                default=False,
                help_text="Marca indicativa de recogido (Odoo picked, compute+store con inverso). No valida ni genera movimientos por sí sola.",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="picking_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de operación (Odoo picking_type_id, compute+store con readonly=False).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="stock.stockpickingtype",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="price_unit",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Coste unitario fijado al confirmar, en la divisa de la empresa (Odoo price_unit; campo técnico, sin digits).",
                max_digits=16,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="priority",
            field=models.CharField(
                choices=[("0", "Normal"), ("1", "Urgent")],
                default="0",
                help_text="Prioridad (Odoo priority, compute+store desde el albarán).",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="procure_method",
            field=models.CharField(
                choices=[
                    ("make_to_stock", "Default: Take From Stock"),
                    ("make_to_order", "Advanced: Apply Procurement Rules"),
                ],
                default="make_to_stock",
                help_text="Método de suministro (Odoo procure_method). make_to_stock espera disponibilidad; make_to_order dispara una regla.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="product_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="La misma demanda en la unidad del PRODUCTO (Odoo product_qty, compute+store; su inverso lanza error a propósito — se escribe product_uom_qty).",
                max_digits=16,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="product_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="Unidad del movimiento (Odoo product_uom, compute+store con readonly=False; la recalcula compute_product_uom).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="uom.uom",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="propagate_cancel",
            field=models.BooleanField(
                default=True,
                help_text="Si al cancelar éste se cancela el movimiento enlazado (Odoo propagate_cancel).",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Etiqueta del movimiento (Odoo reference, compute+store). Es el _rec_name: sale del albarán, del desecho o del nombre de inventario, en ese orden.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="reservation_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha a partir de la cual reservar (Odoo reservation_date, compute+store desde el tipo de operación).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="restrict_partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Propietario cuyos quants son los únicos considerables al marcar hecho (Odoo restrict_partner_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_moves_restricted",
                to="base.respartner",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="route_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="stock_route_move",
                help_text="Rutas de destino preferidas (Odoo route_ids).",
                related_name="stock_moves",
                to="stock.stockroute",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                help_text="Regla que creó el movimiento (Odoo rule_id, ondelete='restrict').",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="stock.stockrule",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="sequence",
            field=models.IntegerField(
                default=10, help_text="Orden dentro del albarán (Odoo sequence)."
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Almacén a considerar al elegir ruta en el siguiente aprovisionamiento (Odoo warehouse_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="stock.stockwarehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="is_locked",
            field=models.BooleanField(
                default=True,
                help_text="Odoo is_locked. Con el albarán sin validar permite cambiar la demanda inicial; ya validado, las cantidades hechas.",
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="location",
            field=models.ForeignKey(
                help_text="Ubicación origen (Odoo location_id, compute+store).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moves_out",
                to="stock.stocklocation",
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="location_dest",
            field=models.ForeignKey(
                help_text="Ubicación destino INTERMEDIA (Odoo location_dest_id, compute+store con inverso).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moves_in",
                to="stock.stocklocation",
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="product",
            field=models.ForeignKey(
                help_text="Producto (Odoo product_id; el dominio excluye servicios).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="product.productproduct",
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="product_uom_qty",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Cantidad demandada, en la unidad del movimiento (Odoo product_uom_qty). Bajarla NO genera pedido pendiente.",
                max_digits=16,
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text="Suma de las cantidades de las líneas (Odoo quantity, compute+store con inverso).",
                max_digits=16,
            ),
        ),
        migrations.AlterField(
            model_name="stockmove",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "Nuevo"),
                    ("waiting", "Esperando otro movimiento"),
                    ("confirmed", "Esperando disponibilidad"),
                    ("partially_available", "Parcialmente disponible"),
                    ("assigned", "Disponible"),
                    ("done", "Hecho"),
                    ("cancel", "Cancelado"),
                ],
                db_index=True,
                default="draft",
                help_text="Estado (Odoo state, readonly). Los SIETE de la referencia.",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="stockmove",
            index=models.Index(
                fields=["product", "location", "location_dest", "company", "state"],
                name="stock_move_product_location_idx",
            ),
        ),
        # ``company_id`` es ``required=True`` en la referencia
        # (``odoo19c: addons/stock/models/stock_move.py:35-37``). Se añade NULL
        # para poder aterrizar sobre una tabla existente, se rellena, y se
        # cierra a NOT NULL — los tres pasos en la misma migración para que el
        # estado intermedio no sobreviva al despliegue.
        migrations.RunPython(_backfill_company, _sin_marcha_atras),
        migrations.AlterField(
            model_name="stockmove",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Odoo company_id, requerido).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_moves",
                to="base.rescompany",
            ),
        ),
    ]
