# Generated by Django 6.0.5 on 2026-08-15 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_alter_stockmove_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpicking",
            name="picking_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de operación que gobierna el albarán (Odoo picking_type_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickings",
                to="stock.stockpickingtype",
                verbose_name="Tipo de operación",
            ),
        ),
    ]
