# Generated by Django 6.0.5 on 2026-08-15 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_rescompany_annual_inventory_day_and_more"),
        ("product", "0009_productproduct_lot_properties_definition"),
        ("stock", "0009_stockpicking_picking_type"),
        ("uom", "0002_uom_package_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockWarehouseOrderpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la regla; lo genera la secuencia ``stock.orderpoint`` (Odoo name, copy=False, readonly).",
                        max_length=64,
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[("auto", "Auto"), ("manual", "Manual")],
                        default="auto",
                        help_text="Auto lo corre el planificador; manual, una persona (Odoo trigger).",
                        max_length=8,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Al desmarcarlo se oculta la regla sin borrarla (Odoo active).",
                    ),
                ),
                (
                    "snoozed_until",
                    models.DateField(
                        blank=True,
                        help_text="Oculta hasta el próximo planificador; sólo válido en reglas manuales (Odoo snoozed_until).",
                        null=True,
                    ),
                ),
                (
                    "product_min_qty",
                    models.FloatField(
                        default=0.0,
                        help_text='Existencia mínima que dispara el reabastecimiento (Odoo product_min_qty, digits="Product Unit").',
                    ),
                ),
                (
                    "product_max_qty",
                    models.FloatField(
                        default=0.0,
                        help_text="Existencia a la que se quiere volver al reabastecer (Odoo product_max_qty, compute+store, readonly=False).",
                    ),
                ),
                (
                    "qty_to_order_computed",
                    models.FloatField(
                        default=0.0,
                        help_text="Cantidad que el cálculo propone pedir (Odoo qty_to_order_computed, compute+store).",
                    ),
                ),
                (
                    "qty_to_order_manual",
                    models.FloatField(
                        default=0.0,
                        help_text="Cantidad fijada a mano; si no es cero, gana sobre la calculada (Odoo qty_to_order_manual).",
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha antes de la cual hay que pedir para no caer bajo el mínimo (Odoo deadline_date, compute+store, readonly).",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderpoint_ids",
                        to="base.rescompany",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Ubicación cuya existencia se vigila (Odoo location_id, compute+store, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderpoint_ids",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto que se reabastece (Odoo product_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderpoint_ids",
                        to="product.productproduct",
                    ),
                ),
                (
                    "replenishment_uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Múltiplo al que se redondea la cantidad a pedir; vacío no redondea (Odoo replenishment_uom_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orderpoint_ids",
                        to="uom.uom",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ruta elegida a mano; vacío usa la que resulte del producto y la ubicación (Odoo route_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orderpoint_ids",
                        to="stock.stockroute",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Almacén (Odoo warehouse_id, compute+store, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderpoint_ids",
                        to="stock.stockwarehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de reabastecimiento",
                "verbose_name_plural": "Reglas de reabastecimiento",
                "db_table": "stock_warehouse_orderpoint",
                "ordering": ["location", "company", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "location", "company"),
                        name="stock_orderpoint_product_location_check",
                        violation_error_message="A replenishment rule already exists for this product on this location.",
                    )
                ],
            },
        ),
    ]
