# Generated by Django 6.0.5 on 2026-08-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_rescompany_annual_inventory_day_and_more"),
        ("stock", "0010_stockwarehouseorderpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocklot",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa (Odoo company_id). Almacenada con compute: la resuelve _compute_company_id desde la del producto.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_lots",
                to="base.rescompany",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación única del lote (Odoo location_id). Almacenada con compute e inverse: se llena cuando todos los quants con cantidad positiva están en una sola ubicación, y al escribirla se reubican.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="single_location_lots",
                to="stock.stocklocation",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="lot_properties",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Propiedades del lote (Odoo lot_properties). Su definición vive en ProductProduct.lot_properties_definition.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Descripción libre del lote (Odoo note).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stocklot",
            name="name",
            field=models.CharField(
                help_text="Número de lote / serie (Odoo name). Único por producto; si llega vacío lo genera la secuencia del producto.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="stocklot",
            name="ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Referencia interna, para cuando difiere del número del fabricante (Odoo ref).",
                max_length=120,
            ),
        ),
    ]
