# Generated by Django 6.0.5 on 2026-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0011_stocklot_company_note_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpicking",
            name="origin",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Documento de origen (Odoo origin).",
                max_length=64,
            ),
        ),
    ]
