# Generated by Django 6.0.5 on 2026-08-15 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_rescompany_annual_inventory_day_and_more"),
        ("stock", "0012_add_picking_origin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpicking",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa (Odoo company_id, related del tipo de operación).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_pickings",
                to="base.rescompany",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="move_type",
            field=models.CharField(
                choices=[
                    ("direct", "En cuanto sea posible"),
                    ("one", "Cuando todos los productos estén listos"),
                ],
                default="direct",
                help_text="Parcial o todo junto (Odoo move_type). Sale del tipo de operación y se puede sobreescribir por albarán.",
                max_length=8,
                verbose_name="Política de envío",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Contacto del albarán (Odoo partner_id). Lo borra ``_assign_picking_values`` cuando el albarán agrupa movimientos de contactos distintos.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickings",
                to="base.respartner",
                verbose_name="Contacto",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="printed",
            field=models.BooleanField(
                default=False,
                help_text="El albarán ya se imprimió (Odoo printed). Un albarán impreso no recibe movimientos nuevos por asignación.",
                verbose_name="Impreso",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Responsable del albarán (Odoo user_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_pickings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
    ]
