# Generated by Django 6.0.5 on 2026-08-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0013_stockpicking_company_stockpicking_move_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmove",
            name="orderpoint",
            field=models.ForeignKey(
                blank=True,
                help_text="La regla de reabastecimiento que originó el movimiento (Odoo orderpoint_id, «Original Reordering Rule», index).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_moves",
                to="stock.stockwarehouseorderpoint",
            ),
        ),
    ]
