# Generated by Django 6.0.5 on 2026-08-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_alter_respartner_options_alter_resusers_options"),
        ("stock", "0014_stockmove_orderpoint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockpicking",
            options={
                "ordering": ["-priority", "-created_at", "-id"],
                "verbose_name": "Transferencia de inventario",
                "verbose_name_plural": "Transferencias de inventario",
            },
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="backorder",
            field=models.ForeignKey(
                blank=True,
                help_text="Si este albarán se dividió, apunta al albarán que ya se procesó (Odoo backorder_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="backorder_ids",
                to="stock.stockpicking",
                verbose_name="Backorder de",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="date_done",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha en que el albarán se procesó o canceló (Odoo date_done).",
                null=True,
                verbose_name="Fecha de proceso",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notas libres del albarán (Odoo note).",
                verbose_name="Notas",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Al validar, los productos se asignan a este propietario (Odoo owner_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_pickings",
                to="base.respartner",
                verbose_name="Propietario asignado",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="priority",
            field=models.CharField(
                choices=[("0", "Normal"), ("1", "Urgent")],
                default="0",
                help_text="Los productos con prioridad alta se reservan primero (Odoo priority).",
                max_length=1,
                verbose_name="Prioridad",
            ),
        ),
        migrations.AddField(
            model_name="stockpicking",
            name="return_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Si este albarán se creó como devolución de otro, apunta al original (Odoo return_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_ids",
                to="stock.stockpicking",
                verbose_name="Devolución de",
            ),
        ),
        migrations.AlterField(
            model_name="stockpicking",
            name="move_type",
            field=models.CharField(
                choices=[
                    ("direct", "En cuanto sea posible"),
                    ("one", "Cuando todos los productos estén listos"),
                ],
                help_text="Parcial o todo junto (Odoo move_type). Sale del tipo de operación y se puede sobreescribir por albarán.",
                max_length=8,
                verbose_name="Política de envío",
            ),
        ),
    ]
