# Generated by Django 6.0.5 on 2026-08-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_projecttasktype_sms_template"),
        (
            "stock",
            "0016_rename_stock_move_product_location_idx_stock_move_product_loc_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpicking",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo project_id (project_stock). Proyecto al que pertenece el albarán. El domain de la referencia (is_template=False) queda pendiente — ver docstring del módulo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickings",
                to="project.project",
            ),
        ),
    ]
