# Generated by Django 6.0.5 on 2026-08-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_productsupplierinfo_purchase_requisition_line_and_more"),
        ("purchase", "0002_purchaseorder_dest_address_and_more"),
        ("stock", "0017_stockpicking_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmove",
            name="created_purchase_line_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="stock_move_created_purchase_line_rel",
                help_text="Líneas de compra que este movimiento hizo crear (Odoo created_purchase_line_ids, caso make-to-order). El inverso es ``line.move_dest_ids``, el nombre que la referencia le da a la otra mitad (purchase_order_line.py:30).",
                related_name="move_dest_ids",
                to="purchase.purchaseorderline",
            ),
        ),
        migrations.AddField(
            model_name="stockmove",
            name="purchase_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Línea de compra que originó este movimiento (Odoo purchase_line_id). El inverso es ``line.move_ids``.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="move_ids",
                to="purchase.purchaseorderline",
            ),
        ),
        migrations.AddField(
            model_name="stockreference",
            name="purchase_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="stock_reference_purchase_rel",
                help_text="Órdenes de compra que comparten esta referencia (Odoo purchase_ids). El inverso es ``order.reference_ids``.",
                related_name="reference_ids",
                to="purchase.purchaseorder",
            ),
        ),
        migrations.AddField(
            model_name="stockwarehouse",
            name="buy_pull",
            field=models.ForeignKey(
                blank=True,
                help_text="Regla que convierte una necesidad de este almacén en una solicitud de cotización (Odoo buy_pull_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buy_warehouse_ids",
                to="stock.stockrule",
                verbose_name="Regla de compra",
            ),
        ),
        migrations.AddField(
            model_name="stockwarehouseorderpoint",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Tarifa del proveedor con el que se reabastece (Odoo supplier_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orderpoint_ids",
                to="product.productsupplierinfo",
                verbose_name="Tarifa de proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="stockrule",
            name="action",
            field=models.CharField(
                choices=[
                    ("pull", "Pull From"),
                    ("push", "Push To"),
                    ("pull_push", "Pull & Push"),
                    ("buy", "Comprar"),
                ],
                db_index=True,
                default="pull",
                help_text="Dirección de la regla (Odoo action).",
                max_length=16,
            ),
        ),
    ]
