# Generated by Django 6.0.5 on 2026-08-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0061_serveractionhistorywizard_and_more"),
        ("stock", "0018_stockmove_created_purchase_line_ids_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockpickingtype",
            name="sequence_id",
            field=models.ForeignKey(
                blank=True,
                db_column="sequence_id",
                help_text="Secuencia de referencia (Odoo sequence_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="picking_types",
                to="base.irsequence",
            ),
        ),
    ]
