# Generated by Django 6.0.5 on 2026-08-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0019_alter_stockpickingtype_sequence_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmove",
            name="to_refund",
            field=models.BooleanField(
                default=True,
                help_text="Dispara la disminución de la cantidad entregada/recibida en la orden de venta o compra asociada (Odoo to_refund).",
                verbose_name="Update quantities on SO/PO",
            ),
        ),
    ]
