# Generated by Django 6.0.5 on 2026-08-19 16:51

import addons.purchase_requisition.models.purchase_requisition
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0030_rescompany_account_peppol_contact_email_and_more"),
        # 0010, no 0011: la 0011 de product AÑADE el FK inverso
        # `productsupplierinfo.purchase_requisition_line` y por tanto depende de
        # esta migración. Apuntar a 0011 cierra el ciclo
        # (CircularDependencyError). Los modelos de aquí sólo necesitan las
        # tablas de product, que ya existen en 0010.
        ("product", "0010_producttemplate_lot_sequence"),
        ("uom", "0003_uom_timesheet_widget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrderGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grupo de órdenes de compra",
                "verbose_name_plural": "Grupos de órdenes de compra",
                "db_table": "purchase_order_group",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default=addons.purchase_requisition.models.purchase_requisition._default_requisition_name,
                        help_text="Referencia del acuerdo; la asigna la secuencia al crearlo (Odoo name, readonly + copy=False).",
                        max_length=64,
                        verbose_name="Acuerdo",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Si se desmarca, el acuerdo se oculta sin borrarlo (Odoo active).",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia libre del acuerdo (Odoo reference).",
                        max_length=64,
                    ),
                ),
                (
                    "requisition_type",
                    models.CharField(
                        choices=[
                            ("blanket_order", "Pedido abierto"),
                            ("purchase_template", "Plantilla de compra"),
                        ],
                        default="blanket_order",
                        help_text="Pedido abierto (precio pactado) o plantilla de compra (lista que se copia) — Odoo requisition_type.",
                        max_length=20,
                        verbose_name="Tipo de acuerdo",
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True,
                        help_text="Odoo date_start. La referencia lo declara tracking=True; ver D-2 del docstring del módulo.",
                        null=True,
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True,
                        help_text="Odoo date_end (tracking=True en la referencia, D-2).",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción del acuerdo (Odoo description).",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("confirmed", "Confirmado"),
                            ("done", "Cerrado"),
                            ("cancel", "Cancelado"),
                        ],
                        default="draft",
                        help_text="Odoo state (tracking=True en la referencia, D-2).",
                        max_length=16,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Odoo company_id (required).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_requisition_ids",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda del acuerdo (Odoo currency_id, compute+store con readonly=False). La calcula _compute_currency_id al guardar.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisition_ids",
                        to="base.rescurrency",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo user_id, con el usuario en curso por defecto.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_requisition_ids",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable de compras",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Proveedor con el que se pacta el acuerdo (Odoo vendor_id, check_company=True).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisition_ids",
                        to="base.respartner",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acuerdo de compra",
                "verbose_name_plural": "Acuerdos de compra",
                "db_table": "purchase_requisition",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analytic_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Odoo analytic_distribution: {"id1,id2,...": porcentaje}.',
                        null=True,
                        verbose_name="Distribución analítica",
                    ),
                ),
                (
                    "product_qty",
                    models.FloatField(
                        default=0.0,
                        help_text="Odoo product_qty (digits='Product Unit').",
                        verbose_name="Cantidad",
                    ),
                ),
                (
                    "product_description_variants",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo product_description_variants.",
                        max_length=255,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "price_unit",
                    models.FloatField(
                        default=0.0,
                        help_text="Odoo price_unit (compute+store, readonly=False). Lo calcula _compute_price_unit al guardar.",
                        verbose_name="Precio unitario",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Odoo product_id, con domain [('purchase_ok', '=', True)].",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisition_line_ids",
                        to="product.productproduct",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "product_uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo product_uom_id (compute+store, readonly=False). La calcula _compute_product_uom_id al guardar.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_requisition_line_ids",
                        to="uom.uom",
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        help_text="Odoo requisition_id (required, ondelete='cascade').",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_ids",
                        to="purchase_requisition.purchaserequisition",
                        verbose_name="Acuerdo de compra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de acuerdo de compra",
                "verbose_name_plural": "Líneas de acuerdo de compra",
                "db_table": "purchase_requisition_line",
                "ordering": ["id"],
            },
        ),
    ]
