# Generated by Django 6.0.5 on 2026-07-12 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                (
                    "asker_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "asker_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ANSWERED", "Respondida"),
                            ("REJECTED", "Rechazada"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("answer_body", models.TextField(blank=True, default="")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_questions_answered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asker_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta de producto",
                "verbose_name_plural": "Preguntas de producto",
                "db_table": "questions_productquestion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("APPROVE", "Aprobar"), ("REJECT", "Rechazar")],
                        max_length=8,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_moderations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="questions.productquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de moderacion de pregunta",
                "verbose_name_plural": "Registros de moderacion de preguntas",
                "db_table": "questions_moderationlog",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["product", "status"], name="questions_p_product_01bf1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(fields=["status"], name="questions_p_status_20bfc5_idx"),
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["-created_at"], name="questions_p_created_47037c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questionmoderationlog",
            index=models.Index(
                fields=["question", "-created_at"],
                name="questions_m_questio_1400ec_idx",
            ),
        ),
    ]
