# Generated by Django 6.0.5 on 2026-07-05 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_squashed_0002_productquestion_softdelete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionModerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("APPROVE", "Aprobar"), ("REJECT", "Rechazar")],
                        max_length=8,
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_moderations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_logs",
                        to="questions.productquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de moderacion de pregunta",
                "verbose_name_plural": "Registros de moderacion de preguntas",
                "db_table": "questions_moderationlog",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["question", "-created_at"],
                        name="questions_m_questio_1400ec_idx",
                    )
                ],
            },
        ),
    ]
