# Generated by Django 6.0.5 on 2026-08-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accessrule",
            name="authz_acces_model_l_02e6e2_idx",
        ),
        migrations.RemoveConstraint(
            model_name="accessrule",
            name="authz_access_rule_at_least_one_perm",
        ),
        migrations.DeleteModel(
            name="AccessRule",
        ),
    ]
