# Generated by Django 6.0.5 on 2026-07-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmsSms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        help_text="Número destino (Odoo sms.sms.number).", max_length=32
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Cuerpo del mensaje (Odoo sms.sms.body)."
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "En cola"),
                            ("sent", "Enviado"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        help_text="Estado de envío (Odoo sms.sms.state, colapsado).",
                        max_length=16,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Motivo del fallo si state=error (Odoo failure_type).",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS saliente",
                "verbose_name_plural": "SMS salientes",
                "db_table": "sms_sms",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SmsTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la plantilla (Odoo sms.template.name).",
                        max_length=100,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Cuerpo con placeholders {campo} (Odoo sms.template.body)."
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, help_text="Plantilla activa."),
                ),
            ],
            options={
                "verbose_name": "Plantilla de SMS",
                "verbose_name_plural": "Plantillas de SMS",
                "db_table": "sms_template",
            },
        ),
    ]
