# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckoutAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=100)),
                ("response_json", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Intento de checkout",
                "db_table": "base_checkout_attempt",
            },
        ),
        migrations.CreateModel(
            name="DecimalPrecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Uso (Odoo name, p. ej. "Product Price"). Único.',
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "digits",
                    models.IntegerField(
                        default=2, help_text="Número de decimales (Odoo digits)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Precisión decimal",
                "verbose_name_plural": "Precisiones decimales",
                "db_table": "decimal_precision",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En proceso"),
                            ("DONE", "Completado"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, default="", max_length=500)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("error_detail", models.TextField(blank=True, default="")),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Export job",
                "verbose_name_plural": "Export jobs",
                "db_table": "report_export_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IrAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del adjunto (Odoo name).", max_length=256
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Odoo description."
                    ),
                ),
                (
                    "res_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Modelo polimórfico referenciado, p. ej. "catalogue.Product" (Odoo res_model). NO es una FK — vínculo plano igual que Odoo.',
                        max_length=128,
                    ),
                ),
                (
                    "res_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Campo binary del modelo referenciado, si aplica (Odoo res_field).",
                        max_length=128,
                    ),
                ),
                (
                    "res_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del registro referenciado (Odoo res_id / Many2oneReference simplificado a Integer plano — el ORM shim del proyecto no tiene un tipo Many2oneReference fiel; Odoo tampoco lo trata como FK real).",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("binary", "File"), ("url", "URL")],
                        default="binary",
                        help_text="Odoo type: binary (archivo) o url (enlace externo).",
                        max_length=8,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", help_text="Odoo url.", max_length=1024
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, help_text="Odoo public — accesible sin auth."
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Token de acceso externo (Odoo access_token).",
                        max_length=64,
                    ),
                ),
                (
                    "mimetype",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo mimetype.",
                        max_length=128,
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        default=0, help_text="Tamaño en bytes (Odoo file_size)."
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA1 del contenido (Odoo checksum, calculado en save()).",
                        max_length=40,
                    ),
                ),
                (
                    "store_fname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre asignado por el storage backend de Django (Odoo store_fname — aquí no es una ruta sha1-sharded propia, ver docstring del módulo).",
                        max_length=256,
                    ),
                ),
                (
                    "datas",
                    models.FileField(
                        blank=True,
                        help_text="Contenido binario (Odoo datas/raw) — FileField de Django, no el filestore propio de Odoo (ver docstring del módulo).",
                        null=True,
                        upload_to="attachments/%Y/%m/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
                "verbose_name_plural": "Adjuntos",
                "db_table": "ir_attachment",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="IrCron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la tarea (Odoo cron_name — ahí computado desde el name de la ir.actions.server delegada; aquí campo local directo porque no se porta esa delegación, ver docstring del módulo).",
                        max_length=256,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text='Modelo técnico objetivo, p. ej. "sale.SaleOrder" (adaptación del model_id delegado en ir.actions.server de Odoo — aquí Char plano, mismo criterio que ir_filters.model_id / ir_attachment.res_model: no es FK real, el runner diferido la resuelve con apps.get_model()).',
                        max_length=128,
                    ),
                ),
                (
                    "method_name",
                    models.CharField(
                        help_text="Nombre del método a invocar sobre model_name (adaptación: sustituye el code Python arbitrario de ir.actions.server de Odoo por una llamada directa a método, resuelta por el runner diferido).",
                        max_length=128,
                    ),
                ),
                (
                    "interval_number",
                    models.IntegerField(
                        default=1, help_text="Repetir cada x (Odoo interval_number)."
                    ),
                ),
                (
                    "interval_type",
                    models.CharField(
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                        ],
                        default="months",
                        help_text="Unidad del intervalo (Odoo interval_type).",
                        max_length=8,
                    ),
                ),
                (
                    "nextcall",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Próxima fecha de ejecución planeada (Odoo nextcall).",
                    ),
                ),
                (
                    "lastcall",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última ejecución exitosa (Odoo lastcall).",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="Prioridad: 0 = más alta, 10 = más baja (Odoo priority, consumida por el runner diferido para ordenar el polling).",
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
            ],
            options={
                "verbose_name": "Tarea programada",
                "verbose_name_plural": "Tareas programadas",
                "db_table": "ir_cron",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="IrDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text='Modelo técnico objetivo, p. ej. "sale.SaleOrder" (adaptación del field_id.model_id delegado de Odoo — aquí Char plano, mismo criterio que ir_filters.model_id / ir_cron.model_name: no es FK real, ver docstring del módulo).',
                        max_length=128,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Nombre del campo del modelo objetivo (adaptación del field_id.name delegado de Odoo — Char plano, no FK real, ver docstring del módulo).",
                        max_length=128,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Condición opcional que acota la aplicabilidad del default (Odoo condition — string opaco para este modelo de control).",
                        max_length=256,
                    ),
                ),
                (
                    "json_value",
                    models.TextField(
                        help_text="Valor por defecto serializado en JSON (Odoo json_value — Text en vez de Char porque Odoo lo declara sin límite de tamaño, ver docstring del módulo)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor por defecto",
                "verbose_name_plural": "Valores por defecto",
                "db_table": "ir_default",
                "ordering": ["model", "field", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IrFilters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del filtro (Odoo name).", max_length=256
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text='Modelo técnico referenciado, p. ej. "catalogue.Product" (Odoo model_id — Selection dinámico en Odoo, aquí Char plano porque no es una FK real, igual criterio que res_model en ir_attachment).',
                        max_length=128,
                    ),
                ),
                (
                    "domain",
                    models.TextField(
                        default="[]",
                        help_text="Dominio de búsqueda serializado (Odoo domain).",
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        default="{}", help_text="Contexto serializado (Odoo context)."
                    ),
                ),
                (
                    "sort",
                    models.CharField(
                        default="[]",
                        help_text="Orden serializado (Odoo sort — Char en la fuente, no Text).",
                        max_length=512,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Filtro por defecto para el alcance modelo+usuario (Odoo is_default).",
                    ),
                ),
                (
                    "action_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de la acción/menú al que aplica el filtro (Odoo action_id — Many2one a ir.actions.actions, modelo no portado en este monolito; se mantiene Integer plano, igual criterio que res_id en ir_attachment). NULL = aplica a todos los menús del modelo.",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
            ],
            options={
                "verbose_name": "Filtro",
                "verbose_name_plural": "Filtros",
                "db_table": "ir_filters",
                "ordering": ["model_id", "name", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IrLogging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("client", "Client"), ("server", "Server")],
                        db_index=True,
                        default="server",
                        max_length=8,
                    ),
                ),
                (
                    "dbname",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("func", models.CharField(blank=True, default="", max_length=255)),
                ("line", models.CharField(blank=True, default="", max_length=32)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("trace", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Logging",
                "verbose_name_plural": "Logging",
                "db_table": "ir_logging",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="IrSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre (Odoo name).", max_length=128),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código de la secuencia (Odoo code).",
                        max_length=64,
                    ),
                ),
                (
                    "implementation",
                    models.CharField(
                        choices=[("standard", "Standard"), ("no_gap", "No gap")],
                        default="standard",
                        help_text="Standard o No gap (Odoo implementation).",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Prefijo, interpolable por fecha (Odoo prefix).",
                        max_length=128,
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sufijo, interpolable por fecha (Odoo suffix).",
                        max_length=128,
                    ),
                ),
                (
                    "number_next",
                    models.IntegerField(
                        default=1, help_text="Próximo número (Odoo number_next)."
                    ),
                ),
                (
                    "number_increment",
                    models.IntegerField(
                        default=1,
                        help_text="Paso de incremento (Odoo number_increment / Step).",
                    ),
                ),
                (
                    "padding",
                    models.IntegerField(
                        default=0,
                        help_text="Ancho con ceros a la izquierda (Odoo padding).",
                    ),
                ),
                (
                    "use_date_range",
                    models.BooleanField(
                        default=False,
                        help_text="Subsecuencias por rango de fecha (Odoo use_date_range).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secuencia",
                "verbose_name_plural": "Secuencias",
                "db_table": "ir_sequence",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del banco (Odoo name).", max_length=128
                    ),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank Identifier Code / SWIFT (Odoo bic).",
                        max_length=16,
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, default="", help_text="Odoo street.", max_length=128
                    ),
                ),
                (
                    "street2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo street2.",
                        max_length=128,
                    ),
                ),
                (
                    "zip",
                    models.CharField(
                        blank=True, default="", help_text="Odoo zip.", max_length=24
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", help_text="Odoo city.", max_length=128
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", help_text="Odoo email.", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", help_text="Odoo phone.", max_length=32
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
            ],
            options={
                "verbose_name": "Banco",
                "verbose_name_plural": "Bancos",
                "db_table": "res_bank",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del país (Odoo res.country.name).",
                        max_length=120,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código ISO 3166-1 alpha-2 (Odoo code).",
                        max_length=2,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone_code",
                    models.IntegerField(
                        blank=True,
                        help_text="Código telefónico del país (Odoo phone_code).",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "db_table": "res_country",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResCountryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del grupo (Odoo name).", max_length=128
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código del grupo (Odoo code).",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de países",
                "verbose_name_plural": "Grupos de países",
                "db_table": "res_country_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResCountryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del estado (Odoo name).", max_length=120
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código del estado (Odoo code).", max_length=8
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado / provincia",
                "verbose_name_plural": "Estados / provincias",
                "db_table": "res_country_state",
                "ordering": ["country", "code"],
            },
        ),
        migrations.CreateModel(
            name="ResCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Código de moneda ISO 4217 (Odoo res.currency.name).",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la moneda (Odoo full_name).",
                        max_length=64,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Signo de la moneda (Odoo symbol).", max_length=8
                    ),
                ),
                (
                    "rounding",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.01"),
                        help_text="Factor de redondeo (Odoo rounding).",
                        max_digits=12,
                    ),
                ),
                (
                    "decimal_places",
                    models.IntegerField(
                        default=2,
                        help_text="Decimales, computado de rounding (Odoo decimal_places).",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("after", "Después del importe"),
                            ("before", "Antes del importe"),
                        ],
                        default="after",
                        help_text="Posición del símbolo (Odoo position).",
                        max_length=6,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Moneda activa (Odoo active)."
                    ),
                ),
                (
                    "currency_unit_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta de la unidad (Odoo currency_unit_label).",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "db_table": "res_currency",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResCurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.DateField(
                        help_text="Fecha del tipo de cambio (Odoo name, requerido)."
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=12,
                        default=Decimal("1.0"),
                        help_text="Tasa por unidad de la moneda de la empresa (Odoo rate).",
                        max_digits=24,
                    ),
                ),
                (
                    "company_rate",
                    models.DecimalField(
                        decimal_places=12,
                        default=Decimal("1.0"),
                        help_text="Tasa vista desde la empresa (Odoo company_rate).",
                        max_digits=24,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de cambio",
                "verbose_name_plural": "Tipos de cambio",
                "db_table": "res_currency_rate",
                "ordering": ["-name", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ResLang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del idioma (Odoo name).", max_length=64
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Locale code (Odoo code, p. ej. es_MX). Único.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "iso_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO code — nombre del .po de traducción (Odoo iso_code).",
                        max_length=16,
                    ),
                ),
                (
                    "url_code",
                    models.CharField(
                        help_text="Código en la URL (Odoo url_code).", max_length=16
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, help_text="Odoo active."),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("ltr", "Left-to-Right"), ("rtl", "Right-to-Left")],
                        default="ltr",
                        help_text="Dirección de escritura (Odoo direction).",
                        max_length=3,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="%m/%d/%Y",
                        help_text="Formato de fecha (Odoo date_format).",
                        max_length=32,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[
                            ("%H:%M:%S", "13:00:00"),
                            ("%I:%M:%S %p", " 1:00:00 PM"),
                        ],
                        default="%H:%M:%S",
                        help_text="Formato de hora (Odoo time_format).",
                        max_length=32,
                    ),
                ),
                (
                    "week_start",
                    models.CharField(
                        choices=[
                            ("1", "Monday"),
                            ("2", "Tuesday"),
                            ("3", "Wednesday"),
                            ("4", "Thursday"),
                            ("5", "Friday"),
                            ("6", "Saturday"),
                            ("7", "Sunday"),
                        ],
                        default="7",
                        help_text="Primer día de la semana (Odoo week_start).",
                        max_length=1,
                    ),
                ),
                (
                    "grouping",
                    models.CharField(
                        choices=[
                            ("[3,0]", "International Grouping"),
                            ("[3,2,0]", "Indian Grouping"),
                        ],
                        default="[3,0]",
                        help_text="Formato de agrupamiento de miles (Odoo grouping).",
                        max_length=16,
                    ),
                ),
                (
                    "decimal_point",
                    models.CharField(
                        default=".",
                        help_text="Separador decimal (Odoo decimal_point).",
                        max_length=4,
                    ),
                ),
                (
                    "thousands_sep",
                    models.CharField(
                        blank=True,
                        default=",",
                        help_text="Separador de miles (Odoo thousands_sep).",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "verbose_name": "Idioma",
                "verbose_name_plural": "Idiomas",
                "db_table": "res_lang",
                "ordering": ["-active", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site_name",
                    models.CharField(default="PracticaYoruba", max_length=100),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logotipo del sitio para el recibo PDF (UC-PAY-10). PNG recomendado.",
                        null=True,
                        upload_to="settings/logo/",
                        verbose_name="Logotipo",
                    ),
                ),
                (
                    "iva_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.16"),
                        help_text="Tasa de IVA expresada como fracción decimal entre 0 y 1 (ej. 0.16 = 16%).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN",
                        help_text="Código ISO 4217 de la moneda (3 letras mayúsculas).",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Currency must be a 3-letter ISO 4217 code (uppercase).",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "payment_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minutos hasta que una orden PENDING se cancela por timeout (UC-SYS-01).",
                    ),
                ),
                (
                    "order_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Minutos antes de que una orden sin pagar expire (FR-CFG-03.01).",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_return_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Días máximos para solicitar una devolución.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("min_stock_threshold", models.PositiveIntegerField(default=5)),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "referral_active",
                    models.BooleanField(
                        default=False,
                        help_text="Si el programa de referidos esta activo (UC-PRO-05 PRE-02).",
                    ),
                ),
                (
                    "referral_welcome_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Descuento fijo del voucher de bienvenida emitido al nuevo comprador que canjea un codigo referral (UC-PRO-05 Subflujo B).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "referral_reward_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50.00"),
                        help_text="Descuento fijo del voucher de recompensa emitido al referidor cuando el referido completa su primera compra (UC-PRO-05 Subflujo C).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.TextField(blank=True, default="")),
                ("social_links", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Configuración del sitio",
                "db_table": "settings_sitesettings",
            },
        ),
        migrations.CreateModel(
            name="SystemParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "System Parameter",
                "verbose_name_plural": "System Parameters",
                "db_table": "system_parameter",
                "ordering": ["key"],
            },
        ),
    ]
