# Generated by Django 6.0.5 on 2026-08-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="billing_email",
            field=models.CharField(
                blank=True,
                default="",
                help_text="DIVERGENCIA DECLARADA: la referencia no separa el correo de contacto del de facturación en ``res.company`` — su ``email`` es ``related`` al partner y la facturación sale del partner de la factura. Se conserva como columna propia porque el negocio sí los distingue; si se unifican, este campo desaparece a favor de la property ``email``.",
                max_length=254,
                verbose_name="Correo de facturación",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="code",
            field=models.SlugField(
                blank=True,
                help_text="Identificador estable del tenant L1 en la plataforma.",
                null=True,
                unique=True,
                verbose_name="Código",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Compañía de datos compartidos de plataforma (L0), no un tenant.",
                verbose_name="Compañía de sistema",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="status",
            field=models.CharField(
                choices=[
                    ("trial", "En prueba"),
                    ("active", "Activo"),
                    ("suspended", "Suspendido"),
                    ("cancelled", "Cancelado"),
                ],
                default="trial",
                help_text="Ciclo de vida de la contratación. Distinto de ``active``, que es el archivado de Odoo.",
                max_length=12,
                verbose_name="Estado",
            ),
        ),
        migrations.AddField(
            model_name="respartner",
            name="company_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Razón social escrita a mano cuando el contacto NO cuelga de una empresa (Odoo ``company_name``, ``odoo19c: res_partner.py:308``).",
                max_length=150,
            ),
        ),
    ]
