# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutattempt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkout_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="export_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="irattachment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa (Odoo company_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="ircron",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario de ejecución (Odoo user_id — ahí required con default=env.user; aquí nullable porque no hay contexto de request implícito al registrar la tarea, ver docstring del módulo).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ir_crons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="irdefault",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que aplica el default (Odoo company_id). NULL = default para todas las empresas.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ir_defaults",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="irdefault",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario al que aplica el default (Odoo user_id). NULL = default para todos los usuarios.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ir_defaults",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="irfilters",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Dueño del filtro (Odoo user_id). NULL = filtro compartido/global (visible para todos); set = filtro privado de ese usuario.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ir_filters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="irlogging",
            index=models.Index(fields=["-created_at"], name="ir_logging_created_idx"),
        ),
        migrations.AddField(
            model_name="irsequence",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa (Odoo company_id).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequences",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="resbank",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="País (Odoo country).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banks",
                to="base.rescountry",
            ),
        ),
        migrations.AddField(
            model_name="rescountrygroup",
            name="country_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="res_country_res_country_group_rel",
                help_text="Países del grupo (Odoo country_ids).",
                related_name="country_groups",
                to="base.rescountry",
            ),
        ),
        migrations.AddField(
            model_name="rescountrystate",
            name="country",
            field=models.ForeignKey(
                help_text="País (Odoo country_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_ids",
                to="base.rescountry",
            ),
        ),
        migrations.AddField(
            model_name="resbank",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="Estado/provincia (Odoo state).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="banks",
                to="base.rescountrystate",
            ),
        ),
        migrations.AddField(
            model_name="rescountry",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Moneda del país (Odoo currency_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="countries",
                to="base.rescurrency",
            ),
        ),
        migrations.AddField(
            model_name="rescurrencyrate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa (Odoo company_id).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency_rates",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="rescurrencyrate",
            name="currency",
            field=models.ForeignKey(
                help_text="Moneda (Odoo currency_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="base.rescurrency",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkoutattempt",
            constraint=models.UniqueConstraint(
                fields=("user", "idempotency_key"), name="unique_checkout_attempt"
            ),
        ),
        migrations.AddIndex(
            model_name="irattachment",
            index=models.Index(
                fields=["res_model", "res_id"], name="ir_attachment_res_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ircron",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval_number__gt", 0)),
                name="ir_cron_interval_number_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="irdefault",
            constraint=models.UniqueConstraint(
                fields=("model", "field", "user", "company", "condition"),
                name="uq_ir_default_model_field_user_company_condition",
            ),
        ),
        migrations.AddConstraint(
            model_name="irfilters",
            constraint=models.UniqueConstraint(
                fields=("model_id", "user", "action_id", "name"),
                name="uq_ir_filters_model_user_action_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="rescountrystate",
            constraint=models.UniqueConstraint(
                fields=("country", "code"), name="unique_state_country_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="rescurrencyrate",
            constraint=models.UniqueConstraint(
                fields=("currency", "company", "name"),
                name="unique_currency_rate_per_day",
            ),
        ),
    ]
