# Generated by Django 6.0.5 on 2026-08-04 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_res_company_users_rel_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irmodelaccess",
            name="group_id",
            field=models.ForeignKey(
                blank=True,
                db_column="group_id",
                help_text="Vacío = acceso global. ondelete restrict de la fuente: no se borra un grupo que aún concede permisos.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="model_access",
                to="base.resgroups",
                verbose_name="Grupo",
            ),
        ),
        migrations.AlterField(
            model_name="irmodelaccess",
            name="model_id",
            field=models.ForeignKey(
                db_column="model_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_ids",
                to="base.irmodel",
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="irmodelfields",
            name="model_id",
            field=models.ForeignKey(
                db_column="model_id",
                help_text="Odoo lo llama field_id (One2many en singular, contra su propia convención _ids); se conserva ese nombre en el reverso.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_id",
                to="base.irmodel",
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="irmodelfields",
            name="related_field_id",
            field=models.ForeignKey(
                blank=True,
                db_column="related_field_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_from",
                to="base.irmodelfields",
                verbose_name="Campo relacionado",
            ),
        ),
        migrations.AlterField(
            model_name="irmodelfields",
            name="relation_field_id",
            field=models.ForeignKey(
                blank=True,
                db_column="relation_field_id",
                help_text="Odoo lo computa con store=True; aquí es columna real igual, poblada por la reflexión.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inverse_of",
                to="base.irmodelfields",
                verbose_name="Campo de relación",
            ),
        ),
        migrations.AlterField(
            model_name="irmodelinherit",
            name="model_id",
            field=models.ForeignKey(
                db_column="model_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inherit_ids",
                to="base.irmodel",
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="irmodelinherit",
            name="parent_field_id",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_field_id",
                help_text="Sólo en herencia por delegación (Odoo _inherits).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inherit_ids",
                to="base.irmodelfields",
                verbose_name="Campo de delegación",
            ),
        ),
        migrations.AlterField(
            model_name="irmodelinherit",
            name="parent_id",
            field=models.ForeignKey(
                db_column="parent_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inherit_child_ids",
                to="base.irmodel",
                verbose_name="Modelo padre",
            ),
        ),
        migrations.AlterField(
            model_name="iruiview",
            name="inherit_id",
            field=models.ForeignKey(
                blank=True,
                db_column="inherit_id",
                help_text="ondelete restrict de la fuente: no se borra una vista de la que otras heredan.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inherit_children_ids",
                to="base.iruiview",
                verbose_name="Vista heredada",
            ),
        ),
        migrations.AlterField(
            model_name="iruiviewcustom",
            name="ref_id",
            field=models.ForeignKey(
                db_column="ref_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_ids",
                to="base.iruiview",
                verbose_name="Vista original",
            ),
        ),
    ]
