# Generated by Django 6.0.5 on 2026-08-01 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre técnico = carpeta del addon (Odoo ir.module.module.name).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "shortdesc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre legible del manifest (Odoo shortdesc ← manifest name).",
                        max_length=200,
                    ),
                ),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                (
                    "category",
                    models.CharField(
                        blank=True, default="Uncategorized", max_length=100
                    ),
                ),
                ("version", models.CharField(blank=True, default="1.0", max_length=32)),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("GPL-2", "GPL Version 2"),
                            ("GPL-2 or any later version", "GPL-2 o posterior"),
                            ("GPL-3", "GPL Version 3"),
                            ("GPL-3 or any later version", "GPL-3 o posterior"),
                            ("AGPL-3", "Affero GPL-3"),
                            ("LGPL-3", "LGPL Version 3"),
                            (
                                "Other OSI approved licence",
                                "Otra licencia aprobada por OSI",
                            ),
                            ("OEEL-1", "Odoo Enterprise Edition License v1.0"),
                            ("OPL-1", "Odoo Proprietary License v1.0"),
                            ("Other proprietary", "Otra propietaria"),
                            ("Confidential", "Propietaria de Kaupamex"),
                        ],
                        default="LGPL-3",
                        help_text="Licencia declarada por el manifest. NO se re-etiqueta (DEC-KX-03).",
                        max_length=32,
                    ),
                ),
                (
                    "application",
                    models.BooleanField(
                        default=False,
                        help_text="Addon vendible como aplicación, no técnico (Odoo application).",
                    ),
                ),
                ("auto_install", models.BooleanField(default=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("uninstallable", "No instalable"),
                            ("uninstalled", "No instalado"),
                            ("installed", "Instalado"),
                        ],
                        db_index=True,
                        default="uninstalled",
                        help_text="Derivado de INSTALLED_APPS; no hay instalador que lo escriba.",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo técnico",
                "db_table": "ir_module_module",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IrModuleDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nombre técnico del addon del que depende.",
                        max_length=100,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="El addon que declara la dependencia.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="base.irmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dependencia de módulo",
                "verbose_name_plural": "Dependencias de módulo",
                "db_table": "ir_module_module_dependency",
                "ordering": ["name"],
                "unique_together": {("module", "name")},
            },
        ),
    ]
