# Generated by Django 6.0.5 on 2026-07-18 20:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_seed_business_keys"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResCurrency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Código de moneda ISO 4217 (Odoo res.currency.name).",
                        max_length=3,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la moneda (Odoo full_name).",
                        max_length=64,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Signo de la moneda (Odoo symbol).", max_length=8
                    ),
                ),
                (
                    "rounding",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0.01"),
                        help_text="Factor de redondeo (Odoo rounding).",
                        max_digits=12,
                    ),
                ),
                (
                    "decimal_places",
                    models.IntegerField(
                        default=2,
                        help_text="Decimales, computado de rounding (Odoo decimal_places).",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("after", "Después del importe"),
                            ("before", "Antes del importe"),
                        ],
                        default="after",
                        help_text="Posición del símbolo (Odoo position).",
                        max_length=6,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Moneda activa (Odoo active)."
                    ),
                ),
                (
                    "currency_unit_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta de la unidad (Odoo currency_unit_label).",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
                "db_table": "res_currency",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del país (Odoo res.country.name).",
                        max_length=120,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Código ISO 3166-1 alpha-2 (Odoo code).",
                        max_length=2,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "phone_code",
                    models.IntegerField(
                        blank=True,
                        help_text="Código telefónico del país (Odoo phone_code).",
                        null=True,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda del país (Odoo currency_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="countries",
                        to="base.rescurrency",
                    ),
                ),
            ],
            options={
                "verbose_name": "País",
                "verbose_name_plural": "Países",
                "db_table": "res_country",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResCountryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del estado (Odoo name).", max_length=120
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código del estado (Odoo code).", max_length=8
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="País (Odoo country_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_ids",
                        to="base.rescountry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado / provincia",
                "verbose_name_plural": "Estados / provincias",
                "db_table": "res_country_state",
                "ordering": ["country", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "code"), name="unique_state_country_code"
                    )
                ],
            },
        ),
    ]
