# Generated by Django 6.0.5 on 2026-07-18 23:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rescurrency_rescountry_rescountrystate"),
        ("company", "0008_alter_company_tax_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DecimalPrecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Uso (Odoo name, p. ej. "Product Price"). Único.',
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "digits",
                    models.IntegerField(
                        default=2, help_text="Número de decimales (Odoo digits)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Precisión decimal",
                "verbose_name_plural": "Precisiones decimales",
                "db_table": "decimal_precision",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResLang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del idioma (Odoo name).", max_length=64
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Locale code (Odoo code, p. ej. es_MX). Único.",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "iso_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ISO code — nombre del .po de traducción (Odoo iso_code).",
                        max_length=16,
                    ),
                ),
                (
                    "url_code",
                    models.CharField(
                        help_text="Código en la URL (Odoo url_code).", max_length=16
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, help_text="Odoo active."),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("ltr", "Left-to-Right"), ("rtl", "Right-to-Left")],
                        default="ltr",
                        help_text="Dirección de escritura (Odoo direction).",
                        max_length=3,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="%m/%d/%Y",
                        help_text="Formato de fecha (Odoo date_format).",
                        max_length=32,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[
                            ("%H:%M:%S", "13:00:00"),
                            ("%I:%M:%S %p", " 1:00:00 PM"),
                        ],
                        default="%H:%M:%S",
                        help_text="Formato de hora (Odoo time_format).",
                        max_length=32,
                    ),
                ),
                (
                    "week_start",
                    models.CharField(
                        choices=[
                            ("1", "Monday"),
                            ("2", "Tuesday"),
                            ("3", "Wednesday"),
                            ("4", "Thursday"),
                            ("5", "Friday"),
                            ("6", "Saturday"),
                            ("7", "Sunday"),
                        ],
                        default="7",
                        help_text="Primer día de la semana (Odoo week_start).",
                        max_length=1,
                    ),
                ),
                (
                    "grouping",
                    models.CharField(
                        choices=[
                            ("[3,0]", "International Grouping"),
                            ("[3,2,0]", "Indian Grouping"),
                        ],
                        default="[3,0]",
                        help_text="Formato de agrupamiento de miles (Odoo grouping).",
                        max_length=16,
                    ),
                ),
                (
                    "decimal_point",
                    models.CharField(
                        default=".",
                        help_text="Separador decimal (Odoo decimal_point).",
                        max_length=4,
                    ),
                ),
                (
                    "thousands_sep",
                    models.CharField(
                        blank=True,
                        default=",",
                        help_text="Separador de miles (Odoo thousands_sep).",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "verbose_name": "Idioma",
                "verbose_name_plural": "Idiomas",
                "db_table": "res_lang",
                "ordering": ["-active", "name"],
            },
        ),
        migrations.CreateModel(
            name="IrSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre (Odoo name).", max_length=128),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código de la secuencia (Odoo code).",
                        max_length=64,
                    ),
                ),
                (
                    "implementation",
                    models.CharField(
                        choices=[("standard", "Standard"), ("no_gap", "No gap")],
                        default="standard",
                        help_text="Standard o No gap (Odoo implementation).",
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Prefijo, interpolable por fecha (Odoo prefix).",
                        max_length=128,
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sufijo, interpolable por fecha (Odoo suffix).",
                        max_length=128,
                    ),
                ),
                (
                    "number_next",
                    models.IntegerField(
                        default=1, help_text="Próximo número (Odoo number_next)."
                    ),
                ),
                (
                    "number_increment",
                    models.IntegerField(
                        default=1,
                        help_text="Paso de incremento (Odoo number_increment / Step).",
                    ),
                ),
                (
                    "padding",
                    models.IntegerField(
                        default=0,
                        help_text="Ancho con ceros a la izquierda (Odoo padding).",
                    ),
                ),
                (
                    "use_date_range",
                    models.BooleanField(
                        default=False,
                        help_text="Subsecuencias por rango de fecha (Odoo use_date_range).",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequences",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secuencia",
                "verbose_name_plural": "Secuencias",
                "db_table": "ir_sequence",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResBank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del banco (Odoo name).", max_length=128
                    ),
                ),
                (
                    "bic",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Bank Identifier Code / SWIFT (Odoo bic).",
                        max_length=16,
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, default="", help_text="Odoo street.", max_length=128
                    ),
                ),
                (
                    "street2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo street2.",
                        max_length=128,
                    ),
                ),
                (
                    "zip",
                    models.CharField(
                        blank=True, default="", help_text="Odoo zip.", max_length=24
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", help_text="Odoo city.", max_length=128
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, default="", help_text="Odoo email.", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", help_text="Odoo phone.", max_length=32
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="País (Odoo country).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banks",
                        to="base.rescountry",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Estado/provincia (Odoo state).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="banks",
                        to="base.rescountrystate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Banco",
                "verbose_name_plural": "Bancos",
                "db_table": "res_bank",
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ResCountryGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del grupo (Odoo name).", max_length=128
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código del grupo (Odoo code).",
                        max_length=16,
                    ),
                ),
                (
                    "country_ids",
                    models.ManyToManyField(
                        blank=True,
                        db_table="res_country_res_country_group_rel",
                        help_text="Países del grupo (Odoo country_ids).",
                        related_name="country_groups",
                        to="base.rescountry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de países",
                "verbose_name_plural": "Grupos de países",
                "db_table": "res_country_group",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ResCurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.DateField(
                        help_text="Fecha del tipo de cambio (Odoo name, requerido)."
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=12,
                        default=Decimal("1.0"),
                        help_text="Tasa por unidad de la moneda de la empresa (Odoo rate).",
                        max_digits=24,
                    ),
                ),
                (
                    "company_rate",
                    models.DecimalField(
                        decimal_places=12,
                        default=Decimal("1.0"),
                        help_text="Tasa vista desde la empresa (Odoo company_rate).",
                        max_digits=24,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_rates",
                        to="company.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        help_text="Moneda (Odoo currency_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="base.rescurrency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de cambio",
                "verbose_name_plural": "Tipos de cambio",
                "db_table": "res_currency_rate",
                "ordering": ["-name", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("currency", "company", "name"),
                        name="unique_currency_rate_per_day",
                    )
                ],
            },
        ),
    ]
