# Generated by Django 6.0.5 on 2026-07-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_decimalprecision_reslang_irsequence_resbank_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrLogging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("client", "Client"), ("server", "Server")],
                        db_index=True,
                        default="server",
                        max_length=8,
                    ),
                ),
                (
                    "dbname",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("path", models.CharField(blank=True, default="", max_length=255)),
                ("func", models.CharField(blank=True, default="", max_length=255)),
                ("line", models.CharField(blank=True, default="", max_length=32)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("trace", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Logging",
                "verbose_name_plural": "Logging",
                "db_table": "ir_logging",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="ir_logging_created_idx")
                ],
            },
        ),
    ]
