# Generated by Django 6.0.5 on 2026-08-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_report_type_solo_pdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iractionsreport",
            name="report_type",
            field=models.CharField(
                choices=[("pdf", "PDF")],
                default="pdf",
                help_text="Formato de salida. Sin el prefijo qweb- de la referencia: aquí no hay QWeb, el render es libharu (ADR-017).",
                max_length=16,
                verbose_name="Tipo de reporte",
            ),
        ),
    ]
