# Generated by Django 6.0.5 on 2026-08-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_iractionsreport_report_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iractionsactions",
            name="path",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Debe ser única (Odoo _path_unique). default=None, no '': la referencia declara el campo sin default (``path = fields.Char(...)``, odoo19c: ir_actions.py:70) y un Char sin valor se escribe NULL en Odoo, no cadena vacía — con NULL el UNIQUE admite múltiples acciones sin ruta (H-API-332: default='' colisionaba en la segunda ir.actions.server creada sin path explícito).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ruta en la URL",
            ),
        ),
        migrations.AlterField(
            model_name="iractionsacturl",
            name="path",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Debe ser única (Odoo _path_unique). default=None, no '': la referencia declara el campo sin default (``path = fields.Char(...)``, odoo19c: ir_actions.py:70) y un Char sin valor se escribe NULL en Odoo, no cadena vacía — con NULL el UNIQUE admite múltiples acciones sin ruta (H-API-332: default='' colisionaba en la segunda ir.actions.server creada sin path explícito).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ruta en la URL",
            ),
        ),
        migrations.AlterField(
            model_name="iractionsactwindow",
            name="path",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Debe ser única (Odoo _path_unique). default=None, no '': la referencia declara el campo sin default (``path = fields.Char(...)``, odoo19c: ir_actions.py:70) y un Char sin valor se escribe NULL en Odoo, no cadena vacía — con NULL el UNIQUE admite múltiples acciones sin ruta (H-API-332: default='' colisionaba en la segunda ir.actions.server creada sin path explícito).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ruta en la URL",
            ),
        ),
        migrations.AlterField(
            model_name="iractionsclient",
            name="path",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Debe ser única (Odoo _path_unique). default=None, no '': la referencia declara el campo sin default (``path = fields.Char(...)``, odoo19c: ir_actions.py:70) y un Char sin valor se escribe NULL en Odoo, no cadena vacía — con NULL el UNIQUE admite múltiples acciones sin ruta (H-API-332: default='' colisionaba en la segunda ir.actions.server creada sin path explícito).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ruta en la URL",
            ),
        ),
        migrations.AlterField(
            model_name="iractionsreport",
            name="path",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Debe ser única (Odoo _path_unique). default=None, no '': la referencia declara el campo sin default (``path = fields.Char(...)``, odoo19c: ir_actions.py:70) y un Char sin valor se escribe NULL en Odoo, no cadena vacía — con NULL el UNIQUE admite múltiples acciones sin ruta (H-API-332: default='' colisionaba en la segunda ir.actions.server creada sin path explícito).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ruta en la URL",
            ),
        ),
        migrations.AlterField(
            model_name="iractionsserver",
            name="path",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Debe ser única (Odoo _path_unique). default=None, no '': la referencia declara el campo sin default (``path = fields.Char(...)``, odoo19c: ir_actions.py:70) y un Char sin valor se escribe NULL en Odoo, no cadena vacía — con NULL el UNIQUE admite múltiples acciones sin ruta (H-API-332: default='' colisionaba en la segunda ir.actions.server creada sin path explícito).",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Ruta en la URL",
            ),
        ),
    ]
