# Generated by Django 6.0.5 on 2026-07-19 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_copiar_applog_a_irlogging"),
        ("company", "0008_alter_company_tax_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del adjunto (Odoo name).", max_length=256
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Odoo description."
                    ),
                ),
                (
                    "res_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Modelo polimórfico referenciado, p. ej. "catalogue.Product" (Odoo res_model). NO es una FK — vínculo plano igual que Odoo.',
                        max_length=128,
                    ),
                ),
                (
                    "res_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Campo binary del modelo referenciado, si aplica (Odoo res_field).",
                        max_length=128,
                    ),
                ),
                (
                    "res_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del registro referenciado (Odoo res_id / Many2oneReference simplificado a Integer plano — el ORM shim del proyecto no tiene un tipo Many2oneReference fiel; Odoo tampoco lo trata como FK real).",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("binary", "File"), ("url", "URL")],
                        default="binary",
                        help_text="Odoo type: binary (archivo) o url (enlace externo).",
                        max_length=8,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default="", help_text="Odoo url.", max_length=1024
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        default=False, help_text="Odoo public — accesible sin auth."
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Token de acceso externo (Odoo access_token).",
                        max_length=64,
                    ),
                ),
                (
                    "mimetype",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo mimetype.",
                        max_length=128,
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        default=0, help_text="Tamaño en bytes (Odoo file_size)."
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA1 del contenido (Odoo checksum, calculado en save()).",
                        max_length=40,
                    ),
                ),
                (
                    "store_fname",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre asignado por el storage backend de Django (Odoo store_fname — aquí no es una ruta sha1-sharded propia, ver docstring del módulo).",
                        max_length=256,
                    ),
                ),
                (
                    "datas",
                    models.FileField(
                        blank=True,
                        help_text="Contenido binario (Odoo datas/raw) — FileField de Django, no el filestore propio de Odoo (ver docstring del módulo).",
                        null=True,
                        upload_to="attachments/%Y/%m/",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adjunto",
                "verbose_name_plural": "Adjuntos",
                "db_table": "ir_attachment",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["res_model", "res_id"], name="ir_attachment_res_idx"
                    )
                ],
            },
        ),
    ]
