# Generated by Django 6.0.5 on 2026-07-19 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_irattachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IrFilters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del filtro (Odoo name).", max_length=256
                    ),
                ),
                (
                    "model_id",
                    models.CharField(
                        help_text='Modelo técnico referenciado, p. ej. "catalogue.Product" (Odoo model_id — Selection dinámico en Odoo, aquí Char plano porque no es una FK real, igual criterio que res_model en ir_attachment).',
                        max_length=128,
                    ),
                ),
                (
                    "domain",
                    models.TextField(
                        default="[]",
                        help_text="Dominio de búsqueda serializado (Odoo domain).",
                    ),
                ),
                (
                    "context",
                    models.TextField(
                        default="{}", help_text="Contexto serializado (Odoo context)."
                    ),
                ),
                (
                    "sort",
                    models.CharField(
                        default="[]",
                        help_text="Orden serializado (Odoo sort — Char en la fuente, no Text).",
                        max_length=512,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Filtro por defecto para el alcance modelo+usuario (Odoo is_default).",
                    ),
                ),
                (
                    "action_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de la acción/menú al que aplica el filtro (Odoo action_id — Many2one a ir.actions.actions, modelo no portado en este monolito; se mantiene Integer plano, igual criterio que res_id en ir_attachment). NULL = aplica a todos los menús del modelo.",
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dueño del filtro (Odoo user_id). NULL = filtro compartido/global (visible para todos); set = filtro privado de ese usuario.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ir_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtro",
                "verbose_name_plural": "Filtros",
                "db_table": "ir_filters",
                "ordering": ["model_id", "name", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model_id", "user", "action_id", "name"),
                        name="uq_ir_filters_model_user_action_name",
                    )
                ],
            },
        ),
    ]
