# Generated by Django 6.0.5 on 2026-07-19 03:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_irfilters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IrCron",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la tarea (Odoo cron_name — ahí computado desde el name de la ir.actions.server delegada; aquí campo local directo porque no se porta esa delegación, ver docstring del módulo).",
                        max_length=256,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text='Modelo técnico objetivo, p. ej. "orders.Order" (adaptación del model_id delegado en ir.actions.server de Odoo — aquí Char plano, mismo criterio que ir_filters.model_id / ir_attachment.res_model: no es FK real, el runner diferido la resuelve con apps.get_model()).',
                        max_length=128,
                    ),
                ),
                (
                    "method_name",
                    models.CharField(
                        help_text="Nombre del método a invocar sobre model_name (adaptación: sustituye el code Python arbitrario de ir.actions.server de Odoo por una llamada directa a método, resuelta por el runner diferido).",
                        max_length=128,
                    ),
                ),
                (
                    "interval_number",
                    models.IntegerField(
                        default=1, help_text="Repetir cada x (Odoo interval_number)."
                    ),
                ),
                (
                    "interval_type",
                    models.CharField(
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours", "Hours"),
                            ("days", "Days"),
                            ("weeks", "Weeks"),
                            ("months", "Months"),
                        ],
                        default="months",
                        help_text="Unidad del intervalo (Odoo interval_type).",
                        max_length=8,
                    ),
                ),
                (
                    "nextcall",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Próxima fecha de ejecución planeada (Odoo nextcall).",
                    ),
                ),
                (
                    "lastcall",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última ejecución exitosa (Odoo lastcall).",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="Prioridad: 0 = más alta, 10 = más baja (Odoo priority, consumida por el runner diferido para ordenar el polling).",
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario de ejecución (Odoo user_id — ahí required con default=env.user; aquí nullable porque no hay contexto de request implícito al registrar la tarea, ver docstring del módulo).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ir_crons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea programada",
                "verbose_name_plural": "Tareas programadas",
                "db_table": "ir_cron",
                "ordering": ["name", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("interval_number__gt", 0)),
                        name="ir_cron_interval_number_positivo",
                    )
                ],
            },
        ),
    ]
