# Generated by Django 6.0.5 on 2026-07-19 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_ircron"),
        ("company", "0008_alter_company_tax_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IrDefault",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        help_text='Modelo técnico objetivo, p. ej. "orders.Order" (adaptación del field_id.model_id delegado de Odoo — aquí Char plano, mismo criterio que ir_filters.model_id / ir_cron.model_name: no es FK real, ver docstring del módulo).',
                        max_length=128,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Nombre del campo del modelo objetivo (adaptación del field_id.name delegado de Odoo — Char plano, no FK real, ver docstring del módulo).",
                        max_length=128,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Condición opcional que acota la aplicabilidad del default (Odoo condition — string opaco para este modelo de control).",
                        max_length=256,
                    ),
                ),
                (
                    "json_value",
                    models.TextField(
                        help_text="Valor por defecto serializado en JSON (Odoo json_value — Text en vez de Char porque Odoo lo declara sin límite de tamaño, ver docstring del módulo)."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa a la que aplica el default (Odoo company_id). NULL = default para todas las empresas.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ir_defaults",
                        to="company.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario al que aplica el default (Odoo user_id). NULL = default para todos los usuarios.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ir_defaults",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor por defecto",
                "verbose_name_plural": "Valores por defecto",
                "db_table": "ir_default",
                "ordering": ["model", "field", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("model", "field", "user", "company", "condition"),
                        name="uq_ir_default_model_field_user_company_condition",
                    )
                ],
            },
        ),
    ]
