# Generated by Django 6.0.5 on 2026-08-06 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_tax_computation_engine"),
        ("base", "0010_respartnerbank"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="account_purchase_tax",
            field=models.ForeignKey(
                blank=True,
                help_text="Impuesto de compra por defecto de la empresa (Odoo account_purchase_tax_id, company.py:127).",
                limit_choices_to={"type_tax_use": "purchase"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="account.accounttax",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="account_sale_tax",
            field=models.ForeignKey(
                blank=True,
                help_text="Impuesto de venta por defecto de la empresa. Lo hereda todo producto nuevo que no declare el suyo (Odoo account_sale_tax_id, company.py:126).",
                limit_choices_to={"type_tax_use": "sale"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="account.accounttax",
            ),
        ),
    ]
