# Generated by Django 6.0.5 on 2026-08-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_company_default_taxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="chart_template",
            field=models.CharField(
                blank=True,
                help_text="Código del plan contable cargado en esta empresa (Odoo chart_template, company.py:117). Una empresa hija hereda el de su raíz al crearse.",
                max_length=64,
                null=True,
            ),
        ),
    ]
