# Generated by Django 6.0.5 on 2026-08-06 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0011_journal_dashboard_fields"),
        ("base", "0012_company_chart_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="account_journal_early_pay_discount_gain_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de ganancia por descuento por pronto pago (Odoo account_journal_early_pay_discount_gain_account_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_account_journal_early_pay_discount_gain_account",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="account_journal_early_pay_discount_loss_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de pérdida por descuento por pronto pago (Odoo account_journal_early_pay_discount_loss_account_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_account_journal_early_pay_discount_loss_account",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="account_journal_suspense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta transitoria de banco (Odoo account_journal_suspense_account_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_account_journal_suspense_account",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="bank_account_code_prefix",
            field=models.CharField(
                blank=True,
                help_text="Prefijo de código de las cuentas bancarias (Odoo bank_account_code_prefix).",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="cash_account_code_prefix",
            field=models.CharField(
                blank=True,
                help_text="Prefijo de código de las cuentas de efectivo (Odoo cash_account_code_prefix).",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="default_cash_difference_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de faltante de efectivo (Odoo default_cash_difference_expense_account_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_default_cash_difference_expense_account",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="default_cash_difference_income_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de sobrante de efectivo (Odoo default_cash_difference_income_account_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_default_cash_difference_income_account",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="transfer_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de transferencia de liquidez (Odoo transfer_account_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_transfer_account",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="transfer_account_code_prefix",
            field=models.CharField(
                blank=True,
                help_text="Prefijo de código de las cuentas de transferencia (Odoo transfer_account_code_prefix).",
                max_length=64,
                null=True,
            ),
        ),
    ]
