# Generated by Django 6.0.5 on 2026-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ircron",
            name="model_name",
            field=models.CharField(
                help_text='Modelo técnico objetivo, p. ej. "sale.SaleOrder" (adaptación del model_id delegado en ir.actions.server de Odoo — aquí Char plano, mismo criterio que ir_filters.model_id / ir_attachment.res_model: no es FK real, el runner diferido la resuelve con apps.get_model()).',
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="irdefault",
            name="model",
            field=models.CharField(
                help_text='Modelo técnico objetivo, p. ej. "sale.SaleOrder" (adaptación del field_id.model_id delegado de Odoo — aquí Char plano, mismo criterio que ir_filters.model_id / ir_cron.model_name: no es FK real, ver docstring del módulo).',
                max_length=128,
            ),
        ),
    ]
