# Generated by Django 6.0.5 on 2026-08-07 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_accounttax_l10n_mx_factor_type_and_more"),
        ("base", "0014_rescompany_fiscalyear_lock_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resbank",
            name="l10n_mx_edi_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número de tres dígitos que la ABM asigna a las instituciones bancarias (Odoo l10n_mx_edi_code; ABM = Asociación de Bancos de México).",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="l10n_mx_income_re_invoicing_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de ingresos para re-facturación (Odoo l10n_mx_income_re_invoicing_account_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="l10n_mx_income_return_discount_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de ingresos para devoluciones y descuentos (Odoo l10n_mx_income_return_discount_account_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="respartnerbank",
            name="l10n_mx_edi_clabe",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CLABE — cifra bancaria estandarizada de México (Odoo l10n_mx_edi_clabe).",
                max_length=18,
            ),
        ),
    ]
