# Generated by Django 6.0.5 on 2026-08-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_resbank_l10n_mx_edi_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescountry",
            name="address_format",
            field=models.TextField(
                blank=True,
                default="%(street)s\n%(street2)s\n%(city)s %(state_code)s %(zip)s\n%(country_name)s",
                help_text="Plantilla con la que se compone una dirección de este país (Odoo address_format).",
            ),
        ),
        migrations.AddField(
            model_name="rescountry",
            name="name_position",
            field=models.CharField(
                choices=[
                    ("before", "Antes de la dirección"),
                    ("after", "Después de la dirección"),
                ],
                default="before",
                help_text="Dónde va el nombre del cliente respecto de la dirección (Odoo name_position).",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="rescountry",
            name="state_required",
            field=models.BooleanField(
                default=False,
                help_text="El estado es obligatorio en una dirección de este país (Odoo state_required).",
            ),
        ),
        migrations.AddField(
            model_name="rescountry",
            name="vat_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cómo se llama el identificador fiscal en este país — «RFC» en México, «NIF» en España (Odoo vat_label).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="rescountry",
            name="zip_required",
            field=models.BooleanField(
                default=True,
                help_text="El código postal es obligatorio (Odoo zip_required).",
            ),
        ),
    ]
