# Generated by Django 6.0.5 on 2026-08-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0018_rescompany_account_fiscal_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="respartnerbank",
            name="include_reference",
            field=models.BooleanField(
                default=False,
                help_text="Incluye la referencia/comunicación en el código QR (Odoo include_reference). Sin efecto en el puente puro: ``_get_additional_data_field`` sigue devolviendo None hasta que una localización lo sobreescriba.",
            ),
        ),
        migrations.AddField(
            model_name="respartnerbank",
            name="proxy_type",
            field=models.CharField(
                choices=[("none", "Ninguno")],
                default="none",
                help_text='Tipo de proxy del método EMV activo (Odoo proxy_type). El único valor del puente es "none" — cada localización agrega los suyos (teléfono, CLABE, RFC…).',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="respartnerbank",
            name="proxy_value",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Valor del proxy (teléfono, CLABE, RFC…) que el método EMV activo usa (Odoo proxy_value).",
                max_length=255,
            ),
        ),
    ]
