# Generated by Django 6.0.5 on 2026-08-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0019_respartnerbank_include_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="quotation_validity_days",
            field=models.IntegerField(
                default=30,
                help_text="Días entre la cotización y su vencimiento; 0 desactiva el vencimiento automático (Odoo quotation_validity_days, res_company.py:22-27).",
            ),
        ),
        migrations.AddConstraint(
            model_name="rescompany",
            constraint=models.CheckConstraint(
                condition=models.Q(quotation_validity_days__gte=0),
                name="sale_quotation_validity_days_check",
                violation_error_message="No puede fijar un número negativo para la validez por defecto de la cotización. Déjelo vacío (o en 0) para desactivar el vencimiento automático de cotizaciones.",
            ),
        ),
    ]
