# Generated by Django 6.0.5 on 2026-08-13 14:51

import addons.base.models.res_bank
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0020_rescompany_quotation_validity_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="respartnerbank",
            name="acc_type",
            field=models.CharField(
                choices=addons.base.models.res_bank._supported_account_types,
                default="bank",
                help_text="Tipo inferido del número: ``bank`` en el núcleo, ``iban`` cuando base_iban lo valide (Odoo acc_type; ver divergencia 2).",
                max_length=16,
            ),
        ),
    ]
