# Generated by Django 6.0.5 on 2026-08-13 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0021_alter_respartnerbank_acc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="irmodelfields",
            name="serialization_field_id",
            field=models.ForeignKey(
                blank=True,
                db_column="serialization_field_id",
                help_text="Si está puesto, el campo se guarda dentro de la estructura dispersa del campo de serialización en vez de tener columna propia. No se puede cambiar después de crearlo.",
                limit_choices_to={"ttype": "serialized"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sparse_field_ids",
                to="base.irmodelfields",
                verbose_name="Campo de serialización",
            ),
        ),
        migrations.AlterField(
            model_name="irmodelfields",
            name="ttype",
            field=models.CharField(
                choices=[
                    ("binary", "binary"),
                    ("boolean", "boolean"),
                    ("char", "char"),
                    ("date", "date"),
                    ("datetime", "datetime"),
                    ("float", "float"),
                    ("html", "html"),
                    ("image", "image"),
                    ("integer", "integer"),
                    ("json", "json"),
                    ("many2many", "many2many"),
                    ("many2one", "many2one"),
                    ("many2one_reference", "many2one_reference"),
                    ("monetary", "monetary"),
                    ("one2many", "one2many"),
                    ("properties", "properties"),
                    ("properties_definition", "properties_definition"),
                    ("reference", "reference"),
                    ("selection", "selection"),
                    ("text", "text"),
                    ("serialized", "serialized"),
                ],
                max_length=32,
                verbose_name="Tipo de campo",
            ),
        ),
    ]
