# Generated by Django 6.0.5 on 2026-08-15 05:24

import addons.stock.models.res_company
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0022_irmodelfields_serialization_field_id_and_more"),
        ("mail", "0004_seed_cron_email_queue"),
        ("stock", "0009_stockpicking_picking_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="annual_inventory_day",
            field=models.IntegerField(
                default=31,
                help_text="Día del mes en que ocurre el inventario anual. Cero o negativo se toma como el primer día del mes; mayor que el último día del mes, como el último (Odoo annual_inventory_day).",
                verbose_name="Día del mes",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="annual_inventory_month",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "January"),
                    ("2", "February"),
                    ("3", "March"),
                    ("4", "April"),
                    ("5", "May"),
                    ("6", "June"),
                    ("7", "July"),
                    ("8", "August"),
                    ("9", "September"),
                    ("10", "October"),
                    ("11", "November"),
                    ("12", "December"),
                ],
                default="12",
                help_text="Mes del inventario anual para los productos que no están en una ubicación con conteo cíclico; vacío desactiva el inventario anual automático (Odoo annual_inventory_month).",
                max_length=2,
                null=True,
                verbose_name="Mes del inventario anual",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="horizon_days",
            field=models.FloatField(
                default=365.0,
                help_text="Cuántos días antes se dispara una regla de reabastecimiento para adelantarse a los retrasos; 0 la dispara justo a tiempo y evita sobrestock (Odoo horizon_days, required=True).",
                verbose_name="Horizonte de reabastecimiento",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="internal_transit_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación por la que pasa la mercancía al moverse entre dos almacenes de esta misma empresa (Odoo internal_transit_location_id).",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="companies_as_transit",
                to="stock.stocklocation",
                verbose_name="Ubicación de tránsito interna",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="stock_confirmation_type",
            field=models.CharField(
                blank=True,
                choices=[("sms", "SMS")],
                default="sms",
                help_text="Canal del aviso por texto (Odoo stock_confirmation_type).",
                max_length=8,
                null=True,
                verbose_name="Canal de confirmación",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="stock_mail_confirmation_template",
            field=models.ForeignKey(
                blank=True,
                default=addons.stock.models.res_company._default_confirmation_mail_template,
                help_text="Correo que recibe el cliente cuando su pedido sale (Odoo stock_mail_confirmation_template_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies_as_stock_confirmation",
                to="mail.mailtemplate",
                verbose_name="Plantilla de confirmación de transferencia",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="stock_move_email_validation",
            field=models.BooleanField(
                default=False,
                help_text="Envía un correo al cliente cuando la transferencia se completa (Odoo stock_move_email_validation).",
                verbose_name="Confirmación por correo de la transferencia",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="stock_text_confirmation",
            field=models.BooleanField(
                default=False,
                help_text="Avisa por texto (SMS) al completar la transferencia (Odoo stock_text_confirmation).",
                verbose_name="Confirmación por texto",
            ),
        ),
        migrations.AddField(
            model_name="respartner",
            name="picking_warn_msg",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Mensaje que se muestra al operar una transferencia con este contacto (Odoo picking_warn_msg).",
                verbose_name="Aviso en la transferencia",
            ),
        ),
        migrations.AddField(
            model_name="respartner",
            name="property_stock_customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación destino al enviarle mercancía a este contacto (Odoo property_stock_customer).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners_as_customer_location",
                to="stock.stocklocation",
                verbose_name="Ubicación de cliente",
            ),
        ),
        migrations.AddField(
            model_name="respartner",
            name="property_stock_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación origen al recibir mercancía de este contacto (Odoo property_stock_supplier).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="partners_as_supplier_location",
                to="stock.stocklocation",
                verbose_name="Ubicación de proveedor",
            ),
        ),
    ]
