# Generated by Django 6.0.5 on 2026-08-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """``_check_name`` de la fuente (``odoo19c: res_partner.py:326``, tarea
    #504) — objeto de tabla, hogar ``Meta.constraints``.

    ``makemigrations`` detectó también dos ``AlterModelOptions`` (respartner
    y resusers) como drift preexistente, sin relación con este atributo y
    fuera del alcance de escritura de esta tarea (``res_users.py`` no está
    en la lista de archivos permitidos). Se omiten aquí a propósito —no se
    incluyen operaciones que no correspondan al cambio de esta migración.
    """

    dependencies = [
        ("base", "0023_rescompany_annual_inventory_day_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="respartner",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("name__isnull", False), ("type", "contact")),
                    models.Q(("type", "contact"), _negated=True),
                    _connector="OR",
                ),
                name="res_partner_check_name",
                violation_error_message="Contacts require a name",
            ),
        ),
    ]
