# Generated by Django 6.0.5 on 2026-08-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_respartner_check_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="respartner",
            options={
                "ordering": ["name", "-id"],
                "verbose_name": "Partner",
                "verbose_name_plural": "Partners",
            },
        ),
        migrations.AlterModelOptions(
            name="resusers",
            options={
                "ordering": ["partner__name", "login"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
