# Generated by Django 6.0.5 on 2026-08-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_accountjournal_entries_count_and_more'),
        ('base', '0027_seed_base_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='iractionsreport',
            name='is_invoice_report',
            field=models.BooleanField(default=False, help_text='Odoo is_invoice_report — marca los reportes propios de facturación.', verbose_name='Reporte de factura'),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='contract_expiration_notice_period',
            field=models.IntegerField(default=7, help_text='Odoo contract_expiration_notice_period ("Contract Expiry Notice Period") — días de aviso antes del fin de contrato.'),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='employee_properties_definition',
            field=models.JSONField(blank=True, help_text='Odoo employee_properties_definition ("Employee Properties") — esquema de propiedades dinámicas de los empleados de la empresa.', null=True),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='hr_presence_control_attendance',
            field=models.BooleanField(default=False, help_text='Odoo hr_presence_control_attendance ("Based on attendances").'),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='hr_presence_control_email',
            field=models.BooleanField(default=False, help_text='Odoo hr_presence_control_email ("Based on number of emails sent").'),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='hr_presence_control_email_amount',
            field=models.IntegerField(default=0, help_text='Odoo hr_presence_control_email_amount ("# emails to send") — umbral de correos enviados para considerar presente al empleado.'),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='hr_presence_control_ip',
            field=models.BooleanField(default=False, help_text='Odoo hr_presence_control_ip ("Based on IP Address").'),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='hr_presence_control_ip_list',
            field=models.CharField(blank=True, default='', help_text='Odoo hr_presence_control_ip_list ("Valid IP addresses") — lista de IPs válidas para el control de presencia.', max_length=255),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='hr_presence_control_login',
            field=models.BooleanField(default=True, help_text='Odoo hr_presence_control_login ("Based on user status in system").'),
        ),
        migrations.AddField(
            model_name='rescompany',
            name='work_permit_expiration_notice_period',
            field=models.IntegerField(default=60, help_text='Odoo work_permit_expiration_notice_period ("Work Permit Expiry Notice Period") — días de aviso antes del vencimiento del permiso de trabajo.'),
        ),
        migrations.AddField(
            model_name='rescountrygroup',
            name='exclude_state_ids',
            field=models.ManyToManyField(blank=True, db_table='res_country_group_exclude_state_rel', help_text='Estados/provincias excluidos de este grupo a efectos fiscales, aunque su país sí pertenezca (Odoo exclude_state_ids).', related_name='excluded_from_groups', to='base.rescountrystate'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='autopost_bills',
            field=models.CharField(blank=True, choices=[('always', 'siempre'), ('ask', 'preguntar'), ('never', 'nunca')], default='', help_text='Auto-publicación de facturas de proveedor recurrentes (Odoo autopost_bills).', max_length=16),
        ),
        migrations.AddField(
            model_name='respartner',
            name='credit_limit',
            field=models.FloatField(default=0.0, help_text='Límite de crédito (Odoo credit_limit; sin variación por empresa, ver docstring del módulo).'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='customer_rank',
            field=models.IntegerField(default=0, help_text='Odoo customer_rank.'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='ignore_abnormal_invoice_amount',
            field=models.BooleanField(default=False, help_text='Odoo ignore_abnormal_invoice_amount.'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='ignore_abnormal_invoice_date',
            field=models.BooleanField(default=False, help_text='Odoo ignore_abnormal_invoice_date.'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='invoice_edi_format_store',
            field=models.CharField(blank=True, default='', help_text='Formato EDI de factura preferido (Odoo invoice_edi_format_store).', max_length=64),
        ),
        migrations.AddField(
            model_name='respartner',
            name='invoice_sending_method',
            field=models.CharField(blank=True, choices=[('email', 'por correo'), ('manual', 'manual')], default='', help_text='Método de envío de factura preferido (Odoo invoice_sending_method).', max_length=16),
        ),
        migrations.AddField(
            model_name='respartner',
            name='invoice_template_pdf_report_id',
            field=models.ForeignKey(blank=True, help_text='Plantilla PDF de factura preferida de este socio (Odoo invoice_template_pdf_report_id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.iractionsreport'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='property_account_payable_id',
            field=models.ForeignKey(blank=True, help_text='Cuenta por pagar de este socio (Odoo property_account_payable_id).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_partners', to='account.accountaccount'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='property_account_position_id',
            field=models.ForeignKey(blank=True, help_text='Posición fiscal por defecto de este socio (Odoo property_account_position_id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners', to='account.accountfiscalposition'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='property_account_receivable_id',
            field=models.ForeignKey(blank=True, help_text='Cuenta por cobrar de este socio (Odoo property_account_receivable_id).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_partners', to='account.accountaccount'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='property_inbound_payment_method_line_id',
            field=models.ForeignKey(blank=True, help_text='Método de pago entrante preferido (Odoo property_inbound_payment_method_line_id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_partners', to='account.accountpaymentmethodline'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='property_outbound_payment_method_line_id',
            field=models.ForeignKey(blank=True, help_text='Método de pago saliente preferido (Odoo property_outbound_payment_method_line_id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_partners', to='account.accountpaymentmethodline'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='property_payment_term_id',
            field=models.ForeignKey(blank=True, help_text='Plazo de pago de venta de este socio (Odoo property_payment_term_id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_partners', to='account.accountpaymentterm'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='property_supplier_payment_term_id',
            field=models.ForeignKey(blank=True, help_text='Plazo de pago de compra de este socio (Odoo property_supplier_payment_term_id).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_partners', to='account.accountpaymentterm'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='show_credit_limit',
            field=models.BooleanField(default=False, help_text='Odoo show_credit_limit.'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='supplier_rank',
            field=models.IntegerField(default=0, help_text='Odoo supplier_rank.'),
        ),
        migrations.AddField(
            model_name='respartner',
            name='trust',
            field=models.CharField(blank=True, choices=[('good', 'buen pagador'), ('normal', 'normal'), ('bad', 'mal pagador')], default='', help_text='Grado de confianza en este deudor (Odoo trust).', max_length=16),
        ),
        migrations.AddField(
            model_name='respartner',
            name='use_partner_credit_limit',
            field=models.BooleanField(default=False, help_text='Odoo use_partner_credit_limit.'),
        ),
    ]
