# Generated by Django 6.0.5 on 2026-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0033_retire_observability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irmodule",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Nombre técnico = carpeta del addon (Odoo ir.module.module.name).",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="irmodule",
            name="shortdesc",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre legible del manifest (Odoo shortdesc ← manifest name).",
            ),
        ),
        migrations.AlterField(
            model_name="irmodule",
            name="summary",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="irmodule",
            name="version",
            field=models.CharField(blank=True, default="1.0"),
        ),
        migrations.AlterField(
            model_name="irmodulecategory",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="irmoduledependency",
            name="name",
            field=models.CharField(
                db_index=True, help_text="Nombre técnico del addon del que depende."
            ),
        ),
    ]
