# Generated by Django 6.0.5 on 2026-08-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0034_widen_ir_module_char_columns"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="irmodule",
            options={
                "ordering": ["-application", "sequence", "name"],
                "verbose_name": "Módulo técnico",
            },
        ),
        migrations.AddField(
            model_name="irmodule",
            name="sequence",
            field=models.IntegerField(default=100),
        ),
    ]
