# Generated by Django 6.0.5 on 2026-08-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0035_alter_irmodule_options_irmodule_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rescompany",
            name="hr_presence_control_ip_list",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo hr_presence_control_ip_list ("Valid IP addresses") — lista de IPs válidas para el control de presencia.',
            ),
        ),
    ]
