# Generated by Django 6.0.5 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0036_alter_rescompany_hr_presence_control_ip_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="restrictive_audit_trail",
            field=models.BooleanField(
                default=False,
                help_text="Impide borrar o mutar los mensajes del chatter que documentan asientos ya publicados de esta empresa (Odoo restrictive_audit_trail).",
                verbose_name="Rastro de auditoría restrictivo",
            ),
        ),
    ]
