# Generated by Django 6.0.5 on 2026-08-21 18:24

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0038_resgroups_lock_timeout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResUsersApikeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Odoo name ("Description") — para qué es esta clave.',
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text='Odoo scope. NULL da acceso a cualquier RPC; con valor, sólo a ese ámbito ("rpc", "browser").',
                        null=True,
                        verbose_name="Ámbito",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Odoo expiration_date. NULL es una clave permanente, que sólo un usuario de sistema puede crear.",
                        null=True,
                        verbose_name="Fecha de caducidad",
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        db_index=True,
                        help_text="Odoo index — los primeros 8 hexadecimales de la clave, en claro. Es por lo que se busca la fila; NO es la clave.",
                        max_length=8,
                        verbose_name="Prefijo",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Odoo key — el hash de la clave completa. SECRETO: ningún serializer lo expone, igual que el secreto TOTP.",
                        verbose_name="Clave (hash)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Odoo user_id — el dueño de la clave.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clave de API",
                "verbose_name_plural": "Claves de API",
                "db_table": "res_users_apikeys",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "index"],
                        name="res_users_apikeys_idx_24148d42",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.Exact(
                            django.db.models.functions.text.Length(models.F("index")), 8
                        ),
                        name="res_users_apikeys_index_size",
                        violation_error_code="API_KEY_INDEX_SIZE",
                    )
                ],
            },
        ),
    ]
