# Generated by Django 6.0.5 on 2026-08-26 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0039_resusersapikeys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irsequence",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo code ("Sequence Code").',
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo company_id.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sequences",
                to="base.rescompany",
            ),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="implementation",
            field=models.CharField(
                choices=[("standard", "Standard"), ("no_gap", "No gap")],
                default="standard",
                help_text='Odoo implementation. "no_gap" garantiza que no falte ningún número; es más lento que "standard".',
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="name",
            field=models.CharField(help_text="Odoo name.", max_length=128),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="number_increment",
            field=models.IntegerField(
                default=1, help_text='Odoo number_increment ("Step").'
            ),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="number_next",
            field=models.IntegerField(
                default=1, help_text='Odoo number_next ("Next Number").'
            ),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="padding",
            field=models.IntegerField(
                default=0,
                help_text='Odoo padding ("Sequence Size") — ceros a la izquierda.',
            ),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo prefix — interpolable por fecha.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="suffix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo suffix — interpolable por fecha.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="irsequence",
            name="use_date_range",
            field=models.BooleanField(
                default=False,
                help_text="Odoo use_date_range — subsecuencias por rango de fecha.",
            ),
        ),
        migrations.CreateModel(
            name="IrSequenceDateRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(help_text='Odoo date_from ("From").')),
                ("date_to", models.DateField(help_text='Odoo date_to ("To").')),
                (
                    "number_next",
                    models.IntegerField(
                        default=1, help_text='Odoo number_next ("Next Number").'
                    ),
                ),
                (
                    "sequence",
                    models.ForeignKey(
                        help_text='Odoo sequence_id ("Main Sequence").',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_range_ids",
                        to="base.irsequence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rango de secuencia",
                "verbose_name_plural": "Rangos de secuencia",
                "db_table": "ir_sequence_date_range",
                "ordering": ["date_from", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sequence", "date_from", "date_to"),
                        name="unique_range_per_sequence",
                        violation_error_message="No se pueden crear dos rangos de fecha iguales para la misma secuencia.",
                    )
                ],
            },
        ),
    ]
