# Generated by Django 6.0.5 on 2026-08-26 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0040_alter_irsequence_code_alter_irsequence_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iractionsserver",
            name="usage",
            field=models.CharField(
                choices=[
                    ("ir_actions_server", "Acción de servidor"),
                    ("ir_cron", "Acción programada"),
                ],
                default="ir_actions_server",
                help_text="Odoo usage. ir_cron cuando la accion respalda a una tarea programada.",
                max_length=20,
                verbose_name="Uso",
            ),
        ),
        migrations.AddField(
            model_name="ircron",
            name="failure_count",
            field=models.IntegerField(
                default=0,
                help_text="Fallos consecutivos de este job. Se reinicia al tener exito (Odoo failure_count).",
            ),
        ),
        migrations.AddField(
            model_name="ircron",
            name="first_failure_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Primera vez que el cron fallo. Se reinicia al tener exito (Odoo first_failure_date).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="IrCronProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "remaining",
                    models.IntegerField(default=0, help_text="Odoo remaining."),
                ),
                ("done", models.IntegerField(default=0, help_text="Odoo done.")),
                (
                    "deactivate",
                    models.BooleanField(
                        default=False,
                        help_text="Desactivar el cron al terminar (Odoo deactivate).",
                    ),
                ),
                (
                    "timed_out_counter",
                    models.IntegerField(
                        default=0,
                        help_text="Veces consecutivas que la corrida se quedo sin tiempo (Odoo timed_out_counter).",
                    ),
                ),
                (
                    "cron",
                    models.ForeignKey(
                        help_text="Cron cuyo avance se registra (Odoo cron_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_ids",
                        to="base.ircron",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avance de tarea programada",
                "verbose_name_plural": "Avances de tareas programadas",
                "db_table": "ir_cron_progress",
            },
        ),
        migrations.CreateModel(
            name="IrCronTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Momento en que el cron debe correr (Odoo call_at).",
                    ),
                ),
                (
                    "cron",
                    models.ForeignKey(
                        help_text="Cron a disparar (Odoo cron_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trigger_ids",
                        to="base.ircron",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disparo de tarea programada",
                "verbose_name_plural": "Disparos de tareas programadas",
                "db_table": "ir_cron_trigger",
            },
        ),
    ]
