# Generated by Django 6.0.5 on 2026-08-26 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0041_cron_trigger_progress_and_action_usage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResPartnerCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, verbose_name="Nombre")),
                (
                    "color",
                    models.IntegerField(
                        default=0,
                        help_text="Odoo color. Un entero de 1 a 11 repartido al azar al crear.",
                        verbose_name="Color",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Permite ocultar la categoría sin borrarla (Odoo active).",
                    ),
                ),
                (
                    "parent_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Ruta materializada '1/4/9/' — sostiene _parent_store.",
                        max_length=255,
                        verbose_name="Ruta de ancestros",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo parent_id, con ondelete cascade.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_ids",
                        to="base.respartnercategory",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "partners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Odoo partner_ids, con column1=category_id.",
                        related_name="category_ids",
                        to="base.respartner",
                        verbose_name="Contactos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta de contacto",
                "verbose_name_plural": "Etiquetas de contacto",
                "db_table": "res_partner_category",
                "ordering": ["name", "id"],
            },
        ),
    ]
