# Generated by Django 6.0.5 on 2026-08-27 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0042_res_partner_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="iractionsserver",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo parent_id. Acción compuesta que encadena a ésta.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_ids",
                to="base.iractionsserver",
                verbose_name="Acción padre",
            ),
        ),
    ]
