# Generated by Django 6.0.5 on 2026-08-27 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0046_res_partner_label_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="respartner",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Vendedor: el usuario interno a cargo de este contacto (Odoo user_id). store=True con compute y readonly=False: se hereda del padre al crear y se reescribe a mano.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
