# Generated by Django 6.0.5 on 2026-08-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0047_res_partner_salesperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="irmodule",
            name="author",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo author. NO cae a "Unknown": modules.module ya rellena el autor del proyecto cuando el manifest calla, así que ese literal guardaría un dato falso para un addon propio.',
            ),
        ),
        migrations.AddField(
            model_name="irmodule",
            name="contributors",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Odoo contributors. La fuente la declara Text porque la lista se aplana a una cadena separada por comas.",
            ),
        ),
        migrations.AddField(
            model_name="irmodule",
            name="demo",
            field=models.BooleanField(
                default=False,
                help_text="Odoo demo: el addon tiene datos de demostración cargados.",
            ),
        ),
        migrations.AddField(
            model_name="irmodule",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Descripción larga del manifest (Odoo description).",
            ),
        ),
        migrations.AddField(
            model_name="irmodule",
            name="icon",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo icon: la RUTA del icono, no el binario. El binario es icon_image, computado, y ése no se porta (ver el docstring).",
            ),
        ),
        migrations.AddField(
            model_name="irmodule",
            name="maintainer",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="irmodule",
            name="to_buy",
            field=models.BooleanField(
                default=False,
                help_text="Odoo to_buy. Siempre False aquí: marca un módulo del catálogo comercial de la fuente, que este árbol no consulta.",
            ),
        ),
        migrations.AddField(
            model_name="irmodule",
            name="url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo url, con respaldo a live_test_url del manifest.",
            ),
        ),
        migrations.AddField(
            model_name="irmodule",
            name="website",
            field=models.CharField(blank=True, default=""),
        ),
    ]
