# Generated by Django 6.0.5 on 2026-08-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0049_ir_module_exclusion_and_dependency_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resbank",
            name="bic",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Bank Identifier Code / SWIFT (Odoo bic). A veces se le llama BIC o Swift.",
            ),
        ),
        migrations.AlterField(
            model_name="resbank",
            name="city",
            field=models.CharField(blank=True, default="", help_text="Odoo city."),
        ),
        migrations.AlterField(
            model_name="resbank",
            name="email",
            field=models.CharField(blank=True, default="", help_text="Odoo email."),
        ),
        migrations.AlterField(
            model_name="resbank",
            name="name",
            field=models.CharField(help_text="Nombre del banco (Odoo name)."),
        ),
        migrations.AlterField(
            model_name="resbank",
            name="phone",
            field=models.CharField(blank=True, default="", help_text="Odoo phone."),
        ),
        migrations.AlterField(
            model_name="resbank",
            name="street",
            field=models.CharField(blank=True, default="", help_text="Odoo street."),
        ),
        migrations.AlterField(
            model_name="resbank",
            name="street2",
            field=models.CharField(blank=True, default="", help_text="Odoo street2."),
        ),
        migrations.AlterField(
            model_name="resbank",
            name="zip",
            field=models.CharField(blank=True, default="", help_text="Odoo zip."),
        ),
    
        migrations.AlterField(
            model_name="resbank",
            name="l10n_mx_edi_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Número de tres dígitos que la ABM asigna a las instituciones bancarias (Odoo l10n_mx_edi_code; ABM = Asociación de Bancos de México).",
            ),
        ),
        migrations.AlterField(
            model_name="respartnerbank",
            name="l10n_mx_edi_clabe",
            field=models.CharField(
                blank=True,
                default="",
                help_text="CLABE — cifra bancaria estandarizada de México (Odoo l10n_mx_edi_clabe).",
            ),
        ),
    ]
