# Generated by Django 6.0.5 on 2026-08-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0050_res_bank_unlimited_char"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rescurrency",
            options={
                "ordering": ["-active", "name"],
                "verbose_name": "Moneda",
                "verbose_name_plural": "Monedas",
            },
        ),
        migrations.AddConstraint(
            model_name="rescurrency",
            constraint=models.CheckConstraint(
                condition=models.Q(("rounding__gt", 0)),
                name="res_currency_rounding_gt_zero",
                violation_error_message="El factor de redondeo debe ser mayor que 0.",
            ),
        ),
    ]
