# Generated by Django 6.0.5 on 2026-08-28 02:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0051_res_currency_rounding_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rescurrencyrate",
            options={
                "ordering": ["-name", "id"],
                "verbose_name": "Tipo de cambio",
                "verbose_name_plural": "Tipos de cambio",
            },
        ),
        migrations.RemoveField(
            model_name="rescurrencyrate",
            name="company_rate",
        ),
        migrations.AlterField(
            model_name="rescurrencyrate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa (Odoo company_id). Null = la tasa aplica a todas.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="currency_rates",
                to="base.rescompany",
            ),
        ),
        migrations.AlterField(
            model_name="rescurrencyrate",
            name="name",
            field=models.DateField(
                db_index=True,
                help_text="Fecha del tipo de cambio (Odoo name, requerido).",
            ),
        ),
        migrations.AlterField(
            model_name="rescurrencyrate",
            name="rate",
            field=models.DecimalField(
                decimal_places=12,
                default=Decimal("1.0"),
                help_text="Tasa por unidad de la moneda de tasa 1 (Odoo rate). Es la ÚNICA de las tres que se almacena.",
                max_digits=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="rescurrencyrate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gt", 0)),
                name="res_currency_rate_currency_rate_check",
                violation_error_message="El tipo de cambio debe ser estrictamente positivo.",
            ),
        ),
    ]
