# Generated by Django 6.0.5 on 2026-08-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0052_res_currency_rate_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescurrency",
            name="currency_subunit_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Etiqueta de la subunidad (Odoo currency_subunit_label). La consume amount_to_text para la parte fraccionaria.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="rescurrency",
            name="iso_numeric",
            field=models.IntegerField(
                blank=True,
                help_text="Código numérico ISO 4217 (Odoo iso_numeric).",
                null=True,
            ),
        ),
    ]
