# Generated by Django 6.0.5 on 2026-08-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0054_alter_respartner_tz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resusers",
            name="password",
            field=models.CharField(verbose_name="Contraseña"),
        ),
    ]
