# Generated by Django 6.0.5 on 2026-08-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0055_alter_resusers_password"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="decimalprecision",
            constraint=models.UniqueConstraint(
                fields=("name",),
                name="decimal_precision_name_uniq",
                violation_error_message="Only one value can be defined for each given usage!",
            ),
        ),
    ]
