# Generated by Django 6.0.5 on 2026-08-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0057_respartner_barcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="irrule",
            options={
                "ordering": ["-model_name", "id"],
                "verbose_name": "Regla de registro",
                "verbose_name_plural": "Reglas de registro",
            },
        ),
        migrations.AlterField(
            model_name="irrule",
            name="domain_force",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Expresión del dominio. Vacío equivale a verdadero: no restringe.",
                verbose_name="Dominio",
            ),
        ),
        migrations.AddConstraint(
            model_name="irrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("perm_read", True),
                    ("perm_write", True),
                    ("perm_create", True),
                    ("perm_unlink", True),
                    _connector="OR",
                ),
                name="ir_rule_no_access_rights",
                violation_error_message="La regla debe conceder al menos un permiso.",
            ),
        ),
    ]
