# Generated by Django 6.0.5 on 2026-08-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0059_seed_base_security"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="iractionsserver",
            name="crud_model_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo crud_model_id. Modelo destino del CRUD.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crud_server_actions",
                to="base.irmodel",
                verbose_name="Registro a crear",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="evaluation_type",
            field=models.CharField(
                choices=[
                    ("value", "Actualizar"),
                    ("sequence", "Secuencia"),
                    ("equation", "Calcular"),
                ],
                default="value",
                max_length=16,
                verbose_name="Tipo de valor",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="html_value",
            field=models.TextField(blank=True, default="", verbose_name="Valor HTML"),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="link_field_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo link_field_id. Campo que ata el registro nuevo al registro sobre el que corre la acción.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_server_actions",
                to="base.irmodelfields",
                verbose_name="Campo de enlace",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="resource_ref_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_actions",
                to="contenttypes.contenttype",
                verbose_name="Tipo del registro",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="resource_ref_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Id del registro"
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="selection_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_actions",
                to="base.irmodelfieldsselection",
                verbose_name="Valor de selección",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="sequence_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="server_actions",
                to="base.irsequence",
                verbose_name="Secuencia a usar",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="update_boolean_value",
            field=models.CharField(
                choices=[("true", "Sí (verdadero)"), ("false", "No (falso)")],
                default="true",
                max_length=8,
                verbose_name="Valor booleano",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="update_field_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo update_field_id. Último campo de update_path.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_server_actions",
                to="base.irmodelfields",
                verbose_name="Campo a actualizar",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="update_m2m_operation",
            field=models.CharField(
                choices=[
                    ("add", "Añadiendo"),
                    ("remove", "Quitando"),
                    ("set", "Fijándolo a"),
                    ("clear", "Vaciándolo"),
                ],
                default="add",
                max_length=8,
                verbose_name="Operación Many2many",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="update_path",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo update_path. Ruta punteada, p. ej. 'partner_id.name'.",
                max_length=255,
                verbose_name="Ruta del campo a actualizar",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="update_related_model_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_related_server_actions",
                to="base.irmodel",
                verbose_name="Modelo relacionado del campo",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="value",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Odoo value. En modo "equation" es una expresión Python; este archivo NO la evalúa (ver el docstring del módulo).',
                verbose_name="Valor",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="webhook_field_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="ir_act_server_webhook_field_rel",
                related_name="webhook_server_actions",
                to="base.irmodelfields",
                verbose_name="Campos del webhook",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="webhook_url",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="URL del webhook"
            ),
        ),
    ]
