# Generated by Django 6.0.5 on 2026-08-28 17:36

import django.db.models.deletion
import orm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0060_iractionsserver_crud_model_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerActionHistoryWizard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistente de historial de acción de servidor",
                "verbose_name_plural": "Asistentes de historial de acción de servidor",
                "db_table": "server_action_history_wizard",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="automated_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo automated_name. El nombre que la acción se pondría sola; si coincide con name, name se regenera al cambiar de tipo.",
                max_length=255,
                verbose_name="Nombre automático",
            ),
        ),
        migrations.AddField(
            model_name="iractionsserver",
            name="group_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="ir_act_server_group_rel",
                help_text="Odoo group_ids. Grupos que pueden ejecutar la acción. Vacío = cualquiera con permiso de escritura en el modelo.",
                related_name="server_actions",
                to="base.resgroups",
                verbose_name="Grupos permitidos",
            ),
        ),
        migrations.CreateModel(
            name="IrActionsServerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.TextField(blank=True, default="", verbose_name="Código"),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_history",
                        to="base.iractionsserver",
                        verbose_name="Acción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de acción de servidor",
                "verbose_name_plural": "Historiales de acción de servidor",
                "db_table": "ir_actions_server_history",
                "ordering": ["-created_at", "-id"],
            },
            bases=(
                orm.models.RecordLoaderMixin,
                orm.models.DisplayNameMixin,
                models.Model,
            ),
        ),
    ]
