# Generated by Django 6.0.5 on 2026-08-29 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_accountmove_posted_before"),
        ("base", "0063_alter_iractionsserver_sequence_id"),
        ("product", "0012_port_sale_extension_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="downpayment_account",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo downpayment_account_id ("Downpayment Account"). Cuenta usada en las facturas de anticipo. Acotada por DOWNPAYMENT_ACCOUNT_DOMAIN.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.accountaccount",
                verbose_name="Cuenta de anticipo",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="portal_confirmation_pay",
            field=models.BooleanField(
                default=False,
                help_text='Odoo portal_confirmation_pay ("Online Payment"). Pide pago del cliente para confirmar la cotización.',
                verbose_name="Pago en línea",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="portal_confirmation_sign",
            field=models.BooleanField(
                default=True,
                help_text='Odoo portal_confirmation_sign ("Online Signature"). Pide firma del cliente para confirmar la cotización.',
                verbose_name="Firma en línea",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="prepayment_percent",
            field=models.FloatField(
                default=1.0,
                help_text="Odoo prepayment_percent. Porcentaje del importe que el cliente debe pagar para confirmar la cotización.",
                verbose_name="Porcentaje de anticipo",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="sale_discount_product",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo sale_discount_product_id ("Discount Product"). Producto usado por omisión para materializar un descuento como línea. Acotado por SALE_DISCOUNT_PRODUCT_DOMAIN.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="product.productproduct",
                verbose_name="Producto de descuento",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="sale_onboarding_payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("digital_signature", "Firmar en línea"),
                    ("paypal", "PayPal"),
                    ("stripe", "Stripe"),
                    ("other", "Pagar con otra pasarela"),
                    ("manual", "Pago manual"),
                ],
                help_text="Odoo sale_onboarding_payment_method. Guarda qué método eligió la empresa la primera vez que usó Ventas.",
                max_length=20,
                null=True,
                verbose_name="Método de pago elegido en el arranque de Ventas",
            ),
        ),
        migrations.AlterField(
            model_name="rescompany",
            name="quotation_validity_days",
            field=models.IntegerField(
                default=30,
                help_text='Odoo quotation_validity_days ("Default Quotation Validity"). Días entre la cotización y su vencimiento; 0 desactiva el vencimiento automático.',
                verbose_name="Validez de la cotización",
            ),
        ),
    ]
