# Generated by Django 6.0.5 on 2026-08-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0064_rescompany_downpayment_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="account_price_include",
            field=models.CharField(
                choices=[
                    ("tax_included", "Impuesto incluido"),
                    ("tax_excluded", "Impuesto excluido"),
                ],
                default="tax_excluded",
                help_text="Si el precio de venta que se captura en el producto y en las facturas de esta empresa incluye sus impuestos (Odoo account_price_include).",
                max_length=20,
                verbose_name="Precio de venta con impuesto incluido por omisión",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="account_use_credit_limit",
            field=models.BooleanField(
                default=False,
                help_text="Habilita el uso del límite de crédito en los contactos (Odoo account_use_credit_limit). Es el interruptor que gobierna el aviso de crédito de la orden de venta.",
                verbose_name="Límite de crédito en ventas",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="tax_calculation_rounding_method",
            field=models.CharField(
                choices=[
                    ("round_globally", "Redondear por impuesto"),
                    ("round_per_line", "Redondear por línea"),
                ],
                default="round_globally",
                help_text="Si el impuesto se redondea una vez por impuesto sobre la base agregada, o línea por línea (Odoo tax_calculation_rounding_method).",
                max_length=20,
                verbose_name="Método de redondeo del cálculo de impuestos",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="terms_type",
            field=models.CharField(
                choices=[
                    ("plain", "Añadir una nota"),
                    ("html", "Añadir un enlace a una página web"),
                ],
                default="plain",
                help_text="Si los términos y condiciones se añaden como nota al pie del documento o como enlace a una página web (Odoo terms_type).",
                max_length=10,
                verbose_name="Formato de los términos y condiciones",
            ),
        ),
    ]
