# Generated by Django 6.0.5 on 2026-08-30 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0073_obj_name_uniq_conserva_el_nombre_de_la_fuente"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="irmodelfieldsselection",
            name="ir_model_fields_selection_field_uniq",
        ),
        migrations.AlterField(
            model_name="irmodelfieldsselection",
            name="field",
            field=models.ForeignKey(
                db_column="field_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selection_ids",
                to="base.irmodelfields",
                verbose_name="Campo",
            ),
        ),
        migrations.RenameField(
            model_name="irmodelfieldsselection",
            old_name="field",
            new_name="field_id",
        ),
        migrations.AddConstraint(
            model_name="irmodelfieldsselection",
            constraint=models.UniqueConstraint(
                fields=("field_id", "value"),
                name="ir_model_fields_selection_field_uniq",
            ),
        ),
    ]
