# Generated by Django 6.0.5 on 2026-08-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0074_selection_field_id_conserva_el_nombre_de_la_fuente"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resgroups",
            options={
                "ordering": ["privilege_id", "sequence", "name", "id"],
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
            },
        ),
        migrations.AddConstraint(
            model_name="resgroups",
            constraint=models.UniqueConstraint(
                fields=("privilege", "name"),
                name="res_groups_name_uniq",
                violation_error_message="El nombre del grupo tiene que ser único dentro de su privilegio.",
            ),
        ),
        migrations.AddConstraint(
            model_name="resgroups",
            constraint=models.CheckConstraint(
                condition=models.Q(("api_key_duration__gte", 0)),
                name="res_groups_check_api_key_duration",
                violation_error_message="La duración de la API key no puede ser negativa.",
            ),
        ),
    ]
