# Generated by Django 6.0.5 on 2026-08-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0075_res_groups_conserva_los_dos_objetos_de_tabla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iractionsactwindow",
            name="target",
            field=models.CharField(
                blank=True,
                choices=[
                    ("current", "Ventana actual"),
                    ("new", "Ventana nueva"),
                    ("fullscreen", "Pantalla completa"),
                    ("main", "Acción principal de la ventana actual"),
                ],
                default="current",
                max_length=16,
                null=True,
                verbose_name="Ventana destino",
            ),
        ),
    ]
