"""``ir.filters`` recupera la FK real y los tres objetos de tabla de la fuente.

``action_id`` era un ``Integer`` plano por una razón que su propio bloque ya
reconocía caduca: ``ir.actions.actions`` está portado. Con la FK entran los
tres objetos de tabla que la referencia declara y este porte no traía
(``odoo19c: odoo/addons/base/models/ir_filters.py:26-40``): el índice de
búsqueda de ``get_filters`` y los dos CHECK.

Por qué la conversión no pierde un solo id
==========================================

Porque la FK se declara en la **forma C** de ADR-029 (#141): el símbolo
conserva el nombre de la referencia (``action_id``) y ``db_column`` mantiene la
columna donde ya estaba. Django lo ve como un ``AlterField`` sobre la misma
columna y emite ``ALTER COLUMN "action_id" TYPE bigint USING
"action_id"::bigint`` más la restricción de clave foránea.

Vale la pena registrar el contraste, porque es un argumento a favor de la forma
que ADR-029 fija y no estaba escrito en ninguna parte: declarada como
``action = Many2one(...)`` —forma A, símbolo divergente— Django la trata como
un campo **nuevo** que casualmente comparte la columna con el que se va, y
propone ``ADD COLUMN "action_id"`` seguido de ``DROP COLUMN "action_id"``. Sobre
una tabla con filas eso falla, y si no fallara borraría los ids guardados.
"""
# Generated by Django 6.0.5 on 2026-08-31 08:13

import addons.base.models.ir_filters
import django.db.models.deletion
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0076_target_no_requerido_como_la_fuente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irfilters",
            name="action_id",
            field=models.ForeignKey(
                blank=True,
                db_column="action_id",
                help_text='Acción/menú al que aplica el filtro (Odoo action_id). NULL = aplica a todos los menús del modelo. Docstring de la fuente, verbatim: "The menu action this filter applies to. When left empty the filter applies to all menus for this model."',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filter_ids",
                to="base.iractionsactions",
                verbose_name="Acción",
            ),
        ),
        migrations.AddIndex(
            model_name="irfilters",
            index=models.Index(
                fields=[
                    "model_id",
                    "action_id",
                    "embedded_action",
                    "embedded_parent_res_id",
                ],
                name="ir_filters_get_filters_index",
            ),
        ),
        migrations.AddConstraint(
            model_name="irfilters",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("embedded_action__isnull", True),
                    ("embedded_parent_res_id__isnull", False),
                    _negated=True,
                ),
                name="ir_filters_check_res_id_only_when_embedded_action",
            ),
        ),
        migrations.AddConstraint(
            model_name="irfilters",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sort__isnull", True),
                    django.db.models.lookups.Exact(
                        addons.base.models.ir_filters.JsonbTypeOf("sort"),
                        models.Value("array"),
                    ),
                    _connector="OR",
                ),
                name="ir_filters_check_sort_json",
            ),
        ),
    ]
