# Generated by Django 6.0.5 on 2026-09-02 03:48
"""``report_type`` recupera los tres formatos de la fuente.

La 0006 lo redujo a ``pdf`` con dos motivos, y los dos dejaron de ser ciertos:

- *«su renderizador exigía del builder un contrato distinto (str en vez del
  descriptor) que nada hacía cumplir»* — la tarea #196 construyó
  ``report_template.descriptor_to_html`` y ``descriptor_to_text``, así que los
  dos renderizadores serializan el descriptor y devuelven los ``bytes`` que la
  firma de la fuente promete;
- *«0 addons lo declaraban»* — era **circular**: ``Selection`` es
  ``CharField(choices=…)`` y Django valida ``choices`` en ``full_clean``, así
  que ningún addon podía declarar un valor que el enum no ofrecía.

Ver ``REPORT_TYPE_CHOICES`` en ``ir_actions_report.py`` para las cuatro
exigencias de la condición de reingreso (:ref:`h-api-291`, :ref:`h-api-935`),
medidas una por una.

**Sin conversión de filas, y aquí tampoco hace falta.** El cambio sólo amplía
el conjunto aceptado: ninguna fila existente deja de ser válida. ``pdf`` sigue
siendo el ``default``.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0077_ir_filters_recupera_la_fk_y_sus_tres_objetos_de_tabla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iractionsreport",
            name="report_type",
            field=models.CharField(
                choices=[("html", "HTML"), ("pdf", "PDF"), ("text", "Text")],
                default="pdf",
                help_text="Formato de salida: html, pdf o text. El valor gobierna el despacho de _render. Son los tres de la fuente, sin su prefijo qweb-: aquí el intérprete no es QWeb. El intermedio de la composición es el descriptor, y cada formato tiene su serializador (pdf lo dibuja el helper de libharu, ADR-017; html y text los serializa report_template).",
                max_length=16,
                verbose_name="Tipo de reporte",
            ),
        ),
    ]
