# Generated by Django 6.0.5 on 2026-09-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0078_report_type_recupera_los_tres_de_la_fuente"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="fiscalyear_last_day",
            field=models.IntegerField(
                default=31,
                help_text="Día del mes en que cierra el ejercicio fiscal de esta compañía (Odoo fiscalyear_last_day).",
                verbose_name="Último día del ejercicio fiscal",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="fiscalyear_last_month",
            field=models.CharField(
                choices=[
                    ("1", "January"),
                    ("2", "February"),
                    ("3", "March"),
                    ("4", "April"),
                    ("5", "May"),
                    ("6", "June"),
                    ("7", "July"),
                    ("8", "August"),
                    ("9", "September"),
                    ("10", "October"),
                    ("11", "November"),
                    ("12", "December"),
                ],
                default="12",
                help_text="Mes en que cierra el ejercicio fiscal de esta compañía (Odoo fiscalyear_last_month).",
                max_length=2,
                verbose_name="Último mes del ejercicio fiscal",
            ),
        ),
    ]
