"""``ir.actions.server.usage`` gana el valor que ``base_automation`` añade.

No es un cambio de ``base``: es la consecuencia en el esquema de
``extend_selection_choices(IrActionsServer, 'usage', [('base_automation', …)])``
en ``addons/base_automation/models/ir_actions_server.py`` — el
``selection_add`` que la fuente declara en
``odoo19c: base_automation/models/ir_actions_server.py:14-16``.

Vive en ``base`` porque ahí vive el campo, igual que
``0022_irmodelfields_serialization_field_id_and_more`` lleva el ``AlterField``
de ``ttype`` que produce el ``selection_add`` de ``base_sparse_field``. En
PostgreSQL un ``Char`` con ``choices`` no lleva restricción de base, así que el
DDL es no-destructivo y ninguna fila existente queda inválida.
"""
# Generated by Django 6.0.5 on 2026-09-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0079_add_rescompany_fiscalyear_last_day_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iractionsserver",
            name="usage",
            field=models.CharField(
                choices=[
                    ("ir_actions_server", "Acción de servidor"),
                    ("ir_cron", "Acción programada"),
                    ("base_automation", "Automation Rule"),
                ],
                default="ir_actions_server",
                help_text="Odoo usage. ir_cron cuando la accion respalda a una tarea programada.",
                max_length=20,
                verbose_name="Uso",
            ),
        ),
    ]
