# Generated by Django 6.0.5 on 2026-09-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0080_alter_iractionsserver_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="vat_check_vies",
            field=models.BooleanField(
                default=False,
                help_text="Odoo vat_check_vies — comprobar los identificadores fiscales intracomunitarios contra la base VIES.",
                verbose_name="Verify VAT Numbers",
            ),
        ),
        migrations.AddField(
            model_name="respartner",
            name="vies_valid",
            field=models.BooleanField(
                default=False,
                help_text="European VAT numbers are automatically checked on the VIES database (Odoo vies_valid).",
                verbose_name="Intra-Community Valid",
            ),
        ),
    ]
