# Generated by Django 6.0.5 on 2026-09-02 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0081_base_vat_vat_check_vies"),
    ]

    operations = [
        migrations.AddField(
            model_name="respartner",
            name="commercial_company_name",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Razón social de la entidad comercial (Odoo commercial_company_name, ``odoo19c: res_partner.py:305``).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="respartner",
            name="commercial_partner_id",
            field=models.ForeignKey(
                blank=True,
                db_column="commercial_partner_id",
                editable=False,
                help_text="Entidad comercial del contacto: la primera empresa al subir por la cadena de padres (Odoo commercial_partner_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commercial_children",
                to="base.respartner",
            ),
        ),
    ]
