# Generated by Django 6.0.5 on 2026-09-03 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0026_accountjournal_bank_account_id_and_more"),
        ("base", "0082_respartner_commercial_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rescompany",
            name="account_opening_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha del asiento de apertura; desde ella se lleva la contabilidad (Odoo account_opening_date).",
                null=True,
                verbose_name="Opening Entry",
            ),
        ),
        migrations.AddField(
            model_name="rescompany",
            name="account_opening_move",
            field=models.ForeignKey(
                blank=True,
                help_text="Asiento con el saldo inicial de todas las cuentas de esta empresa (Odoo account_opening_move_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opening_for_companies",
                to="account.accountmove",
                verbose_name="Opening Journal Entry",
            ),
        ),
    ]
