# Generated by Django 6.0.5 on 2026-09-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0085_orm_signaling_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseEnableProfilingWizard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes_5", "5 Minutes"),
                            ("hours_1", "1 Hour"),
                            ("days_1", "1 Day"),
                            ("months_1", "1 Month"),
                        ],
                        help_text="Cuanto dura el permiso de perfilado (Odoo ``duration``, ``odoo19c: ir_profile.py:234``).",
                        max_length=16,
                        null=True,
                        verbose_name="Enable profiling for",
                    ),
                ),
                (
                    "expiration",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="Instante en que caduca el permiso (Odoo ``expiration``, ``odoo19c: ir_profile.py:240``). La fuente lo declara ``readonly=False``: el computo propone y quien llena el formulario puede sobrescribir, que aqui es el ``blank=True`` del campo.",
                        null=True,
                        verbose_name="Enable profiling until",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistente de habilitacion de perfilado",
                "verbose_name_plural": "Asistentes de habilitacion de perfilado",
                "db_table": "base_enable_profiling_wizard",
            },
        ),
    ]
