# Generated by Django 6.0.5 on 2026-08-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TotpRecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 hex del código de recuperación (el plano no se guarda).",
                        max_length=64,
                        verbose_name="Hash del código",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp de uso; NULL = aún válido (un solo uso).",
                        null=True,
                        verbose_name="Consumido en",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de recuperación TOTP",
                "verbose_name_plural": "Códigos de recuperación TOTP",
                "db_table": "authz_totp_recovery_code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TotpSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "secret",
                    models.CharField(
                        help_text="Clave TOTP en base32 (RFC 4648). No se expone salvo en setup.",
                        max_length=64,
                        verbose_name="Secreto (base32)",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True cuando el usuario verificó el primer código (2FA activo).",
                        verbose_name="Confirmado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secreto TOTP",
                "verbose_name_plural": "Secretos TOTP",
                "db_table": "authz_totp_secret",
                "ordering": ["-created_at"],
            },
        ),
    ]
