# Generated by Django 6.0.5 on 2026-07-18 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Marca (issuer) mostrada en la app authenticator. NADA cableado: L2, sembrado
# aquí a 'Kaupamex' (plataforma L0), editable en caliente en SystemParameter.
_ISSUER_KEY = 'authz.totp_issuer'
_ISSUER_DEFAULT = 'Kaupamex'


def seed_issuer(apps, schema_editor):
    SystemParameter = apps.get_model('base', 'SystemParameter')
    db = schema_editor.connection.alias
    if not SystemParameter.objects.using(db).filter(key=_ISSUER_KEY).exists():
        SystemParameter.objects.using(db).create(key=_ISSUER_KEY, value=_ISSUER_DEFAULT)


def unseed_issuer(apps, schema_editor):
    SystemParameter = apps.get_model('base', 'SystemParameter')
    db = schema_editor.connection.alias
    SystemParameter.objects.using(db).filter(key=_ISSUER_KEY).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="TotpSecret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "secret",
                    models.CharField(
                        help_text="Clave TOTP en base32 (RFC 4648). No se expone salvo en setup.",
                        max_length=64,
                        verbose_name="Secreto (base32)",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True cuando el usuario verificó el primer código (2FA activo).",
                        verbose_name="Confirmado",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_secret",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Secreto TOTP",
                "verbose_name_plural": "Secretos TOTP",
                "db_table": "authz_totp_secret",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(seed_issuer, unseed_issuer),
    ]
