# Generated by Django 6.0.5 on 2026-07-18 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Nº de códigos de recuperación por alta. NADA cableado: L2, sembrado aquí a
# '10' (default de Odoo auth_totp), editable en caliente en SystemParameter.
_RECOVERY_KEY = 'authz.totp_recovery_codes'
_RECOVERY_DEFAULT = '10'


def seed_recovery_count(apps, schema_editor):
    SystemParameter = apps.get_model('base', 'SystemParameter')
    db = schema_editor.connection.alias
    if not SystemParameter.objects.using(db).filter(key=_RECOVERY_KEY).exists():
        SystemParameter.objects.using(db).create(key=_RECOVERY_KEY, value=_RECOVERY_DEFAULT)


def unseed_recovery_count(apps, schema_editor):
    SystemParameter = apps.get_model('base', 'SystemParameter')
    db = schema_editor.connection.alias
    SystemParameter.objects.using(db).filter(key=_RECOVERY_KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth_totp", "0001_initial"),
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TotpRecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code_hash",
                    models.CharField(
                        help_text="SHA-256 hex del código de recuperación (el plano no se guarda).",
                        max_length=64,
                        verbose_name="Hash del código",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp de uso; NULL = aún válido (un solo uso).",
                        null=True,
                        verbose_name="Consumido en",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de recuperación TOTP",
                "verbose_name_plural": "Códigos de recuperación TOTP",
                "db_table": "authz_totp_recovery_code",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code_hash"], name="authz_totp_rec_user_hash"
                    )
                ],
            },
        ),
        migrations.RunPython(seed_recovery_count, unseed_recovery_count),
    ]
