# Generated by Django 6.0.5 on 2026-07-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Uom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la unidad (Odoo uom.uom.name).",
                        max_length=100,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de presentación (Odoo sequence). Se deriva del factor.",
                    ),
                ),
                (
                    "relative_factor",
                    models.FloatField(
                        default=1.0,
                        help_text="Cuánto mayor o menor es esta unidad respecto a su unidad de referencia (Odoo relative_factor).",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar para deshabilitar la unidad sin borrarla (Odoo active).",
                    ),
                ),
                (
                    "factor",
                    models.FloatField(
                        default=1.0,
                        help_text="Cantidad absoluta: producto de la cadena de factores relativos (Odoo factor, compute recursivo almacenado).",
                    ),
                ),
                (
                    "parent_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Ruta materializada de la jerarquía (Odoo _parent_store).",
                        max_length=255,
                    ),
                ),
                (
                    "relative_uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unidad de referencia de la que cuelga (Odoo relative_uom_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_uoms",
                        to="uom.uom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad de medida",
                "verbose_name_plural": "Unidades de medida",
                "db_table": "uom_uom",
                "ordering": ["sequence", "relative_uom_id", "id"],
            },
        ),
    ]
