# Generated by Django 6.0.5 on 2026-07-18 18:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0003_product_weight_kg"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLandedCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia (Odoo stock.landed.cost.name).",
                        max_length=64,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("done", "Validado"),
                            ("cancel", "Cancelado"),
                        ],
                        default="draft",
                        help_text="Estado (Odoo stock.landed.cost.state).",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coste en destino",
                "verbose_name_plural": "Costes en destino",
                "db_table": "stock_landed_cost",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockLandedCostLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción de la componente (Odoo name).",
                        max_length=100,
                    ),
                ),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto del coste (Odoo price_unit).",
                        max_digits=14,
                    ),
                ),
                (
                    "split_method",
                    models.CharField(
                        choices=[
                            ("equal", "Igual"),
                            ("by_quantity", "Por cantidad"),
                            ("by_current_cost_price", "Por costo actual"),
                            ("by_weight", "Por peso"),
                            ("by_volume", "Por volumen"),
                        ],
                        default="by_quantity",
                        help_text="Método de reparto (Odoo split_method).",
                        max_length=24,
                    ),
                ),
                (
                    "cost",
                    models.ForeignKey(
                        help_text="Documento (Odoo cost_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_lines",
                        to="stock_landed_costs.stocklandedcost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Componente de coste en destino",
                "verbose_name_plural": "Componentes de coste en destino",
                "db_table": "stock_landed_cost_line",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockValuationAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad recibida (Odoo quantity).",
                        max_digits=12,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Peso total (Odoo weight).",
                        max_digits=12,
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Volumen total (Odoo volume).",
                        max_digits=12,
                    ),
                ),
                (
                    "former_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo antes del ajuste (Odoo former_cost).",
                        max_digits=14,
                    ),
                ),
                (
                    "additional_landed_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Coste en destino repartido (Odoo additional_landed_cost).",
                        max_digits=14,
                    ),
                ),
                (
                    "final_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo final = former + additional (Odoo final_cost).",
                        max_digits=14,
                    ),
                ),
                (
                    "cost",
                    models.ForeignKey(
                        help_text="Documento (Odoo cost_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_lines",
                        to="stock_landed_costs.stocklandedcost",
                    ),
                ),
                (
                    "cost_line",
                    models.ForeignKey(
                        help_text="Componente (Odoo cost_line_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustment_lines",
                        to="stock_landed_costs.stocklandedcostline",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        blank=True,
                        help_text="Movimiento (Odoo move_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landed_cost_adjustments",
                        to="stock.stockmove",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto (Odoo product_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landed_cost_adjustments",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de valoración por coste en destino",
                "verbose_name_plural": "Ajustes de valoración por coste en destino",
                "db_table": "stock_valuation_adjustment",
                "ordering": ["id"],
            },
        ),
    ]
