# Generated by Django 6.0.5 on 2026-07-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
            ],
            options={
                "verbose_name": "System Parameter",
                "verbose_name_plural": "System Parameters",
                "db_table": "system_parameter",
                "ordering": ["key"],
            },
        ),
    ]
