# Generated by Django 6.0.5 on 2026-08-15 01:23

"""El tipo de paquete que ``stock`` cuelga de ``uom.uom``.

≙ ``odoo19c: stock/models/product.py:1344`` (``package_type_id``). De él
propaga ``uom.route_ids``, que la referencia declara ``related``.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0008_alter_stockmove_company"),
        ("uom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uom",
            name="package_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo de paquete del que esta unidad propaga sus rutas (Odoo package_type_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uom_ids",
                to="stock.stockpackagetype",
                verbose_name="Tipo de paquete",
            ),
        ),
    ]
