# Generated by Django 6.0.5 on 2026-08-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uom", "0002_uom_package_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="uom",
            name="timesheet_widget",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo timesheet_widget. Widget del cliente web usado cuando esta unidad captura la hoja de horas.",
                max_length=255,
            ),
        ),
    ]
