# Generated by Django 6.0.5 on 2026-08-28 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uom", "0004_alter_uom_timesheet_widget"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uom",
            options={
                "ordering": ["sequence", "relative_uom_id_id", "id"],
                "verbose_name": "Unidad de medida",
                "verbose_name_plural": "Unidades de medida",
            },
        ),
        migrations.AlterField(
            model_name="uom",
            name="relative_uom",
            field=models.ForeignKey(
                blank=True,
                db_column="relative_uom_id",
                help_text="Unidad de referencia de la que cuelga (Odoo relative_uom_id).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_uoms",
                to="uom.uom",
            ),
        ),
        migrations.RenameField(
            model_name="uom",
            old_name="relative_uom",
            new_name="relative_uom_id",
        ),
    ]
