# Generated by Django 6.0.5 on 2026-08-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_expiry_and_tracking_surface"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="is_storable",
            field=models.BooleanField(
                default=False,
                help_text="Lleva existencias en almacén (Odoo is_storable, «Track Inventory»).",
            ),
        ),
    ]
