# Generated by Django 6.0.5 on 2026-08-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_port_stock_scrap_and_is_storable"),
        ("uom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="description_picking",
            field=models.TextField(
                blank=True,
                help_text="Odoo description_picking. La referencia lo declara traducible; el almacenamiento jsonb de translate=True es la tarea #333.",
                null=True,
                verbose_name="Descripción en el albarán",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="description_pickingin",
            field=models.TextField(
                blank=True,
                help_text="Odoo description_pickingin. La referencia lo declara traducible; el almacenamiento jsonb de translate=True es la tarea #333.",
                null=True,
                verbose_name="Descripción en recepciones",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="description_pickingout",
            field=models.TextField(
                blank=True,
                help_text="Odoo description_pickingout. La referencia lo declara traducible; el almacenamiento jsonb de translate=True es la tarea #333.",
                null=True,
                verbose_name="Descripción en órdenes de entrega",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="uom_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_template_uom_rel",
                help_text='Odoo uom_ids ("Packagings"): unidades adicionales con las que este producto se puede vender. La fuente excluye la unidad base por dominio; aquí lo hace quien las consume.',
                related_name="packaging_product_tmpl_ids",
                to="uom.uom",
                verbose_name="Empaquetados",
            ),
        ),
    ]
