# Generated by Django 6.0.5 on 2026-08-15 01:23

"""Los dos campos que ``stock`` cuelga de ``product.category``.

≙ ``odoo19c: stock/models/product.py:1284-1306`` — ``removal_strategy_id`` y
``packaging_reserve_method``. La columna vive en la app **dueña** del modelo
aunque la declare otro addon con ``add_to_class``; mismo criterio que
``0005_expiry_and_tracking_surface.py``.

``removal_strategy`` ya tenía consumidor esperándola:
``StockQuant._get_removal_strategy`` lee ``product.categ.removal_strategy``
desde antes de que el campo existiera.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_producttemplate_description_picking_and_more"),
        ("stock", "0008_alter_stockmove_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="packaging_reserve_method",
            field=models.CharField(
                choices=[
                    ("full", "Reservar sólo empaques completos"),
                    ("partial", "Reservar empaques parciales"),
                ],
                default="partial",
                help_text="full: no reserva empaques parciales; partial: sí (Odoo packaging_reserve_method).",
                max_length=16,
                verbose_name="Reserva de empaques",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="removal_strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Estrategia que se aplica sin importar la ubicación de origen (Odoo removal_strategy_id). La consume StockQuant._get_removal_strategy, que ya la leía.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categ_ids",
                to="stock.productremoval",
                verbose_name="Estrategia de retiro forzada",
            ),
        ),
    ]
