# Generated by Django 6.0.5 on 2026-08-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_productcategory_packaging_reserve_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productproduct",
            name="lot_properties_definition",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Esquema de las propiedades que llevan los lotes de este producto (Odoo lot_properties_definition).",
                null=True,
                verbose_name="Definición de propiedades de lote",
            ),
        ),
    ]
