# Generated by Django 6.0.5 on 2026-08-15 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0023_rescompany_annual_inventory_day_and_more"),
        ("product", "0009_productproduct_lot_properties_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="lot_sequence",
            field=models.ForeignKey(
                blank=True,
                help_text="Secuencia que genera los números de lote/serie de este producto (Odoo lot_sequence_id). Campo técnico.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lot_product_tmpls",
                to="base.irsequence",
                verbose_name="Secuencia de lote/serie",
            ),
        ),
    ]
