# Generated by Django 6.0.5 on 2026-08-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_producttemplate_lot_sequence"),
        ("purchase_requisition", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="productsupplierinfo",
            name="purchase_requisition_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Línea del acuerdo de compra que creó esta tarifa (Odoo purchase_requisition_line_id). El inverso es ``line.supplier_info_ids``.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier_info_ids",
                to="purchase_requisition.purchaserequisitionline",
                verbose_name="Línea de acuerdo",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="service_upsell_threshold",
            field=models.FloatField(
                default=1.0,
                help_text='Odoo service_upsell_threshold ("Threshold", default=1). Fracción del tiempo vendido que hay que entregar para que se proponga la venta adicional. Quién lo lee está bloqueado — ver el docstring del módulo.',
                verbose_name="Umbral de venta adicional",
            ),
        ),
    ]
