# Generated by Django 6.0.5 on 2026-08-29 08:19

import django.db.models.deletion
import orm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_port_sale_extension_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttributeCustomValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custom_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo custom_value. Lo que el comprador escribió.",
                        max_length=255,
                        verbose_name="Valor personalizado",
                    ),
                ),
                (
                    "custom_product_template_attribute_value_id",
                    models.ForeignKey(
                        db_column="custom_product_template_attribute_value_id",
                        help_text="Odoo custom_product_template_attribute_value_id. El valor de atributo que admite texto libre (is_custom).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="custom_values",
                        to="product.producttemplateattributevalue",
                        verbose_name="Valor del atributo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor personalizado de atributo",
                "verbose_name_plural": "Valores personalizados de atributo",
                "db_table": "product_attribute_custom_value",
                "ordering": ["custom_product_template_attribute_value_id", "id"],
            },
            bases=(
                orm.models.RecordLoaderMixin,
                orm.models.DisplayNameMixin,
                orm.models.CheckCompanyMixin,
                models.Model,
            ),
        ),
    ]
