# Generated by Django 6.0.5 on 2026-07-16 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0008_accessrule"),
        ("company", "0002_company_is_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymodulesubscription",
            name="billing_cycle",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Mensual"), ("annual", "Anual")],
                default="",
                max_length=8,
                verbose_name="Ciclo de cobro",
            ),
        ),
        migrations.CreateModel(
            name="ModulePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Mensual"), ("annual", "Anual")],
                        max_length=8,
                        verbose_name="Ciclo de cobro",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                ("effective_from", models.DateTimeField(verbose_name="Vigente desde")),
                (
                    "effective_to",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Vigente hasta"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="authz.module",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de módulo",
                "verbose_name_plural": "Tarifas de módulo",
                "db_table": "module_price",
                "ordering": ["module__code", "billing_cycle", "-effective_from"],
                "indexes": [
                    models.Index(
                        fields=["module", "billing_cycle", "effective_from"],
                        name="module_pric_module__7622e7_idx",
                    )
                ],
            },
        ),
    ]
