# Generated by Django 6.0.5 on 2026-07-16 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_companymodulesubscription_billing_cycle_moduleprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="company.department",
                        verbose_name="Departamento padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "org_department",
                "ordering": ["subsidiary__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150, verbose_name="Puesto")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="company.department",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puesto",
                "verbose_name_plural": "Puestos",
                "db_table": "org_job",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Subsidiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=2, verbose_name="País"
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(
                        blank=True,
                        default="MXN",
                        max_length=3,
                        verbose_name="Moneda base",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsidiaries",
                        to="company.company",
                        verbose_name="Empresa (tenant)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="company.subsidiary",
                        verbose_name="Subsidiaria padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsidiaria",
                "verbose_name_plural": "Subsidiarias",
                "db_table": "org_subsidiary",
                "ordering": ["company__code", "name"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="subsidiary",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="company.subsidiary",
                verbose_name="Subsidiaria",
            ),
        ),
    ]
