# Generated by Django 6.0.5 on 2026-07-17 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_department_job_subsidiary_department_subsidiary"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255, verbose_name="Clave")),
                ("value", models.TextField(verbose_name="Valor")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="company.company",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de empresa",
                "verbose_name_plural": "Configuraciones de empresa",
                "db_table": "company_setting",
                "ordering": ["company_id", "key"],
                "unique_together": {("company", "key")},
            },
        ),
    ]
