# Generated by Django 6.0.5 on 2026-07-18 02:02

import addons.base_vat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_seed_founder_notifications_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="tax_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RFC del SAT (12 moral / 13 física). Validado por base_vat.",
                max_length=30,
                validators=[addons.base_vat.validators.validate_rfc],
                verbose_name="RFC / Tax ID",
            ),
        ),
    ]
