# Generated by Django 6.0.5 on 2026-07-24 19:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_alter_company_tax_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionBillingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.CharField(max_length=7, verbose_name="Periodo")),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("time", "Planificador (Actor Tiempo)"),
                            ("operator", "Corrida manual del operador"),
                        ],
                        default="time",
                        max_length=8,
                        verbose_name="Disparada por",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Inicio"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "invoices_issued",
                    models.IntegerField(default=0, verbose_name="Facturas emitidas"),
                ),
                (
                    "amount_charged",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto cobrado",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "failures",
                    models.IntegerField(default=0, verbose_name="Cobros fallidos"),
                ),
            ],
            options={
                "verbose_name": "Corrida de facturación",
                "verbose_name_plural": "Corridas de facturación",
                "db_table": "subscription_billing_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["period"], name="subscriptio_period_f11bdd_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period", models.CharField(max_length=7, verbose_name="Periodo")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="MXN", max_length=3, verbose_name="Moneda"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("issued", "Emitida"),
                            ("paid", "Pagada"),
                            ("failed", "Cobro fallido"),
                            ("void", "Anulada"),
                        ],
                        default="draft",
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Emitida en"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Pagada en"
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Motivo de fallo",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_invoices",
                        to="company.company",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="company.subscriptionbillingrun",
                        verbose_name="Corrida",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="company.companymodulesubscription",
                        verbose_name="Suscripción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura de suscripción",
                "verbose_name_plural": "Facturas de suscripción",
                "db_table": "subscription_invoice",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="subscriptio_company_8cb2e1_idx",
                    ),
                    models.Index(fields=["run"], name="subscriptio_run_id_83d8c5_idx"),
                ],
                "unique_together": {("subscription", "period")},
            },
        ),
    ]
