# Generated by Django 6.0.5 on 2026-07-26 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("company", "0009_subscriptionbillingrun_subscriptioninvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptioninvoice",
            name="account_move",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.accountmove",
                verbose_name="Asiento contable",
            ),
        ),
    ]
