# Generated by Django 5.0.1 on 2026-05-20 23:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("settings_app", "0001_initial"),
        ("settings_app", "0002_sitesettings_avatar_max_size_mb_and_more"),
        ("settings_app", "0003_paymentgateway_shippingmethod"),
        ("settings_app", "0004_sitesettings_contact_staticpage"),
        ("settings_app", "0005_timestampedmodel_settings"),
        ("settings_app", "0006_sitesettings_payment_timeout"),
        ("settings_app", "0007_paymentgateway_rename_and_fix_columns"),
        ("settings_app", "0008_sync_model_drift"),
        (
            "settings_app",
            "0009_sitesettings_currency_sitesettings_max_return_days_and_more",
        ),
    ]

    initial = True

    dependencies = [
        ("users", "0001_squashed_0007_user_deactivation_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("mercado_pago", "Mercado Pago"),
                            ("paypal", "PayPal"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Proveedor de pago",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Activo"
                    ),
                ),
                (
                    "credentials_enc",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Credenciales cifradas (Fernet JSON)",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Última verificación de conectividad",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settings_payment_gateway",
                "verbose_name": "Gateway de pago",
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Costo de envio",
                    ),
                ),
                (
                    "estimated_days",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Dias habiles estimados",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "free_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto minimo para envio gratis",
                    ),
                ),
                ("zones", models.JSONField(blank=True, default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settings_shipping_method",
                "ordering": ["cost", "name"],
                "verbose_name": "Metodo de envio",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="PracticaYoruba", max_length=100),
                ),
                (
                    "iva_rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.16"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("1.00")),
                        ],
                    ),
                ),
                ("currency", models.CharField(default="MXN", max_length=3)),
                (
                    "order_timeout_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_return_days",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar_max_size_mb",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Tamaño maximo permitido para avatares, en MB (FR-AUTH-06.04).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Tamaño maximo avatar (MB)",
                    ),
                ),
                (
                    "max_addresses_per_user",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Numero maximo de direcciones de envio por comprador (FR-AUTH-07.02).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maximo de direcciones por usuario",
                    ),
                ),
                (
                    "min_stock_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Umbral minimo de stock que activa alertas de inventario (FR-INV-01.02).",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Umbral minimo de stock",
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Email de soporte",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Telefono de contacto",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, default="", verbose_name="Direccion fisica"
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Redes sociales"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuracion del sitio",
                "db_table": "settings_sitesettings",
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("about", "Acerca de nosotros"),
                            ("terms", "Términos y condiciones"),
                            ("privacy", "Política de privacidad"),
                            ("returns", "Política de devoluciones"),
                            ("faq", "Preguntas frecuentes"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settings_static_page",
                "verbose_name": "Página estática",
            },
        ),
        migrations.CreateModel(
            name="StaticPageVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                (
                    "version",
                    models.PositiveIntegerField(verbose_name="Número de versión"),
                ),
                ("content", models.TextField(verbose_name="Contenido HTML")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PUBLISHED", "Publicado"),
                            ("ARCHIVED", "Archivado"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publicar en fecha futura"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="settings_app.staticpage",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_page_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "settings_static_page_version",
                "ordering": ["-version"],
                "verbose_name": "Versión de página estática",
            },
        ),
        migrations.AddConstraint(
            model_name="staticpageversion",
            constraint=models.UniqueConstraint(
                fields=("page", "version"), name="unique_page_version"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staticpage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staticpageversion",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="payment_timeout_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minutos hasta que una orden PENDING se cancela por timeout (UC-SYS-01).",
            ),
        ),
        migrations.RenameField(
            model_name="paymentgateway",
            old_name="provider",
            new_name="gateway",
        ),
        migrations.AddField(
            model_name="paymentgateway",
            name="name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name="paymentgateway",
            old_name="credentials_enc",
            new_name="credentials",
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="credentials",
            field=models.BinaryField(
                help_text="Credenciales cifradas con Fernet (apps.settings_app.models._fernet_key)"
            ),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelOptions(
            name="paymentgateway",
            options={"verbose_name": "Pasarela de pago"},
        ),
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={"ordering": ["cost", "name"], "verbose_name": "Método de envío"},
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name": "Configuración del sitio"},
        ),
        migrations.RemoveConstraint(
            model_name="staticpageversion",
            name="unique_page_version",
        ),
        migrations.RemoveField(
            model_name="shippingmethod",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="avatar_max_size_mb",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="max_addresses_per_user",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="max_return_days",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="order_timeout_minutes",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="site_name",
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("TEST", "Test (sandbox)"),
                    ("MERCADOPAGO", "MercadoPago"),
                    ("PAYPAL", "PayPal"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="paymentgateway",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="cost",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="estimated_days",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="free_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="shippingmethod",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="min_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="social_links",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="support_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="staticpage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="staticpageversion",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="staticpageversion",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="staticpageversion",
            name="publish_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="staticpageversion",
            name="version",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="staticpageversion",
            unique_together={("page", "version")},
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="currency",
            field=models.CharField(
                default="MXN",
                help_text="Código ISO 4217 de la moneda (3 letras mayúsculas).",
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Currency must be a 3-letter ISO 4217 code (uppercase).",
                        regex="^[A-Z]{3}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_return_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Días máximos para solicitar una devolución.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="order_timeout_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minutos antes de que una orden sin pagar expire (FR-CFG-03.01).",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="PracticaYoruba", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="free_shipping_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("500.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="iva_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.16"),
                help_text="Tasa de IVA expresada como fracción decimal entre 0 y 1 (ej. 0.16 = 16%).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
    ]
