# Generated by Django 5.0.1 on 2026-05-15 05:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_paymentgateway_rename_and_fix_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgateway',
            options={'verbose_name': 'Pasarela de pago'},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'ordering': ['cost', 'name'], 'verbose_name': 'Método de envío'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Configuración del sitio'},
        ),
        migrations.RemoveConstraint(
            model_name='staticpageversion',
            name='unique_page_version',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='avatar_max_size_mb',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='max_addresses_per_user',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='max_return_days',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='order_timeout_minutes',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_name',
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway',
            field=models.CharField(choices=[('TEST', 'Test (sandbox)'), ('MERCADOPAGO', 'MercadoPago'), ('PAYPAL', 'PayPal')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='estimated_days',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='free_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shippingmethod',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='iva_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.16'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='min_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staticpageversion',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staticpageversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staticpageversion',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticpageversion',
            name='version',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='staticpageversion',
            unique_together={('page', 'version')},
        ),
    ]
