# Generated by Django 5.0.1 on 2026-05-19 13:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0008_sync_model_drift"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="currency",
            field=models.CharField(
                default="MXN",
                help_text="Código ISO 4217 de la moneda (3 letras mayúsculas).",
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Currency must be a 3-letter ISO 4217 code (uppercase).",
                        regex="^[A-Z]{3}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="max_return_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Días máximos para solicitar una devolución.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="order_timeout_minutes",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Minutos antes de que una orden sin pagar expire (FR-CFG-03.01).",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_name",
            field=models.CharField(default="PracticaYoruba", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="free_shipping_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("500.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="iva_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.16"),
                help_text="Tasa de IVA expresada como fracción decimal entre 0 y 1 (ej. 0.16 = 16%).",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
    ]
