# Generated by Django 5.0.1 on 2026-05-25 18:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settings_app",
            "0001_squashed_0009_sitesettings_currency_sitesettings_max_return_days_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Costo de envío. 0 = gratis.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
