# Generated by Django 5.0.1 on 2026-06-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0010_alter_shippingmethod_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logotipo del sitio para el recibo PDF (UC-PAY-10). PNG recomendado.",
                null=True,
                upload_to="settings/logo/",
                verbose_name="Logotipo",
            ),
        ),
    ]
