# Generated by Django 5.0.1 on 2026-06-03 08:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0011_sitesettings_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="referral_active",
            field=models.BooleanField(
                default=False,
                help_text="Si el programa de referidos esta activo (UC-PRO-05 PRE-02).",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_reward_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Descuento fijo del voucher de recompensa emitido al referidor cuando el referido completa su primera compra (UC-PRO-05 Subflujo C).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_welcome_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                help_text="Descuento fijo del voucher de bienvenida emitido al nuevo comprador que canjea un codigo referral (UC-PRO-05 Subflujo B).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
