# Generated by Django 5.0.1 on 2026-06-23 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0012_sitesettings_referral_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staticpageversion",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="staticpageversion",
            constraint=models.UniqueConstraint(
                fields=("page", "version"), name="unique_static_page_version"
            ),
        ),
    ]
