# Generated by Django 6.0.5 on 2026-08-03 22:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "tracking_url_template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL template with {tracking_number} placeholder.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "webhook_secret",
                    models.BinaryField(
                        blank=True,
                        help_text="Per-courier webhook secret, Fernet-encrypted (LOG-04).",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paqueteria",
                "db_table": "logistics_courier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_name", models.CharField(max_length=200)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=10)),
                ("country", models.CharField(default="MX", max_length=2)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
            ],
            options={
                "verbose_name": "Dirección de entrega",
                "db_table": "delivery_address",
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Evento de envio",
                "db_table": "logistics_shipment_event",
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                ("tracking_number", models.CharField(db_index=True, max_length=80)),
                (
                    "tracking_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Creada"),
                            ("PICKED_UP", "Recolectada"),
                            ("IN_TRANSIT", "En transito"),
                            ("DELIVERED", "Entregada"),
                            ("INCIDENT", "Incidente"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_delivery", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Guia de envio",
                "db_table": "logistics_shipment_guide",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Costo de envío. 0 = gratis.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("estimated_days", models.PositiveSmallIntegerField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "free_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("zones", models.JSONField(blank=True, default=list)),
            ],
            options={
                "verbose_name": "Método de envío",
                "db_table": "settings_shipping_method",
                "ordering": ["cost", "name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("zip_code_prefix", models.CharField(max_length=5, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "estimated_days_min",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Días hábiles mínimos de entrega en la zona.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "estimated_days_max",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Días hábiles máximos de entrega en la zona.",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo de envío específico de la zona. Vacío = usar el del método.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "free_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Compra mínima para envío gratis en la zona. Vacío = usar el del método de envío.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "delivery_shipping_zone",
            },
        ),
        migrations.CreateModel(
            name="CarrierRateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_per_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transit_days", models.PositiveSmallIntegerField()),
                (
                    "environmental",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                        ],
                        default="medium",
                        help_text="Rating ambiental (mayor es mejor en el ranking).",
                        max_length=6,
                    ),
                ),
                (
                    "max_package_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_length_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_width_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "max_total_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "max_total_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("allows_hazardous", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "courier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_card",
                        to="delivery.courier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de paqueteria",
                "db_table": "logistics_carrier_rate_card",
            },
        ),
    ]
