# Generated by Django 6.0.5 on 2026-07-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthzEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DENY", "Denegación (403)"),
                            ("SENSITIVE_USE", "Uso de capacidad sensible"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "capability_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Capacidad"
                    ),
                ),
                ("ip_addr", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("extra_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Evento de autorización",
                "verbose_name_plural": "Eventos de autorización",
                "db_table": "authz_event",
                "ordering": ["-created_at"],
            },
        ),
    ]
