# Generated by Django 6.0.5 on 2026-08-02 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthzEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DENY", "Denegación (403)"),
                            ("SENSITIVE_USE", "Uso de capacidad sensible"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "capability_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Capacidad"
                    ),
                ),
                ("ip_addr", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("extra_json", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authz_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de autorización",
                "verbose_name_plural": "Eventos de autorización",
                "db_table": "authz_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="authz_event_action_09439a_idx",
                    ),
                    models.Index(
                        fields=["actor", "action", "-created_at"],
                        name="authz_event_actor_i_bb271b_idx",
                    ),
                ],
            },
        ),
    ]
