# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authz_audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="authzevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authz_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Actor",
            ),
        ),
        migrations.AddIndex(
            model_name="authzevent",
            index=models.Index(
                fields=["action", "-created_at"], name="authz_event_action_09439a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="authzevent",
            index=models.Index(
                fields=["actor", "action", "-created_at"],
                name="authz_event_actor_i_bb271b_idx",
            ),
        ),
    ]
