# Generated by Django 6.0.5 on 2026-08-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogPostalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True,
                        default="MX",
                        help_text="Código ISO 3166-1 alpha-2 del país de la fuente.",
                        max_length=2,
                        verbose_name="País",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        db_index=True,
                        help_text="CP del asentamiento (MX: SEPOMEX d_codigo).",
                        max_length=12,
                        verbose_name="Código postal",
                    ),
                ),
                (
                    "settlement_name",
                    models.CharField(max_length=64, verbose_name="Asentamiento"),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        max_length=32, verbose_name="Tipo de asentamiento"
                    ),
                ),
                (
                    "municipality",
                    models.CharField(max_length=64, verbose_name="Municipio"),
                ),
                ("state", models.CharField(max_length=40, verbose_name="Estado")),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Ciudad"
                    ),
                ),
                (
                    "office_postal_code",
                    models.CharField(max_length=5, verbose_name="CP de oficina"),
                ),
                (
                    "state_code",
                    models.CharField(max_length=2, verbose_name="Clave de estado"),
                ),
                (
                    "office_code",
                    models.CharField(max_length=5, verbose_name="Clave de oficina"),
                ),
                (
                    "postal_code_internal_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=4,
                        verbose_name="Clave interna de CP",
                    ),
                ),
                (
                    "settlement_type_code",
                    models.CharField(
                        max_length=2, verbose_name="Clave tipo de asentamiento"
                    ),
                ),
                (
                    "municipality_code",
                    models.CharField(max_length=3, verbose_name="Clave de municipio"),
                ),
                (
                    "settlement_consecutive_id",
                    models.CharField(
                        max_length=4, verbose_name="ID consecutivo de asentamiento"
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Urbano", "Urbano"),
                            ("Semiurbano", "Semiurbano"),
                            ("Rural", "Rural"),
                        ],
                        default="",
                        max_length=12,
                        verbose_name="Zona",
                    ),
                ),
                (
                    "city_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=2,
                        verbose_name="Clave de ciudad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código postal (SEPOMEX)",
                "verbose_name_plural": "Códigos postales (SEPOMEX)",
                "db_table": "geo_catalog_postal_code",
                "indexes": [
                    models.Index(
                        fields=["country", "postal_code", "settlement_name"],
                        name="geo_catalog_country_5ef70a_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country", "postal_code", "settlement_consecutive_id"),
                        name="uq_catalog_postal_code_natural_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CountryAddressPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enforce_cities",
                    models.BooleanField(
                        default=False,
                        help_text="Exigir ciudad del catálogo en direcciones (Odoo enforce_cities).",
                    ),
                ),
                (
                    "country",
                    models.OneToOneField(
                        help_text="País al que aplica la política (Odoo res.country).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_policy",
                        to="base.rescountry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Política de dirección por país",
                "verbose_name_plural": "Políticas de dirección por país",
                "db_table": "res_country_address_policy",
            },
        ),
        migrations.CreateModel(
            name="ResCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la ciudad (Odoo res.city.name).",
                        max_length=120,
                    ),
                ),
                (
                    "zipcode",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código postal (Odoo zipcode).",
                        max_length=16,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="País (Odoo country_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="base.rescountry",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        help_text="Estado/provincia (Odoo state_id, dominio country_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cities",
                        to="base.rescountrystate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciudad",
                "verbose_name_plural": "Ciudades",
                "db_table": "res_city",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AddressStructured",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la calle (Odoo street_name).",
                        max_length=200,
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número exterior (Odoo street_number / House).",
                        max_length=32,
                    ),
                ),
                (
                    "street_number2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número interior / puerta (Odoo street_number2 / Door).",
                        max_length=32,
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        help_text="Partner al que pertenece (Odoo _inherit res.partner).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured",
                        to="base.respartner",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ciudad del catálogo (Odoo city_id → res.city).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addresses",
                        to="base_address_extended.rescity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección estructurada",
                "verbose_name_plural": "Direcciones estructuradas",
                "db_table": "res_partner_address_structured",
            },
        ),
    ]
