# Generated by Django 6.0.5 on 2026-08-28 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_address_extended", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressstructured",
            name="city",
            field=models.ForeignKey(
                blank=True,
                db_column="city_id",
                help_text="Ciudad del catálogo (Odoo city_id → res.city).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="base_address_extended.rescity",
            ),
        ),
        migrations.RenameField(
            model_name="addressstructured",
            old_name="city",
            new_name="city_id",
        ),
        migrations.AlterField(
            model_name="rescity",
            name="country",
            field=models.ForeignKey(
                db_column="country_id",
                help_text="País (Odoo country_id, requerido).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="base.rescountry",
            ),
        ),
        migrations.RenameField(
            model_name="rescity",
            old_name="country",
            new_name="country_id",
        ),
        migrations.AlterField(
            model_name="rescity",
            name="state",
            field=models.ForeignKey(
                blank=True,
                db_column="state_id",
                help_text="Estado/provincia (Odoo state_id, dominio country_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="base.rescountrystate",
            ),
        ),
        migrations.RenameField(
            model_name="rescity",
            old_name="state",
            new_name="state_id",
        ),
    ]
