# Generated by Django 6.0.5 on 2026-08-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="allocated_hours",
            field=models.FloatField(
                default=0.0,
                help_text="Odoo allocated_hours. tracking=True BLOQUEADO — ver docstring del módulo.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="allow_timesheets",
            field=models.BooleanField(
                default=True,
                help_text="Odoo allow_timesheets. La referencia lo apaga cuando no hay cuenta analítica (account_id); ausente aquí — queda escribible directo.",
            ),
        ),
    ]
