# Generated by Django 6.0.5 on 2026-08-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_project_allocated_hours_project_allow_timesheets"),
        ("sms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttasktype",
            name="sms_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo sms_template_id — si está definida, al llegar una tarea a esta etapa se envía un SMS al cliente (su domain por modelo no se porta — ver la divergencia del docstring del módulo).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="task_stages",
                to="sms.smstemplate",
                verbose_name="Plantilla de SMS",
            ),
        ),
    ]
