# Generated by Django 6.0.5 on 2026-08-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_productsupplierinfo_purchase_requisition_line_and_more"),
        ("project", "0003_projecttasktype_sms_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("not_billable", "not billable"),
                    ("manually", "billed manually"),
                ],
                default="not_billable",
                help_text="Odoo billing_type (compute, store, required, default=not_billable). El compute queda bloqueado por allow_billable (sale_project).",
                max_length=16,
                verbose_name="Modo de facturación",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="timesheet_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo timesheet_product_id. Servicio con el que se factura por defecto el tiempo de una tarea. Su domain y su default quedan bloqueados — ver el docstring del módulo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheet_projects",
                to="product.productproduct",
                verbose_name="Producto de hoja de horas",
            ),
        ),
    ]
