# Generated by Django 6.0.5 on 2026-07-22 06:26
#
# Movimiento state-only: PaymentGateway se disuelve desde el addon no-Odoo
# ``settings_app`` hacia ``payment`` (contraparte de ``payment.provider``).
# La tabla física ``settings_payment_gateway`` no cambia — solo el estado
# de Django. La DeleteModel espejo vive en settings_app/0004 y depende de
# esta migración.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="PaymentGateway",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("name", models.CharField(max_length=50)),
                        (
                            "gateway",
                            models.CharField(
                                choices=[
                                    ("TEST", "Test (sandbox)"),
                                    ("MERCADOPAGO", "MercadoPago"),
                                    ("PAYPAL", "PayPal"),
                                ],
                                max_length=20,
                                unique=True,
                            ),
                        ),
                        ("is_active", models.BooleanField(default=False)),
                        (
                            "credentials",
                            models.BinaryField(
                                help_text="Credenciales cifradas con Fernet (addons.payment.models.payment_provider._fernet_key)"
                            ),
                        ),
                        ("verified_at", models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        "verbose_name": "Pasarela de pago",
                        "db_table": "settings_payment_gateway",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
