# Generated by Django 6.0.5 on 2026-07-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_paymentgateway"),
        ("sale", "0008_port_draft_orders_to_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="sale_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="sale.saleorder",
            ),
        ),
    ]
