# Generated by Django 6.0.5 on 2026-07-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_payment_sale_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.CharField(
                choices=[
                    ("MERCADOPAGO", "MercadoPago"),
                    ("PAYPAL", "PayPal"),
                    ("MANUAL", "Conciliación manual"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
