# Generated by Django 5.0.1 on 2026-05-15 05:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_timestampedmodel_voucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Voucher'},
        ),
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(help_text='Siempre en mayusculas. Insensible a mayusculas en validacion.', max_length=50, unique=True, verbose_name='Codigo del cupon'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='current_uses',
            field=models.PositiveIntegerField(default=0, verbose_name='Usos actuales'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje a descontar (0.01-100). Solo para tipo PERCENTAGE.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Porcentaje de descuento'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe fijo a descontar. Solo para tipo FIXED.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor del descuento (FIXED)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tope para descuentos porcentuales. Null = sin tope.', max_digits=10, null=True, verbose_name='Descuento maximo'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Null = ilimitado.', null=True, verbose_name='Usos maximos'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='El subtotal debe ser >= a este valor para aplicar el cupon.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto minimo del carrito'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='restricted_to_email',
            field=models.EmailField(blank=True, help_text='Si se indica, solo ese email puede usar el cupon.', max_length=254, null=True, verbose_name='Solo para este email'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Vigente desde'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Null = sin fecha de expiracion.', null=True, verbose_name='Vigente hasta'),
        ),
        migrations.AlterField(
            model_name='voucherchangelog',
            name='changes',
            field=models.JSONField(help_text='Dict de {campo: {before, after}} con los cambios aplicados.'),
        ),
        migrations.AlterField(
            model_name='voucherchangelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
