# Generated by Django 5.0.1 on 2026-05-23 06:55
# T-119 merge-safe: VoucherUsage may already exist from 0002_voucher_usage (Branch A).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0001_squashed_0004_voucher_softdelete"),
        ("users", "0001_squashed_0007_user_deactivation_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `voucher_usage` (
                            `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                            `used_at` datetime(6) NOT NULL,
                            `user_id` bigint NOT NULL,
                            `voucher_id` bigint NOT NULL,
                            UNIQUE KEY `voucher_usage_user_id_voucher_id_uniq` (`user_id`, `voucher_id`),
                            CONSTRAINT `voucher_usage_user_id_fk_users_user`
                                FOREIGN KEY (`user_id`) REFERENCES `users_user` (`id`),
                            CONSTRAINT `voucher_usage_voucher_id_fk_voucher_voucher`
                                FOREIGN KEY (`voucher_id`) REFERENCES `voucher_voucher` (`id`)
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS `voucher_usage`",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="VoucherUsage",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("used_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "user",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="voucher_usages",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                        (
                            "voucher",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="usages",
                                to="voucher.voucher",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Voucher usage",
                        "db_table": "voucher_usage",
                        "unique_together": {("user", "voucher")},
                    },
                ),
            ],
        ),
    ]
