# Generated by Django 5.0.1 on 2026-06-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0007_alter_voucher_discount_pct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("FIXED", "Descuento fijo"),
                    ("PERCENTAGE", "Porcentaje"),
                    ("FREE_SHIPPING", "Envio gratis"),
                    ("REFERRAL", "Codigo referral"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
