# Generated by Django 5.0.1 on 2026-06-23 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0008_alter_voucher_voucher_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="voucherusage",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="voucherusage",
            constraint=models.UniqueConstraint(
                fields=("user", "voucher"), name="unique_voucher_usage"
            ),
        ),
    ]
