# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_label",
                    models.CharField(
                        help_text="``app_label.model`` en minúsculas, p.ej. ``orders.order``.",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "domain",
                    models.JSONField(
                        default=dict,
                        help_text="Filtro ORM serializado; los valores ``$user``/``$company`` se resuelven en runtime al pk del usuario / id de su company.",
                        verbose_name="Dominio",
                    ),
                ),
                ("perm_read", models.BooleanField(default=True, verbose_name="Leer")),
                (
                    "perm_write",
                    models.BooleanField(default=True, verbose_name="Escribir"),
                ),
                (
                    "perm_create",
                    models.BooleanField(default=True, verbose_name="Crear"),
                ),
                (
                    "perm_unlink",
                    models.BooleanField(default=True, verbose_name="Borrar"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Regla de acceso",
                "verbose_name_plural": "Reglas de acceso",
                "db_table": "authz_access_rule",
                "ordering": ["model_label", "role__code"],
            },
        ),
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Formato 'dominio.verbo' (p.ej. orders.refund).",
                        max_length=100,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Categoría"
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Su uso exitoso se audita en AuthzEvent (DEC-07).",
                        verbose_name="Sensible",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
            ],
            options={
                "verbose_name": "Capacidad",
                "verbose_name_plural": "Capacidades",
                "db_table": "authz_capability",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EntitlementRevocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="Motivo"),
                ),
            ],
            options={
                "verbose_name": "Revocación de grant",
                "verbose_name_plural": "Revocaciones de grant",
                "db_table": "authz_entitlement_revocation",
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "is_application",
                    models.BooleanField(
                        default=False,
                        help_text="Vendible (top-level) vs módulo técnico (dependencia interna).",
                        verbose_name="App vendible",
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[("free", "Gratis"), ("paid", "De pago")],
                        default="free",
                        max_length=8,
                        verbose_name="Tier",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Categoría"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Versión"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "auto_install",
                    models.BooleanField(
                        default=False,
                        help_text="Se activa solo cuando sus dependencias están presentes.",
                        verbose_name="Auto-instalar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "db_table": "authz_module",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "authz_role",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expira"),
                ),
            ],
            options={
                "verbose_name": "Asignación de rol",
                "verbose_name_plural": "Asignaciones de rol",
                "db_table": "authz_role_assignment",
            },
        ),
        migrations.CreateModel(
            name="RoleCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Ninguno"),
                            (10, "Ver"),
                            (20, "Crear"),
                            (30, "Editar"),
                            (40, "Total"),
                        ],
                        default=40,
                        verbose_name="Nivel de acceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidad de rol",
                "verbose_name_plural": "Capacidades de rol",
                "db_table": "authz_role_capability",
                "ordering": ["role__code", "capability__code"],
            },
        ),
        migrations.CreateModel(
            name="DirectEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expira"),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_entitlements",
                        to="authz.capability",
                        verbose_name="Capacidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grant directo",
                "verbose_name_plural": "Grants directos",
                "db_table": "authz_direct_entitlement",
            },
        ),
    ]
