# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="directentitlement",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Otorgado por",
            ),
        ),
        migrations.AddField(
            model_name="directentitlement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="direct_entitlements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="entitlementrevocation",
            name="capability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entitlement_revocations",
                to="authz.capability",
                verbose_name="Capacidad",
            ),
        ),
        migrations.AddField(
            model_name="entitlementrevocation",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revocado por",
            ),
        ),
        migrations.AddField(
            model_name="entitlementrevocation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entitlement_revocations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="depends",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependents",
                to="authz.module",
                verbose_name="Depende de",
            ),
        ),
        migrations.AddField(
            model_name="capability",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="capabilities",
                to="authz.module",
                verbose_name="Módulo",
            ),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Rol al que aplica la regla; **nulo = regla global** (obligatoria, se combina con AND). Paridad ``ir.rule.groups``.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_rules",
                to="authz.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado por",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="authz.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="rolecapability",
            name="capability",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_capabilities",
                to="authz.capability",
                verbose_name="Capacidad",
            ),
        ),
        migrations.AddField(
            model_name="rolecapability",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_capabilities",
                to="authz.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="authz.RoleCapability",
                to="authz.capability",
                verbose_name="Capacidades",
            ),
        ),
        migrations.AddIndex(
            model_name="directentitlement",
            index=models.Index(
                fields=["user", "capability"], name="authz_direc_user_id_ec8311_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="directentitlement",
            constraint=models.UniqueConstraint(
                fields=("user", "capability"), name="uq_authz_direct_entitlement"
            ),
        ),
        migrations.AddIndex(
            model_name="entitlementrevocation",
            index=models.Index(
                fields=["user", "capability"], name="authz_entit_user_id_47dd02_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitlementrevocation",
            constraint=models.UniqueConstraint(
                fields=("user", "capability"), name="uq_authz_entitlement_revocation"
            ),
        ),
        migrations.AddIndex(
            model_name="accessrule",
            index=models.Index(
                fields=["model_label", "is_active"],
                name="authz_acces_model_l_02e6e2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("perm_read", True),
                    ("perm_write", True),
                    ("perm_create", True),
                    ("perm_unlink", True),
                    _connector="OR",
                ),
                name="authz_access_rule_at_least_one_perm",
            ),
        ),
        migrations.AddIndex(
            model_name="roleassignment",
            index=models.Index(
                fields=["user", "role"], name="authz_role__user_id_f2e4a8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="roleassignment",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="uq_authz_role_assignment"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rolecapability",
            unique_together={("role", "capability")},
        ),
    ]
