# Generated by Django 6.0.5 on 2026-07-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0003_menuitem_audience"),
    ]

    operations = [
        # Django no permite AlterField para añadir through= a un M2M: hay que
        # quitar el M2M plano, crear el through y re-añadir el M2M con through.
        # Los grants existentes se re-siembran (seed_authz) — no hay data en prod.
        migrations.RemoveField(
            model_name="role",
            name="capabilities",
        ),
        migrations.CreateModel(
            name="RoleCapability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Ninguno"),
                            (10, "Ver"),
                            (20, "Crear"),
                            (30, "Editar"),
                            (40, "Total"),
                        ],
                        default=40,
                        verbose_name="Nivel de acceso",
                    ),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_capabilities",
                        to="authz.capability",
                        verbose_name="Capacidad",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_capabilities",
                        to="authz.role",
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidad de rol",
                "verbose_name_plural": "Capacidades de rol",
                "db_table": "authz_role_capability",
                "ordering": ["role__code", "capability__code"],
                "unique_together": {("role", "capability")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="capabilities",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="authz.RoleCapability",
                to="authz.capability",
                verbose_name="Capacidades",
            ),
        ),
    ]
