# Generated by Django 6.0.5 on 2026-07-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0006_module_depends"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="auto_install",
            field=models.BooleanField(
                default=False,
                help_text="Se activa solo cuando sus dependencias están presentes.",
                verbose_name="Auto-instalar",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="category",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Categoría"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Descripción"),
        ),
        migrations.AddField(
            model_name="module",
            name="is_application",
            field=models.BooleanField(
                default=False,
                help_text="Vendible (top-level) vs módulo técnico (dependencia interna).",
                verbose_name="App vendible",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="tier",
            field=models.CharField(
                choices=[("free", "Gratis"), ("paid", "De pago")],
                default="free",
                max_length=8,
                verbose_name="Tier",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="version",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Versión"
            ),
        ),
    ]
