# Generated by Django 6.0.5 on 2026-07-16 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0007_module_auto_install_module_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_label",
                    models.CharField(
                        help_text="``app_label.model`` en minúsculas, p.ej. ``orders.order``.",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "domain",
                    models.JSONField(
                        default=dict,
                        help_text="Filtro ORM serializado; los valores ``$user``/``$company`` se resuelven en runtime al pk del usuario / id de su company.",
                        verbose_name="Dominio",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="authz.role",
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de acceso",
                "verbose_name_plural": "Reglas de acceso",
                "db_table": "authz_access_rule",
                "ordering": ["model_label", "role__code"],
                "indexes": [
                    models.Index(
                        fields=["model_label", "is_active"],
                        name="authz_acces_model_l_02e6e2_idx",
                    )
                ],
            },
        ),
    ]
