# Generated by Django 6.0.5 on 2026-07-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0008_accessrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrule",
            name="perm_create",
            field=models.BooleanField(default=True, verbose_name="Crear"),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="perm_read",
            field=models.BooleanField(default=True, verbose_name="Leer"),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="perm_unlink",
            field=models.BooleanField(default=True, verbose_name="Borrar"),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="perm_write",
            field=models.BooleanField(default=True, verbose_name="Escribir"),
        ),
        migrations.AlterField(
            model_name="accessrule",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Rol al que aplica la regla; **nulo = regla global** (obligatoria, se combina con AND). Paridad ``ir.rule.groups``.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_rules",
                to="authz.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AddConstraint(
            model_name="accessrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("perm_read", True),
                    ("perm_write", True),
                    ("perm_create", True),
                    ("perm_unlink", True),
                    _connector="OR",
                ),
                name="authz_access_rule_at_least_one_perm",
            ),
        ),
    ]
