# Generated by Django 5.0.1 on 2026-05-19 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0007_order_deleted_at_order_is_deleted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "tracking_url_template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL template with {tracking_number} placeholder.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Paqueteria",
                "db_table": "logistics_courier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(db_index=True, max_length=80, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Creada"),
                            ("PICKED_UP", "Recolectada"),
                            ("IN_TRANSIT", "En transito"),
                            ("DELIVERED", "Entregada"),
                            ("INCIDENT", "Incidente"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guides",
                        to="logistics.courier",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_guide",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guia de envio",
                "db_table": "logistics_shipment_guide",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShipmentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=20)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="logistics.shipmentguide",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de envio",
                "db_table": "logistics_shipment_event",
                "ordering": ["-occurred_at", "-created_at"],
            },
        ),
    ]
