# Generated by Django 5.0.1 on 2026-05-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_shipmentguide_estimated_delivery"),
        ("orders", "0014_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentguide",
            name="tracking_number",
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name="shipmentguide",
            constraint=models.UniqueConstraint(
                fields=("courier", "tracking_number"),
                name="unique_tracking_per_courier",
            ),
        ),
    ]
