# Generated by Django 5.0.1 on 2026-06-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_tracking_number_unique_per_courier"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipmentguide",
            name="tracking_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
