# Generated by Django 5.0.1 on 2026-06-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_shipmentguide_tracking_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="webhook_secret",
            field=models.BinaryField(
                blank=True,
                help_text="Per-courier webhook secret, Fernet-encrypted (LOG-04).",
                null=True,
            ),
        ),
    ]
