# Generated by Django 6.0.5 on 2026-08-07 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0018_rescompany_account_fiscal_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerGln",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "global_location_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Global Location Number (Odoo global_location_number).",
                        max_length=255,
                        verbose_name="GLN",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        help_text="Partner al que pertenece (Odoo _inherit res.partner).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gln",
                        to="base.respartner",
                    ),
                ),
            ],
            options={
                "verbose_name": "GLN del partner",
                "verbose_name_plural": "GLN de partners",
                "db_table": "res_partner_gln",
            },
        ),
    ]
