# Generated by Django 6.0.5 on 2026-08-03 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ORDER_CREATED", "Order creada"),
                            ("ORDER_CANCELLED", "Order cancelada"),
                            ("RETURN_REQUESTED", "Return solicitada"),
                            ("RETURN_RESOLVED", "Return resuelta"),
                            ("STOCK_ADJUSTED_TO_ZERO", "Stock ajustado a cero"),
                            ("RECEIPT_PDF_GENERATED", "Receipt PDF generado"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_addr", models.GenericIPAddressField(blank=True, null=True)),
                ("extra_json", models.JSONField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "observability_business_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="observabili_action_22cc2d_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="observabili_target__559655_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=32)),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(db_index=True, max_length=512)),
                ("view_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "exception_class",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("error_detail", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="requestlog_created_idx")
                ],
            },
        ),
    ]
