# Generated by Django 6.0.5 on 2026-07-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="Company de datos compartidos de plataforma (L0), no un tenant.",
                verbose_name="Company de sistema",
            ),
        ),
    ]
