# Generated by Django 6.0.5 on 2026-07-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_seed_message_subtypes"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="mail_message",
            field=models.ForeignKey(
                blank=True,
                help_text="Mensaje de chatter que origino esta notificacion (familia mail).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbox_notifications",
                to="mail.mailmessage",
            ),
        ),
    ]
