# Generated by Django 6.0.5 on 2026-08-02 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authz", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("version", models.PositiveIntegerField(default=1)),
            ],
            options={
                "verbose_name": "Contenido estatico",
                "db_table": "static_content_page",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("about", "Acerca de nosotros"),
                            ("terms", "Términos y condiciones"),
                            ("privacy", "Política de privacidad"),
                            ("returns", "Política de devoluciones"),
                            ("faq", "Preguntas frecuentes"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Página estática",
                "db_table": "settings_static_page",
            },
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="banners/%Y/%m/", verbose_name="Imagen"
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("HERO", "Hero de portada"),
                            ("PROMO_STRIP", "Franja promocional"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Título"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(max_length=200, verbose_name="Texto alternativo"),
                ),
                (
                    "link_url",
                    models.URLField(blank=True, default="", verbose_name="Enlace"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "db_table": "settings_banner",
                "ordering": ["placement", "order", "id"],
                "indexes": [
                    models.Index(
                        fields=["placement", "is_active", "order"],
                        name="settings_ba_placeme_427603_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.CharField(max_length=200)),
                ("normalized_query", models.CharField(db_index=True, max_length=200)),
                ("results_count", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de historial de busqueda",
                "db_table": "search_history_entry",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaticContentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="website.staticcontent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version de contenido",
                "db_table": "static_content_version",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("content", "version"),
                        name="unique_static_content_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StaticPageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("PUBLISHED", "Publicado"),
                            ("ARCHIVED", "Archivado"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="static_page_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="website.staticpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de página estática",
                "db_table": "settings_static_page_version",
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "version"), name="unique_static_page_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebsiteMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, verbose_name="Menú")),
                ("active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "sequence",
                    models.PositiveIntegerField(default=10, verbose_name="Secuencia"),
                ),
                (
                    "route",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo url. Ruta del router React (p.ej. '/account/orders').",
                        max_length=160,
                        verbose_name="Ruta SPA",
                    ),
                ),
                (
                    "web_icon",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="Icono"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Slug estable del item, para seed idempotente.",
                        max_length=80,
                        unique=True,
                        verbose_name="Clave",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo group_ids. Lleva la capacidad que enforce el endpoint del destino, no la del ítem. Null en secciones.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="website_menu_items",
                        to="authz.capability",
                        verbose_name="Capacidad requerida",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = sección de nivel 0.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="website.websitemenu",
                        verbose_name="Menú padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de menú del sitio",
                "verbose_name_plural": "Entradas de menú del sitio",
                "db_table": "website_menu",
                "ordering": ["sequence", "id"],
                "indexes": [
                    models.Index(
                        fields=["parent", "sequence"],
                        name="website_men_parent__93195a_idx",
                    )
                ],
            },
        ),
    ]
