# Generated by Django 6.0.5 on 2026-08-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "signup_type",
                    models.CharField(
                        choices=[
                            ("signup", "Alta invitada"),
                            ("reset", "Restablecer contraseña"),
                        ],
                        help_text='Odoo signup_type: "signup" (alta invitada) o "reset" (restablecer contraseña).',
                        max_length=16,
                        verbose_name="Tipo de signup",
                    ),
                ),
                (
                    "partner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signup_request",
                        to="base.respartner",
                        verbose_name="Partner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Signup pendiente",
                "verbose_name_plural": "Signups pendientes",
                "db_table": "authz_signup_request",
            },
        ),
    ]
