# Generated by Django 5.0.1 on 2026-05-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reject_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONTENIDO_INAPROPIADO", "Contenido inapropiado"),
                    ("SPAM", "Spam"),
                    ("LANGUAGE_NOT_SUPPORTED", "Idioma no soportado"),
                    ("NO_RELACIONADA", "No relacionada con el producto"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
