# Generated by T-118 — UC-REV-02 FR-REV-02.02: helpful_count + ReviewHelpfulVote
from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_reject_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, db_index=True),
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='helpful_votes',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('review', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='helpful_votes',
                    to='reviews.review',
                )),
            ],
            options={
                'db_table': 'reviews_helpful_vote',
                'verbose_name': 'Voto util',
                'unique_together': {('user', 'review')},
            },
        ),
    ]
