# Generated by Django 5.0.1 on 2026-06-23 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0019_alter_attributevalue_unique_together_and_more"),
        ("orders", "0018_delete_activeorder_delete_cancelledorder_and_more"),
        ("reviews", "0004_add_review_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="reviewhelpfulvote",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("user", "product"), name="unique_review_user_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewhelpfulvote",
            constraint=models.UniqueConstraint(
                fields=("user", "review"), name="unique_helpful_vote_user_review"
            ),
        ),
    ]
