# Generated by Django 6.0.5 on 2026-08-18 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0018_payment_state"),
        ("analytic", "0001_initial"),
        ("product", "0010_producttemplate_lot_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountanalyticapplicability",
            name="account_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo account_prefix. Prefijos de cuenta contable sobre los que aplica esta regla de aplicabilidad.",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticapplicability",
            name="product_categ",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo product_categ_id. Categoría de producto sobre la que aplica esta regla.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytic_applicabilities",
                to="product.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticdistributionmodel",
            name="account_prefix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo account_prefix. Esta distribución analítica aplica a todas las cuentas contables que compartan el prefijo especificado.",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticdistributionmodel",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo product_id (ondelete=cascade). Producto para el que se usa esta distribución.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytic_distribution_models",
                to="product.productproduct",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticdistributionmodel",
            name="product_categ",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo product_categ_id (ondelete=cascade). Categoría de producto que usa la cuenta analítica en el default analítico.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytic_distribution_models",
                to="product.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="code",
            field=models.CharField(
                blank=True, default="", help_text="Odoo code.", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="general_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo general_account_id (ondelete=restrict, compute+store+readonly=False). Se deriva de move_line.account cuando no se fija a mano — ver docstring del módulo.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytic_lines",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="move_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo move_line_id (ondelete=cascade). El apunte contable que generó esta línea analítica.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytic_lines",
                to="account.accountmoveline",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo product_id.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytic_lines",
                to="product.productproduct",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="ref",
            field=models.CharField(
                blank=True, default="", help_text="Odoo ref.", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="accountanalyticapplicability",
            name="business_domain",
            field=models.CharField(
                choices=[
                    ("general", "Miscelánea"),
                    ("invoice", "Factura de cliente"),
                    ("bill", "Factura de proveedor"),
                ],
                help_text="Odoo business_domain; único valor en la referencia base (otros addons de Odoo extienden la selección — no aplica aquí).",
                max_length=32,
                verbose_name="Dominio de negocio",
            ),
        ),
        migrations.AlterField(
            model_name="accountanalyticline",
            name="category",
            field=models.CharField(
                choices=[
                    ("other", "Otro"),
                    ("invoice", "Factura de cliente"),
                    ("vendor_bill", "Factura de proveedor"),
                ],
                default="other",
                max_length=16,
                verbose_name="Categoría",
            ),
        ),
    ]
