# Generated by Django 6.0.5 on 2026-08-19 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytic", "0002_accountanalyticapplicability_account_prefix_and_more"),
        ("hr", "0009_hremployeepublic"),
        ("project", "0002_project_allocated_hours_project_allow_timesheets"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountanalyticline",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo department_id (compute, store=True) — sincronizado desde employee.department en pre_save.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheets",
                to="hr.hrdepartment",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo employee_id. Empleado que registra la hora — define un hourly_cost en el empleado para valorizarla.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheets",
                to="hr.hremployee",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo manager_id (related=employee_id.parent_id, store=True) — sincronizado en pre_save.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_timesheets",
                to="hr.hremployee",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo project_id. Proyecto sobre el que se registra la hora — sincronizado desde task en pre_save cuando task está presente.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheets",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="task",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo task_id. Tarea sobre la que se registra la hora.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheets",
                to="project.projecttask",
            ),
        ),
        migrations.AlterField(
            model_name="accountanalyticapplicability",
            name="business_domain",
            field=models.CharField(
                choices=[
                    ("general", "Miscelánea"),
                    ("invoice", "Factura de cliente"),
                    ("bill", "Factura de proveedor"),
                    ("timesheet", "Hoja de horas"),
                ],
                help_text="Odoo business_domain; único valor en la referencia base (otros addons de Odoo extienden la selección — no aplica aquí).",
                max_length=32,
                verbose_name="Dominio de negocio",
            ),
        ),
    ]
