# Generated by Django 6.0.5 on 2026-08-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_accountjournal_is_peppol_journal_and_more"),
        ("analytic", "0003_accountanalyticline_department_and_more"),
        ("sale", "0006_saleorderline_has_displayed_warning_upsell"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountanalyticline",
            name="is_so_line_edited",
            field=models.BooleanField(
                default=False,
                help_text="Odoo is_so_line_edited.",
                verbose_name="Línea de pedido fijada a mano",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo order_id (related=so_line.order_id, store, index). Escribible directo: so_line no existe en este árbol — ver el bloqueo raíz del docstring del módulo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheet_ids",
                to="sale.saleorder",
                verbose_name="Pedido de venta",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="timesheet_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo timesheet_invoice_id (readonly, copy=False, index=btree_not_null). Factura creada a partir de la hoja de horas. El related_name es el timesheet_ids de account.move (odoo19c: account_move.py:185).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheet_ids",
                to="account.accountmove",
                verbose_name="Factura",
            ),
        ),
        migrations.AddField(
            model_name="accountanalyticline",
            name="timesheet_invoice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("billable_time", "Billed on Timesheets"),
                    ("billable_fixed", "Billed at a Fixed price"),
                    ("billable_milestones", "Billed on Milestones"),
                    ("billable_manual", "Billed Manually"),
                    ("non_billable", "Non-Billable"),
                    ("timesheet_revenues", "Timesheet Revenues"),
                    ("service_revenues", "Service Revenues"),
                    ("other_revenues", "Other revenues"),
                    ("other_costs", "Other costs"),
                ],
                default=None,
                help_text="Odoo timesheet_invoice_type (compute, store, readonly). Derivación parcial declarada — ver timesheet_invoice_type_for.",
                max_length=20,
                null=True,
                verbose_name="Tipo de facturación",
            ),
        ),
    ]
