# Generated by Django 6.0.5 on 2026-08-19 04:08

import addons.base_automation.models.base_automation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0028_iractionsreport_is_invoice_report_and_more"),
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseAutomation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Odoo name (tracking=True en la referencia: sin chatter genérico portado, el seguimiento de cambios no aplica).",
                        max_length=255,
                        verbose_name="Nombre de la regla",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Sincronizado desde model_id.model en save() (Odoo model_name, related+inverse).",
                        max_length=255,
                        verbose_name="Nombre técnico del modelo",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Calculado en save() cuando trigger=on_webhook (Odoo url, compute, no store).",
                        max_length=255,
                        verbose_name="URL del webhook",
                    ),
                ),
                (
                    "webhook_uuid",
                    models.CharField(
                        default=addons.base_automation.models.base_automation.default_webhook_uuid,
                        max_length=64,
                        verbose_name="UUID del webhook",
                    ),
                ),
                (
                    "record_getter",
                    models.CharField(
                        blank=True,
                        default="model.env[payload.get('_model')].browse(int(payload.get('_id')))",
                        help_text="Código evaluado con safe_eval para ubicar el registro sobre el que corre el webhook (Odoo record_getter).",
                        max_length=1024,
                        verbose_name="Localizador de registro",
                    ),
                ),
                (
                    "log_webhook_calls",
                    models.BooleanField(
                        default=False, verbose_name="Registrar llamadas"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "trigger",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("on_stage_set", "Stage is set to"),
                            ("on_user_set", "User is set"),
                            ("on_tag_set", "Tag is added"),
                            ("on_state_set", "State is set to"),
                            ("on_priority_set", "Priority is set to"),
                            ("on_archive", "On archived"),
                            ("on_unarchive", "On unarchived"),
                            ("on_create", "On create"),
                            ("on_create_or_write", "On create and edit"),
                            ("on_write", "On update"),
                            ("on_unlink", "On deletion"),
                            ("on_change", "On UI change"),
                            ("on_time", "Based on date field"),
                            ("on_time_created", "After creation"),
                            ("on_time_updated", "After last update"),
                            ("on_message_received", "On incoming message"),
                            ("on_message_sent", "On outgoing message"),
                            ("on_webhook", "On webhook"),
                        ],
                        default="",
                        max_length=32,
                        verbose_name="Disparador",
                    ),
                ),
                (
                    "trg_field_ref_model_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Modelo de referencia",
                    ),
                ),
                (
                    "trg_field_ref",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Referencia disparadora"
                    ),
                ),
                (
                    "trg_date_range",
                    models.IntegerField(blank=True, null=True, verbose_name="Retraso"),
                ),
                (
                    "trg_date_range_mode",
                    models.CharField(
                        blank=True,
                        choices=[("after", "After"), ("before", "Before")],
                        default="",
                        max_length=8,
                        verbose_name="Modo del retraso",
                    ),
                ),
                (
                    "trg_date_range_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "Minutes"),
                            ("hour", "Hours"),
                            ("day", "Days"),
                            ("month", "Months"),
                        ],
                        default="",
                        max_length=8,
                        verbose_name="Unidad del retraso",
                    ),
                ),
                (
                    "filter_pre_domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Debe cumplirse ANTES de la escritura (Odoo filter_pre_domain).",
                        max_length=2048,
                        verbose_name="Dominio antes",
                    ),
                ),
                (
                    "previous_domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="No-store en la referencia (default=filter_domain); aquí columna real por el mismo motivo que el resto de la cadena de cómputo (sin motor @api.depends genérico).",
                        max_length=2048,
                        verbose_name="Dominio previo",
                    ),
                ),
                (
                    "filter_domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Debe cumplirse para ejecutar la regla (Odoo filter_domain).",
                        max_length=2048,
                        verbose_name="Dominio de aplicación",
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última corrida"
                    ),
                ),
                (
                    "model_id",
                    models.ForeignKey(
                        help_text="Modelo objetivo (Odoo model_id, domain abstract=False).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_automations",
                        to="base.irmodel",
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "on_change_field_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Poblado por dominio; dispatch bloqueado (ver docstring).",
                        related_name="+",
                        to="base.irmodelfields",
                        verbose_name="Campos disparadores de onchange",
                    ),
                ),
                (
                    "trg_date_calendar",
                    models.ForeignKey(
                        blank=True,
                        help_text="GAP — ResourceCalendar.plan_days no está portado; ver docstring del módulo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_automations",
                        to="resource.resourcecalendar",
                        verbose_name="Calendario laboral",
                    ),
                ),
                (
                    "trg_date_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuándo evaluar la condición (Odoo trg_date_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="base.irmodelfields",
                        verbose_name="Campo de fecha disparador",
                    ),
                ),
                (
                    "trg_selection_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="base_automations",
                        to="base.irmodelfieldsselection",
                        verbose_name="Campo de selección disparador",
                    ),
                ),
                (
                    "trigger_field_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Si vacío, se vigilan todos los campos (Odoo trigger_field_ids).",
                        related_name="automations_watching",
                        to="base.irmodelfields",
                        verbose_name="Campos disparadores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de automatización",
                "verbose_name_plural": "Reglas de automatización",
                "db_table": "base_automation",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="BaseAutomationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="base_automation_link",
                        to="base.iractionsserver",
                        verbose_name="Acción servidor",
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_links",
                        to="base_automation.baseautomation",
                        verbose_name="Regla de automatización",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liga acción-automatización",
                "verbose_name_plural": "Ligas acción-automatización",
                "db_table": "base_automation_action",
            },
        ),
    ]
