# Generated by Django 6.0.5 on 2026-08-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0061_serveractionhistorywizard_and_more"),
        ("base_automation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseautomation",
            name="model_id",
            field=models.ForeignKey(
                db_column="model_id",
                help_text="Modelo objetivo (Odoo model_id, domain abstract=False).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_automations",
                to="base.irmodel",
                verbose_name="Modelo",
            ),
        ),
        migrations.AlterField(
            model_name="baseautomation",
            name="trg_date_id",
            field=models.ForeignKey(
                blank=True,
                db_column="trg_date_id",
                help_text="Cuándo evaluar la condición (Odoo trg_date_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="base.irmodelfields",
                verbose_name="Campo de fecha disparador",
            ),
        ),
    ]
