# Generated by Django 6.0.5 on 2026-08-28 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_automation", "0002_alter_baseautomation_model_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseautomation",
            name="trg_date_calendar",
            field=models.ForeignKey(
                blank=True,
                db_column="trg_date_calendar_id",
                help_text="GAP — ResourceCalendar.plan_days no está portado; ver docstring del módulo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="base_automations",
                to="resource.resourcecalendar",
                verbose_name="Calendario laboral",
            ),
        ),
        migrations.RenameField(
            model_name="baseautomation",
            old_name="trg_date_calendar",
            new_name="trg_date_calendar_id",
        ),
        migrations.AlterField(
            model_name="baseautomation",
            name="trg_selection_field",
            field=models.ForeignKey(
                blank=True,
                db_column="trg_selection_field_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="base_automations",
                to="base.irmodelfieldsselection",
                verbose_name="Campo de selección disparador",
            ),
        ),
        migrations.RenameField(
            model_name="baseautomation",
            old_name="trg_selection_field",
            new_name="trg_selection_field_id",
        ),
    ]
