# Generated by Django 6.0.5 on 2026-07-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authz", "0004_rolecapability_alter_role_capabilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "En prueba"),
                            ("active", "Activo"),
                            ("suspended", "Suspendido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="trial",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Correo de facturación",
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Razón social",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="RFC / Tax ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenancy_tenant",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="TenantModuleSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "En prueba"),
                            ("active", "Activo"),
                            ("suspended", "Suspendido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="active",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Inicio"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expira"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="authz.module",
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="tenancy.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción de módulo",
                "verbose_name_plural": "Suscripciones de módulo",
                "db_table": "tenancy_module_subscription",
                "ordering": ["tenant__code", "module__code"],
                "unique_together": {("tenant", "module")},
            },
        ),
    ]
