# Generated by Django 6.0.5 on 2026-08-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0019_respartnerbank_include_reference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResUsersSettingsEmbeddedAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "res_model",
                    models.CharField(
                        help_text="Modelo donde se embebe la acción (Odoo res_model, requerido).",
                        max_length=120,
                        verbose_name="Modelo del registro",
                    ),
                ),
                (
                    "res_id",
                    models.IntegerField(
                        default=0,
                        help_text="ID del registro donde se embebe; 0 = ningún registro particular (Odoo res_id).",
                        verbose_name="ID del registro",
                    ),
                ),
                (
                    "embedded_actions_order",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='IDs separados por coma, en el orden elegido por el usuario; "false" marca un hueco (Odoo embedded_actions_order).',
                        max_length=255,
                        verbose_name="Orden de las acciones embebidas",
                    ),
                ),
                (
                    "embedded_actions_visibility",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IDs separados por coma de las acciones visibles (Odoo embedded_actions_visibility).",
                        max_length=255,
                        verbose_name="Visibilidad de las acciones embebidas",
                    ),
                ),
                (
                    "embedded_visibility",
                    models.BooleanField(
                        default=False,
                        help_text="Si la barra superior de acciones embebidas está visible (Odoo embedded_visibility).",
                        verbose_name="Barra superior visible",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        help_text="Acción embebida a la que aplica el ajuste (Odoo action_id, requerido, ondelete=cascade).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedded_user_settings",
                        to="base.iractionsactwindow",
                        verbose_name="Acción",
                    ),
                ),
                (
                    "user_setting",
                    models.ForeignKey(
                        help_text="Preferencias del usuario dueño de este ajuste (Odoo user_setting_id, requerido, ondelete=cascade).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedded_actions_config_ids",
                        to="base.resuserssettings",
                        verbose_name="Preferencias del usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de acción embebida por usuario",
                "verbose_name_plural": "Ajustes de acciones embebidas por usuario",
                "db_table": "res_users_settings_embedded_action",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_setting", "action", "res_id"),
                        name="res_users_settings_embedded_action_unique",
                    )
                ],
            },
        ),
    ]
