# Generated by Django 6.0.5 on 2026-07-18 23:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0004_rescurrency_rescountry_rescountrystate"),
        ("company", "0008_alter_company_tax_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código de cuenta (Odoo account.account.code).",
                        max_length=64,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la cuenta (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset_receivable", "Por cobrar"),
                            ("asset_cash", "Banco y efectivo"),
                            ("asset_current", "Activo circulante"),
                            ("asset_non_current", "Activo no circulante"),
                            ("asset_prepayments", "Pagos anticipados"),
                            ("asset_fixed", "Activo fijo"),
                            ("liability_payable", "Por pagar"),
                            ("liability_credit_card", "Tarjeta de crédito"),
                            ("liability_current", "Pasivo circulante"),
                            ("liability_non_current", "Pasivo no circulante"),
                            ("equity", "Capital"),
                            ("equity_unaffected", "Resultado del ejercicio"),
                            ("income", "Ingreso"),
                            ("income_other", "Otros ingresos"),
                            ("expense", "Gasto"),
                            ("expense_depreciation", "Depreciación"),
                            ("expense_direct_cost", "Costo de ventas"),
                            ("expense_other", "Otros gastos"),
                            ("off_balance", "Fuera de balance"),
                        ],
                        help_text="Tipo de cuenta (Odoo account_type, requerido).",
                        max_length=32,
                    ),
                ),
                (
                    "internal_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("equity", "Capital"),
                            ("asset", "Activo"),
                            ("liability", "Pasivo"),
                            ("income", "Ingreso"),
                            ("expense", "Gasto"),
                            ("off", "Fuera de balance"),
                        ],
                        default="",
                        help_text="Grupo interno derivado de account_type (Odoo internal_group).",
                        max_length=16,
                    ),
                ),
                (
                    "reconcile",
                    models.BooleanField(
                        default=False,
                        help_text="Permite conciliación (Odoo reconcile).",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False, help_text="Cuenta obsoleta (Odoo deprecated)."
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Notas internas (Odoo note)."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id / company_ids).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="company.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda de la cuenta (Odoo currency_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts",
                        to="base.rescurrency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta contable",
                "verbose_name_plural": "Cuentas contables",
                "db_table": "account_account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del diario (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código corto del diario (Odoo code).", max_length=12
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sale", "Ventas"),
                            ("purchase", "Compras"),
                            ("cash", "Efectivo"),
                            ("bank", "Banco"),
                            ("credit", "Tarjeta de crédito"),
                            ("general", "Varios"),
                        ],
                        help_text="Tipo de diario (Odoo type, requerido).",
                        max_length=12,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Diario activo (Odoo active)."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="company.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda del diario (Odoo currency_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journals",
                        to="base.rescurrency",
                    ),
                ),
                (
                    "default_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta por defecto (Odoo default_account_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_journals",
                        to="account.accountaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diario contable",
                "verbose_name_plural": "Diarios contables",
                "db_table": "account_journal",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AccountMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="/",
                        help_text='Número del asiento (Odoo name; "/" hasta postear).',
                        max_length=255,
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia (Odoo ref).",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Fecha contable (Odoo date, requerido)."
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("posted", "Publicado"),
                            ("cancel", "Cancelado"),
                        ],
                        default="draft",
                        help_text="Estado (Odoo state).",
                        max_length=8,
                    ),
                ),
                (
                    "move_type",
                    models.CharField(
                        choices=[
                            ("entry", "Asiento contable"),
                            ("out_invoice", "Factura de cliente"),
                            ("out_refund", "Nota de crédito de cliente"),
                            ("in_invoice", "Factura de proveedor"),
                            ("in_refund", "Nota de crédito de proveedor"),
                            ("out_receipt", "Recibo de venta"),
                            ("in_receipt", "Recibo de compra"),
                        ],
                        default="entry",
                        help_text="Tipo de asiento (Odoo move_type).",
                        max_length=16,
                    ),
                ),
                (
                    "amount_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total del asiento (Odoo amount_total, computado de líneas).",
                        max_digits=16,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="company.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda (Odoo currency_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moves",
                        to="base.rescurrency",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        help_text="Diario (Odoo journal_id, requerido).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves",
                        to="account.accountjournal",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contacto (Odoo partner_id → res.partner ≡ party).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_moves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asiento contable",
                "verbose_name_plural": "Asientos contables",
                "db_table": "account_move",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AccountMoveLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta del apunte (Odoo name).",
                        max_length=255,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Debe (Odoo debit).",
                        max_digits=16,
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Haber (Odoo credit).",
                        max_digits=16,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Saldo = debe - haber (Odoo balance, computado).",
                        max_digits=16,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("product", "Producto"),
                            ("tax", "Impuesto"),
                            ("cogs", "Costo de venta"),
                            ("payment_term", "Plazo de pago"),
                            ("line_section", "Sección"),
                            ("line_note", "Nota"),
                            ("rounding", "Redondeo"),
                        ],
                        default="",
                        help_text="Tipo de línea (Odoo display_type).",
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0"),
                        help_text="Cantidad (Odoo quantity).",
                        max_digits=16,
                    ),
                ),
                (
                    "price_unit",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0"),
                        help_text="Precio unitario (Odoo price_unit).",
                        max_digits=16,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta contable (Odoo account_id).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="move_lines",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda (Odoo currency_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="move_lines",
                        to="base.rescurrency",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        help_text="Asiento al que pertenece (Odoo move_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_ids",
                        to="account.accountmove",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apunte contable",
                "verbose_name_plural": "Apuntes contables",
                "db_table": "account_move_line",
                "ordering": ["move", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Importe del pago (Odoo amount).",
                        max_digits=16,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("outbound", "Enviar"), ("inbound", "Recibir")],
                        default="inbound",
                        help_text="Tipo de pago (Odoo payment_type, requerido).",
                        max_length=8,
                    ),
                ),
                (
                    "partner_type",
                    models.CharField(
                        choices=[("customer", "Cliente"), ("supplier", "Proveedor")],
                        default="customer",
                        help_text="Tipo de contraparte (Odoo partner_type, requerido).",
                        max_length=8,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("in_process", "En proceso"),
                            ("paid", "Pagado"),
                            ("canceled", "Cancelado"),
                            ("rejected", "Rechazado"),
                        ],
                        default="draft",
                        help_text="Estado del pago (Odoo state).",
                        max_length=12,
                    ),
                ),
                (
                    "memo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Concepto (Odoo memo).",
                        max_length=255,
                    ),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(
                        default=False, help_text="Pago conciliado (Odoo is_reconciled)."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="company.company",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda (Odoo currency_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="base.rescurrency",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        help_text="Diario (Odoo journal_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="account.accountjournal",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contacto (Odoo partner_id → party).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "db_table": "account_payment",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AccountTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del impuesto (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0"),
                        help_text="Monto/porcentaje del impuesto (Odoo amount).",
                        max_digits=16,
                    ),
                ),
                (
                    "amount_type",
                    models.CharField(
                        choices=[
                            ("group", "Grupo de impuestos"),
                            ("fixed", "Fijo"),
                            ("percent", "Porcentaje"),
                            ("division", "Porcentaje impuesto incluido"),
                        ],
                        default="percent",
                        help_text="Forma de cómputo (Odoo amount_type, requerido).",
                        max_length=12,
                    ),
                ),
                (
                    "type_tax_use",
                    models.CharField(
                        choices=[
                            ("sale", "Ventas"),
                            ("purchase", "Compras"),
                            ("none", "Ninguno"),
                        ],
                        default="sale",
                        help_text="Uso del impuesto (Odoo type_tax_use, requerido).",
                        max_length=12,
                    ),
                ),
                (
                    "price_include",
                    models.BooleanField(
                        default=False,
                        help_text="Precio con impuesto incluido (Odoo price_include).",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Impuesto activo (Odoo active)."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
                "db_table": "account_tax",
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="accountaccount",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_account_code_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountjournal",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_journal_code_company"
            ),
        ),
    ]
