# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountaccount",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Odoo company_id / company_ids).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="company.company",
            ),
        ),
    ]
