# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0002_initial"),
        ("base", "0001_initial"),
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountaccount",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Moneda de la cuenta (Odoo currency_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="base.rescurrency",
            ),
        ),
        migrations.AddField(
            model_name="accountjournal",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Odoo company_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journals",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="accountjournal",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Moneda del diario (Odoo currency_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="journals",
                to="base.rescurrency",
            ),
        ),
        migrations.AddField(
            model_name="accountjournal",
            name="default_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta por defecto (Odoo default_account_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_journals",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="accountmove",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Odoo company_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="moves",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="accountmove",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Moneda (Odoo currency_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moves",
                to="base.rescurrency",
            ),
        ),
        migrations.AddField(
            model_name="accountmove",
            name="journal",
            field=models.ForeignKey(
                help_text="Diario (Odoo journal_id, requerido).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moves",
                to="account.accountjournal",
            ),
        ),
    ]
