# Generated by Django 6.0.5 on 2026-08-06 06:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_accountfullreconcile_accountincoterms_and_more"),
        ("base", "0007_alter_iractionsreport_report_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del método (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificación interna (Odoo code, requerido).",
                        max_length=64,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("inbound", "Entrante"), ("outbound", "Saliente")],
                        help_text="Tipo de pago (Odoo payment_type, requerido).",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "Método de pago",
                "verbose_name_plural": "Métodos de pago",
                "db_table": "account_payment_method",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "payment_type"),
                        name="unique_payment_method_code_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AccountPaymentMethodLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre visible (Odoo name, computado del método si vacío).",
                        max_length=255,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de presentación (Odoo sequence)."
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Diario donde queda habilitado (Odoo journal_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_method_lines",
                        to="account.accountjournal",
                    ),
                ),
                (
                    "payment_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta de contrapartida (Odoo payment_account_id).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_method_lines",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        help_text="Método de pago (Odoo payment_method_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="method_line_ids",
                        to="account.accountpaymentmethod",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de método de pago",
                "verbose_name_plural": "Líneas de método de pago",
                "db_table": "account_payment_method_line",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountPaymentTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del plazo de pago (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Si es falso, oculta el plazo sin borrarlo (Odoo active).",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción para la factura (Odoo note).",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de presentación (Odoo sequence)."
                    ),
                ),
                (
                    "display_on_invoice",
                    models.BooleanField(
                        default=True,
                        help_text="Muestra las fechas de las cuotas en la factura (Odoo display_on_invoice).",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.0"),
                        help_text="% de descuento por pronto pago (Odoo discount_percentage).",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_days",
                    models.IntegerField(
                        default=10,
                        help_text="Días antes de que expire el pronto pago (Odoo discount_days).",
                    ),
                ),
                (
                    "early_pay_discount_computation",
                    models.CharField(
                        choices=[
                            ("included", "Al pago anticipado"),
                            ("excluded", "Nunca"),
                            ("mixed", "Siempre (sobre la factura)"),
                        ],
                        default="included",
                        help_text="Tratamiento fiscal del descuento (Odoo early_pay_discount_computation). Valor por defecto fijo — la derivación BE/NL por país de la compañía no está portada (ver docstring del módulo).",
                        max_length=8,
                    ),
                ),
                (
                    "early_discount",
                    models.BooleanField(
                        default=False,
                        help_text="Activa el pronto pago (Odoo early_discount).",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa (Odoo company_id; sin compañía = plazo global).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_terms",
                        to="base.rescompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plazo de pago",
                "verbose_name_plural": "Plazos de pago",
                "db_table": "account_payment_term",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountPaymentTermLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        choices=[("percent", "Porcentaje"), ("fixed", "Fijo")],
                        default="percent",
                        help_text="Tipo de valuación de la cuota (Odoo value, requerido).",
                        max_length=8,
                    ),
                ),
                (
                    "value_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.0"),
                        help_text="Importe/porcentaje de la cuota (Odoo value_amount).",
                        max_digits=7,
                    ),
                ),
                (
                    "delay_type",
                    models.CharField(
                        choices=[
                            ("days_after", "Días después de la fecha de factura"),
                            ("days_after_end_of_month", "Días después de fin de mes"),
                            (
                                "days_after_end_of_next_month",
                                "Días después de fin del mes siguiente",
                            ),
                            ("days_end_of_month_on_the", "Fin de mes en el día"),
                        ],
                        default="days_after",
                        help_text="Base del cómputo de la fecha de vencimiento (Odoo delay_type).",
                        max_length=32,
                    ),
                ),
                (
                    "days_next_month",
                    models.CharField(
                        blank=True,
                        default="10",
                        help_text="Día del mes siguiente (Odoo days_next_month, sólo con delay_type=days_end_of_month_on_the).",
                        max_length=2,
                    ),
                ),
                (
                    "nb_days",
                    models.IntegerField(
                        default=0, help_text="Días de la cuota (Odoo nb_days)."
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        help_text="Plazo de pago al que pertenece (Odoo payment_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_ids",
                        to="account.accountpaymentterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota de plazo de pago",
                "verbose_name_plural": "Cuotas de plazo de pago",
                "db_table": "account_payment_term_line",
                "ordering": ["id"],
            },
        ),
    ]
