# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_initial"),
        ("base", "0001_initial"),
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmove",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Contacto (Odoo partner_id → res.partner ≡ party).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_moves",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accountmoveline",
            name="account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta contable (Odoo account_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="move_lines",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="accountmoveline",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Moneda (Odoo currency_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="move_lines",
                to="base.rescurrency",
            ),
        ),
        migrations.AddField(
            model_name="accountmoveline",
            name="move",
            field=models.ForeignKey(
                help_text="Asiento al que pertenece (Odoo move_id, requerido).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_ids",
                to="account.accountmove",
            ),
        ),
        migrations.AddField(
            model_name="accountpayment",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Odoo company_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="company.company",
            ),
        ),
        migrations.AddField(
            model_name="accountpayment",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Moneda (Odoo currency_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="base.rescurrency",
            ),
        ),
        migrations.AddField(
            model_name="accountpayment",
            name="journal",
            field=models.ForeignKey(
                help_text="Diario (Odoo journal_id).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="account.accountjournal",
            ),
        ),
        migrations.AddField(
            model_name="accountpayment",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                help_text="Contacto (Odoo partner_id → party).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="account_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accounttax",
            name="company",
            field=models.ForeignKey(
                help_text="Empresa (Odoo company_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxes",
                to="company.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountaccount",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_account_code_company"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountjournal",
            constraint=models.UniqueConstraint(
                fields=("company", "code"), name="unique_journal_code_company"
            ),
        ),
    ]
