# Generated by Django 6.0.5 on 2026-08-06 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_accountpaymentmethod_accountpaymentmethodline_and_more"),
        ("base", "0007_alter_iractionsreport_report_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountbankstatementline",
            options={
                "ordering": ["-internal_index"],
                "verbose_name": "Línea de estado de cuenta bancario",
                "verbose_name_plural": "Líneas de estado de cuenta bancario",
            },
        ),
        migrations.AddField(
            model_name="accountbankstatementline",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa — denormalizada de move.company (Odoo company_id, related=move_id.company_id, store=True). Se sincroniza en save(); no se edita directo, se cambia linea.move.company.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_statement_lines",
                to="base.rescompany",
            ),
        ),
        migrations.AddField(
            model_name="accountbankstatementline",
            name="internal_index",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Índice de orden: fecha + secuencia invertida + id, zero-padded (Odoo internal_index, compute=_compute_internal_index, store=True). Se recalcula en save() — ver docstring del módulo.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="accountbankstatementline",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                help_text="Diario — denormalizado de move.journal (Odoo journal_id, related=move_id.journal_id, store=True, index=False # covered by _main_idx). Se sincroniza en save(); no se edita directo, se cambia linea.move.journal.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bank_statement_lines",
                to="account.accountjournal",
            ),
        ),
        migrations.AlterField(
            model_name="accountbankstatement",
            name="first_line_index",
            field=models.CharField(
                blank=True,
                default="",
                help_text="internal_index más chico entre las líneas del estado (Odoo first_line_index, computado — _compute_first_line_index, ver docstring del módulo).",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="accountbankstatementline",
            name="move",
            field=models.ForeignKey(
                help_text="Asiento contable del que esta línea es la extensión bancaria (Odoo move_id, _inherits). currency/date/state se delegan a él; journal/company se sincronizan en save() (ver docstring del módulo).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_statement_line",
                to="account.accountmove",
            ),
        ),
        migrations.AlterField(
            model_name="accountbankstatementline",
            name="sequence",
            field=models.IntegerField(
                default=1,
                help_text="Orden dentro del estado de cuenta (Odoo sequence; invertido dentro de internal_index, ver docstring del módulo).",
            ),
        ),
        migrations.AddIndex(
            model_name="accountbankstatement",
            index=models.Index(
                fields=["journal", "first_line_index"],
                name="acc_bank_stmt_first_line_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountbankstatementline",
            index=models.Index(
                fields=["journal", "company", "internal_index"],
                name="acc_bank_stmt_line_main_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountbankstatementline",
            index=models.Index(
                condition=models.Q(("is_reconciled", False)),
                fields=["journal", "company", "internal_index"],
                name="acc_bank_stmt_line_unrecon_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountbankstatementline",
            index=models.Index(
                condition=models.Q(("statement__isnull", True)),
                fields=["journal", "company", "internal_index"],
                name="acc_bank_stmt_line_orphan_idx",
            ),
        ),
    ]
