# Generated by Django 6.0.5 on 2026-08-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_accountbankstatementline_options_and_more"),
        ("base", "0009_alter_ircron_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountReportExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Etiqueta que empareja la expresión con una columna del reporte (Odoo label, requerido).",
                        max_length=64,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[
                            ("domain", "Dominio Odoo"),
                            ("tax_tags", "Etiquetas de impuesto"),
                            ("aggregation", "Agregación de otras fórmulas"),
                            ("account_codes", "Prefijo de códigos de cuenta"),
                            ("external", "Valor externo"),
                            ("custom", "Función Python a medida"),
                        ],
                        help_text="Motor que resuelve la fórmula. Se declaran los seis de la referencia aunque el evaluador aún no exista — recortar el enum haría que la declaración mintiera (Odoo engine).",
                        max_length=16,
                    ),
                ),
                (
                    "formula",
                    models.CharField(
                        help_text="Fórmula, interpretada según engine (Odoo formula, requerido).",
                        max_length=1024,
                    ),
                ),
                (
                    "subformula",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Modificador de la fórmula, p. ej. el signo o el ámbito (Odoo subformula).",
                        max_length=1024,
                    ),
                ),
                (
                    "date_scope",
                    models.CharField(
                        choices=[
                            ("from_beginning", "Desde el inicio absoluto"),
                            ("from_fiscalyear", "Desde el inicio del ejercicio fiscal"),
                            (
                                "to_beginning_of_fiscalyear",
                                "Al inicio del ejercicio fiscal",
                            ),
                            ("to_beginning_of_period", "Al inicio del periodo"),
                            ("strict_range", "Estrictamente en las fechas dadas"),
                            (
                                "previous_return_period",
                                "Del periodo de declaración anterior",
                            ),
                        ],
                        default="strict_range",
                        help_text="Ventana temporal sobre la que se evalúa (Odoo date_scope).",
                        max_length=32,
                    ),
                ),
                (
                    "figure_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monetary", "Monetario"),
                            ("percentage", "Porcentaje"),
                            ("integer", "Entero"),
                            ("float", "Decimal"),
                            ("date", "Fecha"),
                            ("datetime", "Fecha y hora"),
                            ("boolean", "Booleano"),
                            ("string", "Texto"),
                        ],
                        default="",
                        help_text="Cómo se presenta el resultado (Odoo figure_type).",
                        max_length=12,
                    ),
                ),
                (
                    "green_on_positive",
                    models.BooleanField(
                        default=True,
                        help_text="Un crecimiento positivo se pinta en verde; falso invierte el criterio, p. ej. en gastos (Odoo green_on_positive).",
                    ),
                ),
                (
                    "blank_if_zero",
                    models.BooleanField(
                        default=False,
                        help_text="Deja la celda vacía en vez de mostrar 0 (Odoo blank_if_zero).",
                    ),
                ),
                (
                    "auditable",
                    models.BooleanField(
                        default=False,
                        help_text="El valor se puede auditar hasta sus apuntes de origen (Odoo auditable).",
                    ),
                ),
                (
                    "carryover_target",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Destino del arrastre entre periodos, en la forma codigo_linea.etiqueta (Odoo carryover_target).",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "account_report_expression",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AccountReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del reporte (Odoo name, requerido, traducible).",
                        max_length=255,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0, help_text="Orden de presentación (Odoo sequence)."
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Reporte disponible; desactivar lo archiva sin borrarlo (Odoo active).",
                    ),
                ),
                (
                    "use_sections",
                    models.BooleanField(
                        default=False,
                        help_text="Reporte compuesto por secciones navegables e imprimibles a la vez (Odoo use_sections).",
                    ),
                ),
                (
                    "chart_template",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Plan de cuentas al que aplica. Texto libre, no enum: en la referencia el catálogo lo construye account.chart.template en tiempo de ejecución (Odoo chart_template; ver divergencia 2).",
                        max_length=64,
                    ),
                ),
                (
                    "only_tax_exigible",
                    models.BooleanField(
                        default=False,
                        help_text="Sólo considera apuntes con impuesto exigible (Odoo only_tax_exigible).",
                    ),
                ),
                (
                    "availability_condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("country", "Coincide el país"),
                            ("coa", "Coincide el plan de cuentas"),
                            ("always", "Siempre"),
                        ],
                        default="",
                        help_text="Cuándo se ofrece el reporte al usuario (Odoo availability_condition).",
                        max_length=8,
                    ),
                ),
                (
                    "load_more_limit",
                    models.IntegerField(
                        default=0,
                        help_text='Filas por página antes de "cargar más"; 0 = sin límite (Odoo load_more_limit).',
                    ),
                ),
                (
                    "search_bar",
                    models.BooleanField(
                        default=False,
                        help_text="Muestra barra de búsqueda sobre el reporte (Odoo search_bar).",
                    ),
                ),
                (
                    "prefix_groups_threshold",
                    models.IntegerField(
                        default=4000,
                        help_text="Número de líneas a partir del cual se agrupa por prefijo de código de cuenta (Odoo prefix_groups_threshold).",
                    ),
                ),
                (
                    "integer_rounding",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HALF-UP", "Al más cercano"),
                            ("UP", "Hacia arriba"),
                            ("DOWN", "Hacia abajo"),
                        ],
                        default="",
                        help_text="Redondeo a entero al presentar importes (Odoo integer_rounding).",
                        max_length=8,
                    ),
                ),
                (
                    "allow_foreign_vat",
                    models.BooleanField(
                        default=False,
                        help_text="Admite posiciones fiscales con IVA extranjero (Odoo allow_foreign_vat).",
                    ),
                ),
                (
                    "default_opening_date_filter",
                    models.CharField(
                        choices=[
                            ("this_year", "Este año"),
                            ("this_quarter", "Este trimestre"),
                            ("this_month", "Este mes"),
                            ("today", "Hoy"),
                            ("previous_month", "Mes anterior"),
                            ("previous_quarter", "Trimestre anterior"),
                            ("previous_year", "Año anterior"),
                            ("this_return_period", "Este periodo de declaración"),
                            (
                                "previous_return_period",
                                "Periodo de declaración anterior",
                            ),
                        ],
                        default="previous_month",
                        help_text="Periodo preseleccionado al abrir el reporte (Odoo default_opening_date_filter).",
                        max_length=24,
                    ),
                ),
                (
                    "currency_translation",
                    models.CharField(
                        choices=[
                            (
                                "current",
                                "Tipo de cambio más reciente a la fecha del reporte",
                            ),
                            ("cta", "Usar CTA"),
                        ],
                        default="cta",
                        help_text="Cómo se convierten importes en otra divisa (Odoo currency_translation).",
                        max_length=8,
                    ),
                ),
                (
                    "filter_multi_company",
                    models.CharField(
                        choices=[
                            ("selector", "Selector de empresa"),
                            ("tax_units", "Unidades fiscales"),
                        ],
                        default="selector",
                        help_text="Cómo se eligen las empresas incluidas (Odoo filter_multi_company).",
                        max_length=16,
                    ),
                ),
                (
                    "filter_date_range",
                    models.BooleanField(
                        default=True,
                        help_text="Ofrece rango de fechas (Odoo filter_date_range).",
                    ),
                ),
                (
                    "filter_show_draft",
                    models.BooleanField(
                        default=False,
                        help_text="Ofrece incluir asientos borrador (Odoo filter_show_draft).",
                    ),
                ),
                (
                    "filter_unreconciled",
                    models.BooleanField(
                        default=False,
                        help_text="Ofrece filtrar sólo apuntes no conciliados (Odoo filter_unreconciled).",
                    ),
                ),
                (
                    "filter_unfold_all",
                    models.BooleanField(
                        default=False,
                        help_text="Ofrece desplegar todas las líneas (Odoo filter_unfold_all).",
                    ),
                ),
                (
                    "filter_hide_0_lines",
                    models.CharField(
                        choices=[
                            ("by_default", "Activo por defecto"),
                            ("optional", "Opcional"),
                            ("never", "Nunca"),
                        ],
                        default="optional",
                        help_text="Ocultar líneas en cero (Odoo filter_hide_0_lines).",
                        max_length=12,
                    ),
                ),
                (
                    "filter_period_comparison",
                    models.BooleanField(
                        default=True,
                        help_text="Ofrece comparar contra otro periodo (Odoo filter_period_comparison).",
                    ),
                ),
                (
                    "filter_growth_comparison",
                    models.BooleanField(
                        default=True,
                        help_text="Ofrece la columna de crecimiento (Odoo filter_growth_comparison).",
                    ),
                ),
                (
                    "filter_journals",
                    models.BooleanField(
                        default=False,
                        help_text="Ofrece filtrar por diario (Odoo filter_journals).",
                    ),
                ),
                (
                    "filter_analytic",
                    models.BooleanField(
                        default=False,
                        help_text="Ofrece filtrar por cuenta analítica (Odoo filter_analytic).",
                    ),
                ),
                (
                    "filter_hierarchy",
                    models.CharField(
                        choices=[
                            ("by_default", "Activo por defecto"),
                            ("optional", "Opcional"),
                            ("never", "Nunca"),
                        ],
                        default="optional",
                        help_text="Agrupar por grupos de cuentas (Odoo filter_hierarchy).",
                        max_length=12,
                    ),
                ),
                (
                    "filter_account_type",
                    models.CharField(
                        choices=[
                            ("both", "Por pagar y por cobrar"),
                            ("payable", "Por pagar"),
                            ("receivable", "Por cobrar"),
                            ("disabled", "Desactivado"),
                        ],
                        default="disabled",
                        help_text="Filtro por tipo de cuenta (Odoo filter_account_type).",
                        max_length=12,
                    ),
                ),
                (
                    "filter_partner",
                    models.BooleanField(
                        default=False,
                        help_text="Ofrece filtrar por contacto (Odoo filter_partner).",
                    ),
                ),
                (
                    "filter_aml_ir_filters",
                    models.BooleanField(
                        default=False,
                        help_text="Ofrece los filtros favoritos del usuario sobre apuntes (Odoo filter_aml_ir_filters).",
                    ),
                ),
                (
                    "filter_budgets",
                    models.BooleanField(
                        default=False,
                        help_text="Ofrece comparar contra presupuesto (Odoo filter_budgets).",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="País cuya normativa describe el reporte (Odoo country_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_reports",
                        to="base.rescountry",
                    ),
                ),
                (
                    "root_report",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reporte del que este es una variante — la variante hereda sus opciones (Odoo root_report_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variants",
                        to="account.accountreport",
                    ),
                ),
                (
                    "section_reports",
                    models.ManyToManyField(
                        blank=True,
                        db_table="account_report_section_rel",
                        help_text='Sub-reportes que componen este reporte compuesto (Odoo section_report_ids, relación account_report_section_rel). symmetrical=False porque la relación es dirigida: la referencia declara los dos sentidos como campos distintos con column1/column2 invertidos (odoo19c: account_report.py:58-59), y un M2M reflexivo de Django es simétrico por defecto — dejarlo así fundiría "contiene" con "está contenido en".',
                        related_name="section_main_reports",
                        to="account.accountreport",
                    ),
                ),
            ],
            options={
                "db_table": "account_report",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountReportColumn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Encabezado de la columna (Odoo name, requerido, traducible).",
                        max_length=255,
                    ),
                ),
                (
                    "expression_label",
                    models.CharField(
                        help_text="Etiqueta que empareja la columna con la expresión de cada línea (Odoo expression_label, requerido).",
                        max_length=64,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0, help_text="Orden de la columna (Odoo sequence)."
                    ),
                ),
                (
                    "sortable",
                    models.BooleanField(
                        default=False,
                        help_text="El usuario puede ordenar por esta columna (Odoo sortable).",
                    ),
                ),
                (
                    "figure_type",
                    models.CharField(
                        choices=[
                            ("monetary", "Monetario"),
                            ("percentage", "Porcentaje"),
                            ("integer", "Entero"),
                            ("float", "Decimal"),
                            ("date", "Fecha"),
                            ("datetime", "Fecha y hora"),
                            ("boolean", "Booleano"),
                            ("string", "Texto"),
                        ],
                        default="monetary",
                        help_text="Cómo se presentan los valores de la columna (Odoo figure_type).",
                        max_length=12,
                    ),
                ),
                (
                    "blank_if_zero",
                    models.BooleanField(
                        default=False,
                        help_text="Deja la celda vacía en vez de mostrar 0 (Odoo blank_if_zero).",
                    ),
                ),
                (
                    "custom_audit_action",
                    models.ForeignKey(
                        blank=True,
                        help_text="Acción de auditoría a medida al pulsar una celda (Odoo custom_audit_action_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_report_columns",
                        to="base.iractionsactwindow",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Reporte al que pertenece la columna (Odoo report_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="account.accountreport",
                    ),
                ),
            ],
            options={
                "db_table": "account_report_column",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountReportLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Etiqueta de la línea (Odoo name, requerido, traducible).",
                        max_length=255,
                    ),
                ),
                (
                    "hierarchy_level",
                    models.IntegerField(
                        default=0,
                        help_text="Profundidad en la jerarquía; la referencia la deriva del padre (Odoo hierarchy_level).",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0, help_text="Orden dentro del reporte (Odoo sequence)."
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identificador único de la línea dentro del reporte; lo usan las fórmulas de agregación para referirse a ella (Odoo code).",
                        max_length=64,
                    ),
                ),
                (
                    "groupby",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Campos de account.move.line, separados por coma, por los que se subdivide la línea (Odoo groupby).",
                        max_length=255,
                    ),
                ),
                (
                    "user_groupby",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Agrupación elegida por el usuario, que sustituye a groupby (Odoo user_groupby).",
                        max_length=255,
                    ),
                ),
                (
                    "foldable",
                    models.BooleanField(
                        default=False,
                        help_text="La línea nace plegada y muestra botón de despliegue (Odoo foldable).",
                    ),
                ),
                (
                    "print_on_new_page",
                    models.BooleanField(
                        default=False,
                        help_text="Esta línea y las siguientes se imprimen en página nueva (Odoo print_on_new_page).",
                    ),
                ),
                (
                    "hide_if_zero",
                    models.BooleanField(
                        default=False,
                        help_text="Oculta la línea y sus hijas cuando todas sus columnas son cero (Odoo hide_if_zero).",
                    ),
                ),
                (
                    "horizontal_split_side",
                    models.CharField(
                        blank=True,
                        choices=[("left", "Izquierda"), ("right", "Derecha")],
                        default="",
                        help_text="Lado en un reporte partido horizontalmente, p. ej. un balance activo/pasivo (Odoo horizontal_split_side).",
                        max_length=8,
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        blank=True,
                        help_text="Acción a ejecutar al pulsar la línea; si está puesta, la línea es un enlace (Odoo action_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_report_lines",
                        to="base.iractionsactions",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Línea padre en la jerarquía (Odoo parent_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="account.accountreportline",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="Reporte al que pertenece la línea (Odoo report_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="account.accountreport",
                    ),
                ),
            ],
            options={
                "db_table": "account_report_line",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountReportExternalValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descripción del valor (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        default=0.0,
                        help_text="Importe numérico. ``Float``, no ``Monetary``, fiel a la referencia (odoo19c: account_report.py:952): el valor no lleva divisa propia — la toma del reporte que lo consume.",
                    ),
                ),
                (
                    "text_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Valor textual, cuando la expresión no es numérica (Odoo text_value).",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Fecha a la que aplica el valor (Odoo date, requerido)."
                    ),
                ),
                (
                    "carryover_origin_expression_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta de la expresión de la que proviene el arrastre (Odoo carryover_origin_expression_label).",
                        max_length=64,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa dueña del valor (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_report_external_values",
                        to="base.rescompany",
                    ),
                ),
                (
                    "target_report_expression",
                    models.ForeignKey(
                        help_text="Expresión a la que se suma este valor (Odoo target_report_expression_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_values",
                        to="account.accountreportexpression",
                    ),
                ),
                (
                    "carryover_origin_report_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Línea de la que proviene el arrastre (Odoo carryover_origin_report_line_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carryover_external_values",
                        to="account.accountreportline",
                    ),
                ),
            ],
            options={
                "db_table": "account_report_external_value",
                "ordering": ["date", "id"],
            },
        ),
        migrations.AddField(
            model_name="accountreportexpression",
            name="report_line",
            field=models.ForeignKey(
                help_text="Línea a la que pertenece la expresión (Odoo report_line_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expressions",
                to="account.accountreportline",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountreportline",
            constraint=models.UniqueConstraint(
                fields=("report", "code"), name="unique_account_report_line_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountreportexpression",
            constraint=models.UniqueConstraint(
                fields=("report_line", "label"),
                name="unique_account_report_expression_label",
            ),
        ),
    ]
