# Generated by Django 6.0.5 on 2026-08-06 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0008_tax_computation_engine"),
        ("base", "0011_company_default_taxes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmove",
            name="sequence_number",
            field=models.IntegerField(
                default=0,
                help_text='Parte numérica del nombre, como entero. El "último" se obtiene con MAX sobre esta columna, nunca ordenando el nombre — ver H-API-339 (Odoo sequence_number).',
            ),
        ),
        migrations.AlterField(
            model_name="accountmove",
            name="sequence_prefix",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Parte no numérica del nombre — p. ej. ``INV/VTA/2026/``. Es la forma consultable del prefijo (Odoo sequence_prefix).",
                max_length=128,
            ),
        ),
        migrations.AddIndex(
            model_name="accountmove",
            index=models.Index(
                fields=["journal", "-sequence_prefix", "-sequence_number", "name"],
                name="account_move_sequence_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accountmove",
            index=models.Index(
                fields=["journal", "-id", "sequence_prefix"],
                name="account_move_sequence_idx2",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountmove",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state", "posted"), models.Q(("name", "/"), _negated=True)
                ),
                fields=("name", "journal"),
                name="account_move_unique_name_journal",
            ),
        ),
    ]
