# Generated by Django 6.0.5 on 2026-08-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_accountgroup_account_group_prefix_length_eq"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttax",
            name="l10n_mx_factor_type",
            field=models.CharField(
                choices=[("Tasa", "Tasa"), ("Cuota", "Cuota"), ("Exento", "Exento")],
                default="Tasa",
                help_text="Factor SAT (TipoFactor) para CFDI 4.0: indica cómo se aplica el monto sobre la base del impuesto (Odoo l10n_mx_factor_type).",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="accounttax",
            name="l10n_mx_tax_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("isr", "ISR"),
                    ("iva", "IVA"),
                    ("ieps", "IEPS"),
                    ("local", "Local"),
                ],
                default="",
                help_text='Clasificación SAT del impuesto — ISR/IVA/IEPS/Local. Se rellena en "iva" cuando la empresa dueña del impuesto es mexicana y el campo está vacío (Odoo l10n_mx_tax_type, compute).',
                max_length=8,
            ),
        ),
    ]
