# Generated by Django 5.0.1 on 2026-05-20 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("wishlist", "0001_initial"),
        ("wishlist", "0002_timestampedmodel_wishlist"),
        ("wishlist", "0003_sync_model_drift"),
        ("wishlist", "0004_wishlistitem_deleted_at_wishlistitem_is_deleted"),
    ]

    initial = True

    dependencies = [
        ("catalogue", "0005_productimage_admin_products"),
        ("catalogue", "0007_sync_model_drift"),
        ("chartsize", "0001_initial"),
        ("chartsize", "0003_sync_model_drift"),
        ("users", "0001_squashed_0007_user_deactivation_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("price_at_add", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="catalogue.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wishlist_items",
                        to="chartsize.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "wishlist_item",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="wishlistitem",
            constraint=models.UniqueConstraint(
                fields=("user", "product", "variant"),
                name="unique_user_product_variant",
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name="wishlistitem",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Item de lista de deseos",
            },
        ),
        migrations.RemoveConstraint(
            model_name="wishlistitem",
            name="unique_user_product_variant",
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("user", "product", "variant")},
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="wishlistitem",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
    ]
