# Generated by Django 5.0.1 on 2026-05-15 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_sync_model_drift'),
        ('chartsize', '0003_sync_model_drift'),
        ('wishlist', '0002_timestampedmodel_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Item de lista de deseos'},
        ),
        migrations.RemoveConstraint(
            model_name='wishlistitem',
            name='unique_user_product_variant',
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('user', 'product', 'variant')},
        ),
    ]
