# Generated by Django 5.0.1 on 2026-05-25 16:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0014_productpricehistory"),
        ("chartsize", "0005_alter_productvariant_created_at"),
        (
            "wishlist",
            "0001_squashed_0004_wishlistitem_deleted_at_wishlistitem_is_deleted",
        ),
        ("users", "0001_squashed_0007_user_deactivation_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="wishlistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", False)),
                fields=("user", "product", "variant"),
                name="unique_wishlist_user_product_variant",
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlistitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("user", "product"),
                name="unique_wishlist_user_product_no_variant",
            ),
        ),
    ]
