# Generated by Django 6.0.5 on 2026-08-28 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmlead",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                db_column="partner_id",
                help_text="Cliente asociado (Odoo partner_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="crmlead",
            old_name="partner",
            new_name="partner_id",
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                db_column="stage_id",
                help_text="Etapa del pipeline (Odoo stage_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="crm.crmstage",
            ),
        ),
        migrations.RenameField(
            model_name="crmlead",
            old_name="stage",
            new_name="stage_id",
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_column="team_id",
                help_text="Equipo de venta (Odoo team_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to="sales_team.crmteam",
            ),
        ),
        migrations.RenameField(
            model_name="crmlead",
            old_name="team",
            new_name="team_id",
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                help_text="Vendedor (Odoo user_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads_owned",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name="crmlead",
            old_name="user",
            new_name="user_id",
        ),
    ]
