# Generated by Django 6.0.5 on 2026-08-28 23:18

import addons.crm.models.crm_lead_scoring_frequency
import django.db.models.deletion
import orm.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0063_alter_iractionsserver_sequence_id"),
        ("crm", "0002_alter_crmlead_partner_and_more"),
        ("sales_team", "0003_alter_crmtag_color"),
        ("utm", "0003_alter_utmcampaign_stage_id_alter_utmcampaign_user_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmLostReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descripción del motivo (Odoo name).", max_length=255
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Archivar sin borrar (Odoo active)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo de pérdida",
                "verbose_name_plural": "Motivos de pérdida",
                "db_table": "crm_lost_reason",
                "ordering": ["id"],
            },
            bases=(
                orm.models.RecordLoaderMixin,
                orm.models.DisplayNameMixin,
                models.Model,
            ),
        ),
        migrations.AlterModelOptions(
            name="crmlead",
            options={
                "ordering": ["-priority", "-id"],
                "verbose_name": "Oportunidad de CRM",
                "verbose_name_plural": "Oportunidades de CRM",
            },
        ),
        migrations.AlterModelOptions(
            name="crmstage",
            options={
                "ordering": ["sequence", "name", "id"],
                "verbose_name": "Etapa de CRM",
                "verbose_name_plural": "Etapas de CRM",
            },
        ),
        migrations.AddField(
            model_name="crmlead",
            name="automated_probability",
            field=models.FloatField(
                default=0.0,
                help_text="Probabilidad calculada por el scoring (Odoo automated_probability).",
                verbose_name="Automated Probability",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="campaign_id",
            field=models.ForeignKey(
                blank=True,
                db_column="campaign_id",
                help_text="Nombre con el que se distingue cada esfuerzo de campaña, p. ej. Fall_Drive, Christmas_Special.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmcampaign",
                verbose_name="Campaña",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="city",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="color",
            field=models.IntegerField(
                default=0,
                help_text="Índice de color (Odoo color).",
                verbose_name="Color Index",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="company_id",
            field=models.ForeignKey(
                blank=True,
                db_column="company_id",
                help_text="Empresa dueña (Odoo company_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to="base.rescompany",
                verbose_name="Company",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="country_id",
            field=models.ForeignKey(
                blank=True,
                db_column="country_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to="base.rescountry",
                verbose_name="Country",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="date_automation_last",
            field=models.DateTimeField(
                blank=True,
                help_text="Última acción automatizada (Odoo date_automation_last).",
                null=True,
                verbose_name="Last Action",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="date_closed",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha de cierre (Odoo date_closed).",
                null=True,
                verbose_name="Closed Date",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="date_conversion",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha de conversión a oportunidad (Odoo date_conversion).",
                null=True,
                verbose_name="Conversion Date",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="date_deadline",
            field=models.DateField(
                blank=True,
                help_text="Estimación de la fecha en que se ganará la oportunidad.",
                null=True,
                verbose_name="Expected Closing",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="date_last_stage_update",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Último cambio de etapa (Odoo date_last_stage_update).",
                null=True,
                verbose_name="Last Stage Update",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="date_open",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha de asignación (Odoo date_open).",
                null=True,
                verbose_name="Assignment Date",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="day_close",
            field=models.FloatField(
                blank=True,
                help_text="Días hasta el cierre (Odoo day_close).",
                null=True,
                verbose_name="Days to Close",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="day_open",
            field=models.FloatField(
                blank=True,
                help_text="Días hasta la asignación (Odoo day_open).",
                null=True,
                verbose_name="Days to Assign",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="email_domain_criterion",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Dominio del correo, para buscar duplicados por coincidencia exacta (Odoo email_domain_criterion).",
                max_length=255,
                verbose_name="Email Domain Criterion",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="email_normalized",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Correo normalizado, en minúsculas (Odoo email_normalized).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="email_state",
            field=models.CharField(
                blank=True,
                choices=[("correct", "Correct"), ("incorrect", "Incorrect")],
                help_text="Calidad del correo (Odoo email_state).",
                max_length=9,
                null=True,
                verbose_name="Email Quality",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="function",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Puesto del contacto (Odoo function).",
                max_length=255,
                verbose_name="Job Position",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="lang_id",
            field=models.ForeignKey(
                blank=True,
                db_column="lang_id",
                help_text="Idioma del contacto (Odoo lang_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to="base.reslang",
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="lead_properties",
            field=models.JSONField(
                blank=True,
                help_text="Propiedades libres definidas por el equipo (Odoo lead_properties).",
                null=True,
                verbose_name="Properties",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="medium_id",
            field=models.ForeignKey(
                blank=True,
                db_column="medium_id",
                help_text="Método de entrega: postal, correo, banner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmmedium",
                verbose_name="Medio",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="partner_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Nombre de la futura empresa que se creará al convertir la iniciativa en oportunidad.",
                max_length=255,
                verbose_name="Company Name",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="phone_sanitized",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Teléfono en formato E.164 (Odoo phone_sanitized).",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="phone_state",
            field=models.CharField(
                blank=True,
                choices=[("correct", "Correct"), ("incorrect", "Incorrect")],
                help_text="Calidad del teléfono (Odoo phone_state).",
                max_length=9,
                null=True,
                verbose_name="Phone Quality",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="prorated_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ingreso prorrateado por probabilidad (Odoo prorated_revenue).",
                max_digits=16,
                verbose_name="Prorated Revenue",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="recurring_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ingreso recurrente (Odoo recurring_revenue).",
                max_digits=16,
                verbose_name="Recurring Revenues",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="recurring_revenue_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ingreso recurrente mensual (Odoo recurring_revenue_monthly).",
                max_digits=16,
                verbose_name="Expected MRR",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="recurring_revenue_monthly_prorated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="MRR prorrateado (Odoo recurring_revenue_monthly_prorated).",
                max_digits=16,
                verbose_name="Prorated MRR",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="recurring_revenue_prorated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Recurrente prorrateado (Odoo recurring_revenue_prorated).",
                max_digits=16,
                verbose_name="Prorated Recurring Revenues",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="referred",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Quién refirió la iniciativa (Odoo referred).",
                max_length=255,
                verbose_name="Referred By",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="source_id",
            field=models.ForeignKey(
                blank=True,
                db_column="source_id",
                help_text="Origen del enlace: un buscador, otro dominio, o el nombre de una lista de correo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmsource",
                verbose_name="Fuente",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="state_id",
            field=models.ForeignKey(
                blank=True,
                db_column="state_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to="base.rescountrystate",
                verbose_name="State",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="street",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Street"
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="street2",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Street2"
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="tag_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="crm_tag_rel",
                help_text="Clasifica y analiza las categorías de la iniciativa: formación, servicio…",
                related_name="crm_leads",
                to="sales_team.crmtag",
                verbose_name="Tags",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="website",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Sitio web del contacto (Odoo website).",
                max_length=255,
                verbose_name="Website",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="won_status",
            field=models.CharField(
                choices=[("won", "Won"), ("lost", "Lost"), ("pending", "Pending")],
                default="pending",
                help_text="Ganada, perdida o en curso (Odoo won_status).",
                max_length=8,
                verbose_name="Won/Lost",
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="zip",
            field=models.CharField(
                blank=True, default="", max_length=24, verbose_name="Zip"
            ),
        ),
        migrations.AddField(
            model_name="crmstage",
            name="requirements",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Requisitos internos de la etapa (Odoo requirements).",
            ),
        ),
        migrations.AddField(
            model_name="crmstage",
            name="rotting_threshold_days",
            field=models.IntegerField(
                default=0,
                help_text="Días sin actualizar tras los que la oportunidad se resalta; 0 desactiva (Odoo rotting_threshold_days).",
            ),
        ),
        migrations.AddField(
            model_name="crmstage",
            name="team_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Equipos de venta que usan la etapa (Odoo team_ids).",
                related_name="crm_stages",
                to="sales_team.crmteam",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Archivar sin borrar (Odoo active).",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="contact_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Nombre de contacto (Odoo contact_name).",
                max_length=255,
                verbose_name="Contact Name",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Notas (Odoo description).",
                verbose_name="Notes",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="email_from",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Correo del contacto (Odoo email_from).",
                max_length=255,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="expected_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ingreso esperado (Odoo expected_revenue).",
                max_digits=16,
                verbose_name="Expected Revenue",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Nombre de la oportunidad (Odoo crm.lead.name).",
                max_length=255,
                verbose_name="Opportunity",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="partner_id",
            field=models.ForeignKey(
                blank=True,
                db_column="partner_id",
                help_text="Contacto vinculado (opcional). Normalmente se crea al convertir la iniciativa.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to="base.respartner",
                verbose_name="Contact",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="phone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Teléfono del contacto (Odoo phone).",
                max_length=255,
                verbose_name="Phone",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="priority",
            field=models.CharField(
                choices=[
                    ("0", "Baja"),
                    ("1", "Media"),
                    ("2", "Alta"),
                    ("3", "Muy alta"),
                ],
                db_index=True,
                default="0",
                help_text="Prioridad (Odoo priority).",
                max_length=1,
                verbose_name="Priority",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="probability",
            field=models.FloatField(
                default=0.0,
                help_text="Probabilidad de ganar, en porcentaje (Odoo probability).",
                verbose_name="Probability",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="stage_id",
            field=models.ForeignKey(
                blank=True,
                db_column="stage_id",
                help_text="Etapa del pipeline (Odoo stage_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="crm.crmstage",
                verbose_name="Stage",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="team_id",
            field=models.ForeignKey(
                blank=True,
                db_column="team_id",
                help_text="Equipo de venta (Odoo team_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to="sales_team.crmteam",
                verbose_name="Sales Team",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="type",
            field=models.CharField(
                choices=[("lead", "Lead"), ("opportunity", "Opportunity")],
                db_index=True,
                default="lead",
                help_text="Iniciativa u oportunidad (Odoo type).",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                help_text="Vendedor asignado (Odoo user_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads_owned",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Salesperson",
            ),
        ),
        migrations.CreateModel(
            name="CrmLeadScoringFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variable",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Nombre del campo de crm.lead que actúa como variable.",
                        max_length=255,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Valor de la variable, siempre como texto.",
                        max_length=255,
                    ),
                ),
                (
                    "won_count",
                    models.FloatField(
                        default=0.0, help_text="Veces ganadas (Odoo won_count)."
                    ),
                ),
                (
                    "lost_count",
                    models.FloatField(
                        default=0.0, help_text="Veces perdidas (Odoo lost_count)."
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="team_id",
                        help_text="Equipo de venta dueño de la frecuencia (Odoo team_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_scoring_frequencies",
                        to="sales_team.crmteam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frecuencia de scoring",
                "verbose_name_plural": "Frecuencias de scoring",
                "db_table": "crm_lead_scoring_frequency",
            },
            bases=(
                orm.models.RecordLoaderMixin,
                orm.models.DisplayNameMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CrmLeadScoringFrequencyField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.IntegerField(
                        default=addons.crm.models.crm_lead_scoring_frequency._get_default_color,
                        help_text="Índice de color (Odoo color).",
                    ),
                ),
                (
                    "field_id",
                    models.ForeignKey(
                        db_column="field_id",
                        help_text="Campo de crm.lead usado como variable (Odoo field_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_lead_scoring_uses",
                        to="base.irmodelfields",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campo de scoring",
                "verbose_name_plural": "Campos de scoring",
                "db_table": "crm_lead_scoring_frequency_field",
            },
            bases=(
                orm.models.RecordLoaderMixin,
                orm.models.DisplayNameMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="lost_reason_id",
            field=models.ForeignKey(
                blank=True,
                db_column="lost_reason_id",
                help_text="Motivo de pérdida (Odoo lost_reason_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="crm.crmlostreason",
                verbose_name="Lost Reason",
            ),
        ),
        migrations.CreateModel(
            name="CrmRecurringPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del plan (Odoo name).", max_length=255
                    ),
                ),
                (
                    "number_of_months",
                    models.IntegerField(
                        help_text="Número de meses del plan (Odoo number_of_months)."
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Archivar sin borrar (Odoo active)."
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de listado (Odoo sequence)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de ingreso recurrente",
                "verbose_name_plural": "Planes de ingreso recurrente",
                "db_table": "crm_recurring_plan",
                "ordering": ["sequence"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("number_of_months__gte", 0)),
                        name="crm_recurring_plan_check_number_of_months",
                        violation_error_message="El número de meses no puede ser negativo.",
                    )
                ],
            },
            bases=(
                orm.models.RecordLoaderMixin,
                orm.models.DisplayNameMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="crmlead",
            name="recurring_plan",
            field=models.ForeignKey(
                blank=True,
                db_column="recurring_plan",
                help_text="Plan recurrente (Odoo recurring_plan).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to="crm.crmrecurringplan",
                verbose_name="Recurring Plan",
            ),
        ),
        migrations.AddIndex(
            model_name="crmlead",
            index=models.Index(
                fields=["user_id", "team_id", "type"],
                name="crm_lead_user_team_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crmlead",
            index=models.Index(
                fields=["created_at", "team_id"], name="crm_lead_create_team_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crmlead",
            index=models.Index(
                condition=models.Q(("active", True)),
                fields=["-priority", "-id"],
                name="crm_lead_default_order_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="crmlead",
            constraint=models.CheckConstraint(
                condition=models.Q(("probability__gte", 0), ("probability__lte", 100)),
                name="crm_lead_check_probability",
                violation_error_message="The probability of closing the deal should be between 0% and 100%!",
            ),
        ),
    ]
