# Generated by Django 6.0.5 on 2026-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_crmlostreason_alter_crmlead_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crmlead",
            name="date_last_stage_update",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Último cambio de etapa (Odoo date_last_stage_update).",
                null=True,
                verbose_name="Last Stage Update",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="date_open",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Fecha de asignación (Odoo date_open).",
                null=True,
                verbose_name="Assignment Date",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="day_close",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="Días hasta el cierre (Odoo day_close).",
                null=True,
                verbose_name="Days to Close",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="day_open",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="Días hasta la asignación (Odoo day_open).",
                null=True,
                verbose_name="Days to Assign",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="email_domain_criterion",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                editable=False,
                help_text="Dominio del correo, para buscar duplicados por coincidencia exacta (Odoo email_domain_criterion).",
                max_length=255,
                verbose_name="Email Domain Criterion",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="email_state",
            field=models.CharField(
                blank=True,
                choices=[("correct", "Correct"), ("incorrect", "Incorrect")],
                editable=False,
                help_text="Calidad del correo (Odoo email_state).",
                max_length=9,
                null=True,
                verbose_name="Email Quality",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="phone_state",
            field=models.CharField(
                blank=True,
                choices=[("correct", "Correct"), ("incorrect", "Incorrect")],
                editable=False,
                help_text="Calidad del teléfono (Odoo phone_state).",
                max_length=9,
                null=True,
                verbose_name="Phone Quality",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="prorated_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Ingreso prorrateado por probabilidad (Odoo prorated_revenue).",
                max_digits=16,
                verbose_name="Prorated Revenue",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="recurring_revenue_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Ingreso recurrente mensual (Odoo recurring_revenue_monthly).",
                max_digits=16,
                verbose_name="Expected MRR",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="recurring_revenue_monthly_prorated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="MRR prorrateado (Odoo recurring_revenue_monthly_prorated).",
                max_digits=16,
                verbose_name="Prorated MRR",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="recurring_revenue_prorated",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Recurrente prorrateado (Odoo recurring_revenue_prorated).",
                max_digits=16,
                verbose_name="Prorated Recurring Revenues",
            ),
        ),
        migrations.AlterField(
            model_name="crmlead",
            name="won_status",
            field=models.CharField(
                choices=[("won", "Won"), ("lost", "Lost"), ("pending", "Pending")],
                default="pending",
                editable=False,
                help_text="Ganada, perdida o en curso (Odoo won_status).",
                max_length=8,
                verbose_name="Won/Lost",
            ),
        ),
    ]
