"""La tabla del asistente de importación de módulos.

**Por qué hay un ``RunPython`` antes del ``CreateModel``.** La tabla apareció
en la base compartida de la sesión SIN su fila en ``django_migrations``
—medido: ``to_regclass('base_import_module')`` la devolvía, con las siete
columnas correctas, y ``select name from django_migrations where
app='base_import_module'`` devolvía **cero filas**—, así que el
``CreateModel`` abortaba con ``relation … already exists`` y dejaba fuera de
servicio a todo pytest que compartiera esa base.

Es el mismo síntoma que ``addons/base_install_request/migrations/0001_initial.py``
documenta, y la misma cura: una tabla presente sin registro sólo puede venir de
una corrida interrumpida o de un ``migrate --fake``, y ésta es de un
``TransientModel``, cuyo contenido es desechable por definición
(``src/orm/models_transient.py``: un transitorio se recolecta por vacuum).

El paso no crea nada — crear sigue siendo trabajo del ``CreateModel``, y
dejárselo a él mantiene el estado de migraciones exacto sin tener que resolver
el modelo histórico, que en una migración ``initial`` todavía no existe en
``from_state``.
"""
# Generated by Django 6.0.5 on 2026-09-02 09:23

from django.db import migrations, models


#: La tabla que esta migración materializa.
TABLAS = ('base_import_module',)


def soltar_tablas_huerfanas(apps, schema_editor):
    """Suelta lo que quede de una corrida interrumpida, antes del ``CreateModel``."""
    for tabla in TABLAS:
        schema_editor.execute(
            'DROP TABLE IF EXISTS %s CASCADE' % schema_editor.quote_name(tabla))


def sin_efecto(apps, schema_editor):
    """Marcha atrás del paso de arriba: el ``CreateModel`` ya suelta la tabla."""



class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(soltar_tablas_huerfanas, sin_efecto),
        migrations.CreateModel(
            name="BaseImportModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_file",
                    models.BinaryField(
                        help_text="El .zip del módulo (Odoo module_file, attachment=False).",
                        verbose_name="Module .ZIP file",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("init", "init"), ("done", "done")],
                        default="init",
                        help_text="Odoo state: init mientras no se haya importado.",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                ("import_message", models.TextField(blank=True, default="")),
                (
                    "force",
                    models.BooleanField(
                        default=False,
                        help_text="Force init mode even if installed. (will update `noupdate='1'` records)",
                        verbose_name="Force init",
                    ),
                ),
                (
                    "with_demo",
                    models.BooleanField(
                        default=False, verbose_name="Import demo data of module"
                    ),
                ),
                ("modules_dependencies", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Importación de módulo",
                "verbose_name_plural": "Importaciones de módulo",
                "db_table": "base_import_module",
            },
        ),
    ]
