# Generated by Django 6.0.5 on 2026-08-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digestdigest',
            name='kpi_account_total_revenue',
            field=models.BooleanField(default=False, help_text='Muestra el KPI de ingreso total del período en el digest (Odoo kpi_account_total_revenue).', verbose_name='Ingresos'),
        ),
    ]
