# Generated by Django 6.0.5 on 2026-08-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digest", "0002_digestdigest_kpi_account_total_revenue"),
    ]

    operations = [
        migrations.AddField(
            model_name="digestdigest",
            name="kpi_hr_recruitment_new_colleagues",
            field=models.BooleanField(
                default=False,
                help_text='Odoo kpi_hr_recruitment_new_colleagues ("New Employees"). Su valor calculado (kpi_hr_recruitment_new_colleagues_value) queda BLOQUEADO — ver docstring del módulo.',
                verbose_name="Nuevos empleados",
            ),
        ),
    ]
