# Generated by Django 6.0.5 on 2026-08-28 20:05

import django.db.models.deletion
import orm.environments
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digest", "0003_digestdigest_kpi_hr_recruitment_new_colleagues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digestdigest",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_column="company_id",
                default=orm.environments.get_current_company,
                help_text="Odoo company_id (default=env.company.id → get_current_company()).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="digests",
                to="base.rescompany",
                verbose_name="Compañía",
            ),
        ),
        migrations.RenameField(
            model_name="digestdigest",
            old_name="company",
            new_name="company_id",
        ),
    ]
