# Generated by Django 6.0.5 on 2026-09-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digest", "0005_digestdigest_kpi_crm_lead_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digestdigest",
            name="kpi_hr_recruitment_new_colleagues",
            field=models.BooleanField(
                default=False,
                help_text='Odoo kpi_hr_recruitment_new_colleagues ("New Employees"). Su valor calculado (kpi_hr_recruitment_new_colleagues_value) queda BLOQUEADO — ver docstring del módulo, tarea #159.',
                verbose_name="Nuevos empleados",
            ),
        ),
    ]
