# Generated by Django 6.0.5 on 2026-09-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digest", "0007_alter_digestdigest_kpi_hr_recruitment_new_colleagues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digestdigest",
            name="kpi_hr_recruitment_new_colleagues",
            field=models.BooleanField(
                default=False,
                help_text='Odoo kpi_hr_recruitment_new_colleagues ("New Employees").',
                verbose_name="Nuevos empleados",
            ),
        ),
    ]
