# Generated by Django 6.0.5 on 2026-08-06 00:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0007_alter_iractionsreport_report_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo de servicio (Odoo name, translate=True en la referencia; i18n no portado).",
                        max_length=150,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("contract", "Contrato"), ("service", "Servicio")],
                        help_text="Si el tipo aplica a contratos, a servicios, o a ambos (Odoo category).",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de servicio de flota",
                "verbose_name_plural": "Tipos de servicio de flota",
                "db_table": "fleet_service_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FleetVehicleModelBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Odoo name (required).", max_length=150),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "image_128",
                    models.ImageField(
                        blank=True,
                        help_text="Logo de la marca, 128×128 (Odoo image_128, sin las otras reducciones del image.mixin — la referencia no hereda el mixin completo aquí, sólo declara este campo).",
                        null=True,
                        upload_to="fleet/brand_logos/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca de vehículo",
                "verbose_name_plural": "Marcas de vehículo",
                "db_table": "fleet_vehicle_model_brand",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FleetVehicleState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del estado (Odoo name, translate=True en la referencia; i18n no portado).",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0, help_text="Orden del kanban (Odoo sequence)."
                    ),
                ),
                (
                    "fold",
                    models.BooleanField(
                        default=False,
                        help_text="Columna plegada en el kanban (Odoo fold).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de vehículo",
                "verbose_name_plural": "Estados de vehículo",
                "db_table": "fleet_vehicle_state",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="FleetVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Odoo description."
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "license_plate",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Placa (Odoo license_plate).",
                        max_length=32,
                    ),
                ),
                (
                    "vin_sn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de chasís/VIN (Odoo vin_sn).",
                        max_length=64,
                    ),
                ),
                (
                    "next_assignation_date",
                    models.DateField(
                        blank=True, help_text="Odoo next_assignation_date.", null=True
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        blank=True, help_text="Odoo order_date.", null=True
                    ),
                ),
                (
                    "acquisition_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="Fecha de alta (Odoo acquisition_date).",
                        null=True,
                    ),
                ),
                (
                    "write_off_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de baja de placas (Odoo write_off_date).",
                        null=True,
                    ),
                ),
                (
                    "contract_date_start",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="Odoo contract_date_start.",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo color (sync).",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo location.",
                        max_length=150,
                    ),
                ),
                (
                    "seats",
                    models.IntegerField(
                        blank=True, help_text="Odoo seats (sync).", null=True
                    ),
                ),
                (
                    "model_year",
                    models.IntegerField(
                        blank=True, help_text="Odoo model_year (sync).", null=True
                    ),
                ),
                (
                    "doors",
                    models.IntegerField(
                        blank=True, help_text="Odoo doors (sync).", null=True
                    ),
                ),
                (
                    "odometer_unit",
                    models.CharField(
                        choices=[("kilometers", "km"), ("miles", "mi")],
                        default="kilometers",
                        help_text="Odoo odometer_unit.",
                        max_length=10,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("manual", "Manual"), ("automatic", "Automática")],
                        help_text="Odoo transmission (sync).",
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diesel", "Diésel"),
                            ("gasoline", "Gasolina"),
                            ("full_hybrid", "Híbrido completo"),
                            ("plug_in_hybrid_diesel", "Híbrido enchufable (diésel)"),
                            (
                                "plug_in_hybrid_gasoline",
                                "Híbrido enchufable (gasolina)",
                            ),
                            ("cng", "GNC"),
                            ("lpg", "GLP"),
                            ("hydrogen", "Hidrógeno"),
                            ("electric", "Eléctrico"),
                        ],
                        help_text="Odoo fuel_type (sync de default_fuel_type).",
                        max_length=23,
                        null=True,
                    ),
                ),
                (
                    "power_unit",
                    models.CharField(
                        choices=[
                            ("power", "kW"),
                            ("horsepower", "Caballos de fuerza (hp)"),
                        ],
                        default="power",
                        help_text="Odoo power_unit.",
                        max_length=10,
                    ),
                ),
                (
                    "horsepower",
                    models.FloatField(
                        blank=True, help_text="Odoo horsepower (sync).", null=True
                    ),
                ),
                (
                    "horsepower_tax",
                    models.FloatField(
                        blank=True, help_text="Odoo horsepower_tax (sync).", null=True
                    ),
                ),
                (
                    "power",
                    models.FloatField(
                        blank=True,
                        help_text="Potencia en kW (Odoo power, sync).",
                        null=True,
                    ),
                ),
                (
                    "co2",
                    models.FloatField(
                        blank=True,
                        help_text="Emisiones CO₂ (Odoo co2, sync de default_co2).",
                        null=True,
                    ),
                ),
                (
                    "co2_standard",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo co2_standard (sync).",
                        max_length=150,
                    ),
                ),
                (
                    "car_value",
                    models.FloatField(
                        blank=True,
                        help_text="Valor de catálogo con IVA (Odoo car_value).",
                        null=True,
                    ),
                ),
                (
                    "net_car_value",
                    models.FloatField(
                        blank=True,
                        help_text="Valor de compra (Odoo net_car_value).",
                        null=True,
                    ),
                ),
                (
                    "residual_value",
                    models.FloatField(
                        blank=True, help_text="Odoo residual_value.", null=True
                    ),
                ),
                (
                    "plan_to_change_car",
                    models.BooleanField(
                        default=False, help_text="Odoo plan_to_change_car."
                    ),
                ),
                (
                    "plan_to_change_bike",
                    models.BooleanField(
                        default=False, help_text="Odoo plan_to_change_bike."
                    ),
                ),
                (
                    "frame_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("diamant", "Diamante"),
                            ("trapez", "Trapecio"),
                            ("wave", "Wave"),
                        ],
                        help_text="Odoo frame_type (bicicletas).",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "electric_assistance",
                    models.BooleanField(
                        default=False, help_text="Odoo electric_assistance (sync)."
                    ),
                ),
                (
                    "frame_size",
                    models.FloatField(
                        blank=True, help_text="Odoo frame_size.", null=True
                    ),
                ),
                (
                    "vehicle_properties",
                    models.JSONField(
                        blank=True,
                        help_text="Propiedades dinámicas del vehículo (Odoo vehicle_properties). Sin validación de esquema contra model.vehicle_properties_definition (deferido).",
                        null=True,
                    ),
                ),
                (
                    "vehicle_range",
                    models.IntegerField(
                        blank=True, help_text="Odoo vehicle_range (sync).", null=True
                    ),
                ),
                (
                    "range_unit",
                    models.CharField(
                        choices=[("km", "km"), ("mi", "mi")],
                        default="km",
                        help_text="Odoo range_unit (sync).",
                        max_length=2,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo company_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_vehicles",
                        to="base.rescompany",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conductor actual (Odoo driver_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_vehicles_driven",
                        to="base.respartner",
                    ),
                ),
                (
                    "future_driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Próximo conductor (Odoo future_driver_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_vehicles_future_driven",
                        to="base.respartner",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gestor de flota (Odoo manager_id). El ``domain=`` de la referencia (grupo fleet.fleet_group_user) no se porta — ver punto 5 del docstring del módulo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_vehicles_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehículo",
                "verbose_name_plural": "Vehículos",
                "db_table": "fleet_vehicle",
                "ordering": ["license_plate", "acquisition_date"],
            },
        ),
        migrations.CreateModel(
            name="FleetVehicleAssignationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_start",
                    models.DateField(
                        blank=True, help_text="Odoo date_start.", null=True
                    ),
                ),
                (
                    "date_end",
                    models.DateField(blank=True, help_text="Odoo date_end.", null=True),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Odoo driver_id (required).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fleet_assignation_logs",
                        to="base.respartner",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Odoo vehicle_id (required).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignation_logs",
                        to="fleet.fleetvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de conductor",
                "verbose_name_plural": "Historial de conductores",
                "db_table": "fleet_vehicle_assignation_log",
                "ordering": ["-created_at", "-date_start"],
            },
        ),
        migrations.CreateModel(
            name="FleetVehicleLogContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Odoo amount.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Fecha del gasto (Odoo date).", null=True
                    ),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Odoo start_date (default hoy).",
                        null=True,
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True,
                        help_text="Odoo expiration_date (default: un año después de start_date; ver next_year_date()).",
                        null=True,
                    ),
                ),
                (
                    "ins_ref",
                    models.CharField(
                        blank=True, default="", help_text="Odoo ins_ref.", max_length=64
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("futur", "Próximo"),
                            ("open", "En curso"),
                            ("expired", "Vencido"),
                            ("closed", "Cancelado"),
                        ],
                        default="open",
                        help_text="Odoo state.",
                        max_length=7,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Odoo notes."),
                ),
                (
                    "cost_generated",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Odoo cost_generated.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "cost_frequency",
                    models.CharField(
                        choices=[
                            ("no", "No"),
                            ("daily", "Diaria"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("yearly", "Anual"),
                        ],
                        default="monthly",
                        help_text="Odoo cost_frequency.",
                        max_length=7,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo company_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_contracts",
                        to="base.rescompany",
                    ),
                ),
                (
                    "cost_subtype",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tipo de costo (Odoo cost_subtype_id). El ``domain=[(category, =, contract)]`` de la referencia es un filtro de UI, no se porta como restricción de datos.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="fleet.fleetservicetype",
                    ),
                ),
                (
                    "insurer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo insurer_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_contracts_insured",
                        to="base.respartner",
                    ),
                ),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True,
                        db_table="fleet_vehicle_log_contract_service_rel",
                        help_text="Odoo service_ids.",
                        related_name="contracts_included_in",
                        to="fleet.fleetservicetype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Responsable (Odoo user_id; el default desde vehicle.manager_id no se auto-aplica — ver sync_defaults).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_contracts_responsible",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Odoo vehicle_id (required).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_contracts",
                        to="fleet.fleetvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de vehículo",
                "verbose_name_plural": "Contratos de vehículo",
                "db_table": "fleet_vehicle_log_contract",
                "ordering": ["-state", "expiration_date"],
            },
        ),
        migrations.CreateModel(
            name="FleetVehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Odoo name (required).", max_length=150),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("car", "Auto"), ("bike", "Bicicleta/moto")],
                        default="car",
                        help_text="Odoo vehicle_type.",
                        max_length=4,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("manual", "Manual"), ("automatic", "Automática")],
                        help_text="Odoo transmission.",
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "model_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Año del modelo (Odoo model_year, Selection dinámico 1970..hoy → entero; ver docstring del módulo).",
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", help_text="Odoo color.", max_length=50
                    ),
                ),
                (
                    "seats",
                    models.IntegerField(blank=True, help_text="Odoo seats.", null=True),
                ),
                (
                    "doors",
                    models.IntegerField(
                        blank=True,
                        help_text="Número de puertas, incluidas cajuela y portón trasero si aplica (Odoo doors).",
                        null=True,
                    ),
                ),
                (
                    "trailer_hook",
                    models.BooleanField(
                        default=False,
                        help_text="Enganche de remolque (Odoo trailer_hook).",
                    ),
                ),
                (
                    "default_co2",
                    models.FloatField(
                        blank=True,
                        help_text="Emisiones CO₂ por defecto (Odoo default_co2).",
                        null=True,
                    ),
                ),
                (
                    "co2_standard",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Norma de emisiones bajo la que se mide (Odoo co2_standard).",
                        max_length=150,
                    ),
                ),
                (
                    "default_fuel_type",
                    models.CharField(
                        choices=[
                            ("diesel", "Diésel"),
                            ("gasoline", "Gasolina"),
                            ("full_hybrid", "Híbrido completo"),
                            ("plug_in_hybrid_diesel", "Híbrido enchufable (diésel)"),
                            (
                                "plug_in_hybrid_gasoline",
                                "Híbrido enchufable (gasolina)",
                            ),
                            ("cng", "GNC"),
                            ("lpg", "GLP"),
                            ("hydrogen", "Hidrógeno"),
                            ("electric", "Eléctrico"),
                        ],
                        default="electric",
                        help_text="Odoo default_fuel_type.",
                        max_length=23,
                    ),
                ),
                (
                    "power",
                    models.FloatField(
                        blank=True, help_text="Potencia en kW (Odoo power).", null=True
                    ),
                ),
                (
                    "horsepower",
                    models.FloatField(
                        blank=True, help_text="Odoo horsepower.", null=True
                    ),
                ),
                (
                    "horsepower_tax",
                    models.FloatField(
                        blank=True, help_text="Odoo horsepower_tax.", null=True
                    ),
                ),
                (
                    "electric_assistance",
                    models.BooleanField(
                        default=False, help_text="Odoo electric_assistance."
                    ),
                ),
                (
                    "power_unit",
                    models.CharField(
                        choices=[
                            ("power", "kW"),
                            ("horsepower", "Caballos de fuerza (hp)"),
                        ],
                        default="power",
                        help_text="Odoo power_unit.",
                        max_length=10,
                    ),
                ),
                (
                    "vehicle_properties_definition",
                    models.JSONField(
                        blank=True,
                        help_text="Esquema de propiedades dinámicas del modelo (Odoo vehicle_properties_definition). Sin motor de validación de esquema (deferido).",
                        null=True,
                    ),
                ),
                (
                    "vehicle_range",
                    models.IntegerField(
                        blank=True, help_text="Odoo vehicle_range.", null=True
                    ),
                ),
                (
                    "range_unit",
                    models.CharField(
                        choices=[("km", "km"), ("mi", "mi")],
                        default="km",
                        help_text="Odoo range_unit.",
                        max_length=2,
                    ),
                ),
                (
                    "drive_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fwd", "Tracción delantera (FWD)"),
                            ("awd", "Tracción integral (AWD)"),
                            ("rwd", "Tracción trasera (RWD)"),
                            ("4wd", "Tracción en las 4 ruedas (4WD)"),
                        ],
                        help_text="Odoo drive_type.",
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "vendors",
                    models.ManyToManyField(
                        blank=True,
                        db_table="fleet_vehicle_model_vendors",
                        help_text="Proveedores del modelo (Odoo vendor_ids).",
                        related_name="fleet_vehicle_models",
                        to="base.respartner",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="Fabricante (Odoo brand_id, required).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="models",
                        to="fleet.fleetvehiclemodelbrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de vehículo",
                "verbose_name_plural": "Modelos de vehículo",
                "db_table": "fleet_vehicle_model",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="model",
            field=models.ForeignKey(
                help_text="Odoo model_id (required).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="fleet.fleetvehiclemodel",
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo brand_id (related+store; ver sync_fields_from_model).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles_by_brand",
                to="fleet.fleetvehiclemodelbrand",
            ),
        ),
        migrations.CreateModel(
            name="FleetVehicleModelCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Odoo name (unique).", max_length=150, unique=True
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0, help_text="Orden en el kanban (Odoo sequence)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de modelo de vehículo",
                "verbose_name_plural": "Categorías de modelo de vehículo",
                "db_table": "fleet_vehicle_model_category",
                "ordering": ["sequence", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="fleet_model_category_name_uniq"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="fleetvehiclemodel",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría (Odoo category_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="models",
                to="fleet.fleetvehiclemodelcategory",
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo category_id (related+store; ver sync_fields_from_model).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="fleet.fleetvehiclemodelcategory",
            ),
        ),
        migrations.CreateModel(
            name="FleetVehicleOdometer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Odoo date (default hoy).", null=True
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        default=0,
                        help_text="Lectura del odómetro (Odoo value, aggregator=max).",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conductor al momento de la lectura (Odoo driver_id, compute+store — aquí sincronizado en save() si no viene dado).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_odometer_logs",
                        to="base.respartner",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Odoo vehicle_id (required).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odometer_logs",
                        to="fleet.fleetvehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lectura de odómetro",
                "verbose_name_plural": "Lecturas de odómetro",
                "db_table": "fleet_vehicle_odometer",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FleetVehicleLogServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Odoo amount.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo description.",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Odoo date (default hoy).", null=True
                    ),
                ),
                (
                    "inv_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo inv_ref.",
                        max_length=150,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", help_text="Odoo notes."),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("running", "En curso"),
                            ("done", "Terminado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="new",
                        help_text="Odoo state.",
                        max_length=9,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo company_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_service_logs",
                        to="base.rescompany",
                    ),
                ),
                (
                    "purchaser",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conductor (Odoo purchaser_id, compute+store con default vehicle.driver_id — no auto-aplicado; ver sync_defaults).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_service_logs_as_purchaser",
                        to="base.respartner",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        help_text="Odoo service_type_id (required).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_logs",
                        to="fleet.fleetservicetype",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        help_text="Odoo vehicle_id (required).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_services",
                        to="fleet.fleetvehicle",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo vendor_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleet_service_logs_as_vendor",
                        to="base.respartner",
                    ),
                ),
                (
                    "odometer_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo odometer_id — lectura de odómetro al momento del servicio. Ver la property ``odometer`` para el atajo get/set fiel a ``_get_odometer``/``_set_odometer``.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_logs",
                        to="fleet.fleetvehicleodometer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio de vehículo",
                "verbose_name_plural": "Servicios de vehículo",
                "db_table": "fleet_vehicle_log_services",
            },
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="Estado del kanban (Odoo state_id). Sin default — ver punto 5 del docstring del módulo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="fleet.fleetvehiclestate",
            ),
        ),
        migrations.CreateModel(
            name="FleetVehicleTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la etiqueta (Odoo name, translate=True en la referencia; i18n no portado).",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=0, help_text="Índice de color (Odoo color)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta de vehículo",
                "verbose_name_plural": "Etiquetas de vehículo",
                "db_table": "fleet_vehicle_tag",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="fleet_vehicle_tag_name_uniq"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="fleet_vehicle_vehicle_tag_rel",
                help_text="Odoo tag_ids.",
                related_name="vehicles",
                to="fleet.fleetvehicletag",
            ),
        ),
    ]
