# Generated by Django 6.0.5 on 2026-08-02 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderLineProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "line",
                    models.OneToOneField(
                        help_text="Línea de orden (Odoo sale.order.line).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_link",
                        to="sale.saleorderline",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Proyecto (Odoo project_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_order_lines",
                        to="project.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tarea (Odoo task_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_order_lines",
                        to="project.projecttask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto de línea de orden de venta",
                "verbose_name_plural": "Proyectos de líneas de orden de venta",
                "db_table": "sale_order_line_project",
            },
        ),
    ]
