# Generated by Django 6.0.5 on 2026-08-28 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mass_mailing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mailingsubscription",
            name="unique_mailing_subscription",
        ),
        migrations.AlterField(
            model_name="mailingcontact",
            name="country",
            field=models.ForeignKey(
                blank=True,
                db_column="country_id",
                help_text="Pais (Odoo country_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailing_contacts",
                to="base.rescountry",
            ),
        ),
        migrations.RenameField(
            model_name="mailingcontact",
            old_name="country",
            new_name="country_id",
        ),
        migrations.AlterField(
            model_name="mailingsubscription",
            name="contact",
            field=models.ForeignKey(
                db_column="contact_id",
                help_text="Contacto (Odoo contact_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_ids",
                to="mass_mailing.mailingcontact",
            ),
        ),
        migrations.RenameField(
            model_name="mailingsubscription",
            old_name="contact",
            new_name="contact_id",
        ),
        migrations.AddConstraint(
            model_name="mailingsubscription",
            constraint=models.UniqueConstraint(
                fields=("contact_id", "mailing_list"),
                name="unique_mailing_subscription",
            ),
        ),
    ]
