# Generated by Django 5.0.1 on 2026-06-02 23:03

import apps.returns.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0001_squashed_0002_returnrequest_softdelete"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.returns.models.return_evidence_upload_path
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia de devolucion",
                "verbose_name_plural": "Evidencias de devolucion",
                "db_table": "return_evidence",
                "ordering": ["created_at"],
            },
        ),
    ]
