# Generated by Django 6.0.5 on 2026-07-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatewaySettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adapter", models.CharField(max_length=32, verbose_name="Adaptador")),
                (
                    "gateway_ref",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name="Referencia del gateway",
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Bruto"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Comision"
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Neto"
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(verbose_name="Fecha de liberacion"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Importada"),
                            ("validated", "Validada"),
                            ("reconciled", "Conciliada"),
                        ],
                        default="imported",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements",
                        to="payments.payment",
                        verbose_name="Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidacion del gateway",
                "verbose_name_plural": "Liquidaciones del gateway",
                "db_table": "finance_gateway_settlement",
                "ordering": ["-settled_at"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Ingreso"), ("expense", "Egreso")],
                        max_length=8,
                        verbose_name="Clase",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(verbose_name="Fecha del movimiento"),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="finance.cashconcept",
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="finance.gatewaysettlement",
                        verbose_name="Liquidacion origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de caja",
                "verbose_name_plural": "Movimientos de caja",
                "db_table": "finance_cash_movement",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="GatewaySettlementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("matched", "Cuadrada"),
                            ("discrepant", "Discrepante"),
                            ("duplicate", "Duplicada"),
                        ],
                        default="matched",
                        max_length=12,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe"
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.gatewaysettlement",
                        verbose_name="Liquidacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linea de liquidacion",
                "verbose_name_plural": "Lineas de liquidacion",
                "db_table": "finance_gateway_settlement_line",
            },
        ),
    ]
