# Generated by Django 6.0.5 on 2026-08-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0003_saleorder_sale_order_un_draft_por_partner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleorderline",
            options={
                "ordering": ["order", "sequence", "id"],
                "verbose_name": "Línea de orden de venta",
            },
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="sequence",
            field=models.IntegerField(
                db_index=True,
                default=10,
                help_text="Orden de la línea dentro de la orden (Odoo sequence).",
            ),
        ),
    ]
