# Generated by Django 6.0.5 on 2026-08-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0004_alter_saleorderline_options_saleorderline_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorder",
            name="validity_date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Vigencia de la cotización (Odoo validity_date, sale/models/sale_order.py:135). NULL si la empresa no define quotation_validity_days.",
            ),
        ),
    ]
