# Generated by Django 6.0.5 on 2026-08-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0005_saleorder_validity_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorderline",
            name="has_displayed_warning_upsell",
            field=models.BooleanField(
                default=False,
                help_text="Odoo has_displayed_warning_upsell (copy=False). Quién la escribe está bloqueado por qty_delivered — ver el docstring del módulo.",
                verbose_name="Aviso de venta adicional ya mostrado",
            ),
        ),
    ]
