# Generated by Django 6.0.5 on 2026-08-29 07:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_date_order_from_created_at(apps, schema_editor):
    """Rellena ``date_order`` en las filas que lo tienen vacío.

    Usa el modelo histórico (``apps.get_model``) y no el vivo: una migración
    tiene que seguir corriendo cuando el modelo de hoy ya no se parezca al de
    esta migración.
    """
    SaleOrder = apps.get_model("sale", "SaleOrder")
    SaleOrder.objects.filter(date_order__isnull=True).update(
        date_order=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_accountmove_posted_before"),
        ("base", "0064_rescompany_downpayment_account_and_more"),
        ("delivery", "0002_initial"),
        ("mail", "0004_seed_cron_email_queue"),
        ("product", "0012_port_sale_extension_fields"),
        ("sale", "0007_seed_sale_security"),
        (
            "sales_team",
            "0007_crmteam_assignment_domain_crmteam_assignment_optout_and_more",
        ),
        ("utm", "0003_alter_utmcampaign_stage_id_alter_utmcampaign_user_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saleorder",
            options={
                "ordering": ["-date_order", "-id"],
                "verbose_name": "Orden de venta",
                "verbose_name_plural": "Órdenes de venta",
            },
        ),
        migrations.AddField(
            model_name="saleorder",
            name="access_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Token que permite el acceso al documento por link, saltando los permisos del destinatario (Odoo access_token).",
                max_length=64,
                verbose_name="Token de seguridad",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="campaign_id",
            field=models.ForeignKey(
                blank=True,
                db_column="campaign_id",
                help_text="Nombre con el que se distingue cada esfuerzo de campaña, p. ej. Fall_Drive, Christmas_Special.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmcampaign",
                verbose_name="Campaña",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="client_order_ref",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo client_order_ref ("Customer Reference"). El número con que el cliente identifica esta compra de su lado.',
                max_length=64,
                verbose_name="Referencia del cliente",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="commitment_date",
            field=models.DateTimeField(
                blank=True,
                help_text='Odoo commitment_date ("Delivery Date"). Fecha prometida al cliente; si se fija, el albarán se programa contra ella y no contra los plazos de cada producto.',
                null=True,
                verbose_name="Fecha de entrega",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo currency_id (compute, store=True, precompute, ondelete='restrict'). Sale de la tarifa, o de la empresa si el pedido no tiene tarifa. PROTECT ≙ restrict.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="base.rescurrency",
                verbose_name="Divisa",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="currency_rate",
            field=models.FloatField(
                default=1.0,
                help_text='Odoo currency_rate ("Currency Rate", digits=0 — sin redondeo declarado). Tasa aplicada al confirmar, congelada en el pedido para que un cambio posterior no reescriba el importe.',
                verbose_name="Tipo de cambio",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="fiscal_position",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo fiscal_position_id ("Fiscal Position"). Adapta impuestos y cuentas para un cliente o pedido concreto; su valor por omisión sale del cliente.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.accountfiscalposition",
                verbose_name="Posición fiscal",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="invoice_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upselling", "Oportunidad de venta adicional"),
                    ("invoiced", "Facturado por completo"),
                    ("to invoice", "Por facturar"),
                    ("no", "Nada que facturar"),
                ],
                help_text="Odoo invoice_status (compute, store=True). Deriva del estado de facturación de las líneas: por facturar, facturado por completo, oportunidad de venta adicional, o nada que facturar.",
                max_length=16,
                null=True,
                verbose_name="Estado de facturación",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo journal_id ("Invoicing Journal"). Si se fija, el pedido factura en este diario; si no, se usa el diario de ventas de menor secuencia. Acotado por SALE_JOURNAL_DOMAIN.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.accountjournal",
                verbose_name="Diario de facturación",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="medium_id",
            field=models.ForeignKey(
                blank=True,
                db_column="medium_id",
                help_text="Método de entrega: postal, correo, banner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmmedium",
                verbose_name="Medio",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="note",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Odoo note ("Terms and conditions"). Su valor inicial sale de los términos de la empresa.',
                verbose_name="Términos y condiciones",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="origin",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo origin ("Source Document"). Referencia del documento que originó esta solicitud de venta.',
                max_length=64,
                verbose_name="Documento de origen",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="partner_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo partner_invoice_id ("Invoice Address"). index="btree_not_null" en la fuente: aquí el índice lo pone Django con la FK; el tramo parcial se declara en Meta.indexes cuando el volumen lo justifique.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="base.respartner",
                verbose_name="Dirección de facturación",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="partner_shipping",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo partner_shipping_id ("Delivery Address").',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="base.respartner",
                verbose_name="Dirección de entrega",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="payment_term",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo payment_term_id ("Payment Terms"). Acotado por PAYMENT_TERM_DOMAIN: los de la empresa del pedido o los compartidos (company_id vacío).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.accountpaymentterm",
                verbose_name="Condiciones de pago",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="pending_email_template",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo pending_email_template_id ("Pending Email Template"). La plantilla del correo que queda por enviar de forma asíncrona.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="mail.mailtemplate",
                verbose_name="Plantilla del correo pendiente",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="preferred_payment_method_line",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo preferred_payment_method_line_id ("Payment Method"). Acotado por PREFERRED_PAYMENT_METHOD_DOMAIN: entrante y de la empresa del pedido.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="account.accountpaymentmethodline",
                verbose_name="Método de pago",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="prepayment_percent",
            field=models.FloatField(
                default=1.0,
                help_text='Odoo prepayment_percent ("Prepayment percentage"). Fracción del importe que el cliente debe pagar para confirmar. Su valor inicial sale de company.prepayment_percent.',
                verbose_name="Porcentaje de anticipo",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="pricelist",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo pricelist_id ("Pricelist"). Cambiarla sólo afecta a las líneas que se añadan después. Acotada por PRICELIST_DOMAIN.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="product.productpricelist",
                verbose_name="Tarifa",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo reference ("Payment Ref."). La comunicación de pago de este pedido — lo que el cliente ve en su estado de cuenta.',
                max_length=64,
                verbose_name="Referencia de pago",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="require_payment",
            field=models.BooleanField(
                default=False,
                help_text='Odoo require_payment ("Online payment"). Pide pago del cliente para confirmar el pedido. Su valor inicial sale de company.portal_confirmation_pay.',
                verbose_name="Pago en línea",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="require_signature",
            field=models.BooleanField(
                default=True,
                help_text='Odoo require_signature ("Online signature"). Pide firma del cliente para confirmar el pedido. Su valor inicial sale de company.portal_confirmation_sign.',
                verbose_name="Firma en línea",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="signature",
            field=models.ImageField(
                blank=True,
                help_text='Odoo signature ("Signature", attachment=True, máx. 1024×1024). Imagen de la firma con que el cliente aceptó.',
                null=True,
                upload_to="sale/signatures/",
                verbose_name="Firma",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="signed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Odoo signed_by ("Signed By"). Nombre de quien firmó.',
                max_length=128,
                verbose_name="Firmado por",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="signed_on",
            field=models.DateTimeField(
                blank=True,
                help_text='Odoo signed_on ("Signed On"). Momento de la firma.',
                null=True,
                verbose_name="Firmado el",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="source_id",
            field=models.ForeignKey(
                blank=True,
                db_column="source_id",
                help_text="Origen del enlace: un buscador, otro dominio, o el nombre de una lista de correo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmsource",
                verbose_name="Fuente",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="sale_order_tag_rel",
                help_text='Odoo tag_ids ("Tags", relation="sale_order_tag_rel"). El nombre de la tabla intermedia se conserva verbatim. Su groups=\'sales_team.group_sale_salesman\' se aplica por capacidad en la vista DRF (DEC-11), no en el campo.',
                related_name="sale_orders",
                to="sales_team.crmtag",
                verbose_name="Etiquetas",
            ),
        ),
        migrations.AddField(
            model_name="saleorder",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text='Odoo user_id ("Salesperson"). NO es el cliente —ese es ``partner``—: es quien atiende la venta. Acotado por SALESPERSON_GROUP: usuario interno del grupo de ventas de la empresa del pedido.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_orders_as_salesperson",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendedor",
            ),
        ),
        # ``date_order`` pasa de admitir NULL a ser NOT NULL con
        # ``default=timezone.now`` (≙ ``required=True`` +
        # ``default=fields.Datetime.now``, ``odoo19c:
        # sale/models/sale_order.py:92-96``). Las filas que ya existen con la
        # columna vacía son borradores: la ayuda de la fuente dice que ahí la
        # fecha es la de creación, así que se rellenan con ``created_at`` y no
        # con "ahora" — un pedido de hace un mes no nació hoy.
        #
        # El relleno va ANTES del ``AlterField``: al revés, PostgreSQL rechaza
        # el ``SET NOT NULL`` sobre una columna que todavía tiene NULL.
        migrations.RunPython(
            backfill_date_order_from_created_at,
            migrations.RunPython.noop,
            elidable=False,
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="date_order",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha de la orden (Odoo date_order): fecha de creación en borrador o enviada, fecha de confirmación una vez confirmada.",
            ),
        ),
        migrations.AddIndex(
            model_name="saleorder",
            index=models.Index(
                fields=["-date_order", "-id"], name="sale_order_date_order_id_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="saleorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("date_order__isnull", False), ("state", "sale")),
                    models.Q(("state", "sale"), _negated=True),
                    _connector="OR",
                ),
                name="sale_order_date_order_conditional_required",
                violation_error_message="Una orden de venta confirmada requiere fecha de confirmación.",
            ),
        ),
    ]
