# Generated by Django 6.0.5 on 2026-08-29 08:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_accountmove_posted_before"),
        ("base", "0065_rescompany_account_price_include_and_more"),
        ("product", "0013_productattributecustomvalue"),
        ("sale", "0009_sale_order_fk_symbols_to_reference"),
        ("uom", "0005_alter_uom_options_alter_uom_relative_uom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorderline",
            name="analytic_distribution",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Odoo analytic_distribution: {"id1,id2,...": porcentaje}.',
                null=True,
                verbose_name="Distribución analítica",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="collapse_composition",
            field=models.BooleanField(
                default=False,
                help_text='Odoo collapse_composition ("Collapse Composition", copy=True). Si las líneas de esta sección se ocultan en el reporte y en el portal.',
                verbose_name="Colapsar composición",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="collapse_prices",
            field=models.BooleanField(
                default=False,
                help_text='Odoo collapse_prices ("Collapse Prices", copy=True). Si los precios de las líneas de esta sección se ocultan en el reporte y en el portal.',
                verbose_name="Colapsar precios",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="combo_item_id",
            field=models.ForeignKey(
                blank=True,
                db_column="combo_item_id",
                help_text="Odoo combo_item_id. El elemento del combo que esta línea materializa.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_order_lines",
                to="product.productcomboitem",
                verbose_name="Elemento del combo",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="company_id",
            field=models.ForeignKey(
                blank=True,
                db_column="company_id",
                help_text="Odoo company_id (related order_id.company_id, store, index, precompute). La empresa que vende.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_order_lines",
                to="base.rescompany",
                verbose_name="Empresa",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="currency_id",
            field=models.ForeignKey(
                blank=True,
                db_column="currency_id",
                help_text="Odoo currency_id (related order_id.currency_id, store, precompute). La divisa en que se expresan los importes.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="base.rescurrency",
                verbose_name="Divisa",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="customer_lead",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text='Odoo customer_lead ("Lead Time", compute+store con readonly=False, required, precompute). Días entre la confirmación del pedido y el envío al cliente.',
                max_digits=16,
                verbose_name="Plazo de entrega",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="display_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("line_section", "Sección"),
                    ("line_subsection", "Subsección"),
                    ("line_note", "Nota"),
                ],
                help_text="Odoo display_type. Si tiene valor, la línea NO es una venta sino una sección, subsección o nota del documento.",
                max_length=16,
                null=True,
                verbose_name="Tipo de despliegue",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="extra_tax_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Odoo extra_tax_data. Campo técnico con los datos que el motor de cálculo de impuestos necesita conservar.",
                null=True,
                verbose_name="Datos extra de impuesto",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="invoice_lines",
            field=models.ManyToManyField(
                blank=True,
                db_table="sale_order_line_invoice_rel",
                help_text='Odoo invoice_lines ("Invoice Lines", relation sale_order_line_invoice_rel, copy=False). Las líneas de factura que facturan esta línea de pedido.',
                related_name="sale_line_ids",
                to="account.accountmoveline",
                verbose_name="Líneas de factura",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="invoice_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("upselling", "Oportunidad de venta adicional"),
                    ("invoiced", "Facturada por completo"),
                    ("to invoice", "Por facturar"),
                    ("no", "Nada que facturar"),
                ],
                help_text='Odoo invoice_status ("Invoice Status", compute+store).',
                max_length=16,
                null=True,
                verbose_name="Estado de facturación",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="is_downpayment",
            field=models.BooleanField(
                default=False,
                help_text='Odoo is_downpayment ("Is a down payment"). Los anticipos se crean al facturar desde el pedido; no se copian al duplicarlo.',
                verbose_name="Es anticipo",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="is_expense",
            field=models.BooleanField(
                default=False,
                help_text='Odoo is_expense ("Is expense"). Verdadero si la línea viene de un gasto o de una factura de proveedor.',
                verbose_name="Es gasto",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="linked_line_id",
            field=models.ForeignKey(
                blank=True,
                db_column="linked_line_id",
                help_text='Odoo linked_line_id ("Linked Order Line"). La línea de la que ésta depende — una opción de un combo, por ejemplo. Su inverso ES el One2many linked_line_ids de la fuente.',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_line_ids",
                to="sale.saleorderline",
                verbose_name="Línea enlazada",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="linked_virtual_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo linked_virtual_id. El enlace a otra línea por su virtual_id, para cuando ninguna de las dos tiene id todavía.",
                max_length=64,
                verbose_name="Id virtual enlazado",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="order_partner_id",
            field=models.ForeignKey(
                blank=True,
                db_column="order_partner_id",
                help_text='Odoo order_partner_id ("Customer", related order_id.partner_id, store, index, precompute).',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="base.respartner",
                verbose_name="Cliente",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="price_reduce_taxexcl",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text='Odoo price_reduce_taxexcl ("Price Reduce Tax excl", compute+store, precompute).',
                max_digits=12,
                verbose_name="Precio con descuento sin impuestos",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="price_reduce_taxinc",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text='Odoo price_reduce_taxinc ("Price Reduce Tax incl", compute+store, precompute).',
                max_digits=12,
                verbose_name="Precio con descuento con impuestos",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="product_no_variant_attribute_value_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="sale_order_line_product_no_variant_rel",
                help_text='Odoo product_no_variant_attribute_value_ids ("Extra Values"): los valores de atributo cuyo create_variant es no_variant — no generan variante pero sí precio extra.',
                related_name="sale_order_lines_no_variant",
                to="product.producttemplateattributevalue",
                verbose_name="Valores extra",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="product_uom_id",
            field=models.ForeignKey(
                blank=True,
                db_column="product_uom_id",
                help_text='Odoo product_uom_id ("Unit", compute+store con readonly=False). La unidad en que se vende esta línea.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_order_lines",
                to="uom.uom",
                verbose_name="Unidad",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="qty_delivered",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text='Odoo qty_delivered ("Delivery Quantity", compute+store con readonly=False, copy=False).',
                max_digits=16,
                verbose_name="Cantidad entregada",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="qty_delivered_method",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Manual"), ("analytic", "Analítico, desde gastos")],
                help_text='Odoo qty_delivered_method ("Method to update delivered qty", compute+store, precompute). Cómo se obtiene la cantidad entregada: a mano o desde gastos analíticos.',
                max_length=16,
                null=True,
                verbose_name="Método de cantidad entregada",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="qty_invoiced",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text='Odoo qty_invoiced ("Invoiced Quantity", compute+store).',
                max_digits=16,
                verbose_name="Cantidad facturada",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="qty_to_invoice",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                help_text='Odoo qty_to_invoice ("Quantity To Invoice", compute+store).',
                max_digits=16,
                verbose_name="Cantidad por facturar",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="salesman_id",
            field=models.ForeignKey(
                blank=True,
                db_column="salesman_id",
                help_text='Odoo salesman_id ("Salesperson", related order_id.user_id, store, precompute).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Comercial",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Cotización"),
                    ("sent", "Cotización enviada"),
                    ("sale", "Orden de venta"),
                    ("cancel", "Cancelada"),
                ],
                db_index=True,
                help_text='Odoo state ("Order Status", related order_id.state, store, precompute, copy=False). El vocabulario es el de la orden.',
                max_length=10,
                null=True,
                verbose_name="Estado de la orden",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="tax_ids",
            field=models.ManyToManyField(
                blank=True,
                db_table="sale_order_line_tax_rel",
                help_text='Odoo tax_ids ("Taxes", compute+store con readonly=False, check_company). Los impuestos que gravan esta línea.',
                related_name="sale_order_lines",
                to="account.accounttax",
                verbose_name="Impuestos",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="technical_price_unit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Odoo technical_price_unit. El precio antes de que el usuario lo altere a mano; sirve para detectar el cambio.",
                max_digits=12,
                verbose_name="Precio unitario técnico",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="untaxed_amount_invoiced",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text='Odoo untaxed_amount_invoiced ("Untaxed Invoiced Amount", compute+store).',
                max_digits=12,
                verbose_name="Importe facturado sin impuestos",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="untaxed_amount_to_invoice",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text='Odoo untaxed_amount_to_invoice ("Untaxed Amount To Invoice", compute+store).',
                max_digits=12,
                verbose_name="Importe por facturar sin impuestos",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="virtual_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo virtual_id. Identifica la línea ANTES de que la base le dé un id — mientras el documento se edita en el cliente.",
                max_length=64,
                verbose_name="Id virtual",
            ),
        ),
    ]
