# Generated by Django 6.0.5 on 2026-08-29 08:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0010_saleorderline_analytic_distribution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorderline",
            name="price_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text='Odoo price_subtotal ("Subtotal", compute+store, precompute). El importe de la línea sin impuestos.',
                max_digits=12,
                verbose_name="Subtotal",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="price_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text='Odoo price_tax ("Total Tax", compute+store, precompute). El impuesto de la línea.',
                max_digits=12,
                verbose_name="Impuesto total",
            ),
        ),
        migrations.AddField(
            model_name="saleorderline",
            name="price_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text='Odoo price_total ("Total", compute+store, precompute). El importe de la línea con impuestos.',
                max_digits=12,
                verbose_name="Total",
            ),
        ),
    ]
