# Generated by Django 6.0.5 on 2026-09-02 16:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0011_saleorderline_price_subtotal_saleorderline_price_tax_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleorder",
            name="amount_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text="IVA de la orden, suma de líneas (Odoo amount_tax).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="amount_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text="Total de la orden, suma de líneas (Odoo amount_total).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="saleorder",
            name="amount_untaxed",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text="Subtotal sin IVA, suma de líneas (Odoo amount_untaxed).",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="saleorderline",
            name="price_reduce_taxexcl",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text='Odoo price_reduce_taxexcl ("Price Reduce Tax excl", compute+store, precompute).',
                max_digits=12,
                verbose_name="Precio con descuento sin impuestos",
            ),
        ),
        migrations.AlterField(
            model_name="saleorderline",
            name="price_reduce_taxinc",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text='Odoo price_reduce_taxinc ("Price Reduce Tax incl", compute+store, precompute).',
                max_digits=12,
                verbose_name="Precio con descuento con impuestos",
            ),
        ),
        migrations.AlterField(
            model_name="saleorderline",
            name="price_subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text='Odoo price_subtotal ("Subtotal", compute+store, precompute). El importe de la línea sin impuestos.',
                max_digits=12,
                verbose_name="Subtotal",
            ),
        ),
        migrations.AlterField(
            model_name="saleorderline",
            name="price_tax",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text='Odoo price_tax ("Total Tax", compute+store, precompute). El impuesto de la línea.',
                max_digits=12,
                verbose_name="Impuesto total",
            ),
        ),
        migrations.AlterField(
            model_name="saleorderline",
            name="price_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                help_text='Odoo price_total ("Total", compute+store, precompute). El importe de la línea con impuestos.',
                max_digits=12,
                verbose_name="Total",
            ),
        ),
    ]
