# Generated by Django 6.0.5 on 2026-08-02 22:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        ("uom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del atributo (Odoo product.attribute.name).",
                        max_length=100,
                    ),
                ),
                (
                    "create_variant",
                    models.CharField(
                        choices=[
                            ("always", "Al instante"),
                            ("dynamic", "Dinámicamente"),
                            ("no_variant", "Nunca (no genera variante)"),
                        ],
                        default="always",
                        help_text="Cuándo genera variante (Odoo create_variant).",
                        max_length=16,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("radio", "Radio"),
                            ("select", "Selección"),
                            ("color", "Color"),
                        ],
                        default="radio",
                        help_text="Cómo se muestra (Odoo display_type).",
                        max_length=16,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=10, help_text="Orden (Odoo sequence)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Atributo de producto",
                "verbose_name_plural": "Atributos de producto",
                "db_table": "product_attribute",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="Referencia interna",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Número de artículo internacional. Único por compañía.",
                        max_length=64,
                        verbose_name="Código de barras",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar oculta la variante sin borrarla.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "combination_indices",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Ids de los valores de atributo, ORDENADOS y separados por coma. Almacenado para poder buscar una combinación en una consulta.",
                        max_length=255,
                        verbose_name="Índices de la combinación",
                    ),
                ),
                (
                    "standard_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Coste POR VARIANTE: dos tallas pueden costar distinto. Sobreescribe el de la ficha.",
                        max_digits=16,
                        verbose_name="Coste",
                    ),
                ),
                (
                    "volume",
                    models.FloatField(
                        default=0,
                        help_text="Sobreescribe el de la ficha: el envío se calcula sobre lo que se mueve.",
                        verbose_name="Volumen",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0,
                        help_text="Sobreescribe el de la ficha, por la misma razón.",
                        verbose_name="Peso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de producto",
                "verbose_name_plural": "Variantes de producto",
                "db_table": "product_product",
                "ordering": ["default_code", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Valor (Odoo product.attribute.value.name).",
                        max_length=100,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=10, help_text="Orden (Odoo sequence)."
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="Atributo (Odoo attribute_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="product.productattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de atributo",
                "verbose_name_plural": "Valores de atributo",
                "db_table": "product_attribute_value",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nombre"
                    ),
                ),
                (
                    "complete_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text='Ruta legible "Padre / Hijo". Almacenado y repropagado a los descendientes al renombrar un padre.',
                        max_length=1024,
                        verbose_name="Nombre completo",
                    ),
                ),
                (
                    "parent_path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text='Ruta materializada de ids: responde "qué hay debajo" con un LIKE en vez de N consultas.',
                        max_length=1024,
                        verbose_name="Ruta del árbol",
                    ),
                ),
                (
                    "product_properties_definition",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Esquema de propiedades libres que heredan los productos de esta categoría. La maquinaria que lo aplica vive en product_template.",
                        verbose_name="Propiedades del producto",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo parent_id. El related_name es child_id, que es como la referencia llama al One2many inverso.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_id",
                        to="product.productcategory",
                        verbose_name="Categoría padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de producto",
                "verbose_name_plural": "Categorías de producto",
                "db_table": "product_category",
                "ordering": ["complete_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCombo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la elección"
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10,
                        help_text="Orden de la elección dentro del menú. En la referencia es copy=False: al duplicar, el orden NO se hereda.",
                        verbose_name="Secuencia",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = la elección sirve a todas las compañías.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_ids",
                        to="base.rescompany",
                        verbose_name="Compañía",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elección de combo",
                "verbose_name_plural": "Elecciones de combo",
                "db_table": "product_combo",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar archiva el documento sin borrar el adjunto.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10,
                        help_text="Orden de presentación dentro del producto.",
                        verbose_name="Secuencia",
                    ),
                ),
                (
                    "ir_attachment",
                    models.ForeignKey(
                        help_text="Odoo ir_attachment_id: el enlace de _inherits. FK real, NO herencia multi-tabla (ver el docstring del módulo).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_document_ids",
                        to="base.irattachment",
                        verbose_name="Adjunto relacionado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de producto",
                "verbose_name_plural": "Documentos de producto",
                "db_table": "product_document",
                "ordering": ["sequence", "ir_attachment__name"],
            },
        ),
        migrations.CreateModel(
            name="ProductPricelist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la tarifa"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar oculta la tarifa sin borrarla.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=16,
                        help_text="Desempate cuando varias tarifas encajan: gana la menor.",
                        verbose_name="Secuencia",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = la tarifa sirve a todas las compañías.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelist_ids",
                        to="base.rescompany",
                        verbose_name="Compañía",
                    ),
                ),
                (
                    "country_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Decide qué tarifa ve un visitante según de dónde llega. No interviene en el cálculo.",
                        related_name="pricelist_ids",
                        to="base.rescountrygroup",
                        verbose_name="Grupos de países",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda en que sus reglas expresan los importes.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricelist_ids",
                        to="base.rescurrency",
                        verbose_name="Moneda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa",
                "verbose_name_plural": "Tarifas",
                "db_table": "product_pricelist",
                "ordering": ["sequence", "id", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extra_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sobrecoste de elegir esta opción. En la referencia es Float; aquí Monetary porque se suma a list_price, que ya divergió a Monetary (ver el docstring del módulo).",
                        max_digits=16,
                        verbose_name="Precio adicional",
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        help_text="La elección que ofrece esta opción. Al borrarla se borran sus opciones (Odoo ondelete=cascade).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_item_ids",
                        to="product.productcombo",
                        verbose_name="Elección",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Denormalizada desde la elección (Odoo related + store=True + precompute=True). Se fija en save(), no se captura.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="combo_item_ids",
                        to="base.rescompany",
                        verbose_name="Compañía",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text='Odoo string="Options", ondelete=restrict: no se borra un producto que alguna elección todavía ofrece.',
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combo_item_ids",
                        to="product.productproduct",
                        verbose_name="Opción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de combo",
                "verbose_name_plural": "Opciones de combo",
                "db_table": "product_combo_item",
                "ordering": ["combo_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_1920",
                    models.ImageField(
                        blank=True,
                        help_text="Odoo image_1920. Original; las derivadas salen de aquí.",
                        null=True,
                        upload_to="images/original/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "image_1024",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/1024/",
                        verbose_name="Imagen 1024",
                    ),
                ),
                (
                    "image_512",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/512/",
                        verbose_name="Imagen 512",
                    ),
                ),
                (
                    "image_256",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/256/",
                        verbose_name="Imagen 256",
                    ),
                ),
                (
                    "image_128",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/128/",
                        verbose_name="Imagen 128",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nombre"
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Orden al listar productos.",
                        verbose_name="Secuencia",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "description_purchase",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción de compra"
                    ),
                ),
                (
                    "description_sale",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Se copia a cada pedido, albarán y factura del cliente.",
                        verbose_name="Descripción de venta",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("consu", "Bienes"),
                            ("service", "Servicio"),
                            ("combo", "Combo"),
                        ],
                        default="consu",
                        max_length=16,
                        verbose_name="Tipo de producto",
                    ),
                ),
                (
                    "service_tracking",
                    models.CharField(
                        choices=[("no", "Nada")],
                        default="no",
                        max_length=16,
                        verbose_name="Crear al confirmar el pedido",
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Precio al que se vende al cliente. Monetary, no Float — ver el docstring del módulo.",
                        max_digits=16,
                        verbose_name="Precio de venta",
                    ),
                ),
                (
                    "standard_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Valor del producto. En la referencia lo calcula la valoración AVCO del inventario; aquí es columna, y el cálculo automático no está portado.",
                        max_digits=16,
                        verbose_name="Coste",
                    ),
                ),
                ("volume", models.FloatField(default=0, verbose_name="Volumen")),
                ("weight", models.FloatField(default=0, verbose_name="Peso")),
                (
                    "sale_ok",
                    models.BooleanField(default=True, verbose_name="Se puede vender"),
                ),
                (
                    "purchase_ok",
                    models.BooleanField(default=True, verbose_name="Se puede comprar"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar oculta el producto sin borrarlo.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "color",
                    models.IntegerField(default=0, verbose_name="Índice de color"),
                ),
                (
                    "default_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="Referencia interna",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(default=False, verbose_name="Favorito"),
                ),
                (
                    "has_configurable_attributes",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo lo calcula y almacena: verdadero si alguna línea de atributo ofrece más de un valor.",
                        verbose_name="Producto configurable",
                    ),
                ),
                (
                    "product_properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Pares libres cuyo esquema declara categ.product_properties_definition.",
                        verbose_name="Propiedades",
                    ),
                ),
                (
                    "categ",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo categ_id. FK real: product.category ya está portado.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_tmpl_ids",
                        to="product.productcategory",
                        verbose_name="Categoría de producto",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = producto compartido por todas las compañías.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_tmpl_ids",
                        to="base.rescompany",
                        verbose_name="Compañía",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo uom_id. FK real: uom.uom ya está portado.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_tmpl_ids",
                        to="uom.uom",
                        verbose_name="Unidad de medida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "product_template",
                "ordering": ["-is_favorite", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_1920",
                    models.ImageField(
                        blank=True,
                        help_text="Odoo image_1920. Original; las derivadas salen de aquí.",
                        null=True,
                        upload_to="images/original/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "image_1024",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/1024/",
                        verbose_name="Imagen 1024",
                    ),
                ),
                (
                    "image_512",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/512/",
                        verbose_name="Imagen 512",
                    ),
                ),
                (
                    "image_256",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/256/",
                        verbose_name="Imagen 256",
                    ),
                ),
                (
                    "image_128",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/128/",
                        verbose_name="Imagen 128",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre"
                    ),
                ),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                (
                    "color",
                    models.CharField(
                        default="#3C3C3C", max_length=16, verbose_name="Color"
                    ),
                ),
                (
                    "visible_to_customers",
                    models.BooleanField(
                        default=True, verbose_name="Visible para el cliente"
                    ),
                ),
                (
                    "product_variants",
                    models.ManyToManyField(
                        blank=True,
                        db_table="product_tag_product_product_rel",
                        help_text="Sólo variantes sueltas: su ficha debe tener atributos y NO estar ya etiquetada. Ver el docstring del módulo.",
                        related_name="additional_product_tag_ids",
                        to="product.productproduct",
                        verbose_name="Variantes de producto",
                    ),
                ),
                (
                    "product_templates",
                    models.ManyToManyField(
                        blank=True,
                        db_table="product_tag_product_template_rel",
                        related_name="product_tag_ids",
                        to="product.producttemplate",
                        verbose_name="Fichas de producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta de producto",
                "verbose_name_plural": "Etiquetas de producto",
                "db_table": "product_tag",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductSupplierinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Se usa al imprimir una solicitud de presupuesto. Vacío = se usa el nombre interno.",
                        max_length=255,
                        verbose_name="Nombre del producto para el proveedor",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Idem con la referencia: vacío = se usa la interna.",
                        max_length=64,
                        verbose_name="Código del producto para el proveedor",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Prioridad del proveedor en la lista. Menor gana.",
                        verbose_name="Secuencia",
                    ),
                ),
                (
                    "min_qty",
                    models.FloatField(
                        default=0,
                        help_text="Cantidad a partir de la cual aplica este precio, expresada en la unidad del proveedor.",
                        verbose_name="Cantidad mínima",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Precio de compra en la unidad del proveedor. Monetary, no Float — ver el docstring del módulo.",
                        max_digits=16,
                        verbose_name="Precio unitario",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Porcentaje sobre el precio. Mismo tipo y precisión que purchase_order_line.discount, que es quien lo consume.",
                        max_digits=5,
                        verbose_name="Descuento (%)",
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        blank=True,
                        help_text="Desde cuándo rige este precio.",
                        null=True,
                        verbose_name="Fecha de inicio",
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True,
                        help_text="Hasta cuándo rige este precio.",
                        null=True,
                        verbose_name="Fecha de fin",
                    ),
                ),
                (
                    "delay",
                    models.IntegerField(
                        default=1,
                        help_text="Días entre confirmar la compra y recibir la mercancía. El planificador lo usa para calcular cuándo pedir.",
                        verbose_name="Plazo de entrega (días)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = la tarifa sirve a todas las compañías.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplierinfo_ids",
                        to="base.rescompany",
                        verbose_name="Compañía",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda en que el proveedor cotiza. Requerido en la referencia, con la de la compañía por defecto.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplierinfo_ids",
                        to="base.rescurrency",
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Odoo partner_id. Es el nombre por el que se muestra la fila (_rec_name en la referencia).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplierinfo_ids",
                        to="base.respartner",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vacío = el precio aplica a TODAS las variantes de la plantilla. Con valor, sólo a esa — y gana sobre la fila de plantilla. El related_name no lo nombra la referencia.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplierinfo_ids",
                        to="product.productproduct",
                        verbose_name="Variante de producto",
                    ),
                ),
                (
                    "product_uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unidad en que el proveedor cotiza, que puede no ser la del producto. Odoo la calcula y almacena; aquí se siembra en save() desde la variante o la plantilla.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplierinfo_ids",
                        to="uom.uom",
                        verbose_name="Unidad del proveedor",
                    ),
                ),
                (
                    "product_tmpl",
                    models.ForeignKey(
                        help_text="Obligatorio. Odoo lo calcula desde la variante cuando sólo se da ésta; aquí lo hace save().",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_ids",
                        to="product.producttemplate",
                        verbose_name="Plantilla de producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa de proveedor",
                "verbose_name_plural": "Tarifas de proveedor",
                "db_table": "product_supplierinfo",
                "ordering": ["sequence", "-min_qty", "price", "id"],
            },
        ),
        migrations.AddField(
            model_name="productproduct",
            name="product_tmpl",
            field=models.ForeignKey(
                help_text="Odoo product_tmpl_id. FK real, NO herencia multi-tabla: muchas variantes por ficha. Ver el docstring del módulo.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variant_ids",
                to="product.producttemplate",
                verbose_name="Ficha de producto",
            ),
        ),
        migrations.CreateModel(
            name="ProductPricelistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applied_on",
                    models.CharField(
                        choices=[
                            ("0_product_variant", "Variante de producto"),
                            ("1_product", "Producto"),
                            ("2_product_category", "Categoría de producto"),
                            ("3_global", "Todos los productos"),
                        ],
                        default="3_global",
                        help_text="El prefijo numérico ES la precedencia — ver el docstring del módulo.",
                        max_length=32,
                        verbose_name="Se aplica a",
                    ),
                ),
                (
                    "min_quantity",
                    models.FloatField(
                        default=0,
                        help_text="A igual alcance gana la regla de mínimo mayor: la más exigente.",
                        verbose_name="Cantidad mínima",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de inicio"
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de fin"
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("list_price", "Precio de venta"),
                            ("standard_price", "Coste"),
                            ("pricelist", "Otra tarifa"),
                        ],
                        default="list_price",
                        max_length=32,
                        verbose_name="Basado en",
                    ),
                ),
                (
                    "compute_price",
                    models.CharField(
                        choices=[
                            ("percentage", "Descuento"),
                            ("formula", "Fórmula"),
                            ("fixed", "Precio fijo"),
                        ],
                        db_index=True,
                        default="fixed",
                        max_length=16,
                        verbose_name="Cálculo del precio",
                    ),
                ),
                (
                    "fixed_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Precio fijo",
                    ),
                ),
                (
                    "percent_price",
                    models.FloatField(default=0, verbose_name="Descuento (%)"),
                ),
                (
                    "price_discount",
                    models.FloatField(
                        default=0, verbose_name="Descuento de fórmula (%)"
                    ),
                ),
                (
                    "price_markup",
                    models.FloatField(
                        default=0,
                        help_text="Se usa EN LUGAR del descuento cuando la base es el coste; la fórmula lo aplica como descuento negativo.",
                        verbose_name="Margen sobre coste (%)",
                    ),
                ),
                (
                    "price_round",
                    models.FloatField(
                        default=0,
                        help_text="Se aplica ANTES del recargo — ver el docstring del módulo.",
                        verbose_name="Redondeo",
                    ),
                ),
                (
                    "price_surcharge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Recargo",
                    ),
                ),
                (
                    "price_min_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Se mide contra la BASE, no contra el precio en curso.",
                        max_digits=16,
                        verbose_name="Margen mínimo",
                    ),
                ),
                (
                    "price_max_margin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Se mide contra la BASE, no contra el precio en curso.",
                        max_digits=16,
                        verbose_name="Margen máximo",
                    ),
                ),
                (
                    "base_pricelist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_item_ids",
                        to="product.productpricelist",
                        verbose_name="Otra tarifa",
                    ),
                ),
                (
                    "categ",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelist_item_ids",
                        to="product.productcategory",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "pricelist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_ids",
                        to="product.productpricelist",
                        verbose_name="Tarifa",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelist_rule_ids",
                        to="product.productproduct",
                        verbose_name="Variante",
                    ),
                ),
                (
                    "product_tmpl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricelist_rule_ids",
                        to="product.producttemplate",
                        verbose_name="Producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de tarifa",
                "verbose_name_plural": "Reglas de tarifa",
                "db_table": "product_pricelist_item",
                "ordering": ["applied_on", "-min_quantity", "-categ", "-id"],
            },
        ),
        migrations.AddField(
            model_name="productcombo",
            name="product_tmpls",
            field=models.ManyToManyField(
                blank=True,
                help_text="Odoo declara este M2M en product.template como combo_ids; aquí se declara del lado del combo con ese related_name, así template.combo_ids es el mismo nombre de la fuente. La referencia no nombra el lado inverso.",
                related_name="combo_ids",
                to="product.producttemplate",
                verbose_name="Productos combo que la usan",
            ),
        ),
        migrations.CreateModel(
            name="ProductTemplateAttributeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=10, help_text="Orden (Odoo sequence)."
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="Atributo (Odoo attribute_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_lines",
                        to="product.productattribute",
                    ),
                ),
                (
                    "product_tmpl",
                    models.ForeignKey(
                        help_text="Plantilla de producto (Odoo product_tmpl_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_lines",
                        to="product.producttemplate",
                    ),
                ),
                (
                    "values",
                    models.ManyToManyField(
                        help_text="Valores aplicables a este producto (Odoo value_ids).",
                        related_name="template_lines",
                        to="product.productattributevalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de atributo de producto",
                "verbose_name_plural": "Líneas de atributo de producto",
                "db_table": "product_template_attribute_line",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductTemplateAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sobreprecio de esta opción (Odoo price_extra).",
                        max_digits=12,
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        help_text="Valor del atributo (Odoo product_attribute_value_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_values",
                        to="product.productattributevalue",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        help_text="Línea (Odoo attribute_line_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_values",
                        to="product.producttemplateattributeline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de atributo por producto",
                "verbose_name_plural": "Valores de atributo por producto",
                "db_table": "product_template_attribute_value",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="productproduct",
            name="product_template_attribute_values",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_variant_combination",
                related_name="product_variant_ids",
                to="product.producttemplateattributevalue",
                verbose_name="Valores de atributo",
            ),
        ),
        migrations.CreateModel(
            name="ProductUom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barcode",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Código de barras"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_uom_ids",
                        to="base.rescompany",
                        verbose_name="Compañía",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_uom_ids",
                        to="product.productproduct",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_uom_ids",
                        to="uom.uom",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empaquetado de producto",
                "verbose_name_plural": "Empaquetados de producto",
                "db_table": "product_uom",
            },
        ),
        migrations.AddConstraint(
            model_name="productattributevalue",
            constraint=models.UniqueConstraint(
                fields=("attribute", "name"), name="unique_attribute_value_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttag",
            constraint=models.UniqueConstraint(
                fields=("name",), name="product_tag_name_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttemplateattributeline",
            constraint=models.UniqueConstraint(
                fields=("product_tmpl", "attribute"), name="unique_template_attribute"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttemplateattributevalue",
            constraint=models.UniqueConstraint(
                fields=("line", "attribute_value"),
                name="unique_template_attribute_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="productproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode", ""), _negated=True),
                fields=("barcode",),
                name="product_product_barcode_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="productuom",
            constraint=models.UniqueConstraint(
                fields=("barcode",), name="product_uom_barcode_uniq"
            ),
        ),
    ]
