# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del atributo (Odoo product.attribute.name).",
                        max_length=100,
                    ),
                ),
                (
                    "create_variant",
                    models.CharField(
                        choices=[
                            ("always", "Al instante"),
                            ("dynamic", "Dinámicamente"),
                            ("no_variant", "Nunca (no genera variante)"),
                        ],
                        default="always",
                        help_text="Cuándo genera variante (Odoo create_variant).",
                        max_length=16,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        choices=[
                            ("radio", "Radio"),
                            ("select", "Selección"),
                            ("color", "Color"),
                        ],
                        default="radio",
                        help_text="Cómo se muestra (Odoo display_type).",
                        max_length=16,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=10, help_text="Orden (Odoo sequence)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Atributo de producto",
                "verbose_name_plural": "Atributos de producto",
                "db_table": "product_attribute",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Valor (Odoo product.attribute.value.name).",
                        max_length=100,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=10, help_text="Orden (Odoo sequence)."
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="Atributo (Odoo attribute_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="product.productattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de atributo",
                "verbose_name_plural": "Valores de atributo",
                "db_table": "product_attribute_value",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductTemplateAttributeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=10, help_text="Orden (Odoo sequence)."
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        help_text="Atributo (Odoo attribute_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_lines",
                        to="product.productattribute",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto (Odoo product_tmpl_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_lines",
                        to="catalogue.product",
                    ),
                ),
                (
                    "values",
                    models.ManyToManyField(
                        help_text="Valores aplicables a este producto (Odoo value_ids).",
                        related_name="template_lines",
                        to="product.productattributevalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de atributo de producto",
                "verbose_name_plural": "Líneas de atributo de producto",
                "db_table": "product_template_attribute_line",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductTemplateAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sobreprecio de esta opción (Odoo price_extra).",
                        max_digits=12,
                    ),
                ),
                (
                    "attribute_value",
                    models.ForeignKey(
                        help_text="Valor del atributo (Odoo product_attribute_value_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_values",
                        to="product.productattributevalue",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        help_text="Línea (Odoo attribute_line_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_values",
                        to="product.producttemplateattributeline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de atributo por producto",
                "verbose_name_plural": "Valores de atributo por producto",
                "db_table": "product_template_attribute_value",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="productattributevalue",
            constraint=models.UniqueConstraint(
                fields=("attribute", "name"), name="unique_attribute_value_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttemplateattributeline",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute"), name="unique_template_attribute"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttemplateattributevalue",
            constraint=models.UniqueConstraint(
                fields=("line", "attribute_value"),
                name="unique_template_attribute_value",
            ),
        ),
    ]
