# Generated by Django 6.0.5 on 2026-08-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttemplate",
            name="is_published",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Visible en la tienda. Por defecto NO — igual que _default_is_published de la referencia: dar de alta un producto no es publicarlo.",
                verbose_name="Publicado",
            ),
        ),
    ]
