# Generated by Django 6.0.5 on 2026-08-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_sequence_prefix_number"),
        ("product", "0002_website_published_mixin"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="property_account_expense_categ",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de gasto de la categoría, usada al validar una factura de proveedor cuando el producto no declara la suya (Odoo property_account_expense_categ_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="property_account_income_categ",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de ingreso de la categoría, usada al validar una factura de cliente cuando el producto no declara la suya (Odoo property_account_income_categ_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="account_tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_template_account_tag_rel",
                help_text="Etiquetas a poner en los apuntes de base e impuesto generados por este producto (Odoo account_tag_ids; applicability=products).",
                related_name="product_templates",
                to="account.accountaccounttag",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="property_account_expense",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de gasto del producto. Vacía = se usa la de la categoría (Odoo property_account_expense_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="property_account_income",
            field=models.ForeignKey(
                blank=True,
                help_text="Cuenta de ingreso del producto. Vacía = se usa la de la categoría (Odoo property_account_income_id).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="account.accountaccount",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="supplier_taxes",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_supplier_taxes_rel",
                help_text="Impuestos por defecto al COMPRAR el producto (Odoo supplier_taxes_id; type_tax_use=purchase). Sin default por la misma razón que taxes.",
                related_name="product_templates_purchase",
                to="account.accounttax",
            ),
        ),
        migrations.AddField(
            model_name="producttemplate",
            name="taxes",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_taxes_rel",
                help_text="Impuestos por defecto al VENDER el producto (Odoo taxes_id; type_tax_use=sale). Sin default: el de la referencia lee ResCompany.account_sale_tax_id, campo del Bloque 1 aún ausente (tarea #137).",
                related_name="product_templates_sale",
                to="account.accounttax",
            ),
        ),
    ]
