# Generated by Django 6.0.5 on 2026-08-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0015_accountgroup_account_group_prefix_length_eq"),
        ("product", "0003_account_inherit_surface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producttemplate",
            name="supplier_taxes",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_supplier_taxes_rel",
                help_text="Impuestos por defecto al COMPRAR el producto (Odoo supplier_taxes_id; type_tax_use=purchase). Hereda ResCompany.account_purchase_tax igual que taxes.",
                related_name="product_templates_purchase",
                to="account.accounttax",
            ),
        ),
        migrations.AlterField(
            model_name="producttemplate",
            name="taxes",
            field=models.ManyToManyField(
                blank=True,
                db_table="product_taxes_rel",
                help_text="Impuestos por defecto al VENDER el producto (Odoo taxes_id; type_tax_use=sale). Si se crea vacío, hereda ResCompany.account_sale_tax (ver el receptor de abajo).",
                related_name="product_templates_sale",
                to="account.accounttax",
            ),
        ),
    ]
