# Generated by Django 6.0.5 on 2026-08-28 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockvaluationlayer",
            name="product",
            field=models.ForeignKey(
                db_column="product_id",
                help_text="Producto (Odoo product_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valuation_layers",
                to="product.productproduct",
            ),
        ),
        migrations.RenameField(
            model_name="stockvaluationlayer",
            old_name="product",
            new_name="product_id",
        ),
        migrations.AlterField(
            model_name="stockvaluationlayer",
            name="stock_move",
            field=models.ForeignKey(
                blank=True,
                db_column="stock_move_id",
                help_text="Movimiento (Odoo stock_move_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="valuation_layers",
                to="stock.stockmove",
            ),
        ),
        migrations.RenameField(
            model_name="stockvaluationlayer",
            old_name="stock_move",
            new_name="stock_move_id",
        ),
    ]
