# Generated by Django 6.0.5 on 2026-08-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetvehicle",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Marca/Modelo/Placa. Odoo name (compute + store): se almacena para poder ordenar y buscar por texto. Lo calcula save() con compute_vehicle_name().",
                max_length=255,
            ),
        ),
    ]
