# Generated by Django 6.0.5 on 2026-08-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_accountmoveline_vehicle"),
        ("fleet", "0002_fleetvehicle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetvehiclelogservices",
            name="account_move_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Línea de factura de proveedor que originó este servicio (Odoo account_move_line_id, one2one). ``unique=True`` porque una línea genera a lo sumo un servicio (idempotencia verificada antes de crear).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicle_log_services",
                to="account.accountmoveline",
                unique=True,
            ),
        ),
    ]
