# Generated by Django 6.0.5 on 2026-08-19 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_fleetvehiclelogservices_account_move_line"),
        ("hr", "0009_hremployeepublic"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleetvehicle",
            name="driver_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo driver_employee_id (compute+store; su índice btree_not_null no se fabrica — divergencia 2). El related_name conserva el nombre del One2many car_ids de la referencia (hr_fleet/employee.py).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="car_ids",
                to="hr.hremployee",
                verbose_name="Driver (Employee)",
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="future_driver_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo future_driver_employee_id (compute+store).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="future_car_ids",
                to="hr.hremployee",
                verbose_name="Future Driver (Employee)",
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicle",
            name="mobility_card",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo mobility_card (compute+store — lo refresca el receptor pre_save de hr_fleet).",
                max_length=64,
                verbose_name="Tarjeta de movilidad",
            ),
        ),
        migrations.AddField(
            model_name="fleetvehicleassignationlog",
            name="driver_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo driver_employee_id (compute+store, readonly=False — lo deriva el receptor pre_save cuando el llamador no lo fija).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleet_assignation_logs",
                to="hr.hremployee",
                verbose_name="Driver (Employee)",
            ),
        ),
        migrations.AddField(
            model_name="fleetvehiclelogservices",
            name="purchaser_employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo purchaser_employee_id (compute+store, readonly=False — lo rellena sync_defaults).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fleet_service_logs_as_employee",
                to="hr.hremployee",
                verbose_name="Driver (Employee)",
            ),
        ),
    ]
