# Generated by Django 6.0.5 on 2026-08-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0004_fleetvehicle_driver_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fleetvehicle",
            name="mobility_card",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo mobility_card (compute+store — lo refresca el receptor pre_save de hr_fleet).",
                verbose_name="Tarjeta de movilidad",
            ),
        ),
    ]
