# Generated by Django 6.0.5 on 2026-07-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        db_index=True,
                        help_text="Canal destino (Odoo bus.bus.channel).",
                        max_length=255,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Carga JSON {type, payload} (Odoo bus.bus.message)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje del bus",
                "verbose_name_plural": "Mensajes del bus",
                "db_table": "bus_bus",
                "ordering": ["id"],
            },
        ),
    ]
