# Generated by Django 6.0.5 on 2026-07-12 02:15

import apps.newsletter.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "audience_filter",
                    models.CharField(
                        default="CONFIRMED",
                        help_text="Status objetivo (default: CONFIRMED).",
                        max_length=32,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("recipients_count", models.PositiveIntegerField(default=0)),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_campaigns_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Campana de newsletter",
                "verbose_name_plural": "Campanas de newsletter",
                "db_table": "newsletter_campaign",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("CONFIRMED", "Confirmado"),
                            ("UNSUBSCRIBED", "Dado de baja"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_token",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.CharField(
                        default=apps.newsletter.models._generate_unsubscribe_token,
                        max_length=200,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscriptor de newsletter",
                "verbose_name_plural": "Suscriptores de newsletter",
                "db_table": "newsletter_subscriber",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="newsletter__status_c9941b_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="newsletter__created_4f8f93_idx"
                    ),
                ],
            },
        ),
    ]
