# Generated by Django 5.0.1 on 2026-05-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_emailtask"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailtask",
            new_name="notificatio_status_a7d243_idx",
            old_name="notifications_emailtask_status_idx",
        ),
    ]
