# Generated by Django 6.0.5 on 2026-07-18 06:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0003_product_weight_kg"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la plantilla (Odoo name).", max_length=150
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Archivar sin borrar (Odoo active)."
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de listado (Odoo sequence)."
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Términos y condiciones (Odoo note).",
                    ),
                ),
                (
                    "number_of_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Días de validez de la cotización (Odoo number_of_days).",
                    ),
                ),
                (
                    "require_signature",
                    models.BooleanField(
                        default=False,
                        help_text="Requiere firma online (Odoo require_signature).",
                    ),
                ),
                (
                    "require_payment",
                    models.BooleanField(
                        default=False,
                        help_text="Requiere pago online (Odoo require_payment).",
                    ),
                ),
                (
                    "prepayment_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Porcentaje de anticipo (Odoo prepayment_percent).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de cotización",
                "verbose_name_plural": "Plantillas de cotización",
                "db_table": "sale_order_template",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="SaleOrderTemplateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.IntegerField(
                        default=10,
                        help_text="Orden dentro de la plantilla (Odoo sequence).",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción de la línea (Odoo name).",
                    ),
                ),
                (
                    "product_uom_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Cantidad (Odoo product_uom_qty).",
                        max_digits=12,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Producto"),
                            ("line_section", "Sección"),
                            ("line_note", "Nota"),
                        ],
                        default="",
                        help_text="Tipo de línea: producto/sección/nota (Odoo display_type).",
                        max_length=12,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Producto (Odoo product_id); NULL en sección/nota.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_template_lines",
                        to="catalogue.product",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        help_text="Plantilla (Odoo sale_order_template_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_line",
                        to="sale_management.saleordertemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de plantilla de cotización",
                "verbose_name_plural": "Líneas de plantilla de cotización",
                "db_table": "sale_order_template_line",
                "ordering": ["template", "sequence"],
            },
        ),
    ]
