# Generated by Django 6.0.5 on 2026-07-12 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Módulo",
                "verbose_name_plural": "Módulos",
                "db_table": "authz_module",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Capability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Formato 'dominio.verbo' (p.ej. orders.refund).",
                        max_length=100,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Categoría"
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Su uso exitoso se audita en AuthzEvent (DEC-07).",
                        verbose_name="Sensible",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capabilities",
                        to="authz.module",
                        verbose_name="Módulo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacidad",
                "verbose_name_plural": "Capacidades",
                "db_table": "authz_capability",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True, verbose_name="Código")),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "capabilities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="authz.capability",
                        verbose_name="Capacidades",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "authz_role",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AuthzEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DENY", "Denegación (403)"),
                            ("SENSITIVE_USE", "Uso de capacidad sensible"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "capability_code",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Capacidad"
                    ),
                ),
                ("ip_addr", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                ("extra_json", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authz_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de autorización",
                "verbose_name_plural": "Eventos de autorización",
                "db_table": "authz_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="authz_event_action_09439a_idx",
                    ),
                    models.Index(
                        fields=["actor", "action", "-created_at"],
                        name="authz_event_actor_i_bb271b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DirectEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expira"),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_entitlements",
                        to="authz.capability",
                        verbose_name="Capacidad",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Otorgado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_entitlements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grant directo",
                "verbose_name_plural": "Grants directos",
                "db_table": "authz_direct_entitlement",
                "indexes": [
                    models.Index(
                        fields=["user", "capability"],
                        name="authz_direc_user_id_ec8311_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "capability"),
                        name="uq_authz_direct_entitlement",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntitlementRevocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.TextField(blank=True, default="", verbose_name="Motivo"),
                ),
                (
                    "capability",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlement_revocations",
                        to="authz.capability",
                        verbose_name="Capacidad",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Revocado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlement_revocations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revocación de grant",
                "verbose_name_plural": "Revocaciones de grant",
                "db_table": "authz_entitlement_revocation",
                "indexes": [
                    models.Index(
                        fields=["user", "capability"],
                        name="authz_entit_user_id_47dd02_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "capability"),
                        name="uq_authz_entitlement_revocation",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expira"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="authz.role",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de rol",
                "verbose_name_plural": "Asignaciones de rol",
                "db_table": "authz_role_assignment",
                "indexes": [
                    models.Index(
                        fields=["user", "role"], name="authz_role__user_id_f2e4a8_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "role"), name="uq_authz_role_assignment"
                    )
                ],
            },
        ),
    ]
