# Generated by Django 6.0.5 on 2026-08-15 16:56

import addons.utm.models.utm_tag
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UtmStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la etapa.",
                        max_length=255,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Orden de presentación.",
                        verbose_name="Secuencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de campaña",
                "verbose_name_plural": "Etapas de campaña",
                "db_table": "utm_stage",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="UtmMedium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del medio de entrega.",
                        max_length=255,
                        verbose_name="Nombre del medio",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Permite archivar el medio sin borrarlo.",
                        verbose_name="Activo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medio UTM",
                "verbose_name_plural": "Medios UTM",
                "db_table": "utm_medium",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="utm_medium_unique_name",
                        violation_error_message="The name must be unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UtmSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la fuente del enlace.",
                        max_length=255,
                        verbose_name="Nombre de la fuente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuente UTM",
                "verbose_name_plural": "Fuentes UTM",
                "db_table": "utm_source",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="utm_source_unique_name",
                        violation_error_message="The name must be unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UtmTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la etiqueta.",
                        max_length=255,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=addons.utm.models.utm_tag._default_color,
                        help_text="Color de la etiqueta.",
                        verbose_name="Índice de color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta UTM",
                "verbose_name_plural": "Etiquetas UTM",
                "db_table": "utm_tag",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="utm_tag_name_uniq",
                        violation_error_message="Tag name already exists!",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UtmCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Permite archivar la campaña sin borrarla.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Identificador único que viaja en la URL como utm_campaign. Se deriva del nombre legible.",
                        max_length=255,
                        verbose_name="Identificador de campaña",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Nombre legible de la campaña.",
                        max_length=255,
                        verbose_name="Nombre de campaña",
                    ),
                ),
                (
                    "is_auto_campaign",
                    models.BooleanField(
                        default=False,
                        help_text="Permite filtrar las campañas relevantes de las generadas automáticamente.",
                        verbose_name="Campaña generada automáticamente",
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=0,
                        help_text="Color con el que se presenta la campaña.",
                        verbose_name="Índice de color",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="Persona responsable de la campaña.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utm_campaign_ids",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
                (
                    "stage_id",
                    models.ForeignKey(
                        help_text="Etapa en la que se encuentra la campaña.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaign_ids",
                        to="utm.utmstage",
                        verbose_name="Etapa",
                    ),
                ),
                (
                    "tag_ids",
                    models.ManyToManyField(
                        blank=True,
                        db_table="utm_tag_rel",
                        help_text="Etiquetas con las que se clasifica la campaña.",
                        related_name="campaign_ids",
                        to="utm.utmtag",
                        verbose_name="Etiquetas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaña UTM",
                "verbose_name_plural": "Campañas UTM",
                "db_table": "utm_campaign",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="utm_campaign_unique_name",
                        violation_error_message="The name must be unique",
                    )
                ],
            },
        ),
    ]
