# Generated by Django 6.0.5 on 2026-08-28 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utm", "0002_seed_utm_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="utmcampaign",
            name="stage_id",
            field=models.ForeignKey(
                db_column="stage_id",
                help_text="Etapa en la que se encuentra la campaña.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_ids",
                to="utm.utmstage",
                verbose_name="Etapa",
            ),
        ),
        migrations.AlterField(
            model_name="utmcampaign",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                help_text="Persona responsable de la campaña.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="utm_campaign_ids",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsable",
            ),
        ),
    ]
