# Generated by Django 6.0.5 on 2026-08-02 22:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sales_team", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la etapa (Odoo crm.stage.name).",
                        max_length=100,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Orden del pipeline; menor primero (Odoo sequence).",
                    ),
                ),
                (
                    "is_won",
                    models.BooleanField(
                        default=False, help_text="Etapa ganada (Odoo is_won)."
                    ),
                ),
                (
                    "fold",
                    models.BooleanField(
                        default=False, help_text="Plegada en el pipeline (Odoo fold)."
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=0, help_text="Índice de color (Odoo color)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de CRM",
                "verbose_name_plural": "Etapas de CRM",
                "db_table": "crm_stage",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="CrmLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la oportunidad (Odoo crm.lead.name).",
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("lead", "Iniciativa"),
                            ("opportunity", "Oportunidad"),
                        ],
                        default="lead",
                        help_text="Iniciativa u oportunidad (Odoo type).",
                        max_length=12,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("0", "Baja"),
                            ("1", "Media"),
                            ("2", "Alta"),
                            ("3", "Muy alta"),
                        ],
                        default="0",
                        help_text="Prioridad (Odoo priority).",
                        max_length=1,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Archivar sin borrar (Odoo active)."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Notas (Odoo description)."
                    ),
                ),
                (
                    "expected_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Ingreso esperado (Odoo expected_revenue).",
                        max_digits=14,
                    ),
                ),
                (
                    "probability",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Probabilidad % (Odoo probability).",
                        max_digits=5,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de contacto (Odoo contact_name).",
                        max_length=150,
                    ),
                ),
                (
                    "email_from",
                    models.EmailField(
                        blank=True,
                        help_text="Correo (Odoo email_from).",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Teléfono (Odoo phone).",
                        max_length=30,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente asociado (Odoo partner_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Equipo de venta (Odoo team_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_leads",
                        to="sales_team.crmteam",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Vendedor (Odoo user_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_leads_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Etapa del pipeline (Odoo stage_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="crm.crmstage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oportunidad de CRM",
                "verbose_name_plural": "Oportunidades de CRM",
                "db_table": "crm_lead",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("replied", models.BooleanField(default=False)),
                ("reply_body", models.TextField(blank=True, default="")),
                ("reply_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reply_sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_replies_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de contacto",
                "verbose_name_plural": "Mensajes de contacto",
                "db_table": "contact_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["read"], name="contact_mes_read_d4ce31_idx"),
                    models.Index(
                        fields=["-created_at"], name="contact_mes_created_54923f_idx"
                    ),
                ],
            },
        ),
    ]
