# Generated by Django 6.0.5 on 2026-07-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_gatewaysettlement_cashmovement_gatewaysettlementline"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarrierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.CharField(max_length=64, verbose_name="Transportista"),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe"
                    ),
                ),
                (
                    "free_shipping_subsidy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subsidio envio gratis",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("payable", "Por pagar"),
                            ("paid", "Pagado"),
                            ("disputed", "En disputa"),
                        ],
                        default="payable",
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
            ],
            options={
                "verbose_name": "Flete por pagar",
                "verbose_name_plural": "Fletes por pagar",
                "db_table": "finance_carrier_invoice",
                "ordering": ["-created_at"],
            },
        ),
    ]
