# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0002_initial"),
        ("base_address_extended", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressstructured",
            name="address",
            field=models.OneToOneField(
                help_text="Dirección a la que pertenece (Odoo res.partner).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured",
                to="users.address",
            ),
        ),
        migrations.AddIndex(
            model_name="catalogpostalcode",
            index=models.Index(
                fields=["country", "postal_code", "settlement_name"],
                name="geo_catalog_country_5ef70a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="catalogpostalcode",
            constraint=models.UniqueConstraint(
                fields=("country", "postal_code", "settlement_consecutive_id"),
                name="uq_catalog_postal_code_natural_key",
            ),
        ),
        migrations.AddField(
            model_name="countryaddresspolicy",
            name="country",
            field=models.OneToOneField(
                help_text="País al que aplica la política (Odoo res.country).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_policy",
                to="base.rescountry",
            ),
        ),
        migrations.AddField(
            model_name="rescity",
            name="country",
            field=models.ForeignKey(
                help_text="País (Odoo country_id, requerido).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="base.rescountry",
            ),
        ),
        migrations.AddField(
            model_name="rescity",
            name="state",
            field=models.ForeignKey(
                blank=True,
                help_text="Estado/provincia (Odoo state_id, dominio country_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="base.rescountrystate",
            ),
        ),
        migrations.AddField(
            model_name="addressstructured",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="Ciudad del catálogo (Odoo city_id → res.city).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="base_address_extended.rescity",
            ),
        ),
    ]
