# Generated by Django 6.0.5 on 2026-07-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_address_extended", "0001_initial"),
        ("users", "0003_identityuser_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressStructured",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre de la calle (Odoo street_name).",
                        max_length=200,
                    ),
                ),
                (
                    "street_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número exterior (Odoo street_number / House).",
                        max_length=32,
                    ),
                ),
                (
                    "street_number2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número interior / puerta (Odoo street_number2 / Door).",
                        max_length=32,
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        help_text="Dirección a la que pertenece (Odoo res.partner).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured",
                        to="users.address",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ciudad del catálogo (Odoo city_id → res.city).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addresses",
                        to="base_address_extended.rescity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección estructurada",
                "verbose_name_plural": "Direcciones estructuradas",
                "db_table": "res_partner_address_structured",
            },
        ),
    ]
