# Generated by Django 5.0.1 on 2026-05-20 23:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalogue", "0001_initial"),
        ("catalogue", "0002_product_short_description_fulltext"),
        ("catalogue", "0003_product_is_featured"),
        ("catalogue", "0004_searchhistory_caches"),
        ("catalogue", "0005_productimage_admin_products"),
        ("catalogue", "0006_timestampedmodel_catalogue"),
        ("catalogue", "0007_sync_model_drift"),
        ("catalogue", "0008_fix_postgres_fields_to_mariadb"),
        ("catalogue", "0009_product_is_featured"),
        ("catalogue", "0010_product_discount"),
        ("catalogue", "0011_product_deleted_at_product_is_deleted"),
        ("catalogue", "0012_productdiscount_softdelete"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalogue.category",
                    ),
                ),
            ],
            options={
                "db_table": "catalogue_category",
                "ordering": ["name"],
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("sku", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalogue.category",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "db_table": "catalogue_product",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunSQL(
            sql="ALTER TABLE catalogue_product ADD FULLTEXT INDEX ft_product_name_desc (name, description, short_description)",
            reverse_sql="ALTER TABLE catalogue_product DROP INDEX ft_product_name_desc",
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunSQL(
            sql="\n            CREATE TABLE IF NOT EXISTS `cache_table` (\n                `cache_key`  varchar(255) NOT NULL PRIMARY KEY,\n                `value`      longtext     NOT NULL,\n                `expires`    datetime(6)  NOT NULL\n            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n            ",
            reverse_sql="DROP TABLE IF EXISTS `cache_table`;",
            hints={"target_db": "default"},
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("term", models.CharField(db_index=True, max_length=100)),
                ("searched_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de búsqueda",
                "db_table": "catalogue_search_history",
                "ordering": ["-searched_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="searchhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "term"), name="unique_user_term"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name="searchhistory",
            old_name="searched_at",
            new_name="updated_at",
        ),
        migrations.AlterModelOptions(
            name="searchhistory",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Historial de búsqueda",
            },
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name": "Categoría"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at"], "verbose_name": "Producto"},
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("image", models.ImageField(upload_to="products/%Y/%m/")),
                ("alt_text", models.CharField(blank=True, default="", max_length=200)),
                ("order", models.PositiveSmallIntegerField(db_index=True, default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalogue.product",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "catalogue_product_image",
                "ordering": ["order", "id"],
                "verbose_name": "Imagen de producto",
            },
        ),
        migrations.RemoveConstraint(
            model_name="searchhistory",
            name="unique_user_term",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_cover",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="short_description",
            field=models.TextField(blank=True, default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/images/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="term",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="searchhistory",
            unique_together={("user", "term")},
        ),
        migrations.AddField(
            model_name="product",
            name="search_vector",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje de descuento (0.01 - 100).",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("valid_from", models.DateTimeField(db_index=True)),
                (
                    "valid_until",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_product_discounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deactivated_product_discounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="catalogue.product",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Descuento de producto",
                "db_table": "catalogue_product_discount",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "is_active"],
                        name="catalogue_p_product_843f9f_idx",
                    )
                ],
            },
        ),
    ]
