# Generated by Django 6.0.5 on 2026-07-12 09:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0002_product_fulltext_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Peso en kg para cotización de envío por peso (vacío = usar costo por zona).",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
