# Generated by Django 5.0.1 on 2026-05-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_product_short_description_fulltext'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
