# Generated by Django 5.0.1 on 2026-05-15 05:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_timestampedmodel_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoría'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Imagen de producto'},
        ),
        migrations.RemoveConstraint(
            model_name='searchhistory',
            name='unique_user_term',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=models.TextField(blank=True, null=True,
                help_text='Texto auxiliar para búsqueda fulltext (MariaDB usa FULLTEXT INDEX)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='term',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('user', 'term')},
        ),
        # GinIndex eliminado — MariaDB usa FULLTEXT INDEX (migración 0002)
    ]
