# Generated by Django 5.0.1 on 2026-05-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0011_product_deleted_at_product_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdiscount",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="productdiscount",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
    ]
