# Generated by Django 5.0.1 on 2026-05-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_squashed_0012_productdiscount_softdelete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
