# Generated by Django 5.0.1

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0013_alter_productimage_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("source", models.CharField(
                    choices=[("MANUAL", "Ajuste manual"), ("PRICE_SYNC", "Sincronización CSV")],
                    default="MANUAL",
                    max_length=20,
                )),
                ("changed_by", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="product_price_changes",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("product", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="price_history",
                    to="catalogue.product",
                )),
            ],
            options={
                "verbose_name": "Historial de precio",
                "db_table": "catalogue_product_price_history",
                "ordering": ["-created_at"],
            },
        ),
    ]
