# Generated by Django 5.0.1 on 2026-05-29 20:58

import apps.catalogue.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0015_alter_product_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="catalogue.category"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalogue.utils.category_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.catalogue.utils.product_image_upload_path
            ),
        ),
    ]
