# Generated by Django 5.0.1 on 2026-05-29 20:58
# Repaired 2026-05-29: added RunPython forward/reverse so migration is
# safe for production. Forward preserves ALL category assignments;
# reverse is lossy if products have multiple M2M categories (ADR-012 v3.1.0).

import apps.catalogue.utils
from django.db import migrations, models


def forward_copy_category_to_m2m(apps, schema_editor):
    """
    Copy product.category_id → catalogue_product_categories before FK is dropped.

    Runs AFTER AddField creates the join table and BEFORE RemoveField drops
    category_id. Preserves 100% of category assignments (no data loss).
    """
    # DML (INSERT), not DDL: run via a cursor, NOT schema_editor.execute().
    # schema_editor.execute() carries a guard that raises
    # TransactionManagementError inside an atomic block on databases that
    # can't roll back DDL (MariaDB/MySQL) -- even for plain DML. A cursor
    # has no such guard and is the correct API for data statements.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            INSERT IGNORE INTO catalogue_product_categories (product_id, category_id)
            SELECT id, category_id
            FROM catalogue_product
            WHERE category_id IS NOT NULL
        """)


def backward_copy_m2m_to_category(apps, schema_editor):
    """
    Restore category_id from M2M when reverting this migration.

    STRUCTURAL LIMITATION — lossy if any product has more than one M2M
    category. A FK column can hold only one value; this code preserves
    MIN(category_id) per product. Additional M2M categories are lost on
    reverse. This is a physical consequence of contracting M2M → FK, not
    a fixable code error. See ADR-012 v3.1.0 warning block.

    This reverse is safe (no loss) only when every product has at most
    one category in catalogue_product_categories. Diagnostic query to
    run before reverting in production:

        SELECT product_id, COUNT(*) c
        FROM catalogue_product_categories
        GROUP BY product_id HAVING c > 1;

    If the query returns rows, reverting will lose the extra categories
    for those products. Take a backup before proceeding.

    Runs AFTER RemoveField^-1 re-adds category_id (nullable) and BEFORE
    AddField^-1 drops the M2M join table — both columns/tables present.
    """
    # DML (UPDATE) via cursor, NOT schema_editor.execute() — same reason as
    # the forward function: the schema_editor guard rejects any execute()
    # inside an atomic block on MariaDB.
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE catalogue_product p
            JOIN (
                SELECT product_id, MIN(category_id) AS cat_id
                FROM catalogue_product_categories
                GROUP BY product_id
            ) pc ON pc.product_id = p.id
            SET p.category_id = pc.cat_id
        """)


class Migration(migrations.Migration):

    # MariaDB no puede envolver DDL (AddField/RemoveField) + RunPython en una
    # transaccion reversible (can_rollback_ddl=False). Con atomic=True (default),
    # Django envuelve el RunPython en su propia transaccion y el guard de
    # schema_editor.execute dispara TransactionManagementError en un build
    # from-scratch (lo que hace pytest con --create-db). atomic=False aplica
    # cada operacion por separado; el commit implicito del DDL ya no choca con
    # el RunPython. En MariaDB el DDL ya hacia commit implicito tambien en
    # produccion, asi que la secuencia de operaciones es identica; atomic=False
    # solo lo hace explicito en vez de abortar en un esquema nuevo. (H-API-01)
    atomic = False

    dependencies = [
        ("catalogue", "0015_alter_product_stock"),
    ]

    operations = [
        # Step 1: create M2M join table first (required by RunPython in step 2)
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                related_name="products", to="catalogue.category"
            ),
        ),
        # Step 2: copy category_id data → M2M before category_id is dropped.
        # Reverse: restore MIN(category_id) from M2M after category_id is
        # re-added by RemoveField^-1 and before M2M is dropped by AddField^-1.
        migrations.RunPython(
            forward_copy_category_to_m2m,
            backward_copy_m2m_to_category,
        ),
        # Step 3: drop category_id only after data is safely copied to M2M
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.catalogue.utils.category_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.catalogue.utils.product_image_upload_path
            ),
        ),
    ]
