# Generated by Django 5.0.1 on 2026-05-29 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0016_uc_cat_13_categories_m2m_upload_paths"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttributeAxis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("is_filterable", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "Eje de atributo",
                "db_table": "catalogue_attribute_axis",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.CharField(max_length=100)),
                ("slug", models.SlugField()),
                ("display_order", models.IntegerField(default=0)),
                (
                    "axis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalogue.attributeaxis",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalogue.attributevalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de atributo",
                "db_table": "catalogue_attribute_value",
                "ordering": ["axis", "display_order", "value"],
                "unique_together": {("axis", "slug"), ("axis", "value")},
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="catalogue.product",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalogue.attributevalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atributo de producto",
                "db_table": "catalogue_product_attribute",
                "indexes": [
                    models.Index(
                        fields=["value"], name="catalogue_p_value_i_0423ad_idx"
                    ),
                    models.Index(
                        fields=["product", "value"],
                        name="catalogue_p_product_ccdc7a_idx",
                    ),
                ],
                "unique_together": {("product", "value")},
            },
        ),
    ]
