# Generated by Django 5.0.1 on 2026-06-23 02:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0018_product_cost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attributevalue",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="searchhistory",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="attributevalue",
            constraint=models.UniqueConstraint(
                fields=("axis", "value"), name="unique_attribute_value_axis_value"
            ),
        ),
        migrations.AddConstraint(
            model_name="attributevalue",
            constraint=models.UniqueConstraint(
                fields=("axis", "slug"), name="unique_attribute_value_axis_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="productattribute",
            constraint=models.UniqueConstraint(
                fields=("product", "value"), name="unique_product_attribute"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "term"), name="unique_search_history_user_term"
            ),
        ),
    ]
