# Generated by Django 6.0.5 on 2026-07-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0019_alter_attributevalue_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["order", "name"], "verbose_name": "Categoría"},
        ),
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
