# Generated by Django 6.0.5 on 2026-08-02 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderLineMargin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo unitario snapshot al vender (Odoo purchase_price).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "line",
                    models.OneToOneField(
                        help_text="Línea de orden extendida (Odoo sale.order.line).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="margin",
                        to="sale.saleorderline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Margen de línea de orden",
                "verbose_name_plural": "Márgenes de líneas de orden",
                "db_table": "sale_order_line_margin",
            },
        ),
    ]
