# Generated by Django 6.0.5 on 2026-07-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0001_initial"),
        ("users", "0004_alter_address_postal_code_ref"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name="catalogpostalcode",
                    name="geo_catalog_country_5ef70a_idx",
                ),
                migrations.RemoveConstraint(
                    model_name="catalogpostalcode",
                    name="uq_catalog_postal_code_natural_key",
                ),
                migrations.DeleteModel(
                    name="CatalogPostalCode",
                ),
            ],
            database_operations=[],
        ),
    ]
