# Generated by Django 6.0.5 on 2026-08-06 00:33

import addons.analytic.models.analytic_plan
import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0007_alter_iractionsreport_report_type"),
        ("uom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAnalyticAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Odoo name (requerido, traducible, index=trigram en la referencia — aquí índice simple de MariaDB).",
                        max_length=255,
                        verbose_name="Cuenta analítica",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Odoo code.",
                        max_length=64,
                        verbose_name="Referencia",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytic_accounts",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo partner_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytic_accounts",
                        to="base.respartner",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuenta analítica",
                "verbose_name_plural": "Cuentas analíticas",
                "db_table": "account_analytic_account",
                "ordering": ["plan", "name"],
            },
        ),
        migrations.CreateModel(
            name="AccountAnalyticDistributionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analytic_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Odoo analytic_distribution: {"id1,id2,...": porcentaje}.',
                        null=True,
                        verbose_name="Distribución analítica",
                    ),
                ),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo company_id (ondelete=cascade).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytic_distribution_models",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo partner_id (ondelete=cascade). Selecciona un contacto para el que se usa esta distribución.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytic_distribution_models",
                        to="base.respartner",
                        verbose_name="Contacto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de distribución analítica",
                "verbose_name_plural": "Modelos de distribución analítica",
                "db_table": "account_analytic_distribution_model",
                "ordering": ["sequence", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AccountAnalyticLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Odoo name (requerido).",
                        max_length=255,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, default=datetime.date.today, verbose_name="Fecha"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Odoo amount (requerido).",
                        max_digits=16,
                        verbose_name="Importe",
                    ),
                ),
                (
                    "unit_amount",
                    models.FloatField(default=0.0, verbose_name="Cantidad"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("other", "Otro")],
                        default="other",
                        max_length=16,
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo account_id (ondelete=restrict). Simplificación de columna única — ver docstring del módulo.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="analytic.accountanalyticaccount",
                        verbose_name="Cuenta analítica",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Odoo company_id (requerido, readonly).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytic_lines",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytic_lines",
                        to="base.respartner",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "product_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytic_lines",
                        to="uom.uom",
                        verbose_name="Unidad",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo user_id. Sin default a env.user (ver docstring: esta API no acopla el modelo al usuario ambiental).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytic_lines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apunte analítico",
                "verbose_name_plural": "Apuntes analíticos",
                "db_table": "account_analytic_line",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AccountAnalyticPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del plan (Odoo name, requerido, traducible).",
                        max_length=255,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "parent_path",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=addons.analytic.models.analytic_plan._default_color,
                        verbose_name="Color",
                    ),
                ),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                (
                    "default_applicability",
                    models.CharField(
                        choices=[
                            ("optional", "Opcional"),
                            ("mandatory", "Obligatorio"),
                            ("unavailable", "No disponible"),
                        ],
                        default="optional",
                        help_text="Odoo default_applicability; en la referencia es company_dependent — aquí un default fijo (ver docstring).",
                        max_length=16,
                        verbose_name="Aplicabilidad por defecto",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo parent_id (ondelete=cascade).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="analytic.accountanalyticplan",
                        verbose_name="Plan padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan analítico",
                "verbose_name_plural": "Planes analíticos",
                "db_table": "account_analytic_plan",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountAnalyticApplicability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_domain",
                    models.CharField(
                        choices=[("general", "Miscelánea")],
                        help_text="Odoo business_domain; único valor en la referencia base (otros addons de Odoo extienden la selección — no aplica aquí).",
                        max_length=32,
                        verbose_name="Dominio de negocio",
                    ),
                ),
                (
                    "applicability",
                    models.CharField(
                        choices=[
                            ("optional", "Opcional"),
                            ("mandatory", "Obligatorio"),
                            ("unavailable", "No disponible"),
                        ],
                        max_length=16,
                        verbose_name="Aplicabilidad",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytic_applicabilities",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "analytic_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicability_ids",
                        to="analytic.accountanalyticplan",
                        verbose_name="Plan analítico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aplicabilidad de plan analítico",
                "verbose_name_plural": "Aplicabilidades de plan analítico",
                "db_table": "account_analytic_applicability",
            },
        ),
        migrations.AddField(
            model_name="accountanalyticaccount",
            name="plan",
            field=models.ForeignKey(
                help_text="Odoo plan_id (requerido). on_delete=PROTECT: un plan con cuentas no se puede borrar por accidente (Odoo no fija ondelete explícito aquí; PROTECT es la adaptación segura).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="analytic.accountanalyticplan",
                verbose_name="Plan",
            ),
        ),
    ]
