# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=100, verbose_name="Etiqueta visible"),
                ),
                ("slug", models.SlugField(max_length=120, verbose_name="Slug URL")),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Opcion de variante",
                "db_table": "chartsize_variant_option",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                (
                    "sku_suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Se concatena a Product.sku. Ej: GRD → COL-001-GRD",
                        max_length=20,
                        verbose_name="Sufijo SKU",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Si esta en blanco, se usa el precio base del producto.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Precio diferenciado",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Stock de la variante"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalogue.product",
                    ),
                ),
                (
                    "option",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant",
                        to="chartsize.variantoption",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante de producto",
                "db_table": "chartsize_product_variant",
                "ordering": ["option__order", "option__label"],
            },
        ),
        migrations.CreateModel(
            name="VariantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del atributo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, default=0, verbose_name="Orden de presentacion"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_types",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de variante",
                "db_table": "chartsize_variant_type",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="variantoption",
            name="variant_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="chartsize.varianttype",
            ),
        ),
        migrations.AddConstraint(
            model_name="varianttype",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_variant_type_product_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(
                fields=("variant_type", "label"),
                name="unique_variant_option_type_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(
                fields=("variant_type", "slug"), name="unique_variant_option_type_slug"
            ),
        ),
    ]
