# Generated by Django 6.0.5 on 2026-07-22 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base_address_extended", "0003_catalogpostalcode"),
        ("users", "0003_identityuser_company"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="address",
                    name="postal_code_ref",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Enlace opcional a la colonia del catálogo internacional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addresses",
                        to="base_address_extended.catalogpostalcode",
                        verbose_name="Código postal (catálogo)",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
