# Generated by Django 5.0.1 on 2026-05-20 23:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("chartsize", "0001_initial"),
        ("chartsize", "0002_timestampedmodel_chartsize"),
        ("chartsize", "0003_sync_model_drift"),
        ("chartsize", "0004_chartsize_softdelete"),
    ]

    initial = True

    dependencies = [
        ("catalogue", "0005_productimage_admin_products"),
        ("catalogue", "0007_sync_model_drift"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del atributo"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(db_index=True, default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_types",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "db_table": "chartsize_variant_type",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="varianttype",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_product_variant_type_name"
            ),
        ),
        migrations.CreateModel(
            name="VariantOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("label", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(db_index=True, default=0)),
                (
                    "variant_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="chartsize.varianttype",
                    ),
                ),
            ],
            options={
                "db_table": "chartsize_variant_option",
                "ordering": ["order", "label"],
            },
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(
                fields=("variant_type", "label"), name="unique_vtype_label"
            ),
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(
                fields=("variant_type", "slug"), name="unique_vtype_slug"
            ),
        ),
        migrations.AddField(
            model_name="varianttype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="varianttype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="variantoption",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="variantoption",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("sku_suffix", models.CharField(blank=True, default="", max_length=20)),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalogue.product",
                    ),
                ),
                (
                    "option",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant",
                        to="chartsize.variantoption",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chartsize_product_variant",
                "ordering": ["option__order", "option__label"],
                "verbose_name": "Variante de producto",
            },
        ),
        migrations.AlterModelOptions(
            name="variantoption",
            options={
                "ordering": ["order", "label"],
                "verbose_name": "Opcion de variante",
            },
        ),
        migrations.AlterModelOptions(
            name="varianttype",
            options={"ordering": ["order", "name"], "verbose_name": "Tipo de variante"},
        ),
        migrations.RemoveConstraint(
            model_name="variantoption",
            name="unique_vtype_label",
        ),
        migrations.RemoveConstraint(
            model_name="variantoption",
            name="unique_vtype_slug",
        ),
        migrations.RemoveConstraint(
            model_name="varianttype",
            name="unique_product_variant_type_name",
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Si esta en blanco, se usa el precio base del producto.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Precio diferenciado",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sku_suffix",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Se concatena a Product.sku. Ej: GRD → COL-001-GRD",
                max_length=20,
                verbose_name="Sufijo SKU",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Stock de la variante"
            ),
        ),
        migrations.AlterField(
            model_name="variantoption",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="variantoption",
            name="label",
            field=models.CharField(max_length=100, verbose_name="Etiqueta visible"),
        ),
        migrations.AlterField(
            model_name="variantoption",
            name="slug",
            field=models.SlugField(max_length=120, verbose_name="Slug URL"),
        ),
        migrations.AlterField(
            model_name="varianttype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="varianttype",
            name="order",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=0, verbose_name="Orden de presentacion"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantoption",
            unique_together={("variant_type", "label"), ("variant_type", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="varianttype",
            unique_together={("product", "name")},
        ),
        migrations.AddField(
            model_name="productvariant",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
        migrations.AddField(
            model_name="variantoption",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="variantoption",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
        migrations.AddField(
            model_name="varianttype",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="varianttype",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
    ]
