# Generated by Django 5.0.1 on 2026-05-15 05:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_sync_model_drift'),
        ('chartsize', '0002_timestampedmodel_chartsize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['option__order', 'option__label'], 'verbose_name': 'Variante de producto'},
        ),
        migrations.AlterModelOptions(
            name='variantoption',
            options={'ordering': ['order', 'label'], 'verbose_name': 'Opcion de variante'},
        ),
        migrations.AlterModelOptions(
            name='varianttype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Tipo de variante'},
        ),
        migrations.RemoveConstraint(
            model_name='variantoption',
            name='unique_vtype_label',
        ),
        migrations.RemoveConstraint(
            model_name='variantoption',
            name='unique_vtype_slug',
        ),
        migrations.RemoveConstraint(
            model_name='varianttype',
            name='unique_product_variant_type_name',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si esta en blanco, se usa el precio base del producto.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio diferenciado'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku_suffix',
            field=models.CharField(blank=True, default='', help_text='Se concatena a Product.sku. Ej: GRD → COL-001-GRD', max_length=20, verbose_name='Sufijo SKU'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock de la variante'),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='label',
            field=models.CharField(max_length=100, verbose_name='Etiqueta visible'),
        ),
        migrations.AlterField(
            model_name='variantoption',
            name='slug',
            field=models.SlugField(max_length=120, verbose_name='Slug URL'),
        ),
        migrations.AlterField(
            model_name='varianttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='varianttype',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Orden de presentacion'),
        ),
        migrations.AlterUniqueTogether(
            name='variantoption',
            unique_together={('variant_type', 'label'), ('variant_type', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='varianttype',
            unique_together={('product', 'name')},
        ),
    ]
