# Generated by Django 5.0.1 on 2026-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chartsize", "0003_sync_model_drift"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
        migrations.AddField(
            model_name="variantoption",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="variantoption",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
        migrations.AddField(
            model_name="varianttype",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de borrado logico"
            ),
        ),
        migrations.AddField(
            model_name="varianttype",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True si la fila fue borrada via soft delete.",
                verbose_name="Eliminado (logico)",
            ),
        ),
    ]
