# Generated by Django 5.0.1 on 2026-06-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0019_alter_attributevalue_unique_together_and_more"),
        ("chartsize", "0005_alter_productvariant_created_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="variantoption",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="varianttype",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(
                fields=("variant_type", "label"),
                name="unique_variant_option_type_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="variantoption",
            constraint=models.UniqueConstraint(
                fields=("variant_type", "slug"), name="unique_variant_option_type_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="varianttype",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_variant_type_product_name"
            ),
        ),
    ]
