# Generated by Django 6.0.5 on 2026-08-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0019_accountjournal_entries_count_and_more"),
        ("base", "0029_rescompany_internal_project_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountEdiFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre visible del formato (Odoo name).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código técnico único del formato (Odoo code, requerido).",
                        max_length=64,
                    ),
                ),
                (
                    "journals",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Diarios donde este formato está activo (Odoo journal_id, lado inverso de journal.edi_format_ids).",
                        related_name="edi_format_ids",
                        to="account.accountjournal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formato EDI",
                "verbose_name_plural": "Formatos EDI",
                "db_table": "account_edi_format",
            },
        ),
        migrations.CreateModel(
            name="AccountEdiDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("to_send", "Por enviar"),
                            ("sent", "Enviado"),
                            ("to_cancel", "Por cancelar"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="",
                        help_text="Odoo state.",
                        max_length=9,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Texto del último error EDI (Odoo error).",
                    ),
                ),
                (
                    "blocking_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("info", "Info"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                        ],
                        default="",
                        help_text="Severidad del bloqueo (Odoo blocking_level).",
                        max_length=7,
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Archivo generado por edi_format al postear el asiento (Odoo attachment_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edi_documents",
                        to="base.irattachment",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        help_text="Asiento contable (Odoo move_id, requerido). related_name da a account.move el M2O inverso sin tocar su archivo.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edi_document_ids",
                        to="account.accountmove",
                    ),
                ),
                (
                    "edi_format",
                    models.ForeignKey(
                        help_text="Formato EDI (Odoo edi_format_id, requerido).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="account_edi.accountediformat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento EDI",
                "verbose_name_plural": "Documentos EDI",
                "db_table": "account_edi_document",
            },
        ),
        migrations.AddConstraint(
            model_name="accountediformat",
            constraint=models.UniqueConstraint(
                fields=("code",), name="uniq_edi_format_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountedidocument",
            constraint=models.UniqueConstraint(
                fields=("edi_format", "move"), name="uniq_edi_doc_move_format"
            ),
        ),
    ]
