# Generated by Django 6.0.5 on 2026-08-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0021_accountmove_posted_before"),
        ("account_edi", "0001_initial"),
        ("base", "0063_alter_iractionsserver_sequence_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accountedidocument",
            name="uniq_edi_doc_move_format",
        ),
        migrations.AlterField(
            model_name="accountedidocument",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                db_column="attachment_id",
                help_text="Archivo generado por edi_format al postear el asiento (Odoo attachment_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edi_documents",
                to="base.irattachment",
            ),
        ),
        migrations.RenameField(
            model_name="accountedidocument",
            old_name="attachment",
            new_name="attachment_id",
        ),
        migrations.AlterField(
            model_name="accountedidocument",
            name="edi_format",
            field=models.ForeignKey(
                db_column="edi_format_id",
                help_text="Formato EDI (Odoo edi_format_id, requerido).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="account_edi.accountediformat",
            ),
        ),
        migrations.RenameField(
            model_name="accountedidocument",
            old_name="edi_format",
            new_name="edi_format_id",
        ),
        migrations.AlterField(
            model_name="accountedidocument",
            name="move",
            field=models.ForeignKey(
                db_column="move_id",
                help_text="Asiento contable (Odoo move_id, requerido). related_name da a account.move el M2O inverso sin tocar su archivo.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="edi_document_ids",
                to="account.accountmove",
            ),
        ),
        migrations.RenameField(
            model_name="accountedidocument",
            old_name="move",
            new_name="move_id",
        ),
        migrations.AddConstraint(
            model_name="accountedidocument",
            constraint=models.UniqueConstraint(
                fields=("edi_format_id", "move_id"), name="uniq_edi_doc_move_format"
            ),
        ),
    ]
