# Generated by Django 6.0.5 on 2026-08-03 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nombre")),
                (
                    "credential_identifier",
                    models.CharField(
                        help_text="NO expuesto por la API (group_system en la referencia).",
                        max_length=1024,
                        unique=True,
                        verbose_name="Identificador de credencial",
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="NO expuesta por la API (group_system en la referencia).",
                        max_length=2048,
                        verbose_name="Llave pública",
                    ),
                ),
                (
                    "sign_count",
                    models.IntegerField(default=0, verbose_name="Contador de firmas"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="≙ create_uid; el o2m auth_passkey_key_ids de res_users es este reverso.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey",
                "verbose_name_plural": "Passkeys",
                "db_table": "auth_passkey_key",
                "ordering": ["-id"],
            },
        ),
    ]
