# Generated by Django 5.0.1 on 2026-05-20 23:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("cart", "0001_initial"),
        ("cart", "0002_cart_voucher_fk"),
        ("cart", "0003_timestampedmodel_cart"),
        ("cart", "0004_sync_model_drift"),
        ("cart", "0005_remove_redundant_user_constraint"),
    ]

    initial = True

    dependencies = [
        ("catalogue", "0005_productimage_admin_products"),
        ("catalogue", "0007_sync_model_drift"),
        ("chartsize", "0001_initial"),
        ("chartsize", "0003_sync_model_drift"),
        ("voucher", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True
                    ),
                ),
                (
                    "cart_token",
                    models.UUIDField(blank=True, db_index=True, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cart_cart",
                "verbose_name": "Carrito",
            },
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user",),
                name="unique_user_cart",
            ),
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="catalogue.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="chartsize.productvariant",
                    ),
                ),
            ],
            options={
                "db_table": "cart_cart_item",
                "verbose_name": "Item de carrito",
            },
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "variant"), name="unique_cart_variant"
            ),
        ),
        migrations.CreateModel(
            name="SavedCart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("saved_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cart_saved_cart",
            },
        ),
        migrations.CreateModel(
            name="SavedCartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price_at_save", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "saved_cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.savedcart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "db_table": "cart_saved_cart_item",
            },
        ),
        migrations.AddConstraint(
            model_name="savedcartitem",
            constraint=models.UniqueConstraint(
                fields=("saved_cart", "product"), name="unique_saved_cart_product"
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="voucher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="voucher.voucher",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name="savedcart",
            old_name="saved_at",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="savedcart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedcartitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="savedcartitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelOptions(
            name="savedcart",
            options={"verbose_name": "Carrito guardado"},
        ),
        migrations.AlterModelOptions(
            name="savedcartitem",
            options={"verbose_name": "Item guardado"},
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_variant",
        ),
        migrations.RemoveConstraint(
            model_name="savedcartitem",
            name="unique_saved_cart_product",
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="savedcart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="savedcartitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "variant")},
        ),
        migrations.AlterUniqueTogether(
            name="savedcartitem",
            unique_together={("saved_cart", "product")},
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="unique_user_cart",
        ),
    ]
