# Generated by Django 5.0.1 on 2026-06-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_fix_cart_item_unique_constraint"),
        ("catalogue", "0019_alter_attributevalue_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="savedcartitem",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="savedcartitem",
            constraint=models.UniqueConstraint(
                fields=("saved_cart", "product"), name="unique_saved_cart_item"
            ),
        ),
    ]
