# Generated by Django 5.0.1 on 2026-05-15 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_timestampedmodel_cart'),
        ('catalogue', '0007_sync_model_drift'),
        ('chartsize', '0003_sync_model_drift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedcart',
            options={'verbose_name': 'Carrito guardado'},
        ),
        migrations.AlterModelOptions(
            name='savedcartitem',
            options={'verbose_name': 'Item guardado'},
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_variant',
        ),
        migrations.RemoveConstraint(
            model_name='savedcartitem',
            name='unique_saved_cart_product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedcart',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedcartitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='savedcartitem',
            unique_together={('saved_cart', 'product')},
        ),
    ]
