# Generated by Django 6.0.5 on 2026-08-02 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Oportunidad (Odoo opportunity_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sale_orders",
                        to="crm.crmlead",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Orden de venta (Odoo sale.order).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunity_link",
                        to="sale.saleorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oportunidad de orden de venta",
                "verbose_name_plural": "Oportunidades de órdenes de venta",
                "db_table": "sale_order_opportunity",
            },
        ),
    ]
