# Generated by Django 5.0.1 on 2026-05-20 23:22

import apps.users.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apps.users.migrations.0006_user_deactivation_reason


def _backfill_unverified(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(
        is_active=False, deactivated_reason__isnull=True,
    ).update(deactivated_reason='unverified')


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_alter_user_options_alter_user_avatar_and_more'), ('users', '0003_emailverificationtoken_passwordresettoken'), ('users', '0004_timestampedmodel_users'), ('users', '0005_address_deleted_at_address_is_deleted'), ('users', '0006_user_deactivation_reason'), ('users', '0007_user_deactivation_event')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, help_text='Imagen de perfil del comprador. Formatos: JPEG, PNG, WebP.', null=True, upload_to=apps.users.models.avatar_upload_path, verbose_name='Avatar')),
                ('phone', models.CharField(blank=True, default='', help_text='Numero de telefono del comprador.', max_length=20, verbose_name='Telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('deactivated_reason', models.CharField(blank=True, choices=[('unverified', 'No verificada (email pendiente)'), ('suspended', 'Suspendida por administrador'), ('self_deleted', 'Dada de baja por el usuario')], help_text='Causa por la que is_active=False. NULL cuando la cuenta esta activa. Distingue cuentas reactivables por email (unverified, self_deleted) de las que requieren UC-AUTH-14 (suspended). Ver UC-AUTH-01 Alt-A.', max_length=20, null=True, verbose_name='Causa de inactividad')),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='Timestamp del cambio is_active True -> False.', null=True, verbose_name='Fecha de desactivacion')),
            ],
            options={
                'db_table': 'users_user',
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_password_reset_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users_email_verification_token',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Ej: Casa, Trabajo, Almacen.', max_length=50, verbose_name='Nombre de la direccion')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Nombre del destinatario')),
                ('street', models.CharField(max_length=200, verbose_name='Calle y numero')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Codigo postal')),
                ('country', models.CharField(default='MX', help_text='Codigo ISO 3166-1 alpha-2.', max_length=2, verbose_name='Pais')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono del destinatario')),
                ('is_default', models.BooleanField(default=False, verbose_name='Direccion predeterminada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de borrado logico')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='True si la fila fue borrada via soft delete.', verbose_name='Eliminado (logico)')),
            ],
            options={
                'verbose_name': 'Direccion de envio',
                'verbose_name_plural': 'Direcciones de envio',
                'db_table': 'users_address',
                'ordering': ['-is_default', 'alias'],
            },
        ),
        migrations.RunPython(
            code=_backfill_unverified,
            reverse_code=_noop_reverse,
        ),
        migrations.CreateModel(
            name='UserDeactivationEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('unverified', 'No verificada (email pendiente)'), ('suspended', 'Suspendida por administrador'), ('self_deleted', 'Dada de baja por el usuario')], max_length=20)),
                ('source', models.CharField(choices=[('register', 'Registro (cuenta nueva inactiva por verificar)'), ('self', 'Auto-baja del propio usuario'), ('admin', 'Suspension por administrador')], max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('actor', models.ForeignKey(blank=True, help_text='Quien disparo el evento. NULL para SOURCE_REGISTER o SOURCE_SELF. Solo SOURCE_ADMIN registra al admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de desactivacion',
                'verbose_name_plural': 'Eventos de desactivacion',
                'db_table': 'users_deactivation_event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_deact_user_id_4c2e_idx'), models.Index(fields=['source'], name='users_deact_source_8a31_idx')],
            },
        ),
    ]
