# Generated by Django 5.0.1 on 2026-05-05 17:48

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del comprador. Formatos: JPEG, PNG, WebP.', null=True, upload_to=apps.users.models.avatar_upload_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Numero de telefono del comprador.', max_length=20, verbose_name='Telefono'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(help_text='Ej: Casa, Trabajo, Almacen.', max_length=50, verbose_name='Nombre de la direccion')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Nombre del destinatario')),
                ('street', models.CharField(max_length=200, verbose_name='Calle y numero')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Codigo postal')),
                ('country', models.CharField(default='MX', help_text='Codigo ISO 3166-1 alpha-2.', max_length=2, verbose_name='Pais')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefono del destinatario')),
                ('is_default', models.BooleanField(default=False, verbose_name='Direccion predeterminada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
            ],
            options={
                'verbose_name': 'Direccion de envio',
                'verbose_name_plural': 'Direcciones de envio',
                'db_table': 'users_address',
                'ordering': ['-is_default', 'alias'],
            },
        ),
    ]
