# Generated by Django 5.0.1 on 2026-05-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_squashed_0007_user_deactivation_event"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userdeactivationevent",
            new_name="users_deact_user_id_d7cbf3_idx",
            old_name="users_deact_user_id_4c2e_idx",
        ),
        migrations.RenameIndex(
            model_name="userdeactivationevent",
            new_name="users_deact_source_eafffd_idx",
            old_name="users_deact_source_8a31_idx",
        ),
        migrations.AlterField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userdeactivationevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
