# Generated by Django 5.0.1 on 2026-05-21 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0008_rename_users_deact_user_id_4c2e_idx_users_deact_user_id_d7cbf3_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login exitoso"),
                            ("LOGIN_FAIL", "Login fallido"),
                            ("LOGOUT", "Logout"),
                            ("REFRESH_SUCCESS", "Refresh exitoso"),
                            ("REFRESH_FAIL", "Refresh fallido"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("ip_addr", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=30)),
                ("extra_json", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_auth_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "-created_at"],
                        name="users_auth__user_id_1222c3_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="users_auth__action_ac0624_idx",
                    ),
                ],
            },
        ),
    ]
