# Generated by Django 5.0.1 on 2026-05-21 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_authevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ORDER_CREATED", "Order creada"),
                            ("ORDER_CANCELLED", "Order cancelada"),
                            ("RETURN_REQUESTED", "Return solicitada"),
                            ("RETURN_RESOLVED", "Return resuelta"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_addr", models.GenericIPAddressField(blank=True, null=True)),
                ("extra_json", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_business_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="users_busin_action_377e8e_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="users_busin_target__451beb_idx",
                    ),
                ],
            },
        ),
    ]
