# Generated by Django 5.0.1 on 2026-05-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_authevent_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="exterior_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numero exterior (MX). Ej: 123, 45-B.",
                max_length=20,
                verbose_name="Numero exterior",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="interior_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numero interior si aplica (MX). Ej: Depto 5.",
                max_length=20,
                verbose_name="Numero interior",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="neighborhood",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Colonia / neighborhood (MX).",
                max_length=120,
                verbose_name="Colonia",
            ),
        ),
    ]
