# Generated by Django 5.0.1 on 2026-05-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_address_exterior_number_address_interior_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN_SUCCESS", "Login exitoso"),
                    ("LOGIN_FAIL", "Login fallido"),
                    ("LOGOUT", "Logout"),
                    ("REFRESH_SUCCESS", "Refresh exitoso"),
                    ("REFRESH_FAIL", "Refresh fallido"),
                    ("REGISTER_ATTEMPT", "Registro intento"),
                    ("REGISTER_SUCCESS", "Registro exitoso"),
                    ("REGISTER_FAIL", "Registro fallido"),
                    ("PASSWORD_CHANGE", "Cambio de contrasena"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
