# Generated by Django 6.0.5 on 2026-07-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessevent",
            name="correlation_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
    ]
