# Generated by Django 5.0.1 on 2026-05-20 23:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [("payments", "0001_initial"), ("payments", "0002_sync_model_drift")]

    initial = True

    dependencies = [
        ("orders", "0002_timestampedmodel_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway",
                    models.CharField(
                        choices=[("MERCADOPAGO", "MercadoPago"), ("PAYPAL", "PayPal")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del pago confirmado por el gateway. Null hasta el webhook.",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "preference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de preferencia MP o ID de orden PayPal.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("FAILED", "Fallido"),
                            ("REFUNDED", "Reembolsado"),
                            ("PARTIALLY_REFUNDED", "Reembolso parcial"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importe cobrado. Coincide con OrderValue.total al momento del pago.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "installments",
                    models.PositiveIntegerField(
                        default=1, help_text="Número de cuotas. 1 = pago de contado."
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
                "verbose_name": "Pago",
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("WEBHOOK_RECEIVED", "Webhook recibido"),
                            ("PREFERENCE_CREATED", "Preferencia creada"),
                            ("PAYMENT_APPROVED", "Pago aprobado"),
                            ("PAYMENT_FAILED", "Pago fallido"),
                            ("REFUND_CREATED", "Reembolso creado"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "raw_body",
                    models.TextField(
                        help_text="Respuesta completa del gateway almacenada como texto."
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payments_gateway_event",
                "ordering": ["-created_at"],
                "verbose_name": "Evento del gateway",
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "gateway_refund_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("FAILED", "Fallido"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payments_refund",
                "ordering": ["-created_at"],
                "verbose_name": "Reembolso",
            },
        ),
    ]
