# Generated by Django 6.0.5 on 2026-07-12 02:15

import apps.payments.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway",
                    models.CharField(
                        choices=[("MERCADOPAGO", "MercadoPago"), ("PAYPAL", "PayPal")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del pago confirmado por el gateway. Null hasta el webhook. En Orders API guarda el PAY... anidado (transactions.payments[].id).",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "mp_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ID del recurso Order de MercadoPago (ORD...). Solo Orders API (DEC-ORD-03); null para Payments-legacy y PayPal.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "preference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de preferencia MP o ID de orden PayPal.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("FAILED", "Fallido"),
                            ("REFUNDED", "Reembolsado"),
                            ("PARTIALLY_REFUNDED", "Reembolso parcial"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Importe cobrado. Coincide con OrderValue.total al momento del pago.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "installments",
                    models.PositiveIntegerField(
                        default=1, help_text="Número de cuotas. 1 = pago de contado."
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chargeback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway_chargeback_id",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("gateway_payment_id", models.CharField(db_index=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("lost", "Perdido"),
                            ("won", "Ganado"),
                            ("cancelled", "Cancelado"),
                            ("closed", "Cerrado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chargebacks",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contracargo",
                "db_table": "payments_chargeback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("WEBHOOK_RECEIVED", "Webhook recibido"),
                            ("PREFERENCE_CREATED", "Preferencia creada"),
                            ("PAYMENT_APPROVED", "Pago aprobado"),
                            ("PAYMENT_FAILED", "Pago fallido"),
                            ("REFUND_CREATED", "Reembolso creado"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "raw_body",
                    models.TextField(
                        help_text="Respuesta completa del gateway almacenada como texto."
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento del gateway",
                "db_table": "payments_gateway_event",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("reason", models.TextField(blank=True, default="")),
                (
                    "gateway_refund_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("APPROVED", "Aprobado"),
                            ("FAILED", "Fallido"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reembolso",
                "db_table": "payments_refund",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(max_length=20)),
                ("event_id", models.CharField(max_length=100)),
                (
                    "transmission_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("raw_body", models.TextField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Webhook event",
                "db_table": "payments_webhook_event",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gateway", "event_id", "transmission_id"),
                        name="unique_webhook_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mp_card_id", models.CharField(db_index=True, max_length=100)),
                ("mp_customer_id", models.CharField(db_index=True, max_length=100)),
                ("last_four_digits", models.CharField(max_length=4)),
                (
                    "first_six_digits",
                    models.CharField(blank=True, default="", max_length=6),
                ),
                ("expiration_month", models.PositiveSmallIntegerField()),
                ("expiration_year", models.PositiveSmallIntegerField()),
                (
                    "payment_method_id",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "cardholder_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_verification", "Pendiente de verificación"),
                            ("active", "Activa"),
                            ("deleted", "Eliminada"),
                        ],
                        db_index=True,
                        default="pending_verification",
                        max_length=30,
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        default=apps.payments.models._make_verification_token,
                        help_text="Token de un solo uso enviado por email para activar la tarjeta.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarjeta guardada",
                "db_table": "payments_saved_card",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "mp_card_id"), name="unique_user_mp_card"
                    )
                ],
            },
        ),
    ]
