# Generated by Django 5.0.1 on 2026-05-23 06:55
# T-119 merge-safe: WebhookEvent may already exist from 0003_webhook_event (Branch A).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_squashed_0002_sync_model_drift"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS `payments_webhook_event` (
                            `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                            `gateway` varchar(20) NOT NULL,
                            `event_id` varchar(100) NOT NULL,
                            `transmission_id` varchar(100) NOT NULL DEFAULT '',
                            `raw_body` longtext NOT NULL,
                            `processed_at` datetime(6) NOT NULL,
                            UNIQUE KEY `payments_webhook_event_gwy_eid_tid_uniq`
                                (`gateway`, `event_id`, `transmission_id`)
                        )
                    """,
                    reverse_sql="DROP TABLE IF EXISTS `payments_webhook_event`",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="WebhookEvent",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("gateway", models.CharField(max_length=20)),
                        ("event_id", models.CharField(max_length=100)),
                        (
                            "transmission_id",
                            models.CharField(blank=True, default="", max_length=100),
                        ),
                        ("raw_body", models.TextField()),
                        ("processed_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "verbose_name": "Webhook event",
                        "db_table": "payments_webhook_event",
                        "unique_together": {("gateway", "event_id", "transmission_id")},
                    },
                ),
            ],
        ),
    ]
