# Generated by Django 5.0.1 on 2026-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_merge_webhook_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhookevent",
            options={"verbose_name": "Webhook event"},
        ),
        # State has "unique_webhook_event" (from 0003_webhook_event Branch A).
        # DB has "payments_webhook_event_gwy_eid_tid_uniq" (from 0003_webhookevent Branch B).
        # Must separate ops to drop the index that actually exists in the DB.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE `payments_webhook_event` DROP INDEX IF EXISTS `payments_webhook_event_gwy_eid_tid_uniq`",
                    reverse_sql="ALTER TABLE `payments_webhook_event` ADD UNIQUE INDEX `payments_webhook_event_gwy_eid_tid_uniq` (`gateway`, `event_id`, `transmission_id`)",
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="webhookevent",
                    name="unique_webhook_event",
                ),
            ],
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="event_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="gateway",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="webhookevent",
            name="transmission_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="webhookevent",
            unique_together={("gateway", "event_id", "transmission_id")},
        ),
    ]
