# Generated by Django 5.0.1 on 2026-06-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_webhookevent_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="webhookevent",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="webhookevent",
            constraint=models.UniqueConstraint(
                fields=("gateway", "event_id", "transmission_id"),
                name="unique_webhook_event",
            ),
        ),
    ]
