# Generated by Django 6.0.5 on 2026-06-27 12:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_savedcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedcard",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="Chargeback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gateway_chargeback_id",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                ("gateway_payment_id", models.CharField(db_index=True, max_length=200)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("lost", "Perdido"),
                            ("won", "Ganado"),
                            ("cancelled", "Cancelado"),
                            ("closed", "Cerrado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chargebacks",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contracargo",
                "db_table": "payments_chargeback",
                "ordering": ["-created_at"],
            },
        ),
    ]
