# Generated by Django 6.0.5 on 2026-07-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_chargeback"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="mp_order_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID del recurso Order de MercadoPago (ORD...). Solo Orders API (DEC-ORD-03); null para Payments-legacy y PayPal.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="gateway_payment_id",
            field=models.CharField(
                blank=True,
                help_text="ID del pago confirmado por el gateway. Null hasta el webhook. En Orders API guarda el PAY... anidado (transactions.payments[].id).",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
    ]
