# Generated by Django 6.0.5 on 2026-08-02 22:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Formato REF-{user.id}-{6 chars}. Siempre en mayusculas.",
                        max_length=50,
                        unique=True,
                        verbose_name="Codigo referral",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_code",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Codigo referral",
                "db_table": "referral_code",
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Siempre en mayusculas. Insensible a mayusculas en validacion.",
                        max_length=50,
                        unique=True,
                        verbose_name="Codigo del cupon",
                    ),
                ),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Descuento fijo"),
                            ("PERCENTAGE", "Porcentaje"),
                            ("FREE_SHIPPING", "Envio gratis"),
                            ("REFERRAL", "Codigo referral"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Importe fijo a descontar. Solo para tipo FIXED.",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor del descuento (FIXED)",
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Porcentaje a descontar (0.01-100). Solo para tipo PERCENTAGE.",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="Porcentaje de descuento",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tope para descuentos porcentuales. Null = sin tope.",
                        max_digits=10,
                        null=True,
                        verbose_name="Descuento maximo",
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="El subtotal debe ser >= a este valor para aplicar el cupon.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Monto minimo del carrito",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Null = ilimitado.",
                        null=True,
                        verbose_name="Usos maximos",
                    ),
                ),
                (
                    "current_uses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Usos actuales"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="Vigente desde")),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Null = sin fecha de expiracion.",
                        null=True,
                        verbose_name="Vigente hasta",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "restricted_to_email",
                    models.EmailField(
                        blank=True,
                        help_text="Si se indica, solo ese email puede usar el cupon.",
                        max_length=254,
                        null=True,
                        verbose_name="Solo para este email",
                    ),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deactivated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deactivated_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher",
                "db_table": "voucher_voucher",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pendiente"), ("COMPLETED", "Completado")],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "referee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reward_voucher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Voucher de recompensa emitido al referidor (Subflujo C).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referral_rewards",
                        to="loyalty.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referido",
                "db_table": "referral_referral",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changes",
                    models.JSONField(
                        help_text="Dict de {campo: {before, after}} con los cambios aplicados."
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_log",
                        to="loyalty.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cambio de voucher",
                "db_table": "voucher_change_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VoucherUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="loyalty.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher usage",
                "db_table": "voucher_usage",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "voucher"), name="unique_voucher_usage"
                    )
                ],
            },
        ),
    ]
