# Generated by Django 6.0.5 on 2026-07-21 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_seed_zone_costs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveOrder",
            fields=[],
            options={
                "verbose_name": "Orden activa",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="CancelledOrder",
            fields=[],
            options={
                "verbose_name": "Orden cancelada",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="DeliveredOrder",
            fields=[],
            options={
                "verbose_name": "Orden entregada",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="InPreparationOrder",
            fields=[],
            options={
                "verbose_name": "Orden en preparación",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="PendingOrder",
            fields=[],
            options={
                "verbose_name": "Orden pendiente",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="ProcessingOrder",
            fields=[],
            options={
                "verbose_name": "Orden en procesamiento",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="RefundedOrder",
            fields=[],
            options={
                "verbose_name": "Orden reembolsada",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
        migrations.CreateModel(
            name="ShippedOrder",
            fields=[],
            options={
                "verbose_name": "Orden enviada",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
    ]
