# Generated by Django 6.0.5 on 2026-07-22 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_shippingmethod"),
        ("orders", "0004_activeorder_cancelledorder_deliveredorder_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="order",
                    name="shipping_method",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="delivery.shippingmethod",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
