# Generated by Django 6.0.5 on 2026-07-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_shipping_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cart_token",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Carrito anónimo — draft sin user (S1, analisis-unificar-cart-order-sale).",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Carrito / cotización"),
                    ("PENDING", "Pendiente de pago"),
                    ("PROCESSING", "Procesando pago"),
                    ("PAID", "Pagado"),
                    ("IN_PREPARATION", "En preparación"),
                    ("SHIPPED", "Enviado"),
                    ("DELIVERED", "Entregado"),
                    ("CANCELLED", "Cancelado"),
                    ("CANCELLED_TIMEOUT", "Cancelado por timeout"),
                    ("REFUNDED", "Reembolsado"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
