# Generated by Django 6.0.5 on 2026-07-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_cart_token_alter_order_status"),
        ("sale", "0007_saleorder_guest_email_saleorder_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaddress",
            name="sale_order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_address",
                to="sale.saleorder",
            ),
        ),
        migrations.AddField(
            model_name="orderstatuslog",
            name="sale_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="sale.saleorder",
            ),
        ),
    ]
