# Generated by Django 6.0.5 on 2026-07-22 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderaddress_sale_order_orderstatuslog_sale_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddress",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatuslog",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="orders.order",
            ),
        ),
    ]
