# Generated by Django 6.0.5 on 2026-08-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale_stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorderdelivery",
            name="incoterm_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Lugar del Incoterm (Odoo sale.order.incoterm_location, sale_stock).",
                max_length=255,
            ),
        ),
    ]
