# Generated by Django 6.0.5 on 2026-08-07 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0017_accountmoveline_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountMoveLineTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        help_text="Apunte base sobre el que se aplica el impuesto "
                        "(≙ Odoo account.move.line.tax_ids, lado línea).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_tax_tags_applied_taxes",
                        to="account.accountmoveline",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        help_text="Impuesto aplicado a la línea (≙ Odoo tax_ids, "
                        "lado impuesto).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_tax_tags_move_lines",
                        to="account.accounttax",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impuesto aplicado a un apunte (puente tax_ids)",
                "verbose_name_plural": "Impuestos aplicados a apuntes (puente tax_ids)",
                "db_table": "account_update_tax_tags_aml_tax_rel",
            },
        ),
        migrations.CreateModel(
            name="AccountMoveLineTaxRepartition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    models.OneToOneField(
                        help_text="El apunte de impuesto mismo (≙ Odoo "
                        "tax_repartition_line_id, leído desde el lado del apunte).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_tax_tags_repartition",
                        to="account.accountmoveline",
                    ),
                ),
                (
                    "repartition_line",
                    models.ForeignKey(
                        help_text="Línea de reparto que generó este apunte de "
                        "impuesto (≙ Odoo tax_repartition_line_id, lado reparto).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_tax_tags_originated_lines",
                        to="account.accounttaxrepartitionline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reparto que originó un apunte (puente "
                "tax_repartition_line_id)",
                "verbose_name_plural": "Repartos que originaron apuntes (puente "
                "tax_repartition_line_id)",
                "db_table": "account_update_tax_tags_aml_tax_repartition",
            },
        ),
        migrations.CreateModel(
            name="AccountMoveLineTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        help_text="Apunte que lleva la casilla (≙ Odoo "
                        "tax_tag_ids, lado línea).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_tax_tags_tags",
                        to="account.accountmoveline",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Casilla fiscal vigente en el apunte (≙ Odoo "
                        "tax_tag_ids, lado casilla).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_tax_tags_move_lines",
                        to="account.accountaccounttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Casilla fiscal vigente de un apunte (puente "
                "tax_tag_ids)",
                "verbose_name_plural": "Casillas fiscales vigentes de apuntes "
                "(puente tax_tag_ids)",
                "db_table": "account_update_tax_tags_aml_tag_rel",
            },
        ),
        migrations.AddConstraint(
            model_name="accountmovelinetax",
            constraint=models.UniqueConstraint(
                fields=("line", "tax"), name="account_update_tax_tags_aml_tax_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountmovelinetag",
            constraint=models.UniqueConstraint(
                fields=("line", "tag"), name="account_update_tax_tags_aml_tag_uniq"
            ),
        ),
    ]
