# Generated by Django 6.0.5 on 2026-08-21 18:38

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz_totp", "0002_seed_totp_parameters"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthTotpDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Odoo name ("Description") — para qué es esta clave.',
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        help_text='Odoo scope. NULL da acceso a cualquier RPC; con valor, sólo a ese ámbito ("rpc", "browser").',
                        null=True,
                        verbose_name="Ámbito",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Odoo expiration_date. NULL es una clave permanente, que sólo un usuario de sistema puede crear.",
                        null=True,
                        verbose_name="Fecha de caducidad",
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        db_index=True,
                        help_text="Odoo index — los primeros 8 hexadecimales de la clave, en claro. Es por lo que se busca la fila; NO es la clave.",
                        max_length=8,
                        verbose_name="Prefijo",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Odoo key — el hash de la clave completa. SECRETO: ningún serializer lo expone, igual que el secreto TOTP.",
                        verbose_name="Clave (hash)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Odoo user_id — el dueño del dispositivo de confianza.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispositivo de confianza",
                "verbose_name_plural": "Dispositivos de confianza",
                "db_table": "auth_totp_device",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "index"],
                        name="auth_totp_device_user_id_index_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=django.db.models.lookups.Exact(
                            django.db.models.functions.text.Length(models.F("index")), 8
                        ),
                        name="auth_totp_device_index_size",
                        violation_error_code="TRUSTED_DEVICE_INDEX_SIZE",
                    )
                ],
            },
        ),
    ]
