# Generated by Django 6.0.5 on 2026-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz_totp", "0003_authtotpdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="totpsecret",
            name="last_counter",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Odoo totp_last_counter — el intervalo del último código aceptado. Un código sólo vale una vez: la comprobación exige que el contador del código presentado sea ESTRICTAMENTE mayor que éste.",
                null=True,
                verbose_name="Último contador",
            ),
        ),
    ]
