# Generated by Django 6.0.5 on 2026-08-27 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz_totp", "0004_totpsecret_last_counter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthTotpRateLimitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ip",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Odoo ip — forense. La fuente lo lee de su petición global (request.httprequest.environ["REMOTE_ADDR"]); aquí llega como argumento de _totp_rate_limit, que puede no tenerlo. Ningún consumidor lo lee: medido sobre odoo19c, los dos únicos consumidores del modelo son escribir y borrar.',
                        max_length=45,
                        verbose_name="IP",
                    ),
                ),
                (
                    "limit_type",
                    models.CharField(
                        choices=[
                            ("send_email", "Send Email"),
                            ("code_check", "Code Checking"),
                        ],
                        help_text="Odoo limit_type — qué acción se está contando.",
                        max_length=16,
                        verbose_name="Tipo de límite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Odoo user_id (required, readonly) — de quién es el intento que se cuenta. El readonly de la fuente es de su capa de vista y no tiene receptor en el modelo Django.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_rate_limit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intento 2FA contado",
                "verbose_name_plural": "Intentos 2FA contados",
                "db_table": "auth_totp_rate_limit_log",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["user", "limit_type", "created_at"],
                        name="authz_totp_rate_limit_idx",
                    )
                ],
            },
        ),
    ]
