# Generated by Django 6.0.5 on 2026-07-19 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailMessageSubtype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Nombre del subtipo (Odoo name), p. ej. "Discussions".',
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripcion mostrada en la notificacion (Odoo description).",
                    ),
                ),
                (
                    "internal",
                    models.BooleanField(
                        default=False,
                        help_text="Solo empleados internos reciben este subtipo (Odoo internal). Los subtipos internos no se envian a seguidores del portal.",
                    ),
                ),
                (
                    "res_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Modelo al que aplica el subtipo, p. ej. "orders.Order" (Odoo res_model). Vacio = aplica a todos los modelos.',
                        max_length=128,
                    ),
                ),
                (
                    "relation_field",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Campo de relacion para auto-suscripcion cross-modelo (Odoo relation_field).",
                        max_length=128,
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        default=True,
                        help_text="Activado por defecto al seguir un registro (Odoo default).",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1, help_text="Orden de despliegue (Odoo sequence)."
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Oculto en la vista de preferencias del seguidor (Odoo hidden).",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subtipo padre para relaciones cross-modelo (Odoo parent_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="mail.mailmessagesubtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtipo de mensaje",
                "verbose_name_plural": "Subtipos de mensaje",
                "db_table": "mail_message_subtype",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="MailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Asunto del mensaje (Odoo subject).",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text="Fecha del mensaje (Odoo date, default now — se fija en save()).",
                        null=True,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contenido HTML del mensaje (Odoo body; saneo en capa UI).",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Modelo polimorfico referenciado, p. ej. "support.SupportTicket" (Odoo model). NO es una FK — vinculo plano igual que Odoo.',
                        max_length=128,
                    ),
                ),
                (
                    "res_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del registro referenciado (Odoo res_id, Integer plano).",
                        null=True,
                    ),
                ),
                (
                    "record_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre legible del registro referenciado (Odoo record_name).",
                        max_length=255,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("email", "Incoming Email"),
                            ("comment", "Comment"),
                            ("email_outgoing", "Outgoing Email"),
                            ("notification", "System notification"),
                            ("auto_comment", "Automated Targeted Notification"),
                        ],
                        default="comment",
                        help_text="Tipo de mensaje (Odoo message_type).",
                        max_length=16,
                    ),
                ),
                (
                    "email_from",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Remitente cuando no hay autor registrado (Odoo email_from).",
                        max_length=254,
                    ),
                ),
                (
                    "reply_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Direccion Reply-To (Odoo reply_to).",
                        max_length=254,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        help_text="Autor del mensaje (Odoo author_id → res.partner; party = IdentityUser).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Mensaje padre para el hilo de conversacion (Odoo parent_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="mail.mailmessage",
                    ),
                ),
                (
                    "subtype",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subtipo del mensaje (Odoo subtype_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="mail.mailmessagesubtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje",
                "verbose_name_plural": "Mensajes",
                "db_table": "mail_message",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MailFollowers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "res_model",
                    models.CharField(
                        help_text='Modelo del registro seguido, p. ej. "support.SupportTicket" (Odoo res_model).',
                        max_length=128,
                    ),
                ),
                (
                    "res_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del registro seguido (Odoo res_id, Integer plano).",
                        null=True,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Party seguidor (Odoo partner_id → res.partner; party = IdentityUser).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subtype_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Subtipos que este seguidor recibe (Odoo subtype_ids).",
                        related_name="followers",
                        to="mail.mailmessagesubtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seguidor",
                "verbose_name_plural": "Seguidores",
                "db_table": "mail_followers",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="mailmessagesubtype",
            index=models.Index(fields=["res_model"], name="mail_subtype_res_model_idx"),
        ),
        migrations.AddIndex(
            model_name="mailmessage",
            index=models.Index(
                fields=["model", "res_id"], name="mail_message_record_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailmessage",
            index=models.Index(fields=["author"], name="mail_message_author_idx"),
        ),
        migrations.AddIndex(
            model_name="mailfollowers",
            index=models.Index(
                fields=["res_model", "res_id"], name="mail_followers_record_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mailfollowers",
            constraint=models.UniqueConstraint(
                fields=("res_model", "res_id", "partner"),
                name="mail_followers_res_partner_uniq",
            ),
        ),
    ]
