# Generated by Django 6.0.5 on 2026-07-19 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo (Odoo name).", max_length=255
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resumen por defecto de la actividad (Odoo summary).",
                        max_length=255,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(default=10, help_text="Orden (Odoo sequence)."),
                ),
                ("active", models.BooleanField(default=True, help_text="Odoo active.")),
                (
                    "delay_count",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de plazo por defecto (Odoo delay_count).",
                    ),
                ),
                (
                    "delay_unit",
                    models.CharField(
                        choices=[
                            ("days", "days"),
                            ("weeks", "weeks"),
                            ("months", "months"),
                        ],
                        default="days",
                        help_text="Unidad del plazo (Odoo delay_unit).",
                        max_length=8,
                    ),
                ),
                (
                    "delay_from",
                    models.CharField(
                        choices=[
                            ("current_date", "after completion date"),
                            ("previous_activity", "after previous activity deadline"),
                        ],
                        default="previous_activity",
                        help_text="Origen del plazo (Odoo delay_from).",
                        max_length=20,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icono FontAwesome, p. ej. fa-tasks (Odoo icon).",
                        max_length=64,
                    ),
                ),
                (
                    "decoration_type",
                    models.CharField(
                        blank=True,
                        choices=[("warning", "Alert"), ("danger", "Error")],
                        default="",
                        help_text="Decoracion visual (Odoo decoration_type).",
                        max_length=8,
                    ),
                ),
                (
                    "res_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Modelo al que aplica, p. ej. "orders.Order"; vacio = todos (Odoo res_model).',
                        max_length=128,
                    ),
                ),
                (
                    "chaining_type",
                    models.CharField(
                        choices=[
                            ("suggest", "Suggest Next Activity"),
                            ("trigger", "Trigger Next Activity"),
                        ],
                        default="suggest",
                        help_text="Encadenamiento a la siguiente actividad (Odoo chaining_type).",
                        max_length=8,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("default", "None"),
                            ("upload_file", "Upload Document"),
                            ("phonecall", "Phonecall"),
                        ],
                        default="default",
                        help_text="Categoria de accion (Odoo category).",
                        max_length=16,
                    ),
                ),
                (
                    "default_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Nota por defecto (Odoo default_note).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de actividad",
                "verbose_name_plural": "Tipos de actividad",
                "db_table": "mail_activity_type",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="MailActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "res_model",
                    models.CharField(
                        help_text='Modelo del registro, p. ej. "support.SupportTicket" (Odoo res_model).',
                        max_length=128,
                    ),
                ),
                (
                    "res_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID del registro (Odoo res_id, Integer plano).",
                        null=True,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resumen (Odoo summary).",
                        max_length=255,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, default="", help_text="Nota (Odoo note)."
                    ),
                ),
                (
                    "date_deadline",
                    models.DateField(
                        blank=True,
                        default=django.utils.timezone.localdate,
                        help_text="Fecha limite (Odoo date_deadline, default hoy).",
                    ),
                ),
                (
                    "automated",
                    models.BooleanField(
                        default=False,
                        help_text="Generada por una regla automatica, no manual (Odoo automated).",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario asignado (Odoo user_id → res.users; party = IdentityUser).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "activity_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tipo de actividad (Odoo activity_type_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="mail.mailactivitytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
                "db_table": "mail_activity",
                "ordering": ["date_deadline", "id"],
                "indexes": [
                    models.Index(
                        fields=["res_model", "res_id"], name="mail_activity_record_idx"
                    ),
                    models.Index(
                        fields=["user", "date_deadline"], name="mail_activity_user_idx"
                    ),
                ],
            },
        ),
    ]
