# Generated by Django 6.0.5 on 2026-07-19 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_irdefault"),
        ("mail", "0002_mailactivitytype_mailactivity"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTrackingValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "field",
                    models.CharField(
                        help_text="Nombre del campo rastreado (Odoo field_id.name; plano, sin ir.model.fields).",
                        max_length=128,
                    ),
                ),
                (
                    "field_desc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta legible del campo (Odoo field_id.field_description).",
                        max_length=255,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        blank=True,
                        default="char",
                        help_text="Tipo del campo: char/integer/float/text/datetime/monetary/boolean (Odoo field_type).",
                        max_length=32,
                    ),
                ),
                (
                    "old_value_integer",
                    models.IntegerField(
                        blank=True, help_text="Odoo old_value_integer.", null=True
                    ),
                ),
                (
                    "old_value_float",
                    models.FloatField(
                        blank=True, help_text="Odoo old_value_float.", null=True
                    ),
                ),
                (
                    "old_value_char",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo old_value_char.",
                        max_length=255,
                    ),
                ),
                (
                    "old_value_text",
                    models.TextField(
                        blank=True, default="", help_text="Odoo old_value_text."
                    ),
                ),
                (
                    "old_value_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Odoo old_value_datetime.", null=True
                    ),
                ),
                (
                    "new_value_integer",
                    models.IntegerField(
                        blank=True, help_text="Odoo new_value_integer.", null=True
                    ),
                ),
                (
                    "new_value_float",
                    models.FloatField(
                        blank=True, help_text="Odoo new_value_float.", null=True
                    ),
                ),
                (
                    "new_value_char",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo new_value_char.",
                        max_length=255,
                    ),
                ),
                (
                    "new_value_text",
                    models.TextField(
                        blank=True, default="", help_text="Odoo new_value_text."
                    ),
                ),
                (
                    "new_value_datetime",
                    models.DateTimeField(
                        blank=True, help_text="Odoo new_value_datetime.", null=True
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda para campos monetarios (Odoo currency_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="base.rescurrency",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Mensaje de notificacion asociado (Odoo mail_message_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_value_ids",
                        to="mail.mailmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor rastreado",
                "verbose_name_plural": "Valores rastreados",
                "db_table": "mail_tracking_value",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["message"], name="mail_trackval_message_idx")
                ],
            },
        ),
    ]
