# Generated by Django 6.0.5 on 2026-07-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_seed_message_subtypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailactivitytype",
            name="res_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Modelo al que aplica, p. ej. "sale.SaleOrder"; vacio = todos (Odoo res_model).',
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="mailmessagesubtype",
            name="res_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Modelo al que aplica el subtipo, p. ej. "sale.SaleOrder" (Odoo res_model). Vacio = aplica a todos los modelos.',
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="mailtemplate",
            name="model",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Modelo aplicable, p. ej. "sale.SaleOrder" (Odoo model/model_id).',
                max_length=128,
            ),
        ),
    ]
