# Generated by Django 6.0.5 on 2026-07-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_mailtrackingvalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la plantilla (Odoo name).", max_length=255
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Modelo aplicable, p. ej. "orders.Order" (Odoo model/model_id).',
                        max_length=128,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Asunto con placeholders {{ object.campo }} (Odoo subject).",
                        max_length=255,
                    ),
                ),
                (
                    "email_from",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Remitente, admite placeholders (Odoo email_from).",
                        max_length=255,
                    ),
                ),
                (
                    "use_default_to",
                    models.BooleanField(
                        default=False,
                        help_text="Usar el destinatario por defecto del registro (Odoo use_default_to).",
                    ),
                ),
                (
                    "email_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Destinatarios coma-separados, admite placeholders (Odoo email_to).",
                        max_length=255,
                    ),
                ),
                (
                    "partner_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="IDs de party destinatarios, admite placeholders (Odoo partner_to).",
                        max_length=255,
                    ),
                ),
                (
                    "email_cc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Copia (CC), admite placeholders (Odoo email_cc).",
                        max_length=255,
                    ),
                ),
                (
                    "reply_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Reply-To (Odoo reply_to).",
                        max_length=255,
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Cuerpo HTML con placeholders {{ object.campo }} (Odoo body_html).",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Expresion de idioma para la traduccion (Odoo lang).",
                        max_length=16,
                    ),
                ),
                (
                    "scheduled_date",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fecha/expresion de envio diferido (Odoo scheduled_date).",
                        max_length=64,
                    ),
                ),
                (
                    "auto_delete",
                    models.BooleanField(
                        default=True,
                        help_text="Eliminar el mail.mail tras enviar (Odoo auto_delete).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla de correo",
                "verbose_name_plural": "Plantillas de correo",
                "db_table": "mail_template",
                "ordering": ["name", "id"],
                "indexes": [
                    models.Index(fields=["model"], name="mail_template_model_idx")
                ],
            },
        ),
    ]
