# Generated by Django 6.0.5 on 2026-07-19 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0004_mailtemplate"),
        ("notifications", "0001_initial"),
        ("sms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("inbox", "Inbox"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        default="inbox",
                        help_text="Canal de entrega (Odoo notification_type).",
                        max_length=8,
                    ),
                ),
                (
                    "notification_status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready to Send"),
                            ("process", "Processing"),
                            ("sent", "Sent"),
                            ("bounce", "Bounced"),
                            ("exception", "Exception"),
                            ("canceled", "Canceled"),
                        ],
                        default="ready",
                        help_text="Estado de entrega (Odoo notification_status).",
                        max_length=12,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Leido por el destinatario (Odoo is_read).",
                    ),
                ),
                (
                    "read_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento de lectura (Odoo read_date).",
                        null=True,
                    ),
                ),
                (
                    "failure_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unknown", "Unknown error"),
                            ("mail_email_invalid", "Invalid email address"),
                            ("mail_smtp", "Connection failed (SMTP)"),
                            ("sms_number_missing", "Missing number"),
                            ("sms_credit", "Insufficient credit"),
                        ],
                        help_text="Clasificacion del fallo (Odoo failure_type).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detalle del fallo (Odoo failure_reason).",
                    ),
                ),
                (
                    "email_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Envio de correo asociado (Odoo mail_mail_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mail_notifications",
                        to="notifications.emailtask",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="Mensaje entregado (Odoo mail_message_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_ids",
                        to="mail.mailmessage",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        help_text="Destinatario (Odoo res_partner_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sms",
                    models.ForeignKey(
                        blank=True,
                        help_text="SMS saliente asociado (Odoo sms_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mail_notifications",
                        to="sms.smssms",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificacion de mensaje",
                "verbose_name_plural": "Notificaciones de mensaje",
                "db_table": "mail_notification",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["partner", "is_read"],
                        name="mail_notifi_partner_81a1e9_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "notification_status"],
                        name="mail_notifi_notific_c7073d_idx",
                    ),
                ],
            },
        ),
    ]
