# Generated by Django 6.0.5 on 2026-07-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0006_seed_message_subtypes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Asunto del correo (Odoo mail.message.subject).",
                        max_length=255,
                    ),
                ),
                (
                    "email_from",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Remitente (Odoo mail.message.email_from).",
                        max_length=254,
                    ),
                ),
                (
                    "email_to",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Destinatarios, coma-separados (Odoo email_to).",
                    ),
                ),
                (
                    "email_cc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Copia CC (Odoo email_cc).",
                        max_length=255,
                    ),
                ),
                (
                    "body_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Cuerpo del correo, rich-text/HTML (Odoo body_html).",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("outgoing", "Outgoing"),
                            ("sent", "Sent"),
                            ("received", "Received"),
                            ("exception", "Delivery Failed"),
                            ("cancel", "Cancelled"),
                        ],
                        default="outgoing",
                        help_text="Estado del envio (Odoo state).",
                        max_length=10,
                    ),
                ),
                (
                    "failure_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unknown", "Unknown error"),
                            ("mail_spam", "Detected As Spam"),
                            ("mail_email_invalid", "Invalid email address"),
                            ("mail_email_missing", "Missing email"),
                            ("mail_from_invalid", "Invalid from address"),
                            ("mail_from_missing", "Missing from address"),
                            (
                                "mail_smtp",
                                "Connection failed (outgoing mail server problem)",
                            ),
                        ],
                        help_text="Clasificacion del fallo de entrega (Odoo failure_type).",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detalle del fallo, tipicamente la excepcion SMTP (Odoo failure_reason).",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Envio diferido: la cola envia despues de esta fecha (Odoo scheduled_date).",
                        null=True,
                    ),
                ),
                (
                    "auto_delete",
                    models.BooleanField(
                        default=False,
                        help_text="Eliminar el registro tras enviar (Odoo auto_delete).",
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0,
                        help_text="Intentos de envio realizados (adaptacion de proyecto).",
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3,
                        help_text="Tope de reintentos antes de exception (adaptacion de proyecto).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correo saliente",
                "verbose_name_plural": "Correos salientes",
                "db_table": "mail_mail",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["state", "scheduled_date"], name="mail_mail_queue_idx"
                    )
                ],
            },
        ),
    ]
