# Generated by Django 6.0.5 on 2026-07-19 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0007_mailmail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailnotification",
            name="email_task",
        ),
        migrations.AddField(
            model_name="mailnotification",
            name="mail_mail",
            field=models.ForeignKey(
                blank=True,
                help_text="Envio de correo asociado (Odoo mail_mail_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mail_notifications",
                to="mail.mailmail",
            ),
        ),
    ]
