# Generated by Django 6.0.5 on 2026-08-19 04:55

import addons.hr_recruitment.models.hr_applicant_category
import addons.hr_recruitment.models.hr_recruitment_source
import addons.hr_recruitment.models.hr_recruitment_stage
import addons.hr_recruitment.models.hr_talent_pool
import django.db.models.deletion
import django.utils.timezone
import orm.environments
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0029_rescompany_internal_project_id_and_more"),
        ("hr", "0009_hremployeepublic"),
        ("mail", "0004_seed_cron_email_queue"),
        ("utm", "0002_seed_utm_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HrApplicantCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Odoo "Tag Name".',
                        max_length=255,
                        verbose_name="Nombre de la etiqueta",
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=addons.hr_recruitment.models.hr_applicant_category._get_default_color,
                        verbose_name="Índice de color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta de candidato",
                "verbose_name_plural": "Etiquetas de candidato",
                "db_table": "hr_applicant_category",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="hr_applicant_category_name_uniq",
                        violation_error_message="Tag name already exists!",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HrApplicantRefuseReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.IntegerField(default=10)),
                ("name", models.CharField(max_length=255, verbose_name="Descripción")),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo template_id: plantilla usada al notificar el rechazo (domain hr.applicant filtrado en la capa de formulario, no aquí).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_applicant_refuse_reasons",
                        to="mail.mailtemplate",
                        verbose_name="Plantilla de correo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo de rechazo",
                "verbose_name_plural": "Motivos de rechazo",
                "db_table": "hr_applicant_refuse_reason",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="HrJobPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.CharField(
                        help_text="Applications received from this Email won't be linked to a contact. There will be no email address set on the Applicant either.",
                        max_length=255,
                    ),
                ),
                (
                    "regex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The regex facilitates to extract information from the subject or body of the received email to autopopulate the Applicant's name field.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plataforma de reclutamiento",
                "verbose_name_plural": "Plataformas de reclutamiento",
                "db_table": "hr_job_platform",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email",),
                        name="hr_job_platform_email_uniq",
                        violation_error_message="The Email must be unique, this one already corresponds to another Job Platform.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HrRecruitmentDegree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Odoo "Degree Name".',
                        max_length=255,
                        verbose_name="Nombre del grado",
                    ),
                ),
                ("score", models.FloatField(default=0, verbose_name="Puntaje")),
                ("sequence", models.IntegerField(default=1, verbose_name="Secuencia")),
            ],
            options={
                "verbose_name": "Grado académico",
                "verbose_name_plural": "Grados académicos",
                "db_table": "hr_recruitment_degree",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",),
                        name="hr_recruitment_degree_name_uniq",
                        violation_error_message="The name of the Degree of Recruitment must be unique!",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 1)),
                        name="hr_recruitment_degree_score_range",
                        violation_error_message="Score should be between 0 and 100%",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HrRecruitmentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alias",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recruitment_sources",
                        to="mail.mailalias",
                        verbose_name="Alias de correo",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="utm.utmcampaign",
                        verbose_name="Campaña",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_sources",
                        to="hr.hrjob",
                        verbose_name="Puesto",
                    ),
                ),
                (
                    "medium",
                    models.ForeignKey(
                        blank=True,
                        default=addons.hr_recruitment.models.hr_recruitment_source._default_medium,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="utm.utmmedium",
                        verbose_name="Medio",
                    ),
                ),
                (
                    "source_id",
                    models.ForeignKey(
                        help_text="Fuente UTM asociada a este registro.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="utm.utmsource",
                        verbose_name="Fuente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Origen de reclutamiento",
                "verbose_name_plural": "Orígenes de reclutamiento",
                "db_table": "hr_recruitment_source",
            },
        ),
        migrations.CreateModel(
            name="HrRecruitmentStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nombre de la etapa"),
                ),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                (
                    "requirements",
                    models.TextField(blank=True, default="", verbose_name="Requisitos"),
                ),
                (
                    "fold",
                    models.BooleanField(
                        default=False,
                        help_text="Esta etapa se pliega en la vista kanban cuando no hay registros que mostrar.",
                        verbose_name="Plegada en kanban",
                    ),
                ),
                (
                    "hired_stage",
                    models.BooleanField(
                        default=False,
                        help_text="Si se marca, esta etapa determina la fecha de contratación de un candidato.",
                        verbose_name="Etapa de contratación",
                    ),
                ),
                (
                    "rotting_threshold_days",
                    models.IntegerField(
                        default=0,
                        help_text="Días antes de que los candidatos en esta etapa se consideren vencidos. 0 desactiva.",
                        verbose_name="Días para viciarse",
                    ),
                ),
                (
                    "legend_blocked",
                    models.CharField(
                        default=addons.hr_recruitment.models.hr_recruitment_stage._default_legend_blocked,
                        max_length=255,
                        verbose_name="Etiqueta kanban roja",
                    ),
                ),
                (
                    "legend_waiting",
                    models.CharField(
                        default=addons.hr_recruitment.models.hr_recruitment_stage._default_legend_waiting,
                        max_length=255,
                        verbose_name="Etiqueta kanban naranja",
                    ),
                ),
                (
                    "legend_done",
                    models.CharField(
                        default=addons.hr_recruitment.models.hr_recruitment_stage._default_legend_done,
                        max_length=255,
                        verbose_name="Etiqueta kanban verde",
                    ),
                ),
                (
                    "legend_normal",
                    models.CharField(
                        default=addons.hr_recruitment.models.hr_recruitment_stage._default_legend_normal,
                        max_length=255,
                        verbose_name="Etiqueta kanban gris",
                    ),
                ),
                (
                    "jobs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Odoo job_ids: puestos que usan esta etapa. Otros puestos no la usarán.",
                        related_name="recruitment_stages",
                        to="hr.hrjob",
                        verbose_name="Específica de puestos",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo template_id: se publica un mensaje sobre el candidato con esta plantilla al entrar en la etapa.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_recruitment_stages",
                        to="mail.mailtemplate",
                        verbose_name="Plantilla de correo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de reclutamiento",
                "verbose_name_plural": "Etapas de reclutamiento",
                "db_table": "hr_recruitment_stage",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="HrApplicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.IntegerField(
                        db_index=True, default=10, verbose_name="Secuencia"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="Activo"
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nombre del candidato",
                    ),
                ),
                (
                    "email_from",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=128,
                        verbose_name="Correo",
                    ),
                ),
                (
                    "email_normalized",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "partner_phone",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Teléfono"
                    ),
                ),
                (
                    "partner_phone_sanitized",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                (
                    "linkedin_profile",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Perfil de LinkedIn",
                    ),
                ),
                (
                    "availability",
                    models.DateField(
                        blank=True, null=True, verbose_name="Disponibilidad"
                    ),
                ),
                (
                    "color",
                    models.IntegerField(default=0, verbose_name="Índice de color"),
                ),
                (
                    "probability",
                    models.FloatField(default=0, verbose_name="Probabilidad"),
                ),
                (
                    "date_closed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de contratación"
                    ),
                ),
                (
                    "date_open",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de asignación"
                    ),
                ),
                (
                    "date_last_stage_update",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Última actualización de etapa",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("0", "Normal"),
                            ("1", "Buena"),
                            ("2", "Muy buena"),
                            ("3", "Excelente"),
                        ],
                        default="0",
                        max_length=1,
                        verbose_name="Evaluación",
                    ),
                ),
                (
                    "salary_proposed_extra",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Extra propuesto",
                    ),
                ),
                (
                    "salary_expected_extra",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Extra esperado",
                    ),
                ),
                (
                    "salary_proposed",
                    models.FloatField(default=0, verbose_name="Salario propuesto"),
                ),
                (
                    "salary_expected",
                    models.FloatField(default=0, verbose_name="Salario esperado"),
                ),
                (
                    "delay_close",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Demora al cierre"
                    ),
                ),
                (
                    "kanban_state",
                    models.CharField(
                        choices=[
                            ("normal", "En progreso"),
                            ("done", "Listo para la siguiente etapa"),
                            ("waiting", "Esperando"),
                            ("blocked", "Bloqueado"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Estado kanban",
                    ),
                ),
                (
                    "applicant_properties",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Propiedades del candidato"
                    ),
                ),
                (
                    "applicant_notes",
                    models.TextField(blank=True, default="", verbose_name="Notas"),
                ),
                (
                    "refuse_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de rechazo"
                    ),
                ),
                (
                    "campaign_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Nombre con el que se distingue cada esfuerzo de campaña, p. ej. Fall_Drive, Christmas_Special.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="utm.utmcampaign",
                        verbose_name="Campaña",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicants",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicants",
                        to="hr.hrdepartment",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicant_ids",
                        to="hr.hremployee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "interviewers",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="interviewing_applicants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entrevistadores",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="hr.hrjob",
                        verbose_name="Puesto",
                    ),
                ),
                (
                    "medium_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Método de entrega: postal, correo, banner.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="utm.utmmedium",
                        verbose_name="Medio",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicant_ids",
                        to="base.respartner",
                        verbose_name="Contacto",
                    ),
                ),
                (
                    "pool_applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pool_copies",
                        to="hr_recruitment.hrapplicant",
                        verbose_name="Candidato de la bolsa",
                    ),
                ),
                (
                    "source_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Origen del enlace: un buscador, otro dominio, o el nombre de una lista de correo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="utm.utmsource",
                        verbose_name="Fuente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruited_applicants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reclutador",
                    ),
                ),
                (
                    "categs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="applicants",
                        to="hr_recruitment.hrapplicantcategory",
                        verbose_name="Etiquetas",
                    ),
                ),
                (
                    "refuse_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicants",
                        to="hr_recruitment.hrapplicantrefusereason",
                        verbose_name="Motivo de rechazo",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applicants",
                        to="hr_recruitment.hrrecruitmentdegree",
                        verbose_name="Grado académico",
                    ),
                ),
                (
                    "last_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="hr_recruitment.hrrecruitmentstage",
                        verbose_name="Última etapa",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicants",
                        to="hr_recruitment.hrrecruitmentstage",
                        verbose_name="Etapa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Candidato",
                "verbose_name_plural": "Candidatos",
                "db_table": "hr_applicant",
                "ordering": ["-priority", "sequence", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HrTalentPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "name",
                    models.CharField(
                        help_text='Odoo "Title".', max_length=255, verbose_name="Título"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=addons.hr_recruitment.models.hr_talent_pool._get_default_color,
                        verbose_name="Color",
                    ),
                ),
                (
                    "categs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="talent_pools",
                        to="hr_recruitment.hrapplicantcategory",
                        verbose_name="Etiquetas",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        default=orm.environments.get_current_company,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_talent_pools",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "pool_manager",
                    models.ForeignKey(
                        blank=True,
                        default=orm.environments.get_current_user,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_talent_pools",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable de la bolsa",
                    ),
                ),
                (
                    "talents",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Odoo talent_ids: los candidatos de esta bolsa.",
                        related_name="talent_pools",
                        to="hr_recruitment.hrapplicant",
                        verbose_name="Talentos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bolsa de talento",
                "verbose_name_plural": "Bolsas de talento",
                "db_table": "hr_talent_pool",
            },
        ),
        migrations.AddIndex(
            model_name="hrapplicant",
            index=models.Index(
                condition=models.Q(("active", True)),
                fields=["job", "stage"],
                name="hr_applicant_job_stage_idx",
            ),
        ),
    ]
