# Generated by Django 6.0.5 on 2026-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_recruitment", "0001_initial"),
        ("hr_skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrapplicant",
            name="skill_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Odoo skill_ids (compute+store) — sincronizar con _compute_skill_ids().",
                related_name="applicants_with_skill",
                to="hr_skills.hrskill",
            ),
        ),
    ]
