# Generated by Django 6.0.5 on 2026-08-20 09:14

import addons.hr_recruitment.models.hr_recruitment_stage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_recruitment", "0002_hrapplicant_skill_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrapplicant",
            name="email_normalized",
            field=models.CharField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="kanban_state",
            field=models.CharField(
                choices=[
                    ("normal", "En progreso"),
                    ("done", "Listo para la siguiente etapa"),
                    ("waiting", "Esperando"),
                    ("blocked", "Bloqueado"),
                ],
                default="normal",
                verbose_name="Estado kanban",
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="linkedin_profile",
            field=models.CharField(
                blank=True, default="", verbose_name="Perfil de LinkedIn"
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="partner_name",
            field=models.CharField(
                blank=True, default="", verbose_name="Nombre del candidato"
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="partner_phone_sanitized",
            field=models.CharField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="priority",
            field=models.CharField(
                choices=[
                    ("0", "Normal"),
                    ("1", "Buena"),
                    ("2", "Muy buena"),
                    ("3", "Excelente"),
                ],
                default="0",
                verbose_name="Evaluación",
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="salary_expected_extra",
            field=models.CharField(
                blank=True, default="", verbose_name="Extra esperado"
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="salary_proposed_extra",
            field=models.CharField(
                blank=True, default="", verbose_name="Extra propuesto"
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicantcategory",
            name="name",
            field=models.CharField(
                help_text='Odoo "Tag Name".', verbose_name="Nombre de la etiqueta"
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicantrefusereason",
            name="name",
            field=models.CharField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="hrjobplatform",
            name="email",
            field=models.CharField(
                help_text="Applications received from this Email won't be linked to a contact. There will be no email address set on the Applicant either."
            ),
        ),
        migrations.AlterField(
            model_name="hrjobplatform",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="hrjobplatform",
            name="regex",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The regex facilitates to extract information from the subject or body of the received email to autopopulate the Applicant's name field.",
            ),
        ),
        migrations.AlterField(
            model_name="hrrecruitmentdegree",
            name="name",
            field=models.CharField(
                help_text='Odoo "Degree Name".', verbose_name="Nombre del grado"
            ),
        ),
        migrations.AlterField(
            model_name="hrrecruitmentstage",
            name="legend_blocked",
            field=models.CharField(
                default=addons.hr_recruitment.models.hr_recruitment_stage._default_legend_blocked,
                verbose_name="Etiqueta kanban roja",
            ),
        ),
        migrations.AlterField(
            model_name="hrrecruitmentstage",
            name="legend_done",
            field=models.CharField(
                default=addons.hr_recruitment.models.hr_recruitment_stage._default_legend_done,
                verbose_name="Etiqueta kanban verde",
            ),
        ),
        migrations.AlterField(
            model_name="hrrecruitmentstage",
            name="legend_normal",
            field=models.CharField(
                default=addons.hr_recruitment.models.hr_recruitment_stage._default_legend_normal,
                verbose_name="Etiqueta kanban gris",
            ),
        ),
        migrations.AlterField(
            model_name="hrrecruitmentstage",
            name="legend_waiting",
            field=models.CharField(
                default=addons.hr_recruitment.models.hr_recruitment_stage._default_legend_waiting,
                verbose_name="Etiqueta kanban naranja",
            ),
        ),
        migrations.AlterField(
            model_name="hrrecruitmentstage",
            name="name",
            field=models.CharField(verbose_name="Nombre de la etapa"),
        ),
        migrations.AlterField(
            model_name="hrtalentpool",
            name="name",
            field=models.CharField(help_text='Odoo "Title".', verbose_name="Título"),
        ),
    ]
