# Generated by Django 6.0.5 on 2026-08-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_recruitment", "0003_alter_hrapplicant_email_normalized_and_more"),
        ("utm", "0003_alter_utmcampaign_stage_id_alter_utmcampaign_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrapplicant",
            name="campaign_id",
            field=models.ForeignKey(
                blank=True,
                db_column="campaign_id",
                help_text="Nombre con el que se distingue cada esfuerzo de campaña, p. ej. Fall_Drive, Christmas_Special.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmcampaign",
                verbose_name="Campaña",
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="medium_id",
            field=models.ForeignKey(
                blank=True,
                db_column="medium_id",
                help_text="Método de entrega: postal, correo, banner.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmmedium",
                verbose_name="Medio",
            ),
        ),
        migrations.AlterField(
            model_name="hrapplicant",
            name="source_id",
            field=models.ForeignKey(
                blank=True,
                db_column="source_id",
                help_text="Origen del enlace: un buscador, otro dominio, o el nombre de una lista de correo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="utm.utmsource",
                verbose_name="Fuente",
            ),
        ),
        migrations.AlterField(
            model_name="hrrecruitmentsource",
            name="source_id",
            field=models.ForeignKey(
                db_column="source_id",
                help_text="Fuente UTM asociada a este registro.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="utm.utmsource",
                verbose_name="Fuente",
            ),
        ),
    ]
