# Generated by Django 6.0.5 on 2026-08-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgateway",
            name="so_reference_type",
            field=models.CharField(
                choices=[
                    ("so_name", "Según la referencia del documento"),
                    ("partner", "Según el identificador del cliente"),
                ],
                default="so_name",
                help_text='Odoo so_reference_type ("Communication"). Fija el tipo de comunicación que aparecerá en los pedidos de venta; se le entrega al cliente al elegir el método de pago.',
                max_length=16,
                verbose_name="Comunicación",
            ),
        ),
    ]
