# Generated by Django 5.0.1 on 2026-05-19 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("subject", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("read", models.BooleanField(default=False)),
                ("replied", models.BooleanField(default=False)),
                ("reply_body", models.TextField(blank=True, default="")),
                ("reply_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reply_sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_replies_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de contacto",
                "verbose_name_plural": "Mensajes de contacto",
                "db_table": "contact_message",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["read"], name="contact_mes_read_d4ce31_idx"),
                    models.Index(
                        fields=["-created_at"], name="contact_mes_created_54923f_idx"
                    ),
                ],
            },
        ),
    ]
