# Generated by Django 6.0.5 on 2026-08-03 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductMatrixConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "add_mode",
                    models.CharField(
                        choices=[
                            ("configurator", "Configurador"),
                            ("matrix", "Matriz"),
                        ],
                        default="configurator",
                        help_text="Modo de alta (Odoo product_add_mode).",
                        max_length=16,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Producto (Odoo product.template).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix_config",
                        to="product.productproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Config de matriz de producto",
                "verbose_name_plural": "Configs de matriz de producto",
                "db_table": "product_matrix_config",
            },
        ),
    ]
