# Generated by Django 6.0.5 on 2026-08-06 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0007_alter_iractionsreport_report_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="New key", max_length=255, verbose_name="Nombre"
                    ),
                ),
                ("content", models.BinaryField(verbose_name="Archivo de la llave")),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Contraseña de la llave privada",
                    ),
                ),
                (
                    "pem_key",
                    models.BinaryField(
                        blank=True,
                        help_text="Computado: PEM normalizado de la llave (pública o privada).",
                        null=True,
                        verbose_name="Bytes de la llave en PEM",
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        blank=True,
                        help_text="Computado: True si es pública, False si privada, None si no se pudo determinar (error de carga).",
                        null=True,
                        verbose_name="Pública/privada",
                    ),
                ),
                (
                    "loading_error",
                    models.TextField(
                        blank=True, default="", verbose_name="Error de carga"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Archivar sin borrar la llave.",
                        verbose_name="Activa",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_keys",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Llave criptográfica",
                "verbose_name_plural": "Llaves criptográficas",
                "db_table": "certificate_key",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="CertificateCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Nombre"
                    ),
                ),
                ("content", models.BinaryField(verbose_name="Certificado")),
                (
                    "pkcs12_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contraseña para descifrar el archivo PKCS12.",
                        max_length=255,
                        verbose_name="Contraseña del certificado",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        choices=[("general", "General")],
                        default="",
                        max_length=20,
                        verbose_name="Alcance del certificado",
                    ),
                ),
                (
                    "content_format",
                    models.CharField(
                        blank=True,
                        choices=[("der", "DER"), ("pem", "PEM"), ("pkcs12", "PKCS12")],
                        default="",
                        max_length=10,
                        verbose_name="Formato original del certificado",
                    ),
                ),
                (
                    "pem_certificate",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Certificado en PEM"
                    ),
                ),
                (
                    "subject_common_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nombre del sujeto",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="El número de serie a añadir a documentos electrónicos.",
                        max_length=64,
                        verbose_name="Número de serie",
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="La fecha desde la que el certificado es válido.",
                        null=True,
                        verbose_name="Fecha de disponibilidad",
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="La fecha en que el certificado expira.",
                        null=True,
                        verbose_name="Fecha de expiración",
                    ),
                ),
                (
                    "loading_error",
                    models.TextField(
                        blank=True, default="", verbose_name="Error de carga"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Archivar sin borrar el certificado.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="base.rescompany",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "private_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="Computado: se detecta o crea automáticamente al cargar el certificado.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates_as_private_key",
                        to="certificate.certificatekey",
                        verbose_name="Llave privada",
                    ),
                ),
                (
                    "public_key",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usar cuando la llave pública autocontenida en el certificado es errónea.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates_as_public_key",
                        to="certificate.certificatekey",
                        verbose_name="Llave pública",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "db_table": "certificate_certificate",
                "ordering": ["-date_end"],
            },
        ),
    ]
