# Generated by Django 6.0.5 on 2026-08-06 06:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_initial"),
        ("base", "0007_alter_iractionsreport_report_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountFullReconcile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conciliación total",
                "verbose_name_plural": "Conciliaciones totales",
                "db_table": "account_full_reconcile",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AccountIncoterms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del Incoterm (Odoo name, requerido, traducible).",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text='Código estándar del Incoterm, ej. "FOB" (Odoo code, requerido).',
                        max_length=3,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Ocultar sin eliminar (Odoo active)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Incoterm",
                "verbose_name_plural": "Incoterms",
                "db_table": "account_incoterms",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="accountmoveline",
            name="matching_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo matching_number: 'P<id>' mientras la conciliación es parcial (id del grupo, asignado por AccountPartialReconcile._update_matching_number); el id de account.full.reconcile como texto cuando es total. Vacío si el apunte no está conciliado.",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="AccountAccountTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la etiqueta (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "applicability",
                    models.CharField(
                        choices=[
                            ("accounts", "Cuentas"),
                            ("taxes", "Impuestos"),
                            ("products", "Productos"),
                        ],
                        default="accounts",
                        help_text="Dónde aplica la etiqueta (Odoo applicability, requerido).",
                        max_length=8,
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=0, help_text="Índice de color en UI (Odoo color)."
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Etiqueta activa; desactivar en vez de borrar (Odoo active).",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="País donde aplica, cuando applicability=taxes (Odoo country_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_tags",
                        to="base.rescountry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Casilla fiscal",
                "verbose_name_plural": "Casillas fiscales",
                "db_table": "account_account_tag",
            },
        ),
        migrations.CreateModel(
            name="AccountBankStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia del estado de cuenta (Odoo name, computado de diario+fecha si no se declara).",
                        max_length=255,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia externa: nombre del archivo importado o de la sincronización en línea (Odoo reference).",
                        max_length=255,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la última línea posteada (Odoo date, computado).",
                        null=True,
                    ),
                ),
                (
                    "first_line_index",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Índice de ordenamiento de la primera línea posteada (Odoo first_line_index, computado — ver simplificación en el docstring del módulo).",
                        max_length=64,
                    ),
                ),
                (
                    "balance_start",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Saldo inicial (Odoo balance_start).",
                        max_digits=16,
                    ),
                ),
                (
                    "balance_end",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Saldo final calculado: balance_start + líneas posteadas (Odoo balance_end, computado).",
                        max_digits=16,
                    ),
                ),
                (
                    "balance_end_real",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Saldo final declarado por el banco (Odoo balance_end_real).",
                        max_digits=16,
                    ),
                ),
                (
                    "is_complete",
                    models.BooleanField(
                        default=False,
                        help_text="balance_end == balance_end_real, con líneas posteadas (Odoo is_complete, computado).",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=True,
                        help_text="balance_start coincide con el balance_end_real del estado anterior del mismo diario (Odoo is_valid, computado).",
                    ),
                ),
                (
                    "problem_description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción del problema si no es completo o válido (Odoo problem_description, computado).",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, related de journal_id.company_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statements",
                        to="base.rescompany",
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda (Odoo currency_id, computado de journal/company).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_statements",
                        to="base.rescurrency",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        help_text="Diario bancario (Odoo journal_id, computado de las líneas).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statements",
                        to="account.accountjournal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado de cuenta bancario",
                "verbose_name_plural": "Estados de cuenta bancarios",
                "db_table": "account_bank_statement",
                "ordering": ["-first_line_index"],
            },
        ),
        migrations.CreateModel(
            name="AccountBankStatementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Orden dentro del estado de cuenta (Odoo sequence).",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número de cuenta bancaria del tercero, previo a su creación como registro (Odoo account_number).",
                        max_length=64,
                    ),
                ),
                (
                    "partner_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre del tercero tal como llega en el formato electrónico importado, cuando no se puede resolver a un partner (Odoo partner_name).",
                        max_length=255,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tipo de transacción, si el formato importado lo declara (Odoo transaction_type).",
                        max_length=64,
                    ),
                ),
                (
                    "payment_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta/descripción de la transacción (Odoo payment_ref).",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto de la transacción, en la moneda del diario (Odoo amount).",
                        max_digits=16,
                    ),
                ),
                (
                    "amount_currency",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Monto expresado en foreign_currency (Odoo amount_currency).",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(
                        default=False,
                        help_text="La línea ya fue conciliada contra sus apuntes (Odoo is_reconciled, computado — aquí bandera explícita que fija el flujo de conciliación).",
                    ),
                ),
                (
                    "foreign_currency",
                    models.ForeignKey(
                        blank=True,
                        help_text="Moneda distinta a la del diario, si la transacción es multi-moneda (Odoo foreign_currency_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_statement_lines_foreign",
                        to="base.rescurrency",
                    ),
                ),
                (
                    "move",
                    models.ForeignKey(
                        help_text="Asiento contable del que esta línea es la extensión bancaria (Odoo move_id, _inherits). journal/company/currency/date/state se delegan a él.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_statement_line",
                        to="account.accountmove",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tercero de la transacción (Odoo partner_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bank_statement_lines",
                        to="base.respartner",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        blank=True,
                        help_text="Estado de cuenta al que pertenece, si ya fue agrupada (Odoo statement_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="line_ids",
                        to="account.accountbankstatement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de estado de cuenta bancario",
                "verbose_name_plural": "Líneas de estado de cuenta bancario",
                "db_table": "account_bank_statement_line",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AccountCashRounding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del perfil de redondeo (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "rounding",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.01"),
                        help_text="Menor moneda circulante distinta de cero (Odoo rounding, ej. 0.05).",
                        max_digits=16,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("biggest_tax", "Modificar monto de impuesto"),
                            ("add_invoice_line", "Agregar línea de redondeo"),
                        ],
                        default="add_invoice_line",
                        help_text="Estrategia de redondeo (Odoo strategy).",
                        max_length=16,
                    ),
                ),
                (
                    "rounding_method",
                    models.CharField(
                        choices=[
                            ("UP", "Arriba"),
                            ("DOWN", "Abajo"),
                            ("HALF-UP", "Más cercano"),
                        ],
                        default="HALF-UP",
                        help_text="Regla de desempate del redondeo (Odoo rounding_method).",
                        max_length=8,
                    ),
                ),
                (
                    "loss_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta para la pérdida por redondeo (Odoo loss_account_id, company_dependent en la referencia).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_rounding_loss_profiles",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "profit_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta para la ganancia por redondeo (Odoo profit_account_id, company_dependent en la referencia).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_rounding_profit_profiles",
                        to="account.accountaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Redondeo de efectivo",
                "verbose_name_plural": "Redondeos de efectivo",
                "db_table": "account_cash_rounding",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AccountFiscalPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10,
                        help_text="Orden de emparejamiento, empresa específica primero (Odoo sequence).",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la posición fiscal (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Posición activa; desactivar en vez de borrar (Odoo active).",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Menciones legales a imprimir en la factura (Odoo note, Html en la referencia).",
                    ),
                ),
                (
                    "auto_apply",
                    models.BooleanField(
                        default=False,
                        help_text="Aplica automáticamente si el criterio VAT/país coincide (Odoo auto_apply).",
                    ),
                ),
                (
                    "vat_required",
                    models.BooleanField(
                        default=False,
                        help_text="Sólo aplica si el tercero tiene VAT (Odoo vat_required).",
                    ),
                ),
                (
                    "zip_from",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rango de código postal, desde (Odoo zip_from).",
                        max_length=24,
                    ),
                ),
                (
                    "zip_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Rango de código postal, hasta (Odoo zip_to).",
                        max_length=24,
                    ),
                ),
                (
                    "foreign_vat",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="RFC/VAT propio en la región mapeada por esta posición (Odoo foreign_vat).",
                        max_length=32,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_positions",
                        to="base.rescompany",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="País de entrega requerido para aplicar (Odoo country_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_positions",
                        to="base.rescountry",
                    ),
                ),
                (
                    "country_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Grupo de países requerido para aplicar (Odoo country_group_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_positions",
                        to="base.rescountrygroup",
                    ),
                ),
                (
                    "state_ids",
                    models.ManyToManyField(
                        blank=True,
                        db_table="account_fiscal_position_state_rel",
                        help_text="Estados federales requeridos para aplicar (Odoo state_ids).",
                        related_name="fiscal_positions",
                        to="base.rescountrystate",
                    ),
                ),
                (
                    "tax_ids",
                    models.ManyToManyField(
                        blank=True,
                        db_table="account_fiscal_position_account_tax_rel",
                        help_text="Impuestos destino aplicables bajo esta posición (Odoo tax_ids).",
                        related_name="fiscal_positions",
                        to="account.accounttax",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posición fiscal",
                "verbose_name_plural": "Posiciones fiscales",
                "db_table": "account_fiscal_position",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="AccountFiscalPositionAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_dest",
                    models.ForeignKey(
                        help_text="Cuenta a usar en su lugar (Odoo account_dest_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_position_mappings_dest",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "account_src",
                    models.ForeignKey(
                        help_text="Cuenta declarada en el producto (Odoo account_src_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_position_mappings_src",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa (Odoo company_id, related=position_id.company_id, store=True).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_position_accounts",
                        to="base.rescompany",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        help_text="Posición fiscal dueña de este mapeo (Odoo position_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_ids",
                        to="account.accountfiscalposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeo de cuenta de posición fiscal",
                "verbose_name_plural": "Mapeos de cuenta de posición fiscal",
                "db_table": "account_fiscal_position_account",
            },
        ),
        migrations.AddField(
            model_name="accountmoveline",
            name="full_reconcile",
            field=models.ForeignKey(
                blank=True,
                help_text="Conciliación total que agrupa este apunte (Odoo full_reconcile_id). Nulo mientras no exista match total.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reconciled_line_ids",
                to="account.accountfullreconcile",
            ),
        ),
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del grupo (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "code_prefix_start",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Prefijo de código, inicio del rango (Odoo code_prefix_start).",
                        max_length=32,
                    ),
                ),
                (
                    "code_prefix_end",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Prefijo de código, fin del rango (Odoo code_prefix_end).",
                        max_length=32,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_groups",
                        to="base.rescompany",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Padre en la jerarquía (Odoo parent_id, readonly en la referencia: lo recalcula _adapt_parent_account_group, no se asigna a mano).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="account.accountgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de cuentas",
                "verbose_name_plural": "Grupos de cuentas",
                "db_table": "account_group",
                "ordering": ["code_prefix_start"],
            },
        ),
        migrations.CreateModel(
            name="AccountJournalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del grupo de diarios (Odoo name, requerido, traducible).",
                        max_length=255,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de presentación (Odoo sequence)."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa que puede seleccionar el grupo en filtros de reportes; sin empresa, disponible para todas (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_groups",
                        to="base.rescompany",
                    ),
                ),
                (
                    "excluded_journals",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Diarios excluidos del grupo (Odoo excluded_journal_ids).",
                        related_name="excluded_from_groups",
                        to="account.accountjournal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de diarios",
                "verbose_name_plural": "Grupos de diarios",
                "db_table": "account_journal_group",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="AccountLockException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Vigente (Odoo active)."
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Motivo de la excepción (Odoo reason).",
                        max_length=255,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fin de vigencia; vacío = indefinida (Odoo end_datetime).",
                        null=True,
                    ),
                ),
                (
                    "lock_date_field",
                    models.CharField(
                        choices=[
                            ("fiscalyear_lock_date", "Candado global"),
                            ("tax_lock_date", "Candado de declaración de impuestos"),
                            ("sale_lock_date", "Candado de ventas"),
                            ("purchase_lock_date", "Candado de compras"),
                        ],
                        help_text="Candado que esta excepción modifica (Odoo lock_date_field, requerido).",
                        max_length=32,
                    ),
                ),
                (
                    "lock_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha a la que se mueve el candado (Odoo lock_date).",
                        null=True,
                    ),
                ),
                (
                    "company_lock_date",
                    models.DateField(
                        blank=True,
                        help_text="Candado original de la empresa al crear la excepción (Odoo company_lock_date, técnico, no editable).",
                        null=True,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock_exceptions",
                        to="base.rescompany",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario beneficiario; vacío = para todos (Odoo user_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lock_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Excepción de candado contable",
                "verbose_name_plural": "Excepciones de candado contable",
                "db_table": "account_lock_exception",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AccountPartialReconcile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Importe siempre positivo emparejado por este partial, en moneda de la empresa (Odoo amount).",
                        max_digits=16,
                    ),
                ),
                (
                    "max_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha máxima entre debit_move_id y credit_move_id (Odoo max_date, computado). Se usa para reportes de antigüedad.",
                        null=True,
                    ),
                ),
                (
                    "credit_move",
                    models.ForeignKey(
                        help_text="Apunte del lado haber (Odoo credit_move_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_credit_ids",
                        to="account.accountmoveline",
                    ),
                ),
                (
                    "debit_move",
                    models.ForeignKey(
                        help_text="Apunte del lado debe (Odoo debit_move_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_debit_ids",
                        to="account.accountmoveline",
                    ),
                ),
                (
                    "full_reconcile",
                    models.ForeignKey(
                        blank=True,
                        help_text="Conciliación total que agrupa este partial, si la hay (Odoo full_reconcile_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partial_reconcile_ids",
                        to="account.accountfullreconcile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conciliación parcial",
                "verbose_name_plural": "Conciliaciones parciales",
                "db_table": "account_partial_reconcile",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AccountReconcileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Regla activa (Odoo active)."
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la regla (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de aplicación (Odoo sequence)."
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("auto_reconcile", "Automática"),
                        ],
                        default="manual",
                        help_text="Aplicación manual o automática al validar el extracto (Odoo trigger, requerido).",
                        max_length=16,
                    ),
                ),
                (
                    "can_be_proposed",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo can_be_proposed (computado, ver compute_can_be_proposed — no automático en save()).",
                    ),
                ),
                (
                    "match_amount",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lower", "Es menor o igual a"),
                            ("greater", "Es mayor o igual a"),
                            ("between", "Está entre"),
                        ],
                        default="",
                        help_text="Condición sobre el monto del extracto (Odoo match_amount).",
                        max_length=8,
                    ),
                ),
                (
                    "match_amount_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Odoo match_amount_min.",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "match_amount_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Odoo match_amount_max.",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "match_label",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("contains", "Contiene"),
                            ("not_contains", "No contiene"),
                            ("match_regex", "Coincide con regex"),
                        ],
                        default="",
                        help_text="Condición sobre la etiqueta del extracto (Odoo match_label).",
                        max_length=16,
                    ),
                ),
                (
                    "match_label_param",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Parámetro de match_label (Odoo match_label_param).",
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconcile_models",
                        to="base.rescompany",
                    ),
                ),
                (
                    "mapped_partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo mapped_partner_id (computado, ver compute_mapped_partner_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match_journal_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Diarios donde aplica la regla (Odoo match_journal_ids).",
                        related_name="reconcile_models",
                        to="account.accountjournal",
                    ),
                ),
                (
                    "match_partner_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restringe la regla a estos contactos (Odoo match_partner_ids).",
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de conciliación",
                "verbose_name_plural": "Reglas de conciliación",
                "db_table": "account_reconcile_model",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountReconcileModelLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10,
                        help_text="Orden dentro de la regla (Odoo sequence).",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta de la línea generada (Odoo label).",
                        max_length=255,
                    ),
                ),
                (
                    "amount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fijo"),
                            ("percentage", "Porcentaje del saldo"),
                            ("percentage_st_line", "Porcentaje del extracto"),
                            ("regex", "Extraído de la etiqueta"),
                        ],
                        default="percentage",
                        help_text="Cómo se calcula el monto de la línea (Odoo amount_type, requerido).",
                        max_length=24,
                    ),
                ),
                (
                    "amount_string",
                    models.CharField(
                        default="100",
                        help_text="Valor crudo del monto: porcentaje, fijo, o regex sobre la etiqueta del extracto (Odoo amount_string, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        default=0.0,
                        help_text="amount_string parseado a float (Odoo amount, computado en save() — Odoo lo declara compute+store).",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta destino de la línea generada (Odoo account_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconcile_model_lines",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo company_id (related=model_id.company_id, store=True — columna sincronizada en save(), ver divergencia #5).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconcile_model_lines",
                        to="base.rescompany",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="Regla a la que pertenece (Odoo model_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_ids",
                        to="account.accountreconcilemodel",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contacto de la línea generada (Odoo partner_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de regla de conciliación",
                "verbose_name_plural": "Líneas de regla de conciliación",
                "db_table": "account_reconcile_model_line",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountTaxGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del grupo (Odoo name, requerido).",
                        max_length=255,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de presentación (Odoo sequence)."
                    ),
                ),
                (
                    "preceding_subtotal",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta del subtotal previo al grupo (Odoo preceding_subtotal).",
                        max_length=255,
                    ),
                ),
                (
                    "pos_receipt_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Etiqueta en el ticket de punto de venta (Odoo pos_receipt_label).",
                        max_length=255,
                    ),
                ),
                (
                    "advance_tax_payment_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta de anticipos considerada en el cierre (Odoo advance_tax_payment_account_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax_groups_advance",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        help_text="Empresa (Odoo company_id, requerido).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_groups",
                        to="base.rescompany",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="País de aplicación (Odoo country_id, compute desde la empresa; aquí resuelto en save(), ver _compute_country()).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax_groups",
                        to="base.rescountry",
                    ),
                ),
                (
                    "tax_payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta de contrapartida del asiento de cierre cuando el saldo favorece a la autoridad fiscal (Odoo tax_payable_account_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax_groups_payable",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "tax_receivable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta de contrapartida del asiento de cierre cuando el saldo favorece a la empresa (Odoo tax_receivable_account_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax_groups_receivable",
                        to="account.accountaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grupo de impuestos",
                "verbose_name_plural": "Grupos de impuestos",
                "db_table": "account_tax_group",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="AccountTaxRepartitionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor_percent",
                    models.FloatField(
                        default=100,
                        help_text="Porcentaje del factor aplicado a los apuntes generados (Odoo factor_percent).",
                    ),
                ),
                (
                    "factor",
                    models.FloatField(
                        default=1.0,
                        help_text="Factor en fracción (Odoo factor, compute=_compute_factor; resuelto en save()).",
                    ),
                ),
                (
                    "repartition_type",
                    models.CharField(
                        choices=[("base", "Base"), ("tax", "Del impuesto")],
                        default="tax",
                        help_text="Base sobre la que se aplica el factor (Odoo repartition_type, requerido).",
                        max_length=8,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("invoice", "Factura"), ("refund", "Nota de crédito")],
                        help_text="Factura o nota de crédito (Odoo document_type, requerido).",
                        max_length=8,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Orden de presentación/emparejamiento (Odoo sequence). Para que las notas de crédito casen bien con la factura, el orden debe coincidir entre document_type=invoice y document_type=refund.",
                    ),
                ),
                (
                    "use_in_tax_closing",
                    models.BooleanField(
                        default=False,
                        help_text="Entra en el asiento de cierre de IVA (Odoo use_in_tax_closing, compute; resuelto en save()).",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cuenta donde se postea el monto de impuesto (Odoo account_id). Vacía cuando repartition_type=base, igual que el _onchange de la referencia.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tax_repartition_lines",
                        to="account.accountaccount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa (Odoo company_id, related=tax_id.company_id, store=True).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_repartition_lines",
                        to="base.rescompany",
                    ),
                ),
                (
                    "tag_ids",
                    models.ManyToManyField(
                        blank=True,
                        db_table="account_tax_repartition_line_tag_rel",
                        help_text="Casillas fiscales asociadas (Odoo tag_ids, domain applicability=taxes).",
                        related_name="tax_repartition_lines",
                        to="account.accountaccounttag",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        help_text="Impuesto al que pertenece esta línea (Odoo tax_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repartition_lines",
                        to="account.accounttax",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de reparto de impuesto",
                "verbose_name_plural": "Líneas de reparto de impuesto",
                "db_table": "account_tax_repartition_line",
                "ordering": ["document_type", "repartition_type", "sequence", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="accountaccounttag",
            constraint=models.UniqueConstraint(
                fields=("name", "applicability", "country"),
                name="unique_account_tag_name_applicability_country",
            ),
        ),
        migrations.AddIndex(
            model_name="accountbankstatement",
            index=models.Index(
                fields=["journal", "date", "-id"], name="acc_bank_stmt_journal_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accountbankstatementline",
            index=models.Index(
                fields=["statement", "sequence"], name="acc_bank_stmt_line_seq_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="accountfiscalpositionaccount",
            constraint=models.UniqueConstraint(
                fields=("position", "account_src", "account_dest"),
                name="unique_fiscal_position_account_src_dest",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountjournalgroup",
            constraint=models.UniqueConstraint(
                fields=("company", "name"), name="unique_journal_group_name_company"
            ),
        ),
        migrations.AddIndex(
            model_name="accountlockexception",
            index=models.Index(
                condition=models.Q(("active", True)),
                fields=["company", "user", "end_datetime"],
                name="account_lock_exc_active_idx",
            ),
        ),
    ]
