# Generated by Django 6.0.5 on 2026-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_sequence_prefix_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttax",
            options={
                "ordering": ["sequence", "id"],
                "verbose_name": "Impuesto",
                "verbose_name_plural": "Impuestos",
            },
        ),
        migrations.AddField(
            model_name="accounttax",
            name="children",
            field=models.ManyToManyField(
                blank=True,
                db_table="account_tax_filiation_rel",
                help_text="Sub-impuestos cuando amount_type=group (Odoo children_tax_ids). symmetrical=False: la relación es dirigida, padre → hijos.",
                related_name="parent_taxes",
                to="account.accounttax",
            ),
        ),
        migrations.AddField(
            model_name="accounttax",
            name="include_base_amount",
            field=models.BooleanField(
                default=False,
                help_text="Afecta la base de los impuestos posteriores (Odoo include_base_amount).",
            ),
        ),
        migrations.AddField(
            model_name="accounttax",
            name="is_base_affected",
            field=models.BooleanField(
                default=True,
                help_text="Su base puede ser afectada por impuestos anteriores (Odoo is_base_affected).",
            ),
        ),
        migrations.AddField(
            model_name="accounttax",
            name="sequence",
            field=models.IntegerField(
                db_index=True,
                default=1,
                help_text="Orden de aplicación de los impuestos de una línea (Odoo sequence). NO es decorativo: el motor evalúa por este orden y de él dependen los lotes.",
            ),
        ),
        migrations.AlterField(
            model_name="accounttax",
            name="price_include",
            field=models.BooleanField(
                default=False,
                help_text="Precio con impuesto incluido (Odoo price_include). En la referencia es un compute sobre price_include_override + company_price_include; aquí es el booleano directo.",
            ),
        ),
    ]
