# Generated by Django 6.0.5 on 2026-08-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0009_sequence_mixin_wiring"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttax",
            name="tax_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo al que pertenece el impuesto (Odoo tax_group_id); agrupa los subtotales del documento.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="taxes",
                to="account.accounttaxgroup",
            ),
        ),
    ]
