# Generated by Django 6.0.5 on 2026-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0012_seed_account_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountaccount",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="account_account_account_tag",
                help_text="Etiquetas de reporte de la cuenta (Odoo tag_ids). Una cuenta sin etiqueta propia hereda las de la cuenta de código inmediatamente anterior.",
                related_name="accounts",
                to="account.accountaccounttag",
            ),
        ),
    ]
