# Generated by Django 6.0.5 on 2026-08-06 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0013_account_tags_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTaxAlternative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dest_tax",
                    models.ForeignKey(
                        help_text='Impuesto de reemplazo — "this Replacement tax" en la referencia (Odoo dest_tax_id).',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="account.accounttax",
                    ),
                ),
                (
                    "src_tax",
                    models.ForeignKey(
                        help_text="Impuesto doméstico a reemplazar (Odoo src_tax_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="account.accounttax",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativa de impuesto",
                "verbose_name_plural": "Alternativas de impuesto",
                "db_table": "account_tax_alternatives",
            },
        ),
        migrations.AddField(
            model_name="accounttax",
            name="original_tax_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text='Impuestos que ESTE reemplaza al aplicar cualquiera de las posiciones fiscales estipuladas (Odoo original_tax_ids, string "Replaces"). Es la mitad de escritura del mecanismo de sustitución: sin ella, AccountFiscalPosition._compute_tax_map devuelve siempre {} (H-API-322).',
                related_name="+",
                through="account.AccountTaxAlternative",
                through_fields=("dest_tax", "src_tax"),
                to="account.accounttax",
                verbose_name="Reemplaza a",
            ),
        ),
        migrations.AddField(
            model_name="accounttax",
            name="replacing_tax_ids",
            field=models.ManyToManyField(
                editable=False,
                help_text='Reverso de original_tax_ids: impuestos que reemplazan a ESTE (Odoo replacing_tax_ids, string "Replaced by", readonly=True en la referencia — de ahí editable=False).',
                related_name="+",
                through="account.AccountTaxAlternative",
                through_fields=("src_tax", "dest_tax"),
                to="account.accounttax",
                verbose_name="Reemplazado por",
            ),
        ),
        migrations.AddConstraint(
            model_name="accounttaxalternative",
            constraint=models.UniqueConstraint(
                fields=("src_tax", "dest_tax"), name="unique_account_tax_alternative"
            ),
        ),
    ]
