# Generated by Django 6.0.5 on 2026-08-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0017_accountmoveline_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmove",
            name="payment_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_paid", "Sin pagar"),
                    ("in_payment", "En proceso de pago"),
                    ("paid", "Pagada"),
                    ("partial", "Parcialmente pagada"),
                    ("reversed", "Revertida"),
                    ("blocked", "Bloqueada"),
                    ("invoicing_legacy", "Facturación heredada"),
                ],
                default="not_paid",
                help_text="Estado de pago (Odoo payment_state). Se recalcula con compute_payment_state() al registrar o revertir una conciliación — no se deriva automáticamente en save().",
                max_length=17,
            ),
        ),
    ]
