# Generated by Django 6.0.5 on 2026-08-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_payment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountjournal',
            name='entries_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='has_entries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='has_posted_entries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='has_sequence_holes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='has_statement_lines',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='has_unhashed_entries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='json_activity_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='kanban_dashboard',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accountjournal',
            name='kanban_dashboard_graph',
            field=models.TextField(blank=True, default=''),
        ),
    ]
