# Generated by Django 6.0.5 on 2026-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0020_accountjournal_is_peppol_journal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountmove",
            name="posted_before",
            field=models.BooleanField(
                default=False,
                help_text="Verdadero desde la primera vez que el asiento se publica, y ya no vuelve a False (Odoo posted_before, account_move.py:321). Es lo que distingue un borrador que nunca existió contablemente de uno que sí — la guarda del rastro de auditoría restringido sólo protege el segundo. El copy=False de la fuente no tiene análogo: este ORM no tiene copia de registro (mismo desenlace que sale_timesheet/sale_order_line.py).",
            ),
        ),
    ]
