# Generated by Django 6.0.5 on 2026-08-29 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0022_accountmove_commercial_partner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountmove",
            name="commercial_partner",
            field=models.ForeignKey(
                blank=True,
                db_column="commercial_partner_id",
                help_text='Odoo commercial_partner_id ("Commercial Entity", account_move.py:430). La entidad que factura de verdad cuando el contacto es una direccion de una matriz. La calcula compute_commercial_partner().',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commercial_moves",
                to="base.respartner",
                verbose_name="Entidad comercial",
            ),
        ),
        migrations.RenameField(
            model_name="accountmove",
            old_name="commercial_partner",
            new_name="commercial_partner_id",
        ),
        migrations.AlterField(
            model_name="accountmove",
            name="fiscal_position",
            field=models.ForeignKey(
                blank=True,
                db_column="fiscal_position_id",
                help_text='Odoo fiscal_position_id ("Fiscal Position", account_move.py:456). Adapta impuestos y cuentas para un cliente o pedido concreto; su valor por omision viene del cliente.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="moves",
                to="account.accountfiscalposition",
                verbose_name="Posicion fiscal",
            ),
        ),
        migrations.RenameField(
            model_name="accountmove",
            old_name="fiscal_position",
            new_name="fiscal_position_id",
        ),
        migrations.AlterField(
            model_name="accountmove",
            name="invoice_user",
            field=models.ForeignKey(
                blank=True,
                db_column="invoice_user_id",
                help_text='Odoo invoice_user_id ("Salesperson", account_move.py:678). El tracking=True de la fuente no aplica: este asiento no es un hilo de mail.thread en este arbol.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoiced_moves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendedor",
            ),
        ),
        migrations.RenameField(
            model_name="accountmove",
            old_name="invoice_user",
            new_name="invoice_user_id",
        ),
        migrations.AlterField(
            model_name="accountmoveline",
            name="company_currency",
            field=models.ForeignKey(
                blank=True,
                db_column="company_currency_id",
                help_text='Odoo company_currency_id ("Company Currency", account_move_line.py:59). Related a move_id.company_currency_id, materializado en save().',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="move_lines_as_company_currency",
                to="base.rescurrency",
                verbose_name="Moneda de la empresa",
            ),
        ),
        migrations.RenameField(
            model_name="accountmoveline",
            old_name="company_currency",
            new_name="company_currency_id",
        ),
        migrations.AlterField(
            model_name="accountmoveline",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_column="company_id",
                help_text="Odoo company_id (account_move_line.py:55). Related a move_id.company_id, materializado en save().",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="move_lines",
                to="base.rescompany",
                verbose_name="Empresa",
            ),
        ),
        migrations.RenameField(
            model_name="accountmoveline",
            old_name="company",
            new_name="company_id",
        ),
        migrations.AlterField(
            model_name="accountmoveline",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                db_column="journal_id",
                help_text="Odoo journal_id (account_move_line.py:42). La fuente lo declara related a move_id.journal_id con store=True; aqui es columna propia que save() copia del asiento, que es como este arbol materializa un related almacenado.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lines",
                to="account.accountjournal",
                verbose_name="Diario",
            ),
        ),
        migrations.RenameField(
            model_name="accountmoveline",
            old_name="journal",
            new_name="journal_id",
        ),
        migrations.AlterField(
            model_name="accountmoveline",
            name="partner",
            field=models.ForeignKey(
                blank=True,
                db_column="partner_id",
                help_text='Odoo partner_id ("Partner", account_move_line.py:152). Apunta a res.partner igual que la fuente. El asiento padre apunta al modelo de usuario -- ese desnivel es la tarea #142, y este campo ya nace del lado correcto.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="move_lines",
                to="base.respartner",
                verbose_name="Contacto",
            ),
        ),
        migrations.RenameField(
            model_name="accountmoveline",
            old_name="partner",
            new_name="partner_id",
        ),
        migrations.AlterField(
            model_name="accountmoveline",
            name="product",
            field=models.ForeignKey(
                blank=True,
                db_column="product_id",
                help_text='Odoo product_id ("Product", account_move_line.py:363).',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="move_lines",
                to="product.productproduct",
                verbose_name="Producto",
            ),
        ),
        migrations.RenameField(
            model_name="accountmoveline",
            old_name="product",
            new_name="product_id",
        ),
        migrations.AlterField(
            model_name="accountmoveline",
            name="product_uom",
            field=models.ForeignKey(
                blank=True,
                db_column="product_uom_id",
                help_text='Odoo product_uom_id ("Unit", account_move_line.py:372). La calcula compute_product_uom_id(), que save() invoca. El domain= de la fuente no tiene analogo declarativo en Django y se acota al elegir candidatos.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="move_lines",
                to="uom.uom",
                verbose_name="Unidad",
            ),
        ),
        migrations.RenameField(
            model_name="accountmoveline",
            old_name="product_uom",
            new_name="product_uom_id",
        ),
        migrations.AddField(
            model_name="accountmove",
            name="direction_sign",
            field=models.IntegerField(
                default=1,
                help_text="Odoo direction_sign (account_move.py:541). Multiplicador segun el tipo de documento, para convertir un precio en un saldo. La calcula compute_direction_sign(), que save() invoca.",
                verbose_name="Signo de direccion",
            ),
        ),
    ]
