# Generated by Django 6.0.5 on 2026-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0024_analytic_distribution_on_move_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountaccount",
            name="internal_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equity", "Capital"),
                    ("asset", "Activo"),
                    ("liability", "Pasivo"),
                    ("income", "Ingreso"),
                    ("expense", "Gasto"),
                    ("off", "Fuera de balance"),
                ],
                default="",
                editable=False,
                help_text="Grupo interno derivado de account_type (Odoo internal_group).",
                max_length=16,
            ),
        ),
    ]
