# Generated by Django 6.0.5 on 2026-09-03 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0025_alter_accountaccount_internal_group"),
        ("base", "0082_respartner_commercial_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjournal",
            name="bank_account_id",
            field=models.ForeignKey(
                blank=True,
                db_column="bank_account_id",
                help_text="Cuenta bancaria del diario (Odoo bank_account_id).",
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="journals",
                to="base.respartnerbank",
                verbose_name="Bank Account",
            ),
        ),
        migrations.AddField(
            model_name="accountjournal",
            name="bank_statements_source",
            field=models.CharField(
                choices=[("undefined", "Undefined Yet")],
                default="undefined",
                help_text="Como se registran los extractos bancarios (Odoo bank_statements_source).",
                max_length=32,
                verbose_name="Bank Feeds",
            ),
        ),
        migrations.CreateModel(
            name="AccountFinancialYearOp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        help_text="Empresa cuyo ejercicio se abre (Odoo company_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_year_ops",
                        to="base.rescompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apertura de ejercicio fiscal",
                "verbose_name_plural": "Aperturas de ejercicio fiscal",
                "db_table": "account_financial_year_op",
            },
        ),
        migrations.CreateModel(
            name="AccountSetupBankManualConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "new_journal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre del diario ligado a esta cuenta (Odoo new_journal_name).",
                        max_length=128,
                    ),
                ),
                ("num_journals_without_account_bank", models.IntegerField(default=0)),
                ("num_journals_without_account_credit", models.IntegerField(default=0)),
                (
                    "company_id",
                    models.ForeignKey(
                        db_column="company_id",
                        help_text="Empresa (Odoo company_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_setup_wizards",
                        to="base.rescompany",
                    ),
                ),
                (
                    "linked_journal_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="linked_journal_id",
                        help_text="Diario ligado (Odoo linked_journal_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="setup_wizards",
                        to="account.accountjournal",
                        verbose_name="Journal",
                    ),
                ),
                (
                    "res_partner_bank_id",
                    models.ForeignKey(
                        db_column="res_partner_bank_id",
                        help_text="Cuenta bancaria delegada (Odoo res_partner_bank_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_wizards",
                        to="base.respartnerbank",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alta manual de cuenta bancaria",
                "verbose_name_plural": "Altas manuales de cuenta bancaria",
                "db_table": "account_setup_bank_manual_config",
            },
        ),
    ]
