# Generated by Django 6.0.5 on 2026-08-02 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_grids",
                    models.BooleanField(
                        default=True,
                        help_text="Imprimir la grilla de variantes (Odoo report_grids).",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        help_text="Orden de venta (Odoo sale.order).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matrix",
                        to="sale.saleorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matriz de orden de venta",
                "verbose_name_plural": "Matrices de órdenes de venta",
                "db_table": "sale_order_matrix",
            },
        ),
    ]
