"""Las dos tablas del asistente de activación de módulos.

**Por qué hay un ``RunPython`` antes de los dos ``CreateModel``.** Las dos
tablas aparecieron en bases compartidas de la sesión SIN su fila en
``django_migrations`` —medido: ``to_regclass('base_module_install_request')``
devolvía la tabla y ``select name from django_migrations where
app='base_install_request'`` devolvía **cero filas**—, así que el
``CreateModel`` abortaba con ``relation … already exists`` y dejaba fuera de
servicio a todo pytest que compartiera esa base.

Una tabla presente sin registro sólo puede venir de una corrida interrumpida:
nadie más la declara. Y las dos son de ``TransientModel``, cuyo contenido es
desechable por definición (``src/orm/models_transient.py``: un transitorio se
recolecta por vacuum). Por eso el paso previo **suelta** lo que hubiera en vez
de saltarse el DDL: saltárselo dejaría en pie un esquema viejo —la primera
versión de este puerto nombraba las columnas ``module_id_id`` y ``user_id_id``,
antes de la forma C de ADR-029— y el fallo reaparecería en el primer ``SELECT``.

El paso no crea nada: crear sigue siendo trabajo de los dos ``CreateModel``, y
dejárselo a ellos mantiene el estado de migraciones exacto sin tener que
resolver el modelo histórico — que en una migración ``initial`` todavía no
existe en ``from_state`` (medido: ``LookupError: No installed app with label
'base_install_request'`` al intentarlo).
"""
# Generated by Django 6.0.5 on 2026-09-02 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


#: Las dos tablas que esta migración materializa.
TABLAS = ('base_module_install_request', 'base_module_install_review')


def soltar_tablas_huerfanas(apps, schema_editor):
    """Suelta lo que quede de una corrida interrumpida, antes del ``CreateModel``."""
    for tabla in TABLAS:
        schema_editor.execute(
            'DROP TABLE IF EXISTS %s CASCADE' % schema_editor.quote_name(tabla))


def sin_efecto(apps, schema_editor):
    """Marcha atrás del paso de arriba: los ``CreateModel`` ya sueltan la tabla."""



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0080_alter_iractionsserver_usage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(soltar_tablas_huerfanas, sin_efecto),
        migrations.CreateModel(
            name="BaseModuleInstallRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, default="", verbose_name="Body"),
                ),
                (
                    "module_id",
                    models.ForeignKey(
                        db_column="module_id",
                        help_text="Módulo cuya activación se solicita (Odoo module_id).",
                        limit_choices_to={"state": "uninstalled"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="install_requests",
                        to="base.irmodule",
                        verbose_name="Module",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="user_id",
                        help_text="Quien solicita (Odoo user_id, default self.env.user).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_install_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de activación de módulo",
                "verbose_name_plural": "Solicitudes de activación de módulo",
                "db_table": "base_module_install_request",
            },
        ),
        migrations.CreateModel(
            name="BaseModuleInstallReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_id",
                    models.ForeignKey(
                        db_column="module_id",
                        help_text="Módulo bajo revisión (Odoo module_id).",
                        limit_choices_to={"state": "uninstalled"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="install_reviews",
                        to="base.irmodule",
                        verbose_name="Module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revisión de activación de módulo",
                "verbose_name_plural": "Revisiones de activación de módulo",
                "db_table": "base_module_install_review",
            },
        ),
    ]
