# Generated by Django 6.0.5 on 2026-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0002_menuitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="audience",
            field=models.CharField(
                choices=[("admin", "Panel admin"), ("account", "Cuenta del comprador")],
                db_index=True,
                default="admin",
                help_text="'admin' = panel; 'account' = menú de cuenta del comprador.",
                max_length=10,
                verbose_name="Audiencia",
            ),
        ),
    ]
