# Generated by Django 6.0.5 on 2026-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authz", "0005_reauthsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="depends",
            field=models.ManyToManyField(
                blank=True,
                related_name="dependents",
                to="authz.module",
                verbose_name="Depende de",
            ),
        ),
    ]
