# Generated by Django 6.0.5 on 2026-08-19 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0010_hremployee_friday_location_hremployee_hourly_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrEmployeeLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(blank=True, null=True, verbose_name="Fecha")),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Odoo employee_id (required, ondelete=cascade; su default de usuario ambiente no se porta — divergencia 2).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homeworking_exceptions",
                        to="hr.hremployee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "work_location",
                    models.ForeignKey(
                        help_text="Sede de la excepción (Odoo work_location_id, required). PROTECT: el borrado de una sede pasa por _unlink_except_used_by_employee, que limpia estas filas antes (ver hr_work_location.py de este addon).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="homeworking_exceptions",
                        to="hr.hrworklocation",
                        verbose_name="Ubicación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación de empleado",
                "verbose_name_plural": "Ubicaciones de empleado",
                "db_table": "hr_employee_location",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date"),
                        name="_uniq_exceptional_per_day",
                        violation_error_message="Only one default work location and one exceptional work location per day per employee.",
                    )
                ],
            },
        ),
    ]
