# Generated by Django 6.0.5 on 2026-07-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Slug estable de la empresa; llave del alias company_<code>_db.",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        help_text="Nombre físico de la base MariaDB (p. ej. company_1_db).",
                        max_length=63,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Activa"),
                            ("suspended", "Suspendida"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="trial",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Registro de base por empresa (L0)",
                "verbose_name_plural": "Registro de bases por empresa (L0)",
                "db_table": "orm_company_database",
                "ordering": ["code"],
            },
        ),
    ]
