# Generated by Django 6.0.5 on 2026-08-02 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la etapa (Odoo project.task.type.name).",
                        max_length=100,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10,
                        help_text="Orden kanban; menor primero (Odoo sequence).",
                    ),
                ),
                (
                    "fold",
                    models.BooleanField(
                        default=False, help_text="Plegada en el kanban (Odoo fold)."
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=0, help_text="Índice de color (Odoo color)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Etapa de tarea de proyecto",
                "verbose_name_plural": "Etapas de tarea de proyecto",
                "db_table": "project_task_type",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del proyecto (Odoo project.project.name).",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción (Odoo description).",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Proyecto activo (Odoo active)."
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=10, help_text="Orden de presentación (Odoo sequence)."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Compañía (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="company.company",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente (Odoo partner_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "db_table": "project_project",
                "ordering": ["sequence", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Título de la tarea (Odoo project.task.name).",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción (Odoo description).",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("0", "Normal"), ("1", "Alta")],
                        default="0",
                        help_text="Prioridad (Odoo priority).",
                        max_length=1,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Tarea activa (Odoo active)."
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(default=10, help_text="Orden (Odoo sequence)."),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("in_progress", "En progreso"),
                            ("done", "Terminada"),
                            ("cancel", "Cancelada"),
                        ],
                        default="in_progress",
                        help_text="Estado (Odoo state).",
                        max_length=16,
                    ),
                ),
                (
                    "date_deadline",
                    models.DateField(
                        blank=True,
                        help_text="Fecha límite (Odoo date_deadline).",
                        null=True,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Responsable (Odoo user_ids).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Proyecto (Odoo project_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project.project",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Etapa (Odoo stage_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="project.projecttasktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea de proyecto",
                "verbose_name_plural": "Tareas de proyecto",
                "db_table": "project_task",
                "ordering": ["project", "sequence", "id"],
            },
        ),
    ]
