# Generated by Django 6.0.5 on 2026-07-31 00:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarrierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.CharField(max_length=64, verbose_name="Transportista"),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe"
                    ),
                ),
                (
                    "free_shipping_subsidy",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Subsidio envio gratis",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("payable", "Por pagar"),
                            ("paid", "Pagado"),
                            ("disputed", "En disputa"),
                        ],
                        default="payable",
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de pago"
                    ),
                ),
            ],
            options={
                "verbose_name": "Flete por pagar",
                "verbose_name_plural": "Fletes por pagar",
                "db_table": "finance_carrier_invoice",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CashClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(verbose_name="Fecha de negocio")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("balanced", "Cuadrado"),
                            ("sealed", "Sellado"),
                            ("reopened", "Reabierto"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo inicial",
                    ),
                ),
                (
                    "counted_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo contado (arqueo)",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo final",
                    ),
                ),
                (
                    "discrepancy",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="contado - esperado; distinto de 0 = corte con diferencia (Alt A).",
                        max_digits=12,
                        verbose_name="Diferencia",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Justificacion de la diferencia al aprobar (Alt A).",
                        verbose_name="Nota del aprobador",
                    ),
                ),
                (
                    "reopen_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Motivo de reapertura"
                    ),
                ),
                (
                    "sealed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sellado en"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_closes_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_closes_prepared",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Preparado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte de caja",
                "verbose_name_plural": "Cortes de caja",
                "db_table": "finance_cash_close",
                "ordering": ["-business_date"],
            },
        ),
        migrations.CreateModel(
            name="CashConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Codigo unico e inmutable del concepto (p. ej. FREIGHT_OUT).",
                        max_length=64,
                        unique=True,
                        verbose_name="Codigo",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Ingreso"), ("expense", "Egreso")],
                        help_text="income (ingreso) o expense (egreso); inmutable tras crear.",
                        max_length=8,
                        verbose_name="Clase",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cuenta contable asociada (opcional).",
                        max_length=32,
                        verbose_name="Cuenta contable",
                    ),
                ),
                (
                    "editable",
                    models.BooleanField(
                        default=True,
                        help_text="Un concepto de sistema (False) no admite cambios.",
                        verbose_name="Editable",
                    ),
                ),
                (
                    "leaf",
                    models.BooleanField(
                        default=True,
                        help_text="True si es el ultimo nivel (clasifica movimientos).",
                        verbose_name="Hoja",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance.cashconcept",
                        verbose_name="Concepto padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto de caja",
                "verbose_name_plural": "Conceptos de caja",
                "db_table": "finance_cash_concept",
                "ordering": ["kind", "code"],
            },
        ),
        migrations.CreateModel(
            name="CashFlowProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Nombre del escenario",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("optimistic", "Optimista"),
                            ("pessimistic", "Pesimista"),
                        ],
                        default="base",
                        max_length=12,
                        verbose_name="Escenario",
                    ),
                ),
                (
                    "horizon",
                    models.PositiveIntegerField(
                        verbose_name="Horizonte (nº de sub-periodos)"
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[("week", "Semana"), ("month", "Mes")],
                        default="week",
                        max_length=8,
                        verbose_name="Granularidad",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Caja inicial",
                    ),
                ),
                (
                    "assumptions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="income_per_period / expense_per_period / min_balance.",
                        verbose_name="Supuestos",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_flow_projections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyeccion de flujo de caja",
                "verbose_name_plural": "Proyecciones de flujo de caja",
                "db_table": "finance_cash_flow_projection",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GatewaySettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("adapter", models.CharField(max_length=32, verbose_name="Adaptador")),
                (
                    "gateway_ref",
                    models.CharField(
                        max_length=128,
                        unique=True,
                        verbose_name="Referencia del gateway",
                    ),
                ),
                (
                    "gross",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Bruto"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Comision"
                    ),
                ),
                (
                    "net",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Neto"
                    ),
                ),
                (
                    "settled_at",
                    models.DateTimeField(verbose_name="Fecha de liberacion"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("imported", "Importada"),
                            ("validated", "Validada"),
                            ("reconciled", "Conciliada"),
                        ],
                        default="imported",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements",
                        to="payment.payment",
                        verbose_name="Pago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Liquidacion del gateway",
                "verbose_name_plural": "Liquidaciones del gateway",
                "db_table": "finance_gateway_settlement",
                "ordering": ["-settled_at"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Ingreso"), ("expense", "Egreso")],
                        max_length=8,
                        verbose_name="Clase",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(verbose_name="Fecha del movimiento"),
                ),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="finance.cashconcept",
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="finance.gatewaysettlement",
                        verbose_name="Liquidacion origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de caja",
                "verbose_name_plural": "Movimientos de caja",
                "db_table": "finance_cash_movement",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="GatewaySettlementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("matched", "Cuadrada"),
                            ("discrepant", "Discrepante"),
                            ("duplicate", "Duplicada"),
                        ],
                        default="matched",
                        max_length=12,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Importe"
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.gatewaysettlement",
                        verbose_name="Liquidacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linea de liquidacion",
                "verbose_name_plural": "Lineas de liquidacion",
                "db_table": "finance_gateway_settlement_line",
            },
        ),
        migrations.CreateModel(
            name="PeriodClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fiscal_year",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Ejercicio (ano fiscal)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierto"), ("sealed", "Sellado")],
                        default="open",
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Saldo final del ejercicio anterior (encadenamiento anual).",
                        max_digits=12,
                        verbose_name="Saldo inicial",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Congelado al sellar; None mientras el ejercicio esta open.",
                        max_digits=12,
                        null=True,
                        verbose_name="Saldo final",
                    ),
                ),
                (
                    "opening_balance_stale",
                    models.BooleanField(
                        default=False,
                        help_text="True si el ejercicio anterior se reabrio (POST-03): el saldo heredado queda pendiente de re-cierre.",
                        verbose_name="Saldo inicial invalidado",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Clave del cierre que sello el ejercicio (Alt C, AC-04).",
                        max_length=128,
                        verbose_name="Clave de idempotencia",
                    ),
                ),
                (
                    "sealed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sellado en"
                    ),
                ),
                (
                    "reopened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reabierto en"
                    ),
                ),
                (
                    "reopen_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Motivo de reapertura"
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_closes_reopened",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reabierto por",
                    ),
                ),
                (
                    "sealed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_closes_sealed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sellado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de ejercicio",
                "verbose_name_plural": "Cierres de ejercicio",
                "db_table": "finance_period_close",
                "ordering": ["-fiscal_year"],
            },
        ),
    ]
