# Generated by Django 6.0.5 on 2026-07-16 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CashConcept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Codigo unico e inmutable del concepto (p. ej. FREIGHT_OUT).",
                        max_length=64,
                        unique=True,
                        verbose_name="Codigo",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nombre")),
                (
                    "kind",
                    models.CharField(
                        choices=[("income", "Ingreso"), ("expense", "Egreso")],
                        help_text="income (ingreso) o expense (egreso); inmutable tras crear.",
                        max_length=8,
                        verbose_name="Clase",
                    ),
                ),
                (
                    "account",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cuenta contable asociada (opcional).",
                        max_length=32,
                        verbose_name="Cuenta contable",
                    ),
                ),
                (
                    "editable",
                    models.BooleanField(
                        default=True,
                        help_text="Un concepto de sistema (False) no admite cambios.",
                        verbose_name="Editable",
                    ),
                ),
                (
                    "leaf",
                    models.BooleanField(
                        default=True,
                        help_text="True si es el ultimo nivel (clasifica movimientos).",
                        verbose_name="Hoja",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance.cashconcept",
                        verbose_name="Concepto padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concepto de caja",
                "verbose_name_plural": "Conceptos de caja",
                "db_table": "finance_cash_concept",
                "ordering": ["kind", "code"],
            },
        ),
    ]
