# Generated by Django 6.0.5 on 2026-07-17 06:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_carrierinvoice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(verbose_name="Fecha de negocio")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("balanced", "Cuadrado"),
                            ("sealed", "Sellado"),
                            ("reopened", "Reabierto"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo inicial",
                    ),
                ),
                (
                    "counted_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo contado (arqueo)",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Saldo final",
                    ),
                ),
                (
                    "discrepancy",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="contado - esperado; distinto de 0 = corte con diferencia (Alt A).",
                        max_digits=12,
                        verbose_name="Diferencia",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Justificacion de la diferencia al aprobar (Alt A).",
                        verbose_name="Nota del aprobador",
                    ),
                ),
                (
                    "reopen_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Motivo de reapertura"
                    ),
                ),
                (
                    "sealed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sellado en"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_closes_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_closes_prepared",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Preparado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte de caja",
                "verbose_name_plural": "Cortes de caja",
                "db_table": "finance_cash_close",
                "ordering": ["-business_date"],
            },
        ),
    ]
