# Generated by Django 6.0.5 on 2026-07-17 14:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_cashclose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Nombre del escenario",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("base", "Base"),
                            ("optimistic", "Optimista"),
                            ("pessimistic", "Pesimista"),
                        ],
                        default="base",
                        max_length=12,
                        verbose_name="Escenario",
                    ),
                ),
                (
                    "horizon",
                    models.PositiveIntegerField(
                        verbose_name="Horizonte (nº de sub-periodos)"
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[("week", "Semana"), ("month", "Mes")],
                        default="week",
                        max_length=8,
                        verbose_name="Granularidad",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Caja inicial",
                    ),
                ),
                (
                    "assumptions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="income_per_period / expense_per_period / min_balance.",
                        verbose_name="Supuestos",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_flow_projections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyeccion de flujo de caja",
                "verbose_name_plural": "Proyecciones de flujo de caja",
                "db_table": "finance_cash_flow_projection",
                "ordering": ["-created_at"],
            },
        ),
    ]
