# Generated by Django 6.0.5 on 2026-07-17 14:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_cashflowprojection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fiscal_year",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Ejercicio (ano fiscal)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Abierto"), ("sealed", "Sellado")],
                        default="open",
                        max_length=8,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Saldo final del ejercicio anterior (encadenamiento anual).",
                        max_digits=12,
                        verbose_name="Saldo inicial",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Congelado al sellar; None mientras el ejercicio esta open.",
                        max_digits=12,
                        null=True,
                        verbose_name="Saldo final",
                    ),
                ),
                (
                    "opening_balance_stale",
                    models.BooleanField(
                        default=False,
                        help_text="True si el ejercicio anterior se reabrio (POST-03): el saldo heredado queda pendiente de re-cierre.",
                        verbose_name="Saldo inicial invalidado",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Clave del cierre que sello el ejercicio (Alt C, AC-04).",
                        max_length=128,
                        verbose_name="Clave de idempotencia",
                    ),
                ),
                (
                    "sealed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sellado en"
                    ),
                ),
                (
                    "reopened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Reabierto en"
                    ),
                ),
                (
                    "reopen_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Motivo de reapertura"
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_closes_reopened",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reabierto por",
                    ),
                ),
                (
                    "sealed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="period_closes_sealed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sellado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cierre de ejercicio",
                "verbose_name_plural": "Cierres de ejercicio",
                "db_table": "finance_period_close",
                "ordering": ["-fiscal_year"],
            },
        ),
    ]
