"""Repunta el FK de ``GatewaySettlement.payment`` a ``payment.Payment``.

State-only: la columna y el constraint de BD no cambian (misma tabla
``payments_payment``); solo cambia la referencia de app_label en el estado.
"""
# Generated by Django 6.0.5 on 2026-07-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_periodclose"),
        ("payment", "0001_initial"),
    ]

    state_operations = [
        migrations.AlterField(
            model_name="gatewaysettlement",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settlements",
                to="payment.payment",
                verbose_name="Pago",
            ),
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
            database_operations=[],
        ),
    ]
