# Generated by Django 6.0.5 on 2026-08-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0030_rescompany_account_peppol_contact_email_and_more"),
        ("purchase", "0001_initial"),
        ("purchase_requisition", "__first__"),
        ("stock", "0017_stockpicking_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="dest_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Dirección a la que se envía directamente cuando la operación es dropship (Odoo dest_address_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dropship_purchase_orders",
                to="base.respartner",
                verbose_name="Dirección de destino",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="incoterm_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Lugar al que se refiere el Incoterm de la compra (Odoo incoterm_location).",
                max_length=255,
                verbose_name="Lugar del Incoterm",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="picking_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Determina el tipo de operación de la recepción (Odoo picking_type_id). D-3: opcional aquí, requerido en la referencia.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="stock.stockpickingtype",
                verbose_name="Entregar en",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="purchase_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo que reúne esta orden con sus alternativas (Odoo purchase_group_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_ids",
                to="purchase_requisition.purchaseordergroup",
                verbose_name="Grupo de alternativas",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                help_text="Acuerdo de compra del que nace esta orden (Odoo requisition_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_ids",
                to="purchase_requisition.purchaserequisition",
                verbose_name="Acuerdo",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="location_final",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación final que pidió el abastecimiento; puede ser más profunda que el destino de la recepción (Odoo location_final_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_line_ids",
                to="stock.stocklocation",
                verbose_name="Ubicación del abastecimiento",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="orderpoint",
            field=models.ForeignKey(
                blank=True,
                help_text="Punto de pedido que generó esta línea (Odoo orderpoint_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_line_ids",
                to="stock.stockwarehouseorderpoint",
                verbose_name="Regla de reabastecimiento",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="product_description_variants",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Descripción que el abastecimiento añade a la línea (Odoo product_description_variants).",
                max_length=255,
                verbose_name="Descripción personalizada",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="propagate_cancel",
            field=models.BooleanField(
                default=True,
                help_text="Al cancelar la línea, ¿se cancelan también los movimientos que abastece? (Odoo propagate_cancel).",
                verbose_name="Propagar cancelación",
            ),
        ),
    ]
