# Generated by Django 5.0.1 on 2026-05-20 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("inventory", "0001_initial"),
        ("inventory", "0002_timestampedmodel_inventory"),
        ("inventory", "0003_sync_model_drift"),
    ]

    initial = True

    dependencies = [
        ("catalogue", "0005_productimage_admin_products"),
        ("chartsize", "0001_initial"),
        ("users", "0001_squashed_0007_user_deactivation_event"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_at_alert", models.PositiveIntegerField()),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="catalogue.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_alerts",
                        to="chartsize.productvariant",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "inventory_stock_alert",
                "ordering": ["-created_at"],
                "verbose_name": "Alerta de stock",
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                ("stock_after", models.PositiveIntegerField()),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("SALE", "Venta"),
                            ("CANCELLATION", "Cancelacion"),
                            ("ADJUSTMENT", "Ajuste manual"),
                            ("IMPORT", "Importacion CSV"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=50)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalogue.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="chartsize.productvariant",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "inventory_stock_movement",
                "ordering": ["-created_at"],
                "verbose_name": "Movimiento de stock",
            },
        ),
    ]
