# Generated by Django 5.0.1 on 2026-05-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_squashed_0003_sync_model_drift"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdjustmentMovement",
            fields=[],
            options={
                "verbose_name": "Ajuste manual de stock",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.stockmovement",),
        ),
        migrations.CreateModel(
            name="CancellationMovement",
            fields=[],
            options={
                "verbose_name": "Movimiento de cancelación",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.stockmovement",),
        ),
        migrations.CreateModel(
            name="ImportMovement",
            fields=[],
            options={
                "verbose_name": "Movimiento de importación",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.stockmovement",),
        ),
        migrations.CreateModel(
            name="SaleMovement",
            fields=[],
            options={
                "verbose_name": "Movimiento de venta",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.stockmovement",),
        ),
    ]
