# Generated by Django 5.0.1 on 2026-05-23 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_stockmovement_stock_before_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="inventory/imports/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("RUNNING", "En proceso"),
                            ("DONE", "Completado"),
                            ("FAILED", "Fallido"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("imported_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import job",
                "db_table": "inventory_import_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="AdjustmentMovement",
        ),
        migrations.DeleteModel(
            name="CancellationMovement",
        ),
        migrations.DeleteModel(
            name="ImportMovement",
        ),
        migrations.DeleteModel(
            name="SaleMovement",
        ),
    ]
