# Generated by Django 5.0.1 on 2026-06-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_migrate_adjustment_reason_to_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("SALE", "Venta"),
                    ("CANCELLATION", "Cancelacion"),
                    ("ADJUSTMENT", "Ajuste manual"),
                    ("IMPORT", "Importacion CSV"),
                    ("RESTOCK", "Entrada de stock"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
