# Generated by Django 6.0.5 on 2026-07-18 18:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0003_product_weight_kg"),
    ]

    operations = [
        migrations.CreateModel(
            name="MrpBom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia de la BoM (Odoo mrp.bom.code).",
                        max_length=64,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="BoM activa (Odoo active)."
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("normal", "Fabricar este producto"),
                            ("phantom", "Kit"),
                        ],
                        default="normal",
                        help_text="Tipo de BoM: normal|phantom/kit (Odoo mrp.bom.type).",
                        max_length=16,
                    ),
                ),
                (
                    "product_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Cantidad producida por la BoM (Odoo product_qty).",
                        max_digits=12,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(default=0, help_text="Orden (Odoo sequence)."),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto fabricado (Odoo product_id/product_tmpl_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boms",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de materiales",
                "verbose_name_plural": "Listas de materiales",
                "db_table": "mrp_bom",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="MrpBomLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Cantidad del componente (Odoo product_qty).",
                        max_digits=12,
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(default=1, help_text="Orden (Odoo sequence)."),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        help_text="BoM contenedora (Odoo bom_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_line_ids",
                        to="mrp.mrpbom",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Componente (Odoo mrp.bom.line.product_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de BoM",
                "verbose_name_plural": "Líneas de BoM",
                "db_table": "mrp_bom_line",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="MrpProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia (Odoo mrp.production.name).",
                        max_length=32,
                    ),
                ),
                (
                    "product_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Cantidad a producir (Odoo product_qty).",
                        max_digits=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("confirmed", "Confirmada"),
                            ("progress", "En progreso"),
                            ("done", "Terminada"),
                            ("cancel", "Cancelada"),
                        ],
                        default="draft",
                        help_text="Estado (Odoo mrp.production.state).",
                        max_length=16,
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        blank=True,
                        help_text="BoM aplicada (Odoo bom_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productions",
                        to="mrp.mrpbom",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto a fabricar (Odoo product_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productions",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de fabricación",
                "verbose_name_plural": "Órdenes de fabricación",
                "db_table": "mrp_production",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
