# Generated by Django 6.0.5 on 2026-07-18 18:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0001_initial"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MrpWorkcenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre (Odoo mrp.workcenter.name).", max_length=100
                    ),
                ),
                (
                    "costs_hour",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Costo por hora (Odoo costs_hour).",
                        max_digits=12,
                    ),
                ),
                (
                    "time_efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        help_text="Eficiencia de tiempo % (Odoo time_efficiency).",
                        max_digits=6,
                    ),
                ),
                (
                    "capacity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Capacidad por defecto (Odoo default_capacity).",
                        max_digits=8,
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de trabajo",
                "verbose_name_plural": "Centros de trabajo",
                "db_table": "mrp_workcenter",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MrpProductionMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("raw", "Materia prima (Odoo move_raw_ids)"),
                            ("finished", "Producto terminado (Odoo move_finished_ids)"),
                        ],
                        help_text="raw = move_raw_ids; finished = move_finished_ids.",
                        max_length=16,
                    ),
                ),
                (
                    "move",
                    models.OneToOneField(
                        help_text="Movimiento de stock ligado.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mrp_production_move",
                        to="stock.stockmove",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        help_text="Orden de fabricación (Odoo production_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_moves",
                        to="mrp.mrpproduction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de orden de fabricación",
                "verbose_name_plural": "Movimientos de orden de fabricación",
                "db_table": "mrp_production_move",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MrpRoutingWorkcenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Operación (Odoo mrp.routing.workcenter.name).",
                        max_length=100,
                    ),
                ),
                (
                    "time_cycle",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Duración en minutos (Odoo time_cycle_manual).",
                        max_digits=10,
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=10, help_text="Orden de la operación (Odoo sequence)."
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        blank=True,
                        help_text="BoM (Odoo bom_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="mrp.mrpbom",
                    ),
                ),
                (
                    "workcenter",
                    models.ForeignKey(
                        help_text="Centro de trabajo (Odoo workcenter_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations",
                        to="mrp.mrpworkcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operación de hoja de ruta",
                "verbose_name_plural": "Operaciones de hoja de ruta",
                "db_table": "mrp_routing_workcenter",
                "ordering": ["sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="MrpWorkorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción (Odoo mrp.workorder.name).",
                        max_length=100,
                    ),
                ),
                (
                    "duration_expected",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Duración esperada en minutos (Odoo duration_expected).",
                        max_digits=10,
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Duración real en minutos (Odoo duration).",
                        max_digits=10,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("progress", "En progreso"),
                            ("done", "Terminada"),
                            ("cancel", "Cancelada"),
                        ],
                        default="pending",
                        help_text="Estado (Odoo mrp.workorder.state).",
                        max_length=16,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Operación (Odoo operation_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workorders",
                        to="mrp.mrproutingworkcenter",
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        help_text="Orden de fabricación (Odoo production_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorders",
                        to="mrp.mrpproduction",
                    ),
                ),
                (
                    "workcenter",
                    models.ForeignKey(
                        help_text="Centro de trabajo (Odoo workcenter_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workorders",
                        to="mrp.mrpworkcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de trabajo",
                "verbose_name_plural": "Órdenes de trabajo",
                "db_table": "mrp_workorder",
                "ordering": ["id"],
            },
        ),
    ]
