# Generated by Django 6.0.5 on 2026-07-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mrp", "0002_mrpworkcenter_mrpproductionmove_mrproutingworkcenter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mrpbom",
            name="type",
            field=models.CharField(
                choices=[
                    ("normal", "Fabricar este producto"),
                    ("phantom", "Kit"),
                    ("subcontract", "Subcontratación"),
                ],
                default="normal",
                help_text="Tipo de BoM: normal|phantom/kit (Odoo mrp.bom.type).",
                max_length=16,
            ),
        ),
    ]
