# Generated by Django 6.0.5 on 2026-08-18 19:29

import addons.website.models.website
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_seed_langs"),
        ("website", "0002_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="company",
            field=models.ForeignKey(
                default=addons.website.models.website.default_company,
                help_text="Empresa dueña del sitio (Odoo company_id, required).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="websites",
                to="base.rescompany",
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="default_lang",
            field=models.ForeignKey(
                default=addons.website.models.website.default_language,
                help_text="Idioma por defecto (Odoo default_lang_id, required).",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_websites",
                to="base.reslang",
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="favicon",
            field=models.BinaryField(
                blank=True,
                default=addons.website.models.website.default_favicon,
                help_text="Favicon del sitio (Odoo favicon).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="logo",
            field=models.BinaryField(
                blank=True,
                default=addons.website.models.website.default_logo,
                help_text="Logotipo del sitio (Odoo logo).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="social_discord",
            field=models.CharField(
                blank=True,
                default=addons.website.models.website.default_social_discord,
                help_text="Cuenta de Discord (Odoo social_discord).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="social_facebook",
            field=models.CharField(
                blank=True,
                default=addons.website.models.website.default_social_facebook,
                help_text="Cuenta de Facebook (Odoo social_facebook).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="social_github",
            field=models.CharField(
                blank=True,
                default=addons.website.models.website.default_social_github,
                help_text="Cuenta de GitHub (Odoo social_github).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="social_instagram",
            field=models.CharField(
                blank=True,
                default=addons.website.models.website.default_social_instagram,
                help_text="Cuenta de Instagram (Odoo social_instagram).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="social_linkedin",
            field=models.CharField(
                blank=True,
                default=addons.website.models.website.default_social_linkedin,
                help_text="Cuenta de LinkedIn (Odoo social_linkedin).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="social_tiktok",
            field=models.CharField(
                blank=True,
                default=addons.website.models.website.default_social_tiktok,
                help_text="Cuenta de TikTok (Odoo social_tiktok).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="social_twitter",
            field=models.CharField(
                blank=True,
                default=addons.website.models.website.default_social_twitter,
                help_text="Cuenta de X (Odoo social_twitter).",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="website",
            name="social_youtube",
            field=models.CharField(
                blank=True,
                default=addons.website.models.website.default_social_youtube,
                help_text="Cuenta de Youtube (Odoo social_youtube).",
                max_length=255,
                null=True,
            ),
        ),
    ]
