# Generated by Django 6.0.5 on 2026-08-18 20:12

import addons.website.models.website_menu
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_reference_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitemenu",
            name="new_window",
            field=models.BooleanField(
                default=False,
                help_text="Odoo new_window. Abrir el destino en una pestaña nueva.",
                verbose_name="Ventana nueva",
            ),
        ),
        migrations.AddField(
            model_name="websitemenu",
            name="parent_path",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Odoo parent_path (index=True). Ruta materializada «1/4/9/»; la mantiene save() — es el invariante de _parent_store, cuyo motor este ORM no tiene (#191).",
                max_length=255,
                verbose_name="Ruta del árbol",
            ),
        ),
        migrations.AddField(
            model_name="websitemenu",
            name="website",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo website_id (ondelete=cascade). Null = menú plantilla sin sitio, el que copy_menu_hierarchy clona por sitio.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="website.website",
                verbose_name="Sitio",
            ),
        ),
        migrations.AlterField(
            model_name="websitemenu",
            name="sequence",
            field=models.PositiveIntegerField(
                default=addons.website.models.website_menu.default_sequence,
                help_text="Odoo sequence (default=_default_sequence): el menú nuevo entra al final.",
                verbose_name="Secuencia",
            ),
        ),
    ]
