# Generated by Django 6.0.5 on 2026-08-18 22:36

import addons.website.models.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_seed_langs"),
        ("website", "0006_websiteconfiguratorfeature"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        help_text='La ruta, tal como la declara la URLconf (Odoo path, "Route").',
                        max_length=512,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ruta del sitio",
                "verbose_name_plural": "Rutas del sitio",
                "db_table": "website_route",
                "ordering": ["path"],
            },
        ),
        migrations.CreateModel(
            name="WebsitePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Visible en la tienda. Por defecto NO — igual que _default_is_published de la referencia: dar de alta un producto no es publicarlo.",
                        verbose_name="Publicado",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="Ruta de la página, p. ej. /acerca-de (Odoo url, required; el largo es el max_length del slugify de la fuente).",
                        max_length=1024,
                    ),
                ),
                (
                    "website_indexed",
                    models.BooleanField(
                        default=True,
                        help_text='Aparece en el sitemap y para los buscadores (Odoo website_indexed, "Is Indexed").',
                    ),
                ),
                (
                    "date_publish",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de publicación programada; antes de ella la página no es visible (Odoo date_publish).",
                        null=True,
                    ),
                ),
                (
                    "is_new_page_template",
                    models.BooleanField(
                        default=False,
                        help_text='La página se ofrece como plantilla en "+Nueva", categoría Personalizadas (Odoo is_new_page_template).',
                    ),
                ),
                (
                    "view",
                    models.ForeignKey(
                        db_column="view_id",
                        help_text="La vista que da el contenido (Odoo view_id, required, ondelete=cascade). Es la FK de la delegación _inherits.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_ids",
                        to="base.iruiview",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sitio dueño de la página; vacía = genérica, visible en todos (Odoo website_id; aquí FK real — divergencia 2 del módulo).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="website.website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Página del sitio",
                "verbose_name_plural": "Páginas del sitio",
                "db_table": "website_page",
                "ordering": ["website_id"],
            },
            bases=(addons.website.models.mixins.WebsiteSearchableMixin, models.Model),
        ),
        migrations.AddField(
            model_name="websitemenu",
            name="page",
            field=models.ForeignKey(
                blank=True,
                db_column="page_id",
                help_text="Odoo page_id ('website.page', ondelete='cascade', index=btree_not_null). Null = el menú apunta a una ruta, no a una página.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_ids",
                to="website.websitepage",
                verbose_name="Página relacionada",
            ),
        ),
        migrations.CreateModel(
            name="WebsiteRewrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la regla (Odoo name, required).",
                        max_length=255,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Regla activa (Odoo active)."
                    ),
                ),
                (
                    "url_from",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text='URL de origen (Odoo url_from, "URL from", index).',
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "url_to",
                    models.CharField(
                        blank=True,
                        help_text='URL de destino (Odoo url_to, "URL to").',
                        max_length=1024,
                        null=True,
                    ),
                ),
                (
                    "redirect_type",
                    models.CharField(
                        default="302",
                        help_text='Tipo de redirección/reescritura (Odoo redirect_type, "Action"): 301 el navegador cachea la URL nueva; 302 no la cachea; 404 retira una página/controlador; 308 renombra un controlador — ambas URL sirven y la vieja redirige a la nueva.',
                        max_length=3,
                        verbose_name=[
                            ("404", "404 Not Found"),
                            ("301", "301 Moved permanently"),
                            ("302", "302 Moved temporarily"),
                            ("308", "308 Redirect / Rewrite"),
                        ],
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de aplicación entre reglas (Odoo sequence).",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sitio al que aplica; vacía = todos (Odoo website_id, ondelete='cascade', index).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewrites",
                        to="website.website",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ruta del catálogo de la que parte la regla (Odoo route_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewrites",
                        to="website.websiteroute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reescritura de URL",
                "verbose_name_plural": "Reescrituras de URL",
                "db_table": "website_rewrite",
            },
        ),
    ]
