# Generated by Django 6.0.5 on 2026-08-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_websiteroute_websitepage_websitemenu_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitepage",
            name="footer_visible",
            field=models.BooleanField(
                default=True,
                help_text="La página dibuja el pie del sitio (Odoo footer_visible).",
            ),
        ),
        migrations.AddField(
            model_name="websitepage",
            name="header_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Color o clase de fondo de la cabecera en esta página (Odoo header_color).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="websitepage",
            name="header_overlay",
            field=models.BooleanField(
                default=False,
                help_text="El contenido de la página pasa por debajo de la cabecera (Odoo header_overlay).",
            ),
        ),
        migrations.AddField(
            model_name="websitepage",
            name="header_text_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Color o clase del texto de la cabecera en esta página (Odoo header_text_color).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="websitepage",
            name="header_visible",
            field=models.BooleanField(
                default=True,
                help_text="La página dibuja la cabecera del sitio (Odoo header_visible).",
            ),
        ),
    ]
