# Generated by Django 6.0.5 on 2026-08-19 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_seed_base_groups"),
        (
            "website",
            "0008_websitepage_footer_visible_websitepage_header_color_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteViewInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.BooleanField(
                        default=False,
                        help_text="Permite marcar una página del sitio como rastreable (Odoo track).",
                        verbose_name="Con seguimiento",
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Public"),
                            ("connected", "Signed In"),
                            ("restricted_group", "Restricted Group"),
                            ("password", "With Password"),
                        ],
                        default="",
                        help_text="Quién puede ver la página: pública, con sesión, con grupo restringido o con contraseña (Odoo visibility).",
                        max_length=16,
                        verbose_name="Visibilidad",
                    ),
                ),
                (
                    "visibility_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash de la contraseña con que se desbloquea la página (Odoo visibility_password, groups=base.group_system, copy=False).",
                        max_length=128,
                        verbose_name="Contraseña de visibilidad",
                    ),
                ),
                (
                    "view",
                    models.OneToOneField(
                        help_text="Vista a la que pertenece esta información (Odoo _inherit ir.ui.view).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_info",
                        to="base.iruiview",
                    ),
                ),
                (
                    "website",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sitio dueño de la vista; vacío = genérica, compartida por todos (Odoo website_id, ondelete=cascade).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="website.website",
                    ),
                ),
            ],
            options={
                "verbose_name": "Datos de sitio de la vista",
                "verbose_name_plural": "Datos de sitio de las vistas",
                "db_table": "website_ir_ui_view_info",
                "ordering": ["view_id"],
            },
        ),
    ]
