# Generated by Django 6.0.5 on 2026-07-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogPostalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        db_index=True,
                        help_text="CP del asentamiento (SEPOMEX d_codigo).",
                        max_length=5,
                        verbose_name="Código postal",
                    ),
                ),
                (
                    "settlement_name",
                    models.CharField(max_length=64, verbose_name="Asentamiento"),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        max_length=32, verbose_name="Tipo de asentamiento"
                    ),
                ),
                (
                    "municipality",
                    models.CharField(max_length=64, verbose_name="Municipio"),
                ),
                ("state", models.CharField(max_length=40, verbose_name="Estado")),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Ciudad"
                    ),
                ),
                (
                    "office_postal_code",
                    models.CharField(max_length=5, verbose_name="CP de oficina"),
                ),
                (
                    "state_code",
                    models.CharField(max_length=2, verbose_name="Clave de estado"),
                ),
                (
                    "office_code",
                    models.CharField(max_length=5, verbose_name="Clave de oficina"),
                ),
                (
                    "postal_code_internal_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=4,
                        verbose_name="Clave interna de CP",
                    ),
                ),
                (
                    "settlement_type_code",
                    models.CharField(
                        max_length=2, verbose_name="Clave tipo de asentamiento"
                    ),
                ),
                (
                    "municipality_code",
                    models.CharField(max_length=3, verbose_name="Clave de municipio"),
                ),
                (
                    "settlement_consecutive_id",
                    models.CharField(
                        max_length=4, verbose_name="ID consecutivo de asentamiento"
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        choices=[
                            ("Urbano", "Urbano"),
                            ("Semiurbano", "Semiurbano"),
                            ("Rural", "Rural"),
                        ],
                        max_length=12,
                        verbose_name="Zona",
                    ),
                ),
                (
                    "city_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=2,
                        verbose_name="Clave de ciudad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código postal (SEPOMEX)",
                "verbose_name_plural": "Códigos postales (SEPOMEX)",
                "db_table": "catalog_postal_code",
                "indexes": [
                    models.Index(
                        fields=["postal_code", "settlement_name"],
                        name="catalog_pos_postal__7550c8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("postal_code", "settlement_consecutive_id"),
                        name="uq_catalog_postal_code_natural_key",
                    )
                ],
            },
        ),
    ]
