# Generated by Django 6.0.5 on 2026-07-18 18:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0003_product_weight_kg"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la ubicación (Odoo stock.location.name).",
                        max_length=100,
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("supplier", "Proveedor"),
                            ("view", "Virtual"),
                            ("internal", "Interna"),
                            ("customer", "Cliente"),
                            ("inventory", "Pérdida de inventario"),
                            ("production", "Producción"),
                            ("transit", "Tránsito"),
                        ],
                        default="internal",
                        help_text="Tipo de ubicación (Odoo stock.location.usage).",
                        max_length=16,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación padre (Odoo location_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_ids",
                        to="stock.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación de inventario",
                "verbose_name_plural": "Ubicaciones de inventario",
                "db_table": "stock_location",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockPicking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia (Odoo stock.picking.name).",
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("waiting", "Esperando otro movimiento"),
                            ("confirmed", "Esperando"),
                            ("assigned", "Disponible"),
                            ("done", "Hecho"),
                            ("cancel", "Cancelada"),
                        ],
                        default="draft",
                        help_text="Estado (Odoo stock.picking.state).",
                        max_length=16,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Origen (Odoo location_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickings_out",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_dest",
                    models.ForeignKey(
                        blank=True,
                        help_text="Destino (Odoo location_dest_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickings_in",
                        to="stock.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferencia de inventario",
                "verbose_name_plural": "Transferencias de inventario",
                "db_table": "stock_picking",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descripción (Odoo stock.move.name).",
                        max_length=255,
                    ),
                ),
                (
                    "product_uom_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad demandada (Odoo product_uom_qty).",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad reservada/hecha (Odoo stock.move.quantity).",
                        max_digits=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Nuevo"),
                            ("waiting", "Esperando otro movimiento"),
                            ("confirmed", "Esperando disponibilidad"),
                            ("assigned", "Disponible"),
                            ("done", "Hecho"),
                            ("cancel", "Cancelado"),
                        ],
                        default="draft",
                        help_text="Estado (Odoo stock.move.state).",
                        max_length=16,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Ubicación origen (Odoo location_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_out",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_dest",
                    models.ForeignKey(
                        help_text="Ubicación destino (Odoo location_dest_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moves_in",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "move_orig",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Movimientos origen que abastecen a éste (Odoo move_orig_ids).",
                        related_name="move_dest",
                        to="stock.stockmove",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto (Odoo product_id).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_moves",
                        to="catalogue.product",
                    ),
                ),
                (
                    "picking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transferencia (Odoo picking_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="move_ids",
                        to="stock.stockpicking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "db_table": "stock_move",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la regla (Odoo stock.rule.name).",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("pull", "Extraer de"),
                            ("push", "Empujar a"),
                            ("pull_push", "Extraer y empujar"),
                        ],
                        default="pull",
                        help_text="Acción (Odoo stock.rule.action).",
                        max_length=16,
                    ),
                ),
                (
                    "procure_method",
                    models.CharField(
                        choices=[
                            ("make_to_stock", "Tomar de existencias"),
                            ("make_to_order", "Disparar otra regla"),
                        ],
                        default="make_to_stock",
                        help_text="Método de aprovisionamiento (Odoo procure_method).",
                        max_length=16,
                    ),
                ),
                (
                    "location_dest",
                    models.ForeignKey(
                        help_text="Ubicación destino (Odoo location_dest_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules_in",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "location_src",
                    models.ForeignKey(
                        blank=True,
                        help_text="Ubicación origen (Odoo location_src_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rules_out",
                        to="stock.stocklocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regla de aprovisionamiento",
                "verbose_name_plural": "Reglas de aprovisionamiento",
                "db_table": "stock_rule",
            },
        ),
        migrations.CreateModel(
            name="StockQuant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad a la mano (Odoo stock.quant.quantity).",
                        max_digits=12,
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cantidad reservada (Odoo reserved_quantity).",
                        max_digits=12,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        help_text="Ubicación (Odoo location_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quants",
                        to="stock.stocklocation",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto (Odoo product_id).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quants",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Existencia de inventario",
                "verbose_name_plural": "Existencias de inventario",
                "db_table": "stock_quant",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "location"),
                        name="unique_quant_product_location",
                    )
                ],
            },
        ),
    ]
