# Generated by Django 6.0.5 on 2026-07-18 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_product_weight_kg"),
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Número de lote / serie (Odoo stock.lot.name, requerido).",
                        max_length=120,
                    ),
                ),
                (
                    "ref",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Referencia interna (Odoo stock.lot.ref).",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote / número de serie",
                "verbose_name_plural": "Lotes / números de serie",
                "db_table": "stock_lot",
                "ordering": ["name", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="stockquant",
            name="unique_quant_product_location",
        ),
        migrations.AddField(
            model_name="stockquant",
            name="in_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha de entrada al quant (Odoo stock.quant.in_date; clave de orden de la estrategia FIFO).",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="product",
            field=models.ForeignKey(
                help_text="Producto (Odoo product_id).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="catalogue.product",
            ),
        ),
        migrations.AddField(
            model_name="stockquant",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Lote / número de serie (Odoo lot_id). NULL = sin lote.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quants",
                to="stock.stocklot",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockquant",
            constraint=models.UniqueConstraint(
                fields=("product", "location", "lot"),
                name="unique_quant_product_location_lot",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.UniqueConstraint(
                fields=("product", "name"), name="unique_lot_product_name"
            ),
        ),
    ]
