# Generated by Django 6.0.5 on 2026-07-22 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sale", "0008_port_draft_orders_to_sale"),
        ("stock", "0003_return_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockpicking",
            name="sale_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Orden de venta (Odoo stock.picking.sale_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickings",
                to="sale.saleorder",
            ),
        ),
    ]
