# Generated by Django 6.0.5 on 2026-08-19 04:54

import addons.hr_work_entry.models.resource_calendar_attendance
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_work_entry", "__first__"),
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcecalendarattendance",
            name="work_entry_type",
            field=models.ForeignKey(
                blank=True,
                default=addons.hr_work_entry.models.resource_calendar_attendance._default_work_entry_type_id,
                help_text="Odoo work_entry_type_id (groups=hr.group_hr_user — ACL del cliente, no se porta).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_attendances",
                to="hr_work_entry.hrworkentrytype",
                verbose_name="Work Entry Type",
            ),
        ),
        migrations.AddField(
            model_name="resourcecalendarleaves",
            name="work_entry_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo work_entry_type_id (groups=hr.group_hr_user — ACL del cliente, no se porta).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="calendar_leaves",
                to="hr_work_entry.hrworkentrytype",
                verbose_name="Work Entry Type",
            ),
        ),
    ]
