# Generated by Django 6.0.5 on 2026-08-04 16:53

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_resdevice"),
        ("mail", "0002_seed_message_subtypes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mailalias",
            name="mail_alias_name_domain_unique",
        ),
        migrations.AddField(
            model_name="mailalias",
            name="alias_domain_key",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.comparison.Coalesce(
                    "alias_domain_id", models.Value(0)
                ),
                output_field=models.BigIntegerField(),
            ),
        ),
        migrations.AddConstraint(
            model_name="mailalias",
            constraint=models.UniqueConstraint(
                fields=("alias_name", "alias_domain_key"),
                name="mail_alias_name_domain_unique",
            ),
        ),
    ]
