# Generated by Django 6.0.5 on 2026-07-12 02:15

import apps.modules.users.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Identificador de login (USERNAME_FIELD).",
                        max_length=254,
                        unique=True,
                        verbose_name="Correo electrónico",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="Contraseña"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último acceso"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Cuenta operativa. False = desactivada (ver deactivated_reason).",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Fecha de alta"
                    ),
                ),
                (
                    "deactivated_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unverified", "No verificada (email pendiente)"),
                            ("suspended", "Suspendida por administrador"),
                            ("self_deleted", "Dada de baja por el usuario"),
                        ],
                        help_text="Causa por la que is_active=False. NULL cuando la cuenta está activa. Distingue cuentas reactivables por email (unverified, self_deleted) de las que requieren UC-AUTH-14 (suspended). Ver UC-AUTH-01 Alt-A.",
                        max_length=20,
                        null=True,
                        verbose_name="Causa de inactividad",
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de desactivación"
                    ),
                ),
                (
                    "mp_customer_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID del customer en MP para guardar tarjetas. BR-009.",
                        max_length=100,
                        verbose_name="ID cliente MercadoPago",
                    ),
                ),
            ],
            options={
                "verbose_name": "Identidad de usuario",
                "verbose_name_plural": "Identidades de usuario",
                "db_table": "users_identity_user",
            },
            managers=[
                ("objects", apps.modules.users.models.IdentityUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True si la fila fue borrada via soft delete.",
                        verbose_name="Eliminado (logico)",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de borrado logico"
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        help_text="Ej: Casa, Trabajo, Almacén.",
                        max_length=50,
                        verbose_name="Nombre de la dirección",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=150, verbose_name="Nombre del destinatario"
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=200, verbose_name="Calle y número"),
                ),
                (
                    "exterior_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número exterior (MX). Ej: 123, 45-B.",
                        max_length=20,
                        verbose_name="Número exterior",
                    ),
                ),
                (
                    "interior_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Número interior si aplica (MX). Ej: Depto 5.",
                        max_length=20,
                        verbose_name="Número interior",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Colonia / neighborhood (MX).",
                        max_length=120,
                        verbose_name="Colonia",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ciudad")),
                ("state", models.CharField(max_length=100, verbose_name="Estado")),
                (
                    "zip_code",
                    models.CharField(max_length=10, verbose_name="Código postal"),
                ),
                (
                    "country",
                    models.CharField(
                        default="MX",
                        help_text="Código ISO 3166-1 alpha-2.",
                        max_length=2,
                        verbose_name="País",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, verbose_name="Teléfono del destinatario"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Dirección predeterminada"
                    ),
                ),
                (
                    "postal_code_ref",
                    models.ForeignKey(
                        blank=True,
                        help_text="Enlace opcional a la colonia del catálogo internacional.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="addresses",
                        to="geo.catalogpostalcode",
                        verbose_name="Código postal (catálogo)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comprador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección de envío",
                "verbose_name_plural": "Direcciones de envío",
                "db_table": "users_address",
                "ordering": ["-is_default", "alias"],
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marketing_opt_in",
                    models.BooleanField(default=False, verbose_name="Acepta marketing"),
                ),
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Identidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de comprador",
                "verbose_name_plural": "Perfiles de comprador",
                "db_table": "users_customer_profile",
            },
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_email_verification_token",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Código de empleado",
                    ),
                ),
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Identidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de empleado",
                "verbose_name_plural": "Perfiles de empleado",
                "db_table": "users_employee_profile",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_password_reset_token",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Nombre"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Apellidos"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de perfil. Formatos: JPEG, PNG, WebP.",
                        null=True,
                        upload_to=apps.modules.users.models.avatar_upload_path,
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "identity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Identidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
                "db_table": "users_person",
            },
        ),
        migrations.CreateModel(
            name="AuthEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login exitoso"),
                            ("LOGIN_FAIL", "Login fallido"),
                            ("LOGOUT", "Logout"),
                            ("REFRESH_SUCCESS", "Refresh exitoso"),
                            ("REFRESH_FAIL", "Refresh fallido"),
                            ("REGISTER_ATTEMPT", "Registro intento"),
                            ("REGISTER_SUCCESS", "Registro exitoso"),
                            ("REGISTER_FAIL", "Registro fallido"),
                            ("PASSWORD_CHANGE", "Cambio de contraseña"),
                            ("ADDRESS_CREATED", "Dirección creada"),
                            ("ADDRESS_UPDATED", "Dirección actualizada"),
                            ("ADDRESS_DELETED", "Dirección eliminada"),
                            ("ADDRESS_DEFAULT", "Dirección predeterminada"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("ip_addr", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=30)),
                ("extra_json", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auth_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_auth_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "-created_at"],
                        name="users_auth__user_id_1222c3_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="users_auth__action_ac0624_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ORDER_CREATED", "Order creada"),
                            ("ORDER_CANCELLED", "Order cancelada"),
                            ("RETURN_REQUESTED", "Return solicitada"),
                            ("RETURN_RESOLVED", "Return resuelta"),
                            ("STOCK_ADJUSTED_TO_ZERO", "Stock ajustado a cero"),
                            ("RECEIPT_PDF_GENERATED", "Receipt PDF generado"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_addr", models.GenericIPAddressField(blank=True, null=True)),
                ("extra_json", models.JSONField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=32
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_business_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "-created_at"],
                        name="users_busin_action_377e8e_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="users_busin_target__451beb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserDeactivationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("unverified", "No verificada (email pendiente)"),
                            ("suspended", "Suspendida por administrador"),
                            ("self_deleted", "Dada de baja por el usuario"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            (
                                "register",
                                "Registro (cuenta nueva inactiva por verificar)",
                            ),
                            ("self", "Auto-baja del propio usuario"),
                            ("admin", "Suspensión por administrador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quién disparó el evento. NULL para SOURCE_REGISTER o SOURCE_SELF. Solo SOURCE_ADMIN registra al admin.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deactivation_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de desactivación",
                "verbose_name_plural": "Eventos de desactivación",
                "db_table": "users_deactivation_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="users_deact_user_id_d7cbf3_idx",
                    ),
                    models.Index(
                        fields=["source"], name="users_deact_source_eafffd_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_user_session",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_activity"],
                        name="users_user__user_id_0c2a29_idx",
                    )
                ],
            },
        ),
    ]
