# Generated by Django 6.0.5 on 2026-08-03 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyLdap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                (
                    "ldap_server",
                    models.CharField(
                        default="127.0.0.1",
                        max_length=255,
                        verbose_name="Servidor LDAP",
                    ),
                ),
                (
                    "ldap_server_port",
                    models.IntegerField(default=389, verbose_name="Puerto LDAP"),
                ),
                (
                    "ldap_binddn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cuenta con la que se consulta el directorio. Vacío = conexión anónima.",
                        max_length=255,
                        verbose_name="binddn LDAP",
                    ),
                ),
                (
                    "ldap_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contraseña de la cuenta que consulta el directorio.",
                        max_length=255,
                        verbose_name="Contraseña LDAP",
                    ),
                ),
                (
                    "ldap_filter",
                    models.CharField(
                        help_text="Filtro de búsqueda de cuentas. Cada `%s` se reemplaza por el login; debe producir exactamente 1 resultado. Ej.: (&(objectCategory=person)(objectClass=user)(sAMAccountName=%s))",
                        max_length=1024,
                        verbose_name="Filtro LDAP",
                    ),
                ),
                (
                    "ldap_base",
                    models.CharField(
                        help_text="DN base de la búsqueda: se exploran todos sus descendientes.",
                        max_length=1024,
                        verbose_name="Base LDAP",
                    ),
                ),
                (
                    "create_user",
                    models.BooleanField(
                        default=True,
                        help_text="Crear automáticamente la cuenta local para usuarios nuevos que autentican vía LDAP.",
                        verbose_name="Crear usuario",
                    ),
                ),
                (
                    "ldap_tls",
                    models.BooleanField(
                        default=False,
                        help_text="STARTTLS al conectar. Requiere servidor con STARTTLS; sin él, toda autenticación fallará.",
                        verbose_name="Usar TLS",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ldaps",
                        to="company.company",
                        verbose_name="Company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario a copiar al crear usuarios nuevos.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario plantilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración LDAP",
                "verbose_name_plural": "Configuraciones LDAP",
                "db_table": "res_company_ldap",
                "ordering": ["sequence"],
            },
        ),
    ]
