# Generated by Django 6.0.5 on 2026-08-06 02:40

import django.db.models.deletion
import orm.environments
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0007_alter_iractionsreport_report_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DigestDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Odoo name (required, translate) — nombre del digest.",
                        max_length=255,
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "Diaria"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("quarterly", "Trimestral"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="Periodicidad",
                    ),
                ),
                (
                    "next_run_date",
                    models.DateField(
                        blank=True,
                        help_text="Se calcula en save() si no se da explícitamente (Odoo create()).",
                        null=True,
                        verbose_name="Próximo envío",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("activated", "Activado"),
                            ("deactivated", "Desactivado"),
                        ],
                        default="activated",
                        max_length=12,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "kpi_res_users_connected",
                    models.BooleanField(
                        default=False,
                        help_text="KPI base: cuenta filas de ResUsersLog (accesos) en el periodo.",
                        verbose_name="Usuarios conectados",
                    ),
                ),
                (
                    "kpi_mail_message_total",
                    models.BooleanField(
                        default=False,
                        help_text="KPI base: cuenta MailMessage creados en el periodo.",
                        verbose_name="Mensajes enviados",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        default=orm.environments.get_current_company,
                        help_text="Odoo company_id (default=env.company.id → get_current_company()).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="digests",
                        to="base.rescompany",
                        verbose_name="Compañía",
                    ),
                ),
                (
                    "user_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Odoo user_ids (domain share=False en la referencia — no enforced a nivel de columna, ver action_subscribe).",
                        related_name="digests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatarios",
                    ),
                ),
            ],
            options={
                "verbose_name": "Digest",
                "verbose_name_plural": "Digests",
                "db_table": "digest_digest",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DigestTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.IntegerField(
                        default=1,
                        help_text="Odoo sequence — orden de despliegue en el correo.",
                        verbose_name="Secuencia",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Nombre"
                    ),
                ),
                (
                    "tip_description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "user_ids",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Odoo user_ids — usuarios que ya recibieron este tip.",
                        related_name="seen_digest_tips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ya lo vieron",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consejo de digest",
                "verbose_name_plural": "Consejos de digest",
                "db_table": "digest_tip",
                "ordering": ["sequence", "id"],
            },
        ),
    ]
