"""``db.backup`` + ``db.backup.details`` — la forma de ``app_auto_backup``.

Adaptación de ``app_auto_backup`` (``odoo-tools@622ddc2a``,
``18.x/app-odoo-18.0``, **LGPL-3**). El addon nació sobre la premisa —falsa—
de que la referencia Community no tenía addon de respaldo, así que se quedó
sin el modelo de configuración y con el de ejecución renombrado
(:ref:`h-api-763`). Esta migración lo corrige:

- **``db_backup``** es nuevo: dónde, cómo y cuánto se conserva, más el
  bloque SFTP completo. No existía.
- **``db_backup_details``** sustituye a ``backup_record``: mismo concepto —
  una fila por corrida— con el nombre, la tabla y los campos de la fuente
  (``name``, ``file_path``, ``url``, ``db_backup_id``), conservando los
  cuatro propios que UC-ADM-05 lista (``type``, ``status``, ``size_bytes``,
  ``error_detail``).

**Las filas de ``backup_record`` NO se migran, y es deliberado.** El
autodetector no vio un renombre —cambian tabla, cuatro campos y el tipo de
``url`` (``URLField`` → ``CharField``)— y no se fuerza a mano: la tabla se
creó el 2026-08-03 sobre una base que se levantó desde cero (tarea #319) y
no hay despliegue que la consuma. Lo que se pierde es un log de dev; el
coste de una copia manual de filas supera lo que preserva. Se declara aquí
en vez de callarlo, que es lo que exige `porte-completo-no-parcial.md`.
"""
# Generated by Django 6.0.5 on 2026-08-20 18:32

import addons.auto_backup.models.db_backup
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_backup", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DbBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.CharField(
                        default="localhost",
                        help_text="Odoo host. Sólo alimenta la línea de log del fallo.",
                        verbose_name="Host",
                    ),
                ),
                (
                    "port",
                    models.CharField(
                        default="8069",
                        help_text="Odoo port. Sólo alimenta la línea de log del fallo.",
                        verbose_name="Port",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=addons.auto_backup.models.db_backup._get_db_name,
                        help_text="Base que se quiere respaldar (Odoo name).",
                        verbose_name="Database",
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        default="/var/backups/kaupamex",
                        help_text="Ruta absoluta donde se escriben los respaldos (Odoo folder).",
                        verbose_name="Backup Directory",
                    ),
                ),
                (
                    "backup_type",
                    models.CharField(
                        choices=[("zip", "Zip"), ("dump", "Dump")],
                        default="zip",
                        help_text="Formato del volcado (Odoo backup_type).",
                        max_length=8,
                        verbose_name="Backup Type",
                    ),
                ),
                (
                    "autoremove",
                    models.BooleanField(
                        default=False,
                        help_text="Si se marca, los respaldos locales se borran pasados days_to_keep días (Odoo autoremove).",
                        verbose_name="Auto. Remove Backups",
                    ),
                ),
                (
                    "days_to_keep",
                    models.IntegerField(
                        default=30,
                        help_text="Tras cuántos días se borra el respaldo local. Con 5, los respaldos se retiran a los 5 días (Odoo days_to_keep).",
                        verbose_name="Remove after x days",
                    ),
                ),
                (
                    "sftp_write",
                    models.BooleanField(
                        default=False,
                        help_text="Copiar además el respaldo a un servidor remoto por SFTP.",
                        verbose_name="Write to external server with sftp",
                    ),
                ),
                (
                    "sftp_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Carpeta del servidor remoto donde se escriben los volcados, p. ej. /odoo/backups/ (Odoo sftp_path).",
                        verbose_name="Path external server",
                    ),
                ),
                (
                    "sftp_host",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dirección del servidor remoto (Odoo sftp_host).",
                        verbose_name="IP Address SFTP Server",
                    ),
                ),
                (
                    "sftp_port",
                    models.IntegerField(
                        default=22,
                        help_text="Puerto SSH/SFTP del servidor remoto (Odoo sftp_port).",
                        verbose_name="SFTP Port",
                    ),
                ),
                (
                    "sftp_user",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Usuario del servidor remoto (Odoo sftp_user).",
                        verbose_name="Username SFTP Server",
                    ),
                ),
                (
                    "sftp_password",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SECRETO — contraseña del usuario remoto (Odoo sftp_password). La superficie que lo exponga debe ir gateada por capacidad.",
                        verbose_name="Password User SFTP Server",
                    ),
                ),
                (
                    "days_to_keep_sftp",
                    models.IntegerField(
                        default=30,
                        help_text="Tras cuántos días se borra el respaldo del remoto.",
                        verbose_name="Remove SFTP after x days",
                    ),
                ),
                (
                    "send_mail_sftp_fail",
                    models.BooleanField(
                        default=False,
                        help_text="Avisar por correo cuando la copia al remoto falle.",
                        verbose_name="Auto. E-mail on backup fail",
                    ),
                ),
                (
                    "email_to_notify",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Destinatario del aviso de fallo (Odoo email_to_notify).",
                        verbose_name="E-mail to notify",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de respaldo",
                "verbose_name_plural": "Configuraciones de respaldo",
                "db_table": "db_backup",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DbBackupDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre del archivo de respaldo (Odoo name).",
                        verbose_name="Name",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ruta absoluta del archivo en disco (Odoo file_path).",
                        verbose_name="File Path",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ruta de descarga (Odoo url). Es relativa —/dbbackup/download/<ruta>—, no una URL absoluta.",
                        verbose_name="URL",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("AUTO", "Automático"), ("MANUAL", "Manual")],
                        default="AUTO",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("OK", "Completado"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                ("size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("error_detail", models.TextField(blank=True, default="")),
                (
                    "db_backup_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="Configuración que produjo esta corrida (Odoo db_backup_id).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_details_ids",
                        to="auto_backup.dbbackup",
                        verbose_name="Database Backup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respaldo",
                "verbose_name_plural": "Respaldos",
                "db_table": "db_backup_details",
                "ordering": ["-id"],
            },
        ),
        migrations.DeleteModel(
            name="BackupRecord",
        ),
    ]
