# Generated by Django 6.0.5 on 2026-08-28 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auto_backup", "0003_seed_cron_backup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbbackupdetails",
            name="db_backup_id",
            field=models.ForeignKey(
                blank=True,
                db_column="db_backup_id",
                help_text="Configuración que produjo esta corrida (Odoo db_backup_id).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="backup_details_ids",
                to="auto_backup.dbbackup",
                verbose_name="Database Backup",
            ),
        ),
    ]
