# Generated by Django 6.0.5 on 2026-08-03 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HrDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "parent_path",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                ("note", models.TextField(blank=True, default="", verbose_name="Nota")),
                (
                    "color",
                    models.IntegerField(default=0, verbose_name="Índice de color"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa dueña del departamento (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_departments",
                        to="base.rescompany",
                        verbose_name="Empresa (tenant)",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="hr.hrdepartment",
                        verbose_name="Departamento padre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "db_table": "hr_department",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HrJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, verbose_name="Puesto")),
                (
                    "no_of_recruitment",
                    models.IntegerField(
                        default=1,
                        help_text="Número de nuevos empleados que se espera reclutar.",
                        verbose_name="Objetivo",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, default="", verbose_name="Requisitos"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa dueña del puesto (Odoo company_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_jobs",
                        to="base.rescompany",
                        verbose_name="Empresa (tenant)",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="hr.hrdepartment",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruiter_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reclutador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Puesto",
                "verbose_name_plural": "Puestos",
                "db_table": "hr_job",
                "ordering": ["name"],
            },
        ),
    ]
