# Generated by Django 6.0.5 on 2026-08-18 11:59

import addons.hr.models.hr_departure_reason
import addons.hr.models.hr_employee_category
import addons.hr.models.hr_payroll_structure_type
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0024_respartner_check_name"),
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrContractType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del tipo de contrato (Odoo name).",
                        max_length=150,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código corto (Odoo code). Se auto-rellena desde name si se deja vacío — ver save() (Odoo _compute_code).",
                        max_length=64,
                        verbose_name="Código",
                    ),
                ),
                ("sequence", models.IntegerField(default=0, verbose_name="Secuencia")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="País asociado al tipo de contrato (Odoo country_id). El domain= de la referencia es un filtro de UI — ver docstring del módulo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_contract_types",
                        to="base.rescountry",
                        verbose_name="País",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de contrato",
                "verbose_name_plural": "Tipos de contrato",
                "db_table": "hr_contract_type",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="HrDepartureReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.IntegerField(default=10, verbose_name="Secuencia")),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del motivo de baja (Odoo name).",
                        max_length=150,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        default=addons.hr.models.hr_departure_reason._default_country,
                        help_text="País de la compañía activa al crear el registro (Odoo country_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_departure_reasons",
                        to="base.rescountry",
                        verbose_name="País",
                    ),
                ),
            ],
            options={
                "verbose_name": "Motivo de baja",
                "verbose_name_plural": "Motivos de baja",
                "db_table": "hr_departure_reason",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="HrEmployeeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la etiqueta (Odoo name).",
                        max_length=150,
                        verbose_name="Nombre de la etiqueta",
                    ),
                ),
                (
                    "color",
                    models.IntegerField(
                        default=addons.hr.models.hr_employee_category._default_category_color,
                        help_text="Color del kanban, 1-11 (Odoo color).",
                        verbose_name="Índice de color",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta de empleado",
                "verbose_name_plural": "Etiquetas de empleado",
                "db_table": "hr_employee_category",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="hr_employee_category_name_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HrPayrollStructureType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nombre del tipo de estructura salarial (Odoo name).",
                        max_length=150,
                        verbose_name="Tipo de estructura salarial",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        default=addons.hr.models.hr_payroll_structure_type._default_country,
                        help_text="País de la compañía activa al crear el registro (Odoo country_id).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_payroll_structure_types",
                        to="base.rescountry",
                        verbose_name="País",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de estructura salarial",
                "verbose_name_plural": "Tipos de estructura salarial",
                "db_table": "hr_payroll_structure_type",
            },
        ),
        migrations.CreateModel(
            name="HrWorkLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la sede de trabajo (Odoo name).",
                        max_length=150,
                        verbose_name="Sede de trabajo",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("home", "Casa"),
                            ("office", "Oficina"),
                            ("other", "Otra"),
                        ],
                        default="office",
                        help_text="Casa / oficina / otra (Odoo location_type).",
                        max_length=6,
                        verbose_name="Tipo de ubicación",
                    ),
                ),
                (
                    "location_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Número de ubicación",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dirección de la sede (Odoo address_id, check_company=True en la fuente — ver docstring del módulo).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_work_locations",
                        to="base.respartner",
                        verbose_name="Dirección de trabajo",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empresa dueña de la sede (Odoo company_id, required=True en la fuente — ver docstring del módulo).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_work_locations",
                        to="base.rescompany",
                        verbose_name="Empresa (tenant)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sede de trabajo",
                "verbose_name_plural": "Sedes de trabajo",
                "db_table": "hr_work_location",
                "ordering": ["name"],
            },
        ),
    ]
