# Generated by Django 6.0.5 on 2026-08-18 12:05

import addons.hr.models.hr_payroll_structure_type
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_seed_default_departure_reasons"),
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hrpayrollstructuretype",
            name="default_resource_calendar",
            field=models.ForeignKey(
                blank=True,
                default=addons.hr.models.hr_payroll_structure_type._default_resource_calendar,
                help_text="Horario por defecto del tipo de estructura salarial (Odoo default_resource_calendar_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_payroll_structure_types",
                to="resource.resourcecalendar",
                verbose_name="Horario de trabajo",
            ),
        ),
    ]
