# Generated by Django 6.0.5 on 2026-08-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_alter_respartner_options_alter_resusers_options"),
        ("hr", "0004_hrpayrollstructuretype_default_resource_calendar"),
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HrEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image_1920",
                    models.ImageField(
                        blank=True,
                        help_text="Odoo image_1920. Original; las derivadas salen de aquí.",
                        null=True,
                        upload_to="images/original/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "image_1024",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/1024/",
                        verbose_name="Imagen 1024",
                    ),
                ),
                (
                    "image_512",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/512/",
                        verbose_name="Imagen 512",
                    ),
                ),
                (
                    "image_256",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/256/",
                        verbose_name="Imagen 256",
                    ),
                ),
                (
                    "image_128",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="images/128/",
                        verbose_name="Imagen 128",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Odoo name (related=resource_id.name — aquí columna propia, ver divergencia del docstring del módulo).",
                        max_length=200,
                        verbose_name="Nombre del empleado",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Odoo active (related=resource_id.active — columna propia).",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "hr_presence_state",
                    models.CharField(
                        choices=[
                            ("present", "Presente"),
                            ("absent", "Ausente"),
                            ("archive", "Archivado"),
                            ("out_of_working_hour", "Fuera de horario"),
                        ],
                        default="out_of_working_hour",
                        help_text="BLOQUEADO por ``base.ResUsers.presence_ids`` — _compute_presence_state lo exige junto con resource_calendar_id del contrato; el campo queda en su default. Sucesor: tarea #21.",
                        max_length=20,
                        verbose_name="Estado de presencia",
                    ),
                ),
                (
                    "last_activity",
                    models.DateField(
                        blank=True,
                        help_text="BLOQUEADO por ``base.ResUsers.presence_ids`` — _compute_last_activity lo exige y la infra de bus no está portada. Sucesor: tarea #21.",
                        null=True,
                        verbose_name="Última actividad",
                    ),
                ),
                (
                    "last_activity_time",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "hr_icon_display",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("presence_present", "Presente"),
                            ("presence_out_of_working_hour", "Fuera de horario"),
                            ("presence_absent", "Ausente"),
                            ("presence_archive", "Archivado"),
                            ("presence_undetermined", "Indeterminado"),
                        ],
                        default="",
                        help_text="BLOQUEADO por ``hr_presence_state`` — _compute_presence_icon deriva de ese campo, que queda en su default. Sucesor: tarea #21.",
                        max_length=28,
                    ),
                ),
                ("show_hr_icon_display", models.BooleanField(default=False)),
                (
                    "newly_hired",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo newly_hired — recomputar con newly_hired property; este campo persiste el último valor calculado.",
                        verbose_name="Recién contratado",
                    ),
                ),
                (
                    "company_country_code",
                    models.CharField(blank=True, default="", max_length=8),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Teléfono de trabajo",
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Celular de trabajo",
                    ),
                ),
                (
                    "work_email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Correo de trabajo",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo legal_name (compute+store+readonly=False — se rellena desde name en save() si está vacío).",
                        max_length=200,
                        verbose_name="Nombre legal",
                    ),
                ),
                (
                    "private_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Teléfono privado",
                    ),
                ),
                (
                    "private_email",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="Correo privado",
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Código de base.ResLang.code (Odoo lang — Selection dinámico, ver divergencia del docstring del módulo).",
                        max_length=16,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "place_of_birth",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Lugar de nacimiento",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "birthday_public_display",
                    models.BooleanField(
                        default=False, verbose_name="Mostrar a todos los empleados"
                    ),
                ),
                (
                    "birthday_public_display_string",
                    models.CharField(blank=True, default="hidden", max_length=32),
                ),
                (
                    "salary_distribution",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Odoo salary_distribution: {"<bank_account_id>": {"sequence", "amount", "amount_is_percentage"}}.',
                        null=True,
                        verbose_name="Distribución de nómina",
                    ),
                ),
                (
                    "permit_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="No. de permiso de trabajo",
                    ),
                ),
                (
                    "visa_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="No. de visa",
                    ),
                ),
                (
                    "visa_expire",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimiento de visa"
                    ),
                ),
                (
                    "work_permit_expiration_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Vencimiento de permiso de trabajo",
                    ),
                ),
                (
                    "has_work_permit",
                    models.BinaryField(
                        blank=True,
                        null=True,
                        verbose_name="Permiso de trabajo (archivo)",
                    ),
                ),
                ("work_permit_scheduled_activity", models.BooleanField(default=False)),
                (
                    "work_permit_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "certificate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("graduate", "Bachillerato"),
                            ("bachelor", "Licenciatura"),
                            ("master", "Maestría"),
                            ("doctor", "Doctorado"),
                            ("other", "Otro"),
                        ],
                        default="",
                        max_length=8,
                        verbose_name="Nivel de estudios",
                    ),
                ),
                (
                    "study_field",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Área de estudio",
                    ),
                ),
                (
                    "study_school",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Institución",
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "emergency_phone",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "work_location_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="BLOQUEADO por ``version_id.work_location_id`` — el cómputo depende de ese campo.",
                        max_length=150,
                    ),
                ),
                (
                    "work_location_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Casa"),
                            ("office", "Oficina"),
                            ("other", "Otra"),
                        ],
                        default="",
                        help_text="BLOQUEADO por ``version_id.work_location_id`` — el cómputo depende de ese campo.",
                        max_length=6,
                    ),
                ),
                (
                    "color",
                    models.IntegerField(default=0, verbose_name="Índice de color"),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        help_text="Odoo barcode — identificación del empleado. Unicidad vía Meta.constraints (``hr_employee_barcode_uniq``), no aquí.",
                        max_length=18,
                        null=True,
                        verbose_name="ID de gafete",
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="PIN"
                    ),
                ),
                (
                    "id_card",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Copia de identificación"
                    ),
                ),
                (
                    "driving_license",
                    models.BinaryField(
                        blank=True, null=True, verbose_name="Licencia de conducir"
                    ),
                ),
                (
                    "private_car_plate",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("related_partners_count", models.IntegerField(default=0)),
                (
                    "bank_account",
                    models.ManyToManyField(
                        blank=True,
                        db_table="hr_employee_bank_account_rel",
                        help_text="Odoo bank_account_ids — cuentas para pagar la nómina.",
                        related_name="hr_employees",
                        to="base.respartnerbank",
                        verbose_name="Cuentas bancarias",
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        blank=True,
                        db_table="hr_employee_category_rel",
                        related_name="employees",
                        to="hr.hremployeecategory",
                        verbose_name="Etiquetas",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo coach_id — sincronizado desde parent en save(), ver _compute_coach.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coached_employees",
                        to="hr.hremployee",
                        verbose_name="Coach",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo company_id (related=resource_id.company_id, store=True, readonly=False) — sincronizado en save(), ver divergencia 2.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_resource_mixin_company_set",
                        to="base.rescompany",
                    ),
                ),
                (
                    "country_of_birth",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_employees_born_here",
                        to="base.rescountry",
                        verbose_name="País de nacimiento",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo parent_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="hr.hremployee",
                        verbose_name="Gerente",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        help_text="Odoo resource_id (required, ondelete='restrict').",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_resource_mixin_set",
                        to="resource.resourceresource",
                    ),
                ),
                (
                    "resource_calendar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo resource_calendar_id (related=resource_id.calendar_id, store=True, readonly=False) — sincronizado en save().",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_resource_mixin_calendar_set",
                        to="resource.resourcecalendar",
                    ),
                ),
                (
                    "work_contact",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo work_contact_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_work_contacts",
                        to="base.respartner",
                        verbose_name="Contacto de trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "db_table": "hr_employee",
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("barcode__isnull", False)),
                        fields=("barcode",),
                        name="hr_employee_barcode_uniq",
                    )
                ],
            },
        ),
    ]
