# Generated by Django 6.0.5 on 2026-08-18 15:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0025_alter_respartner_options_alter_resusers_options"),
        ("hr", "0005_hremployee"),
        ("resource", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HrVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="Nombre"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activa")),
                ("date_version", models.DateField(verbose_name="Fecha de versión")),
                (
                    "last_modified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Odoo last_modified_date.",
                        null=True,
                        verbose_name="Modificado por última vez el",
                    ),
                ),
                (
                    "identification_no",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo identification_id.",
                        max_length=64,
                        verbose_name="No. de identificación",
                    ),
                ),
                (
                    "ssn",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="No. de seguridad social",
                    ),
                ),
                (
                    "passport_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="No. de pasaporte",
                    ),
                ),
                (
                    "passport_expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Vencimiento de pasaporte"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Masculino"),
                            ("female", "Femenino"),
                            ("other", "Otro"),
                        ],
                        default="",
                        max_length=6,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "private_street",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Calle (privada)",
                    ),
                ),
                (
                    "private_street2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Calle 2 (privada)",
                    ),
                ),
                (
                    "private_city",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Ciudad (privada)",
                    ),
                ),
                (
                    "private_zip",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=16,
                        verbose_name="C.P. (privado)",
                    ),
                ),
                (
                    "distance_home_work",
                    models.IntegerField(
                        default=0, verbose_name="Distancia casa-trabajo"
                    ),
                ),
                (
                    "distance_home_work_unit",
                    models.CharField(
                        choices=[("kilometers", "km"), ("miles", "mi")],
                        default="kilometers",
                        max_length=10,
                        verbose_name="Unidad de distancia",
                    ),
                ),
                (
                    "marital",
                    models.CharField(
                        choices=[
                            ("single", "Soltero(a)"),
                            ("married", "Casado(a)"),
                            ("cohabitant", "Unión libre"),
                            ("widower", "Viudo(a)"),
                            ("divorced", "Divorciado(a)"),
                        ],
                        default="single",
                        help_text="DIVERGENCIA: la referencia resuelve las opciones vía _get_marital_status_selection (método, se porta abajo); aquí son fijas (TextChoices), mismo criterio que Certificate en hr_employee.py.",
                        max_length=10,
                        verbose_name="Estado civil",
                    ),
                ),
                (
                    "spouse_complete_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Nombre del cónyuge",
                    ),
                ),
                (
                    "spouse_birthdate",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Fecha de nacimiento del cónyuge",
                    ),
                ),
                (
                    "children",
                    models.IntegerField(default=0, verbose_name="Hijos dependientes"),
                ),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("employee", "Empleado"),
                            ("worker", "Obrero"),
                            ("student", "Estudiante"),
                            ("trainee", "Becario"),
                            ("contractor", "Contratista"),
                            ("freelance", "Freelance"),
                        ],
                        default="employee",
                        max_length=10,
                        verbose_name="Tipo de empleado",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Odoo job_title (compute+inverse+store). BLOQUEADO el auto-sync desde job.name — familia (a); se asigna directo.",
                        max_length=150,
                        verbose_name="Título del puesto",
                    ),
                ),
                (
                    "is_custom_job_title",
                    models.BooleanField(
                        default=False,
                        help_text="Odoo is_custom_job_title (compute+store). BLOQUEADO el auto-sync — familia (a).",
                        verbose_name="Título de puesto personalizado",
                    ),
                ),
                (
                    "departure_description",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Información adicional de baja",
                    ),
                ),
                (
                    "departure_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de baja"
                    ),
                ),
                (
                    "contract_date_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Inicio de contrato"
                    ),
                ),
                (
                    "contract_date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de contrato"
                    ),
                ),
                (
                    "trial_date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de periodo de prueba"
                    ),
                ),
                (
                    "wage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Odoo wage — salario mensual bruto.",
                        max_digits=14,
                        verbose_name="Salario",
                    ),
                ),
                (
                    "additional_note",
                    models.TextField(
                        blank=True, default="", verbose_name="Nota adicional"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo address_id. DIVERGENCIA: sin default (la referencia usa self.env.company.partner_id.address_get(['default']) — sesión, familia b, ver _get_default_address_id BLOQUEADO).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions_work_address",
                        to="base.respartner",
                        verbose_name="Dirección de trabajo",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo company_id (compute+store, default=env.company). BLOQUEADO el auto-sync desde employee.company — familia (a).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions",
                        to="base.rescompany",
                        verbose_name="Empresa (tenant)",
                    ),
                ),
                (
                    "contract_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo contract_template_id — otra hr.version sin employee_id.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions_using_template",
                        to="hr.hrversion",
                        verbose_name="Plantilla de contrato",
                    ),
                ),
                (
                    "contract_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions",
                        to="hr.hrcontracttype",
                        verbose_name="Tipo de contrato",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text='Odoo country_id — "Nationality (Country)".',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions_nationality",
                        to="base.rescountry",
                        verbose_name="Nacionalidad",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions",
                        to="hr.hrdepartment",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "departure_reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hr_versions",
                        to="hr.hrdeparturereason",
                        verbose_name="Motivo de baja",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text='Odoo employee_id — el "dueño" de la versión. Un empleado tiene N versiones (historial de carrera); hr.HrEmployee.version apunta a la vigente.',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="hr.hremployee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "hr_responsible",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo hr_responsible_id. DIVERGENCIA: sin default=env.user ni domain dinámico (_get_hr_responsible_domain, familia b).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions_responsible",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable de RH",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions",
                        to="hr.hrjob",
                        verbose_name="Puesto",
                    ),
                ),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo last_modified_uid. DIVERGENCIA: sin default=env.uid (usuario de sesión, ausente a nivel de modelo — familia b).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions_last_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por última vez por",
                    ),
                ),
                (
                    "private_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions_private",
                        to="base.rescountry",
                        verbose_name="País (privado)",
                    ),
                ),
                (
                    "private_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions_private",
                        to="base.rescountrystate",
                        verbose_name="Estado (privado)",
                    ),
                ),
                (
                    "resource_calendar",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo resource_calendar_id (inverse=_inverse_resource_calendar_id). BLOQUEADO el inverse (sincroniza employee.resource.calendar cuando esta versión es la vigente) — familia (a).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions",
                        to="resource.resourcecalendar",
                        verbose_name="Horario de trabajo",
                    ),
                ),
                (
                    "structure_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo structure_type_id (compute+store, default=_default_salary_structure). DIVERGENCIA: sin default de campo — se porta _default_salary_structure_for_company como helper explícito (ver métodos); BLOQUEADO el auto-sync (_compute_structure_type_id) — familia (a).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions",
                        to="hr.hrpayrollstructuretype",
                        verbose_name="Tipo de estructura salarial",
                    ),
                ),
                (
                    "work_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hr_versions",
                        to="hr.hrworklocation",
                        verbose_name="Lugar de trabajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de empleado",
                "verbose_name_plural": "Versiones de empleado",
                "db_table": "hr_version",
                "ordering": ["date_version"],
            },
        ),
        migrations.AddField(
            model_name="hremployee",
            name="version",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo version_id — la ``hr.version`` que ``_inherits`` delegaba. Aquí es una FK real (Django no tiene delegación de campos); ``hr.HrVersion.employee`` (``related_name='versions'``) es el reverso — el historial completo es ``self.versions.all()``.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.hrversion",
                verbose_name="Versión vigente",
            ),
        ),
        migrations.AddConstraint(
            model_name="hrversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("contract_date_end__isnull", True),
                    ("contract_date_start__isnull", False),
                    _connector="OR",
                ),
                name="hr_version_contract_start_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="hrversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("employee__isnull", False)),
                fields=("employee", "date_version"),
                name="hr_version_unique_active_date_version",
            ),
        ),
    ]
