# Generated by Django 6.0.5 on 2026-08-18 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_seed_langs"),
        ("hr", "0006_hrversion_hremployee_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrdepartment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa dueña del departamento (Odoo company_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_departments",
                to="base.rescompany",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="hrjob",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa dueña del puesto (Odoo company_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_jobs",
                to="base.rescompany",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo company_id (compute+store, default=env.company). El auto-sync desde employee.company está BLOQUEADO por ``api.depends`` — sin trigger de recómputo, lo asigna quien escribe (familia (a)).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_versions",
                to="base.rescompany",
                verbose_name="Empresa",
            ),
        ),
        migrations.AlterField(
            model_name="hrworklocation",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa dueña de la sede (Odoo company_id, required=True en la fuente — ver docstring del módulo).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_work_locations",
                to="base.rescompany",
                verbose_name="Empresa",
            ),
        ),
    ]
