# Generated by Django 6.0.5 on 2026-08-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_alter_hrdepartment_company_alter_hrjob_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hremployee",
            name="hr_icon_display",
            field=models.CharField(
                blank=True,
                choices=[
                    ("presence_present", "Presente"),
                    ("presence_out_of_working_hour", "Fuera de horario"),
                    ("presence_absent", "Ausente"),
                    ("presence_archive", "Archivado"),
                    ("presence_undetermined", "Indeterminado"),
                ],
                default="",
                help_text="BLOQUEADO por ``hr_presence_state`` — _compute_presence_icon deriva de ese campo, que queda en su default. Sucesor: tarea #21.",
                max_length=28,
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="hr_presence_state",
            field=models.CharField(
                choices=[
                    ("present", "Presente"),
                    ("absent", "Ausente"),
                    ("archive", "Archivado"),
                    ("out_of_working_hour", "Fuera de horario"),
                ],
                default="out_of_working_hour",
                help_text="BLOQUEADO por ``base.ResUsers.presence_ids`` — el cómputo (_compute_presence_state) necesita la presencia del usuario, infra bus no portada. El campo queda en su default. Sucesor: tarea #21.",
                max_length=20,
                verbose_name="Estado de presencia",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="last_activity",
            field=models.DateField(
                blank=True,
                help_text="BLOQUEADO por ``base.ResUsers.presence_ids`` — el cómputo (_compute_last_activity) necesita la presencia del usuario, infra bus no portada. Sucesor: tarea #21.",
                null=True,
                verbose_name="Última actividad",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="work_location_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo work_location_name — lo materializa _compute_work_location_name desde version.work_location al guardar (tarea #524).",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="work_location_type",
            field=models.CharField(
                blank=True,
                choices=[("home", "Casa"), ("office", "Oficina"), ("other", "Otra")],
                default="",
                help_text="Odoo work_location_type — lo materializa _compute_work_location_type desde version.work_location al guardar (tarea #524).",
                max_length=6,
            ),
        ),
    ]
