# Generated by Django 6.0.5 on 2026-08-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_hremployee_hr_icon_display_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmployeePublic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, help_text='Odoo create_date — en la vista sale de e.created_at.', null=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=32)),
                ('work_phone', models.CharField(blank=True, default='', max_length=32)),
                ('work_email', models.CharField(blank=True, default='', max_length=254)),
                ('color', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Empleado (público)',
                'verbose_name_plural': 'Empleados (públicos)',
                'db_table': 'hr_employee_public',
                'ordering': ['name'],
                'managed': False,
            },
        ),
    ]
