# Generated by Django 6.0.5 on 2026-08-19 04:54

import addons.hr_work_entry.models.hr_version
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0029_rescompany_internal_project_id_and_more"),
        ("hr", "0009_hremployeepublic"),
        ("hr_recruitment", "__first__"),
        ("hr_skills", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hremployee",
            name="friday_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación de trabajo del día (Odoo friday_location_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.hrworklocation",
                verbose_name="Friday",
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="hourly_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Costo por hora del empleado (Odoo hourly_cost). Lo consume hr_timesheet para valorizar las horas registradas — HrEmployee.currency ya resuelve la moneda (divergencia de currency_field, ver docstring del módulo).",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="mobility_card",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo mobility_card (su groups= no se porta — divergencia 1 del docstring del módulo).",
                max_length=64,
                verbose_name="Tarjeta de movilidad",
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="monday_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación de trabajo del día (Odoo monday_location_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.hrworklocation",
                verbose_name="Monday",
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="saturday_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación de trabajo del día (Odoo saturday_location_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.hrworklocation",
                verbose_name="Saturday",
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="skill_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Odoo skill_ids (compute+store) — sincronizar con _compute_skill_ids().",
                related_name="employees_with_skill",
                to="hr_skills.hrskill",
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="sunday_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación de trabajo del día (Odoo sunday_location_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.hrworklocation",
                verbose_name="Sunday",
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="thursday_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación de trabajo del día (Odoo thursday_location_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.hrworklocation",
                verbose_name="Thursday",
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="tuesday_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación de trabajo del día (Odoo tuesday_location_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.hrworklocation",
                verbose_name="Tuesday",
            ),
        ),
        migrations.AddField(
            model_name="hremployee",
            name="wednesday_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Ubicación de trabajo del día (Odoo wednesday_location_id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hr.hrworklocation",
                verbose_name="Wednesday",
            ),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="address",
            field=models.ForeignKey(
                blank=True,
                help_text="Odoo address_id: dirección donde trabajará el candidato.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hr_jobs_located",
                to="base.respartner",
                verbose_name="Ubicación",
            ),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="applicant_properties_definition",
            field=models.JSONField(
                blank=True,
                null=True,
                verbose_name="Definición de propiedades de candidato",
            ),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="color",
            field=models.IntegerField(default=0, verbose_name="Índice de color"),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="expected_degree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="hr_recruitment.hrrecruitmentdegree",
                verbose_name="Grado esperado",
            ),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="expected_employees",
            field=models.IntegerField(default=0, verbose_name="Empleados esperados"),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="favorite_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuarios que lo marcaron favorito",
            ),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="interviewers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ven todos los candidatos del puesto y pueden rechazarlos, sin necesitar permisos de reclutamiento.",
                related_name="interviewer_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Entrevistadores",
            ),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="job_properties",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Propiedades del puesto"
            ),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="no_of_employee",
            field=models.IntegerField(
                default=0, verbose_name="Número de empleados actual"
            ),
        ),
        migrations.AddField(
            model_name="hrjob",
            name="skill_ids",
            field=models.ManyToManyField(
                blank=True,
                help_text="Odoo skill_ids (compute+store) — sincronizar con _compute_skill_ids().",
                related_name="jobs_with_skill",
                to="hr_skills.hrskill",
            ),
        ),
        migrations.AddField(
            model_name="hrversion",
            name="date_generated_from",
            field=models.DateTimeField(
                default=addons.hr_work_entry.models.hr_version._generation_boundary_today,
                help_text="Odoo date_generated_from (required, readonly, groups=hr.group_hr_user, tracking — D-1).",
                verbose_name="Generated From",
            ),
        ),
        migrations.AddField(
            model_name="hrversion",
            name="date_generated_to",
            field=models.DateTimeField(
                default=addons.hr_work_entry.models.hr_version._generation_boundary_today,
                help_text="Odoo date_generated_to (required, readonly, groups=hr.group_hr_user, tracking — D-1).",
                verbose_name="Generated To",
            ),
        ),
        migrations.AddField(
            model_name="hrversion",
            name="last_generation_date",
            field=models.DateField(
                blank=True,
                help_text="Odoo last_generation_date (readonly, groups=hr.group_hr_user, tracking — D-1).",
                null=True,
                verbose_name="Last Generation Date",
            ),
        ),
        migrations.AddField(
            model_name="hrversion",
            name="work_entry_source",
            field=models.CharField(
                choices=[("calendar", "Working Schedule")],
                default="calendar",
                help_text="Defines the source for work entries generation. Working Schedule: Work entries will be generated from the working hours below. Attendances/Planning los añaden sus addons puente (no portados).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="hr_icon_display",
            field=models.CharField(
                blank=True,
                choices=[
                    ("presence_present", "Presente"),
                    ("presence_out_of_working_hour", "Fuera de horario"),
                    ("presence_absent", "Ausente"),
                    ("presence_archive", "Archivado"),
                    ("presence_undetermined", "Indeterminado"),
                    ("presence_home", "En casa"),
                    ("presence_office", "En la oficina"),
                    ("presence_other", "En otra ubicación"),
                ],
                default="",
                help_text="BLOQUEADO por ``hr_presence_state`` — _compute_presence_icon deriva de ese campo, que queda en su default. Sucesor: tarea #21.",
                max_length=28,
            ),
        ),
    ]
