# Generated by Django 6.0.5 on 2026-08-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_hremployee_friday_location_hremployee_hourly_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrcontracttype",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código corto (Odoo code). Se auto-rellena desde name si se deja vacío — ver save() (Odoo _compute_code).",
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="hrcontracttype",
            name="name",
            field=models.CharField(
                help_text="Nombre del tipo de contrato (Odoo name).",
                verbose_name="Nombre",
            ),
        ),
        migrations.AlterField(
            model_name="hrdepartment",
            name="name",
            field=models.CharField(verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="hrdepartment",
            name="parent_path",
            field=models.CharField(blank=True, db_index=True, default=""),
        ),
        migrations.AlterField(
            model_name="hrdeparturereason",
            name="name",
            field=models.CharField(
                help_text="Nombre del motivo de baja (Odoo name).",
                verbose_name="Motivo",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="barcode",
            field=models.CharField(
                blank=True,
                help_text="Odoo barcode — identificación del empleado. Unicidad vía Meta.constraints (``hr_employee_barcode_uniq``), no aquí.",
                null=True,
                verbose_name="ID de gafete",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="birthday_public_display_string",
            field=models.CharField(blank=True, default="hidden"),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="certificate",
            field=models.CharField(
                blank=True,
                choices=[
                    ("graduate", "Bachillerato"),
                    ("bachelor", "Licenciatura"),
                    ("master", "Maestría"),
                    ("doctor", "Doctorado"),
                    ("other", "Otro"),
                ],
                default="",
                verbose_name="Nivel de estudios",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="company_country_code",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="emergency_contact",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="emergency_phone",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="hr_icon_display",
            field=models.CharField(
                blank=True,
                choices=[
                    ("presence_present", "Presente"),
                    ("presence_out_of_working_hour", "Fuera de horario"),
                    ("presence_absent", "Ausente"),
                    ("presence_archive", "Archivado"),
                    ("presence_undetermined", "Indeterminado"),
                    ("presence_home", "En casa"),
                    ("presence_office", "En la oficina"),
                    ("presence_other", "En otra ubicación"),
                ],
                default="",
                help_text="BLOQUEADO por ``hr_presence_state`` — _compute_presence_icon deriva de ese campo, que queda en su default. Sucesor: tarea #21.",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="hr_presence_state",
            field=models.CharField(
                choices=[
                    ("present", "Presente"),
                    ("absent", "Ausente"),
                    ("archive", "Archivado"),
                    ("out_of_working_hour", "Fuera de horario"),
                ],
                default="out_of_working_hour",
                help_text="BLOQUEADO por ``base.ResUsers.presence_ids`` — el cómputo (_compute_presence_state) necesita la presencia del usuario, infra bus no portada. El campo queda en su default. Sucesor: tarea #21.",
                verbose_name="Estado de presencia",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="lang",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Código de base.ResLang.code (Odoo lang — Selection dinámico, ver divergencia del docstring del módulo).",
                verbose_name="Idioma",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="last_activity_time",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="legal_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo legal_name (compute+store+readonly=False — se rellena desde name en save() si está vacío).",
                verbose_name="Nombre legal",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="mobile_phone",
            field=models.CharField(
                blank=True, default="", verbose_name="Celular de trabajo"
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="name",
            field=models.CharField(
                help_text="Odoo name (related=resource_id.name — aquí columna propia, ver divergencia del docstring del módulo).",
                verbose_name="Nombre del empleado",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="permit_no",
            field=models.CharField(
                blank=True, default="", verbose_name="No. de permiso de trabajo"
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="pin",
            field=models.CharField(blank=True, default="", verbose_name="PIN"),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="place_of_birth",
            field=models.CharField(
                blank=True, default="", verbose_name="Lugar de nacimiento"
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="private_car_plate",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="private_email",
            field=models.CharField(
                blank=True, default="", verbose_name="Correo privado"
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="private_phone",
            field=models.CharField(
                blank=True, default="", verbose_name="Teléfono privado"
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="study_field",
            field=models.CharField(
                blank=True, default="", verbose_name="Área de estudio"
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="study_school",
            field=models.CharField(blank=True, default="", verbose_name="Institución"),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="visa_no",
            field=models.CharField(blank=True, default="", verbose_name="No. de visa"),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="work_email",
            field=models.CharField(
                blank=True, default="", verbose_name="Correo de trabajo"
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="work_location_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo work_location_name — lo materializa _compute_work_location_name desde version.work_location al guardar (tarea #524).",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="work_location_type",
            field=models.CharField(
                blank=True,
                choices=[("home", "Casa"), ("office", "Oficina"), ("other", "Otra")],
                default="",
                help_text="Odoo work_location_type — lo materializa _compute_work_location_type desde version.work_location al guardar (tarea #524).",
            ),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="work_permit_name",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hremployee",
            name="work_phone",
            field=models.CharField(
                blank=True, default="", verbose_name="Teléfono de trabajo"
            ),
        ),
        migrations.AlterField(
            model_name="hremployeecategory",
            name="name",
            field=models.CharField(
                help_text="Nombre de la etiqueta (Odoo name).",
                verbose_name="Nombre de la etiqueta",
            ),
        ),
        migrations.AlterField(
            model_name="hrjob",
            name="name",
            field=models.CharField(verbose_name="Puesto"),
        ),
        migrations.AlterField(
            model_name="hrpayrollstructuretype",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nombre del tipo de estructura salarial (Odoo name).",
                verbose_name="Tipo de estructura salarial",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="distance_home_work_unit",
            field=models.CharField(
                choices=[("kilometers", "km"), ("miles", "mi")],
                default="kilometers",
                verbose_name="Unidad de distancia",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="employee_type",
            field=models.CharField(
                choices=[
                    ("employee", "Empleado"),
                    ("worker", "Obrero"),
                    ("student", "Estudiante"),
                    ("trainee", "Becario"),
                    ("contractor", "Contratista"),
                    ("freelance", "Freelance"),
                ],
                default="employee",
                verbose_name="Tipo de empleado",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="identification_no",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo identification_id.",
                verbose_name="No. de identificación",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="job_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo job_title (compute+inverse+store). BLOQUEADO el auto-sync desde job.name — familia (a); se asigna directo.",
                verbose_name="Título del puesto",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="marital",
            field=models.CharField(
                choices=[
                    ("single", "Soltero(a)"),
                    ("married", "Casado(a)"),
                    ("cohabitant", "Unión libre"),
                    ("widower", "Viudo(a)"),
                    ("divorced", "Divorciado(a)"),
                ],
                default="single",
                help_text="DIVERGENCIA: la referencia resuelve las opciones vía _get_marital_status_selection (método, se porta abajo); aquí son fijas (TextChoices), mismo criterio que Certificate en hr_employee.py.",
                verbose_name="Estado civil",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="name",
            field=models.CharField(blank=True, default="", verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="passport_no",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo passport_id.",
                verbose_name="No. de pasaporte",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="private_city",
            field=models.CharField(
                blank=True, default="", verbose_name="Ciudad (privada)"
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="private_street",
            field=models.CharField(
                blank=True, default="", verbose_name="Calle (privada)"
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="private_street2",
            field=models.CharField(
                blank=True, default="", verbose_name="Calle 2 (privada)"
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="private_zip",
            field=models.CharField(
                blank=True, default="", verbose_name="C.P. (privado)"
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Masculino"),
                    ("female", "Femenino"),
                    ("other", "Otro"),
                ],
                default="",
                verbose_name="Sexo",
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="spouse_complete_name",
            field=models.CharField(
                blank=True, default="", verbose_name="Nombre del cónyuge"
            ),
        ),
        migrations.AlterField(
            model_name="hrversion",
            name="ssn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Odoo ssnid.",
                verbose_name="No. de seguridad social",
            ),
        ),
        migrations.AlterField(
            model_name="hrworklocation",
            name="location_number",
            field=models.CharField(
                blank=True, default="", verbose_name="Número de ubicación"
            ),
        ),
        migrations.AlterField(
            model_name="hrworklocation",
            name="location_type",
            field=models.CharField(
                choices=[("home", "Casa"), ("office", "Oficina"), ("other", "Otra")],
                default="office",
                help_text="Casa / oficina / otra (Odoo location_type).",
                verbose_name="Tipo de ubicación",
            ),
        ),
        migrations.AlterField(
            model_name="hrworklocation",
            name="name",
            field=models.CharField(
                help_text="Nombre de la sede de trabajo (Odoo name).",
                verbose_name="Sede de trabajo",
            ),
        ),
    ]
