# Generated by Django 6.0.5 on 2026-08-19 04:55

import addons.hr_work_entry.models.hr_work_entry
import django.db.models.deletion
import orm.environments
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("base", "0029_rescompany_internal_project_id_and_more"),
        ("hr", "0010_hremployee_friday_location_hremployee_hourly_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HrWorkEntryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Odoo name (required, translate).", max_length=255
                    ),
                ),
                (
                    "display_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="This code can be changed, it is only for a display purpose (3 letters max)",
                        max_length=3,
                        verbose_name="Display Code",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Careful, the Code is used in many references, changing it could lead to unwanted changes.",
                        max_length=64,
                        verbose_name="Payroll Code",
                    ),
                ),
                (
                    "external_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Use this code to export your data to a third party",
                        max_length=64,
                    ),
                ),
                ("color", models.IntegerField(default=0)),
                ("sequence", models.IntegerField(default=25)),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="If the active field is set to false, it will allow you to hide the work entry type without removing it.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_leave",
                    models.BooleanField(
                        default=False,
                        help_text="Allow the work entry type to be linked with time off types.",
                        verbose_name="Time Off",
                    ),
                ),
                (
                    "amount_rate",
                    models.FloatField(
                        default=1.0,
                        help_text="If you want the hours should be paid double, the rate should be 200%.",
                        verbose_name="Rate",
                    ),
                ),
                (
                    "is_extra_hours",
                    models.BooleanField(
                        default=False,
                        help_text="Check this setting if you want the hours to be considered as extra time and added as a bonus to the basic salary.",
                        verbose_name="Added to Monthly Pay",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="Odoo country_id. DIVERGENCIA D-2: sin el domain= de sesión (env.companies) — lo aplica la capa DRF.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_entry_types",
                        to="base.rescountry",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de entrada de trabajo",
                "verbose_name_plural": "Tipos de entrada de trabajo",
                "db_table": "hr_work_entry_type",
            },
        ),
        migrations.CreateModel(
            name="HrUserWorkEntryEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_checked", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Odoo employee_id (required).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_entry_user_filters",
                        to="hr.hremployee",
                        verbose_name="Employee",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=orm.environments.get_current_uid,
                        help_text="Odoo user_id (required, default=env.user → get_current_uid, ondelete=cascade).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_entry_employee_filters",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Me",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filtro de empleados (entradas de trabajo)",
                "verbose_name_plural": "Filtros de empleados (entradas de trabajo)",
                "db_table": "hr_user_work_entry_employee",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "employee"),
                        name="user_id_employee_id_unique",
                        violation_error_message="You cannot have the same employee twice.",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HrWorkEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("date", models.DateField(help_text="Odoo date (required).")),
                ("duration", models.FloatField(default=8, verbose_name="Duration")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "New"),
                            ("conflict", "In Conflict"),
                            ("validated", "In Payslip"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "amount_rate",
                    models.FloatField(
                        blank=True,
                        help_text="Odoo amount_rate. None = sin fijar; la mitad de alta de save() lo toma del tipo (≙ create, :245-250).",
                        null=True,
                        verbose_name="Pay rate",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        default=orm.environments.get_current_company,
                        help_text="Odoo company_id (required, readonly, default=env.company → get_current_company). Nullable aquí porque el default de sesión puede ser None fuera de una petición; la mitad de alta de save() lo completa desde el empleado (≙ create).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="work_entries",
                        to="base.rescompany",
                        verbose_name="Company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Odoo employee_id (required, index). DIVERGENCIA: sin el domain= de compañía (filtro de formulario; lo aplica DRF).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_entries",
                        to="hr.hremployee",
                        verbose_name="Empleado",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        help_text="Odoo version_id (required, index).",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_entries",
                        to="hr.hrversion",
                        verbose_name="Employee Record",
                    ),
                ),
                (
                    "work_entry_type",
                    models.ForeignKey(
                        blank=True,
                        default=addons.hr_work_entry.models.hr_work_entry._default_work_entry_type,
                        help_text="Odoo work_entry_type_id. El domain= dinámico es _get_work_entry_type_domain (D-7).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_entries",
                        to="hr_work_entry.hrworkentrytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada de trabajo",
                "verbose_name_plural": "Entradas de trabajo",
                "db_table": "hr_work_entry",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        condition=models.Q(("state__in", ("draft", "validated"))),
                        fields=["version", "date"],
                        name="contract_date_start_stop_idx",
                    )
                ],
            },
        ),
    ]
