# Generated by Django 6.0.5 on 2026-08-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr_work_entry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hrworkentry",
            name="name",
            field=models.CharField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="hrworkentry",
            name="state",
            field=models.CharField(
                choices=[
                    ("draft", "New"),
                    ("conflict", "In Conflict"),
                    ("validated", "In Payslip"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
            ),
        ),
        migrations.AlterField(
            model_name="hrworkentrytype",
            name="code",
            field=models.CharField(
                help_text="Careful, the Code is used in many references, changing it could lead to unwanted changes.",
                verbose_name="Payroll Code",
            ),
        ),
        migrations.AlterField(
            model_name="hrworkentrytype",
            name="external_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Use this code to export your data to a third party",
            ),
        ),
        migrations.AlterField(
            model_name="hrworkentrytype",
            name="name",
            field=models.CharField(help_text="Odoo name (required, translate)."),
        ),
    ]
